### ISSUE TITLE
broom

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#1002]
Related:
- https://github.com/rstudio/sparklyr/issues/598

**Comment by javierluraschi** [comment]
@samuelmacedo83 is taking a look at this one.

**Comment by samuelmacedo83** [comment]
done: 
- ml_naive_bayes
- ml_logistic_regression
- ml_decision_tree
- ml_random_forest
- ml_gradient_boosted_trees
- ml_bisecting_kmeans
- ml_kmeans
- ml_gaussian_mixture
- ml_linear_regression
- ml_generalized_linear_regression

in progress:
- ml_aft_survival_regression
- ml_isotonic_regression

not-done:
- ml_als
- ml_als_factorization
- ml_association_rules
- ml_fpgrowth
- ml_linear_svc
- ml_lda
- ml_multilayer_perceptron
- ml_pca

**Comment by realviacauchy** [comment]
How do I call the implementation for visualization of a decision tree / random forest / etc.?

**Comment by shwetapurushe** [comment]
Hello, the code example at #598 no longer works. The error i get is 
`> invoke(model$model, "toDebugString")
Error in UseMethod("invoke") : 
  no applicable method for 'invoke' applied to an object of class "c('ml_decision_tree_classification_model', 'ml_prediction_model', 'ml_transformer', 'ml_pipeline_stage')"`

I was thinking of pulling the model into R (using a collect) and visualizing it with a rpart.plot(). But that doesnt seem to work either. 

Any help or feedback will be greatly appreciated. :)

**Comment by shwetapurushe** [comment]
Alright, after some experimentation and help online , the code below helps you crudely visualize a tree 
get the debug string
`model_stage <- fitted_model$stages[[3]]
 spark_jobj(model_stage) %>% invoke(., "toDebugString") %>% cat()
`
