### ISSUE TITLE
TypeTag

### ISSUE THREAD

**Issue by schlichtanders** [sparklyr/sparklyr#1037]
it seems that if I use ``invoke`` to call some scala code, e.g. to ask for a function value (defined in my custom scala package), then the ``TypeTag`` information is lost.

If I try to call ``spark_session(sc) %>% invoke("udf") %>% invoke("register", myscalafuncjobj)`` I get
```
Error: java.lang.Exception: No matched method found for class
org.apache.spark.sql.UDFRegistration.register
```
However if I call a method which don't needs the TypeTag, then everything works fine.

Any ideas how to solve this? Why is the TypeTag information lost?

**Comment by javierluraschi** [comment]
@schlichtanders How does `myscalafuncjobj` look like? Would be great if you could provide the scala signature for us to reproduce this.

BTW. In case it helps, there is a sample https://github.com/javierluraschi/sparklyudf project.

**Comment by schlichtanders** [comment]
as far as I thought, I expect this to happen for all functions wrapped in a jobj on R side - or can you provide an example which works as expected?

On Scala side, I can replicate this kind of error by making an ad-hoc function wrapper which forgets the ``TypeTag`` information (I actually don't know why this forgets the TypeTag information but it apparently does)
```scala
object foo{
  def func_wrapper[A,B](f: A => B) = f

  def times2(x: Double) = x*2
}
```
If you now try to register this function as UDF by running something like
```scala
spark.udf.register("times2", foo.func_warpper(foo.times2))
```
then it will give a similar error (``spark`` is the spark session).

That is why I concluded that wrapping a function into an jobj on R side has a similar effect, i.e. forgets the TypeTag somehow.

**Comment by yitao-li** [comment]
`TypeTag`s are obtained at compile time. Objects do not carry type tag along with them at runtime because of type erasure. The only way you can invoke Scala methods with `TypeTag` params is by passing in `TypeTag` objects generated from compile time explicitly.
