### ISSUE TITLE
first() and last() functions not working

### ISSUE THREAD

**Issue by admoseremic** [sparklyr/sparklyr#1051]
I'm trying to get the first and last functions from dplyr working with sparklyr, but I'm getting some weird behavior. As an example, normal dplyr allows me to do the following:

```r
> thing <- data.frame(values = c(1,1,1,1,2,2,2,2,2,6,6,6,6,10), row_num = 1:14)
> thing
   values row_num
1       1       1
2       1       2
3       1       3
4       1       4
5       2       5
6       2       6
7       2       7
8       2       8
9       2       9
10      6      10
11      6      11
12      6      12
13      6      13
14     10      14
```

Then, when I run the following code I get:

```r
> thing %>%
+   group_by(values) %>%
+   summarize(
+     first_val = first(row_num),
+     last_val = last(row_num)
+   )
# A tibble: 4 x 3
  values first_val last_val
   <dbl>     <int>    <int>
1      1         1        4
2      2         5        9
3      6        10       13
4     10        14       14
```

This is just what I want. However, when running this in sparklyr, this is what I get:

```r
> sc <- spark_connect(master = "local")
> thing <- data.frame(values = c(1,1,1,1,2,2,2,2,2,6,6,6,6,10), row_num = 1:14)
> thing_tbl <- copy_to(sc, thing)
> thing_tbl %>%
+   group_by(values) %>%
+   summarize(
+     first_val = first(row_num),
+     last_val = last(row_num)
+   )
# Source:   lazy query [?? x 3]
# Database: spark_connection
  values first_val  last_val
   <dbl>     <chr>     <chr>
1      6 `row_num` `row_num`
2      1 `row_num` `row_num`
3     10 `row_num` `row_num`
4      2 `row_num` `row_num`
```

Why is it filling the columns with the text 'row_num'?

Any help is much appreciated!

**Comment by joshuatpack** [comment]
I am having the exact same issue - any response, fix, or workaround is much appreciated!!!

**Comment by kevinykuo** [comment]
This is a Spark limitation, see https://issues.apache.org/jira/browse/SPARK-19428.

Workaround:

```
thing_with_group_row_num <- thing_tbl %>%
  group_by(values) %>%
  arrange(row_num) %>%
  mutate(group_row_num = row_number())

inner_join(
  thing_with_group_row_num %>%
    filter(group_row_num == 1) %>%
    select(values, first_value = row_num),
  thing_with_group_row_num %>%
    filter(group_row_num == max(group_row_num)) %>%
    select(values, last_value = row_num),
  by = "values"
) %>%
  arrange(values)
```

**Comment by admoseremic** [comment]
Ah, thanks.

I also found that using the top_n() function was a good workaround too.

**Comment by AjarKeen** [comment]
Update: Spark SQL now supports [`last_value`](https://spark.apache.org/docs/latest/api/sql/index.html#last_value) and [`first_value`](https://spark.apache.org/docs/latest/api/sql/index.html#first_value) directly. 

A reprex based on your original issue code:

```
library(dplyr)
library(sparklyr)

sc <- spark_connect(master = "local",
                    spark_home = "/usr/lib/spark")

thing <- data.frame(values = c(1,1,1,1,2,2,2,2,2,6,6,6,6,10), row_num = 1:14)

thing_tbl <- copy_to(sc, thing)

thing_tbl %>%
  group_by(values) %>%
  summarize(
    first_val = first_value(row_num),
    last_val = last_value(row_num)
  )

#> # Source:   lazy query [?? x 3]
#> # Database: spark_connection
#>   values first_val last_val
#>    <dbl>     <int>    <int>
#> 1     6.        10       13
#> 2    10.        14       14
#> 3     1.         1        4
#> 4     2.         5        9
```

**Comment by alexfun** [comment]
> Update: Spark SQL now supports [`last_value`](https://spark.apache.org/docs/latest/api/sql/index.html#last_value) and [`first_value`](https://spark.apache.org/docs/latest/api/sql/index.html#first_value) directly.
> 
> A reprex based on your original issue code:
> 
> ```
> library(dplyr)
> library(sparklyr)
> 
> sc <- spark_connect(master = "local",
>                     spark_home = "/usr/lib/spark")
> 
> thing <- data.frame(values = c(1,1,1,1,2,2,2,2,2,6,6,6,6,10), row_num = 1:14)
> 
> thing_tbl <- copy_to(sc, thing)
> 
> thing_tbl %>%
>   group_by(values) %>%
>   summarize(
>     first_val = first_value(row_num),
>     last_val = last_value(row_num)
>   )
> 
> #> # Source:   lazy query [?? x 3]
> #> # Database: spark_connection
> #>   values first_val last_val
> #>    <dbl>     <int>    <int>
> #> 1     6.        10       13
> #> 2    10.        14       14
> #> 3     1.         1        4
> #> 4     2.         5        9
> ```

While Spark SQL does support `first_value` and `last_value`, it seems dangerous to use it since the partition over clause is not built automatically with `summarise`. Depending on how `thing_tbl` is partitioned I have gotten differing results.

**Comment by admoseremic** [comment]
Reopening based on this feedback.

**Comment by degomezl** [comment]
How to get nth value? Thanks in advance.

**Comment by degomezl** [comment]
I did it using:

https://dplyr.tidyverse.org/reference/nth.html

I hope it works.

**Comment by yitao-li** [comment]
I don't think the concept of `first()` and `last()` on a grouped R dataframe maps well to the Spark world. There are "workarounds" that seem to work when Spark is running in local mode, but then become non-deterministic when Spark is running in distributed mode and data is partitioned.
