### ISSUE TITLE
UDFs in dplyr

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#1052]
See:
- https://github.com/rstudio/sparklyr/issues/1049
- https://github.com/rstudio/sparklyr/issues/1178

**Comment by yitao-li** [comment]
I don't think applying UDFs written in R to a Spark dataframe in a way that makes sense to `dplyr` will be a good idea performance-wise, as it would be even slower than applying UDFs written in Scala:

- We need to ensure the resulting `dplyr::mutate(result = my_udf_in_r(input))` is translatable into Spark SQL in order for it to make sense in relation to the rest of `dplyr`. 
- Therefore `my_udf_in_r` presumably needs to be translated into a Spark UDF registered by `sparklyr` taking both serialized R bytes of `my_udf_in_r` and `input` as inputs
- But then the UDF we would implement to support this functionalitity will need to launch a R process to unserialize and evaluate both inputs in R for each row, and then write the result back to Spark, which sounds super expensive

So unfortunately unless any of the above changes, I think `spark_apply()` will always make more sense.
