### ISSUE TITLE
Read RDS or RData using SparklyR

### ISSUE THREAD

**Issue by tarunparmar** [sparklyr/sparklyr#1059]
Hi, 

I did not notice any specific function to read RDS or RData files using SparklyR.
Not sure if it is possible at all. 

I am trying to look for something similar to `spark_read_csv()`

**Comment by javierluraschi** [comment]
@tarunparmar there is no support for this yet. Is the data distributed?
- No: You could try loading it in R and copy it using `copy_to`
- Yes: You try to use `spark_apply()` to read each RDS over the distributed files.

**Comment by tarunparmar** [comment]
Hi @javierluraschi , the data is on a shared drive and each rds file is quite large. 
I will try `spark_apply`.

**Comment by deepayanbiswas** [comment]
I am also trying to read RDS file which is located in HDFS using SparklyR. So far I have tried with spark_apply() without any luck. 
@javierluraschi can you please let me know how I can achieve that. Any sample code snippet would be very helpful.

**Comment by englianhu** [comment]
```
# load the data 
loan_data <- readRDS("loan_data.rds")
loan_data_tbl <- copy_to(sc, loan_data) # copying it to spark
```
By refer to [Installing and preparing sparklyr](https://github.com/JosiahParry/sparklyr_exploration), there has only `loan_data.rds` file, how about read multiple files by using `sparklyr` where every single file has million rows.

```
> session_info()$platform
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language en                          
 collate  Japanese_Japan.932          
 ctype    Japanese_Japan.932          
 tz       Asia/Tokyo                  
 date     2018-09-28
```
I wondered if my processor and RAM able to cope with the problem.

**Comment by javierluraschi** [comment]
Took a quick look at this, we can probably do something like https://issues.apache.org/jira/browse/SPARK-20528, but this is indeed a small feature request.

**Comment by cndesantana** [comment]
I am also trying to load an .rdata file with SparkR and didn't have any success so far. I was trying to use function ```read.df("file.rdata")```, but got an error message like this:

```Error in load : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): org.apache.spark.SparkException: Exception thrown in awaitResult:```

**Comment by cndesantana** [comment]
I am trying to load a .rdata file with 75Mb. It contains a data frame with some thousands of rows and some thousands of columns. I tried to use function ```readRDS``` but it obviously didn't work. Any suggestion so far?

**Comment by yitao-li** [comment]
Closing this issue because the recently implemented support for binary data source in sparklyr (https://github.com/sparklyr/sparklyr/pull/3002) can be used in conjunction with `spark_apply()` to import data from RDS file(s) into a Spark dataframe.

**Comment by ashvinmanoj** [comment]
Hi @yitao-li ,
I tried to look into the merge #3002 but unable to succeed in finding ways to read RDS file using spark_apply. Can you please share an example on how to do that?
