### ISSUE TITLE
FeatureRequest: invoke with named arguments

### ISSUE THREAD

**Issue by schlichtanders** [sparklyr/sparklyr#1068]
Motivation: It would be really awesome to switch more seamlessly between R and scala.
Current Limitation: The current implementation of invoke does not support named arguments to be passed to scala.

I am not sure, whether this is easily possible, however I spotted the internal method dealing with the arguments (args here is indeed a named list, however the names are not used)
```r
> sparklyr:::writeArgs
function (con, args) 
{
    if (length(args) > 0) {
        for (a in args) {
            writeObject(con, a)
        }
    }
}
```

**Comment by yitao-li** [comment]
This is not possible with Scala's runtime reflection API at the moment.

**Comment by yitao-li** [comment]
If it becomes possible in some future version of Scala and there are Apache Spark distributions built using this Scala version, then we'll revisit this issue.
