### ISSUE TITLE
when more cores used Spark (Sparklyr) error to many files open

### ISSUE THREAD

**Issue by yissylevi** [sparklyr/sparklyr#1080]
---

I am using the following configuration on Sparklyr in local mode:
```r
    conf <- spark_config()
    conf$`sparklyr.cores.local` <- 28
    conf$`sparklyr.shell.driver-memory` <- "1000G"
    conf$spark.memory.fraction <- 0.9

    sc <- spark_connect(master = "local", 
                    version = "2.1.1",
                    config = conf)
```
This works fine when I read in a csv using spark_read_csv. However when I used more cores such as 
```r
    conf <- spark_config()
    conf$`sparklyr.cores.local` <- 30
    conf$`sparklyr.shell.driver-memory` <- "1000G"
    conf$spark.memory.fraction <- 0.9

I get the following error:

```
> 
>   Error in value[[3L]](cond) : 
>     Failed to fetch data: org.apache.spark.SparkException: Job aborted due 
>     to stage failure: Task 10 in stage 3.0 failed 1 times, most recent 
>     failure: Lost task 10.0 in stage 3.0 (TID 132, localhost, executor 
>     driver): java.io.FileNotFoundException: /tmp/blockmgr-9ded7dfb-20b8-
>     4c72-8a6f-2db12ba884fb/1f/temp_shuffle_e69d56ba-80b4-499f-a91f-
>     0ae63fe4553f (Too many open files)
> 	at java.io.FileOutputStream.open0(Native Method)
> 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
> 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
> 	at org.apache.spark.storage.DiskBlockObjectWriter.initialize(DiskBlockObjectWriter.scala:102)
> 	at org.apache.spark.storage.DiskBlockObjectWriter.open(DiskBlockObjectWriter.scala:115)
> 	at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:235)
> 	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:152)
> 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMa
> 
I increased ulimit to 419430 from 1040 (both soft and hard) and this made no difference. 

My VM has **128 cores and 2T** of memory and I'd like to be able to use all of it.

Any suggestions?

**Comment by geoHeil** [comment]
you need to configure more file descriptors. https://www.google.at/search?client=safari&rls=en&q=too+many+open+files&ie=UTF-8&oe=UTF-8&gfe_rd=cr&dcr=0&ei=H_btWZ26OsXPXvi2jZAN

**Comment by yissylevi** [comment]
That made no difference. As I said "I increased ulimit to 419430 from 1040 (both soft and hard) and this made no difference."
