### ISSUE TITLE
how to read XML files with Sparklyr?

### ISSUE THREAD

**Issue by randomgambit** [sparklyr/sparklyr#1089]
Hello everyone!

I see there is `spark_json`, `spark_csv` and `spark_parquet`... but what about `XML` files? Is there a native way to load them while using `Sparklyr`? My workflow is written in `Sparklyr` but now I need to load large XML files as well..

Any ideas? Many thanks!!

**Comment by kevinykuo** [comment]
There's no native parser in Spark but there's a package for it: https://github.com/databricks/spark-xml
