### ISSUE TITLE
Better external package handlings with extensions for off line users

### ISSUE THREAD

**Issue by chezou** [sparklyr/sparklyr#1112]
According to [this PR](https://github.com/rstudio/sparklyr/pull/314), sparklyr has embedded jar of csv parser. 

Some users requested [my extension to have it's dependent jars](https://github.com/chezou/sparkavro/pull/5), but I think it is not smart to include all dependent jars for each extension.

So, is there any smart way to consider external dependencies for air-gapped clusters, or could we have good documentation for that situation?

**Comment by mattpollock** [comment]
A work around that I've used is to maintain a local maven repository including the necessary dependencies (it seems Spark will look at local maven/ant repos first, then try hitting spark-packages externally) using the `mvndeps` package (https://github.com/mitre/mvndeps).

```
> mvndeps::download_dependency("com.databricks:spark-avro_2.11:3.2.0")
JAVA_HOME now set to /usr
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:get (default-cli) @ standalone-pom ---
[INFO] Resolving com.databricks:spark-avro_2.11:jar:3.2.0 with transitive dependencies
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.001 s
[INFO] Finished at: 2017-11-09T10:45:38-05:00
[INFO] Final Memory: 16M/966M
[INFO] ------------------------------------------------------------------------
JAVA_HOME is now unset
```

This is a moderately big ask for users who are unfamiliar with maven though and comes with system requirements. Would be great if there was another solution that didn't require all versions of a jar to be stuffed into the `inst` directory.
