### ISSUE TITLE
user defined functions in dplyr

### ISSUE THREAD

**Issue by zhf526** [sparklyr/sparklyr#120]
The document says "dplyr translates the commands into Spark SQL statements". Does it mean that dplyr in sparkly does not support user defined R functions which are not defined in Spark SQL?

For example, I tried to run this:

```
tsDF <- tsDF %>%
  mutate(DayNum = as.numeric(factor(DimDateKey)))
```

and got the error:

`Error: org.apache.spark.sql.AnalysisException: undefined function FACTOR; line 2 pos 539`

**Comment by javierluraschi** [comment]
@zhf526 correct. Currently, `sparklyr` supports `dplyr` functions with Spark SQL equivalents; however, expanding to support UDFs is something that we are looking forward to implement.

For the code above, you could remove `factor` and get a base cast from date to numeric. However, I suspect this wouldn't be sufficient. If you want to give us more context on the problem you are solving, we might be able to find an equivalent conversion from date to numeric.

**Comment by dfalbel** [comment]
This will be a nice feature! I was looking for something like this:
https://spark.apache.org/docs/latest/sparkr.html#applying-user-defined-function
but with a friendly dplyr interface :)

**Comment by algattik** [comment]
In the meantime, how can I filter using substring match? This works over an R Data Frame: 
`iris %>% filter(grepl("ica", Species))`

but over a Spark DataFrame:
`Error: org.apache.spark.sql.AnalysisException: Undefined function: 'GREPL'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'`

**Comment by konradedgar** [comment]
@algattik Concerning string matching, you should be able to use [`locate`](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-StringOperators) functions available in Hive:
```sql
locate(string substr, string str[, int pos])
```
as it it's possible to use Hive functions in sparklyr workflow:
```r
aDataFrame %>% 
  mutate(clnD = regexp_replace(d, "-", "")) %>%
  # ...
```
and then filter by obtained integers.
*As discussed [on SO.](https://stackoverflow.com/a/43910077/1655567)*

**Comment by axiomoixa** [comment]
similar question.
Instead of using the basic aggregating functions, I would like to use **median**.
Then I get an error
`Error: org.apache.spark.sql.AnalysisException: Undefined function: 'MEDIAN'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; `

**Comment by shabbybanks** [comment]
`percentile` is a function in Spark SQL that you might be able to use for this purpose. If confirmed, it would then be an exercise in the SQL translation within `sparklyr` to translate `median` to `percentile(x,0.5)`.

**Comment by shabbybanks** [comment]
It might make sense to add `median` to the aggregate functions around here: https://github.com/rstudio/sparklyr/blob/e4f63a495d1f589f5366114721f0478cec423c1e/R/dplyr_spark_connection.R#L97-L106 to do this translation automagically.

**Comment by samuelmacedo83** [comment]
It's possible to use quantile, median and work with dates inside the `dplyr::mutate()`.  For example:
```
library(sparklyr)

sc <- spark_connect(master = "local")
iris_tbl <- sc %>% 
  sdf_copy_to(iris, "iris_tbl", memory = FALSE)

iris %>% 
  group_by(Species) %>% 
  summarise(Q1 = quantile(Petal.Length, 0.25))
```
It's also possible to run UDF's with `sparklyr::spark_apply()`. You can see examples [here](https://therinspark.com/distributed.html).

Feel free to open a new GitHub issue if you disagree with this resolution, thanks for your feedback
