### ISSUE TITLE
Provide tidyr functions

### ISSUE THREAD

**Issue by kevinykuo** [sparklyr/sparklyr#1231]
Tracking tidyr feature requests here

https://github.com/rstudio/sparklyr/issues/863
https://github.com/rstudio/sparklyr/issues/830
https://github.com/rstudio/sparklyr/issues/252

**Comment by javierluraschi** [comment]
Here a tracking item for this under the sparklyboard: https://github.com/rstudio/sparklyr/issues/1233 - I wonder how far we are after fixing this issue to call `tidyr` fully implemented.

**Comment by overmar** [comment]
Has there been any progress on this? I can mimic gather using sdf_pivot, but won't submit a pull request if you guys already have an elegant solution.

**Comment by kevinykuo** [comment]
I think @edgararuiz is working on these at the dbplyr level, and those are done we should get them for free in sparklyr.

**Comment by jmerone** [comment]
@kevinykuo or @edgararuiz is this still being worked on?

**Comment by kevinykuo** [comment]
Possibly related: https://github.com/apache/spark/pull/21187

@edgararuiz I remember there was a PR for `gather()` (in dbplyr?) that I can't locate... is that still happening?

**Comment by overmar** [comment]
#' @param tbl spark table
#' @param vr column names of columns to gather, or "all_columns" to gather all but non.strat
#' @param non.strat string of column name that shouldn't be gathered
#' @param fun sdf_pivot requires a summarise function, so this can cause problems, but it works for both min and max.
gather_sparklyr <- function(tbl,vr,non.strat, fun = "max") {
  pivot.formula <- function(non.strat){
    as.formula(paste(paste0(non.strat, collapse = " + "), "rown2", sep = " ~ "))
  }
  gather_inner <- function(tbl,.x, non.strat){
    quos.list <- list(fun)
    names(quos.list) <- .x
    tbl %>% 
      mutate(rown2 = "variable") %>% 
      sdf_pivot(pivot.formula(non.strat), quos.list) %>% mutate(loc = .x) %>% 
      filter(!variable %in% c("","0000000"))
  }
  if (all(vr == "all_columns")){
    vr <- colnames(tbl)[-which.max(colnames(tbl) == "patient_id")]
  }
  ret <- purrr::map(vr, ~ gather_inner(tbl,.x, non.strat))
  Reduce("union_all",ret)
}

**Comment by jkylearmstrong** [comment]
have these ```r spread ``` and ```r gather``` been implemented in sparklyr ?

**Comment by kevinykuo** [comment]
Not yet. There's some changes to the tidyr API soon and once that's settled we'll implement in sparklyr.

**Comment by jmerone** [comment]
@kevinykuo Now that `tidyr::pivot_longer`  and `tidyr::pivot_wider` has been created, is the tidyr API sufficient enough to implemented in sparklyr?

**Comment by kevinykuo** [comment]
@yl790 https://github.com/sparklyr/sparklyr/pull/2652 doesn't seem to implement the pivot functions, which are the core of tidyr, perhaps we should leave this open to track?

**Comment by yl790** [comment]
Yep didn't realize merging the PR would close an issue
