### ISSUE TITLE
tidyr

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#1233]
Related:
 - https://github.com/rstudio/sparklyr/issues/1640

and in general: [tidyr labeled issues](https://github.com/rstudio/sparklyr/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Atidyr+)

**Comment by javierluraschi** [comment]
At JSM 2018, at least one attendee asked to get this implemented.

**Comment by mattpollock** [comment]
I have initial implementations of [`nest`](https://github.com/mitre/sparklyr.nested/blob/master/R/nest.R) and [`unnest`](https://github.com/mitre/sparklyr.nested/blob/master/R/unnest.R). The latter is a bit buggy, but that has more to do with my getting distracted with my real job than any serious technical difficulty. 

`sparklyr.nested` makes no attempt to do other `tidyr` things like `spread`/`gather`

**Comment by javierluraschi** [comment]
From, https://blog.rstudio.com/2016/09/27/sparklyr-r-interface-for-apache-spark/:

```
login_df % tidyr::separate(ip, c("ip_01","ip_02","ip_03","ip_04","port"), "\\.") %>%
+ unite(ip_addr, ip_01, ip_02, ip_03, ip_04, sep=".", remove=TRUE)
Error in UseMethod("separate_") :
no applicable method for 'separate_' applied to an object of class "c('tbl_spark', 'tbl_sql', 'tbl_lazy', 'tbl')"
```
