### ISSUE TITLE
sample_n() fails after select()

### ISSUE THREAD

**Issue by kevinykuo** [sparklyr/sparklyr#1299]
```
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local")
#> * Using Spark: 2.2.0
iris_tbl <- sdf_copy_to(sc, iris)

iris_tbl %>%
  select(Petal_Length) %>%
  sample_n(5)
#> Error in vapply(dots(...), escape_expr, character(1)): values must be length 1,
#>  but FUN(X[[2]]) result is length 8

iris_tbl %>%
  sample_n(5)
#> # Source:   lazy query [?? x 5]
#> # Database: spark_connection
#>   Sepal_Length Sepal_Width Petal_Length Petal_Width Species
#>          <dbl>       <dbl>        <dbl>       <dbl> <chr>  
#> 1         5.10        3.50         1.40       0.200 setosa 
#> 2         4.90        3.00         1.40       0.200 setosa 
#> 3         4.70        3.20         1.30       0.200 setosa 
#> 4         4.60        3.10         1.50       0.200 setosa 
#> 5         5.00        3.60         1.40       0.200 setosa
```

See https://stackoverflow.com/questions/48687122/sample-data-after-using-filter-or-select-from-sparkly

**Comment by mariana-yn** [comment]
Thaks for the fix, the select operator works!
Unfortunatelly, I'm still having trouble sampling after using filter and/or mutate operators.
I get this message:

> Error in set_current_con(con) : 
>   argument "con" is missing, with no default

The code I'm trying to execute:

```
library(sparklyr)
library(dplyr)

sc<-spark_connect(master='local')

data_example<-copy_to(sc,iris,'iris')

data_select<-filter(data_example,Sepal.Length>5)
data_sample<-sample_n(data_select,25)

data_sample

data_select1<-mutate(data_example,var_test=Sepal.Length+Sepal.Width)
data_sample1<-sample_n(data_select1,25)

data_sample1
```
Am I doing something wrong with the code or is it a problem with sparklyr?
Thanks again!

**Comment by kevinykuo** [comment]
@mariana-yn The first case (with `filter()`) won't work because I don't think Spark SQL `TABLEAMPLE` works with filtered subqueries. The second case should work with devel dbplyr, after https://github.com/tidyverse/dbplyr/pull/73 is merged, if you fix the spelling of the variables (should be `Sepal_Length + Sepal_Width`.)

**Comment by harryprince** [comment]
same issue +1

**Comment by javierluraschi** [comment]
@harryprince can you share your `sessionInfo()`?

**Comment by deepachawla** [comment]
same issue +1 

list <- sdf_collect(dfAll %>% sample_n(2))
argument "con" is missing, with no default
