### ISSUE TITLE
Datetime support seems only one-way, missing conversion support from R to Spark

### ISSUE THREAD

**Issue by schlichtanders** [sparklyr/sparklyr#1310]
Dear sparklyr team,

first time using sparkly 7.0 with its datetime support/posixct
+1 the conversion from scala to R seems to work seamlessly
-1 the conversion from R to Scala seems buggy

For instance filtering a sparkdataframe datetime column by a Posixct from R does not seem to work correctly. It does something and also something related to comparing timestamps, however with e.g. ``filtering <= 2018.01.01  18:03``   it still keeps times like ``2018.01.01 19:08`` ocassionally...

I guess this is due to timezones and ``Posixct`` being auto-converted to Double/``Numeric``

(Creating a minimal working example is quite involved in my case, hence this issue now without. Maybe I have time later to check this. For now I will fall back to using strings again)

**Comment by randomgambit** [comment]
related https://github.com/rstudio/sparklyr/issues/1321

**Comment by yitao-li** [comment]
This issue has been addressed in recent versions of `sparklyr`. For example, the following works as expected now

```
library(sparklyr)
library(dplyr)
library(nycflights13)

sc <- spark_connect(master = "local")
flights_sdf <- copy_to(sc, flights, name = random_string())

# let's sanity-check the generated Spark SQL query
flights_sdf %>% filter(time_hour >= as.Date("2013-12-18")) %>% dbplyr::remote_query() %>% print()
# run the query
flights_sdf %>% filter(time_hour >= as.Date("2013-12-18")) %>% print()
```
