### ISSUE TITLE
Can read data from nested json file on first layer but not deeper layers

### ISSUE THREAD

**Issue by gabrielwong1991** [sparklyr/sparklyr#1311]
Hi I am not sure if this is the right place to post this but I run into problem with this issue.

https://stackoverflow.com/questions/48869472/sparklyr-how-to-view-variables

Basically in short I can select first layer nested json file and display the data but when the json is deeply nested, it returns <list [1]> instead of the actual data. Is there a way to get the actual data?

In sparkR, I can totally view the data from the deeply nested json but I still want to use sparklyr syntax... I have run out of ideas so decided to post here. In sparkR I would do 
"select(data, c$c2.c22)" and get the result.

Thanks

**Comment by gabrielwong1991** [comment]
The best I could do is by doing:
data %>% sdf_select(c.c2.c22) %>% mutate(c22 = as.character(c22))

The best result I achieved is:
"[Good]"
"[Bad]"
NA

I cannot use data %>% mutate(c22 = list(unlist(c22))) as the warning suggest it is not a registered temporary function.

It would be best if sparklyr can add this feature.

**Comment by yl790** [comment]
@gabrielwong1991 Hey good news: `data %>% sdf_select(c.c2.c22)` works as expected now several after recent improvements to `sdf_collect` in Sparklyr.

You can get a preview of this improved version with `devtools::install_github(repo = "yl790/sparklyr", ref = "sdf_collect_be_gooder")`
