### ISSUE TITLE
Spark via sparklyr fails to work efficiently with very wide dataframes

### ISSUE THREAD

**Issue by alexmosc** [sparklyr/sparklyr#1322]
We work a lot with wide dataframes, 50K columns can be an everyday case. (Example: put all distinct files in a corporate system in separate columns, and users in rows; calculate average number of actions with the files; run kmeans)

In R (and Python) scripts those operations are being run fast using either `dplyr`, or `data.table` (or `pandas`).

We now research the possibilities of transferring our knowledge to the Spark environment (**on a single machine so far**), using `sparklyr` (or `pyspark`). Whether it is R or Py, the problem is that we cannot allocate very large dataframes in reasonable memory, in reasonable time.

For example, the example below works around 120 times slower in `sparklyr `than in R's memory.

Besides, if I would make 1 M rows instead of 100K rows, the system fails with `stack approaching its limit` error.

What is more, if I try to pivot to more than 10,000 columns, `sparklyr `fails with a warning that this maybe an error in my data design (?).

What is it that makes Spark so slow and memory consuming when dealing with very wide data? How would one go about a sentiment analysis with possibly hundreds of thousands of columns-words, suing Spark? 

**Optional question: can one create vector-column of features avoiding pivoting (which is not practically possible in the big data case)?**

This question can be considered `sparklyr's`.

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.4         sparklyr_0.7.0      data.table_1.10.4-3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14     dbplyr_1.2.0     compiler_3.4.0   pillar_1.1.0     plyr_1.8.4       bindr_0.1        base64enc_0.1-3  tools_3.4.0      digest_0.6.12   
[10] jsonlite_1.5     tibble_1.4.2     nlme_3.1-131     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.1.6      psych_1.7.8      shiny_1.0.5      DBI_0.7         
[19] rstudioapi_0.7   yaml_2.1.14      parallel_3.4.0   bindrcpp_0.2     withr_2.1.0      httr_1.3.1       stringr_1.2.0    rappdirs_0.3.1   rprojroot_1.2   
[28] grid_3.4.0       glue_1.2.0       R6_2.2.2         foreign_0.8-67   tidyr_0.7.2      purrr_0.2.4      reshape2_1.4.3   magrittr_1.5     backports_1.1.1 
[37] htmltools_0.3.6  assertthat_0.2.0 mnormt_1.5-5     mime_0.5         xtable_1.8-2     httpuv_1.3.5     config_0.2       stringi_1.1.6    openssl_0.9.9   
[46] lazyeval_0.2.1   broom_0.4.3
```

A reproducible example:

```
library(data.table)
library(sparklyr)
library(dplyr)

#spark_install(version = "2.1.0")

r_spark_connection <- spark_connect(master = "local")

dummy_dat <- data.table(
     x = paste0('_', round(runif(100000, 1, 599)))
     , y = paste0('_', round(runif(100000, 1, 9999)))
     , z = rnorm(100000, 0, 1)
)

spark_dummy_dat <- copy_to(r_spark_connection, dummy_dat, 'spark_dummy_dat', overwrite = T)

start_time <- Sys.time()

spark_dummy_dat_wide <- 
     spark_dummy_dat %>%
     sdf_pivot(
          formula = x ~ y
          , fun.aggregate = list(z = "sum")
     ) %>%
     na.replace(0) %>%
     ft_r_formula(
          formula = ~ . -x
          , features_col = "features"
             )

dummy_kmeans <- 
     spark_dummy_dat_wide %>%
     ml_kmeans(
          k = 5L
          , max_iter = 100L
          , tol = 1e-04
          #, init_steps = 2L
          #, init_mode = "k-means||"
          , seed = 777
          , features_col = 'features'
          , prediction_col = 'predict'
          , x = .
     )

Sys.time() - start_time
### 8 mninutes

start_time <- Sys.time()

## using data.table

spark_dummy_dat_wide <- 
     dcast(
          dummy_dat
          , formula = x ~ y
          , fun.aggregate = sum
     )

kmeans_dat <- as.matrix(spark_dummy_dat_wide[, -'x', with = F])

## stats::kmeans

dummy_kmeans <- 
     kmeans(x = kmeans_dat
            , centers = 5
            , iter.max = 100)

Sys.time() - start_time
### 4 sec
```

**Comment by harryprince** [comment]
maybe the best choice is using sparklyr::spark_apply to distribute your R code.

**Comment by alexmosc** [comment]
Hi, OK, let me try it. Alexey 28.02.2018, 10:44, "HarryZhu" <notifications@github.com>:maybe the best choice is using sparklyr::spark_apply to distribute your R code.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   -- С уважением,Алексей Бурнаков

**Comment by alexmosc** [comment]
I would rather be grateful for the under-the-hood explanation of why using very wide dataframes is a bad idea, or how it should be used wisely.

**Comment by dalloliogm** [comment]
I have never worked with such wide tables, and I am not a sparklyr/spark developer.

However, the operations you are describing would work better by storing the data into a long format, and partitioning the data by the groups you want to use for the averages.

For example, you would have to create a dataset like the following:

```
filename user tot_actions
file1.txt user1 3
file1.txt user2 5
file1.txt user3 4
file2.txt user1 2
file2.txt user2 4
file3.txt user3 1

```
Let's say that you want to calculate the average tot_actions by user; it would be best to store the table partitioned by user (e.g., spark_write_table(mytbl, partition_by="user")), then calculate using group_by(user) %>% summarise(mean=mean(tot_actions))

**Comment by alexmosc** [comment]
Thanks. I will shortly return to playing with sparklyr, and will check this idea in a deeper fashion.

**Comment by ttdtrang** [comment]
Many pre-implemented functions, .e.g `sparklyr::ml_cor`, make assumptions about the input data frame, i.e. variables in columns and observations in rows. Changing this convention will mess up a lot of routine tasks in data analysis. I second the question on why sparklyr has trouble with wide data set and whether it's a solvable problem in the near future.
