### ISSUE TITLE
Weird NA Handling

### ISSUE THREAD

**Issue by nviets** [sparklyr/sparklyr#1328]
Could someone fix this?

library(sparklyr)
library(DBI)
library(dplyr)

sc <- spark_connect(master = "local[4]")

iris_nas <- iris %>% 
  mutate(Sepal.Width = ifelse(Sepal.Width > 3.5, NA, Sepal.Width)) %>%
  mutate(testCol = Sepal.Width > 3) %>%
  select(testCol)

iris_nas %>% group_by(testCol) %>% tally

iris_tbl <- copy_to(sc, iris_nas)

iris_tbl %>% group_by(testCol) %>% tally

Output:

> iris_nas %>% group_by(testCol) %>% tally
# A tibble: 3 x 2
  testCol     n
  <lgl>   <int>
1 F          83
2 T          48
3 NA         19
> 
> iris_tbl <- copy_to(sc, iris_nas)
Error in sdf_import.default(x, sc, name, memory, repartition, overwrite,  : 
  table iris_nas already exists (pass overwrite = TRUE to overwrite)
> 
> iris_tbl %>% group_by(testCol) %>% tally
# Source:   lazy query [?? x 2]
# Database: spark_connection
  testCol     n
  <lgl>   <dbl>
1 F        83.0
2 F        19.0
3 T        48.0

**Comment by yitao-li** [comment]
Recent versions of `sparklyr` (in particular, I tried version 1.6.3) outputs the correct `NA 19` results now (modulo difference in row ordering).

**Comment by nviets** [comment]
thanks @yitao-li !
