### ISSUE TITLE
sdf_copy_to Issue

### ISSUE THREAD

**Issue by bblubaum** [sparklyr/sparklyr#1372]
After updating to SparklyR 7.0 sdf_copy_to seems to run forever without failure. This seems to be working fine in version 6.4. Have you had any experience with this?

Syntax: sdf_copy_to(sc,objectname,"sparkobjectname")

**Comment by javierluraschi** [comment]
@bblubaum haven't heard of this, for `yarn-cluster`, `sdf_copy_to()` remained unchanged, for local clusters, a change was made that does make copy a bit slower but more reliable.

Which kind of cluster are you using?

Could you share the error logs? Could you try reducing the data size and check if a smaller subset succeeds to be copied?

**Comment by bblubaum** [comment]
Good afternoon Javier,

This is being ran on our on prem Cloudera cluster using RStudio on the gateway node.  I do not believe there was any error reported as the job did not ever complete.

Sid or Cody,  Can you please confirm or is there anything to add?

Thank you,

Bryan Blubaum
Data Warehouse and Integration Analyst
Vectren Corporation
812-491-5622

**Comment by bblubaum** [comment]
I think Sarah said it just hangs and never come back.  The same copy works using sparklyr 0.6.4 and 0.7.0-9021

From: Blubaum, Bryan J.
Sent: Friday, March 23, 2018 3:03 PM
To: rstudio/sparklyr; rstudio/sparklyr
Cc: Mention; Hales, Sid; Krietemeyer, Cody
Subject: RE: [rstudio/sparklyr] sdf_copy_to Issue (#1372)

Good afternoon Javier,

This is being ran on our on prem Cloudera cluster using RStudio on the gateway node.  I do not believe there was any error reported as the job did not ever complete.

Sid or Cody,  Can you please confirm or is there anything to add?

Thank you,

Bryan Blubaum
Data Warehouse and Integration Analyst
Vectren Corporation
812-491-5622

**Comment by javierluraschi** [comment]
Thank you. In order to troubleshoot this, we are going to need the logs from the failed copy operation or a screenshot of the Spark UI to give us hints as to what is going on in Spark. Let me know if you need more pointers on where to get this information from.

**Comment by bblubaum** [comment]
How would you like these to be uploaded?

Bryan Blubaum
Data Warehouse and Integration Analyst
Vectren Corporation
812-491-5622

**Comment by bblubaum** [comment]
There was no output error in R, as the sdf_copy_to ran for hours without completing, multiple times! I am not sure if there are Spark log files?


________________________________
On: 23 March 2018 16:19,
"Blubaum, Bryan J." <bblubaum@vectren.com<mailto:bblubaum@vectren.com>> wrote:

How would you like these to be uploaded?

Bryan Blubaum
Data Warehouse and Integration Analyst
Vectren Corporation
812-491-5622

**Comment by mariobecerra** [comment]
I'm having the same problem. I'm trying to copy a relatively large dataframe (400 MB) to Spark, but when I run `sdf_copy_to` it just keeps running without failing.

**Comment by hughandersen** [comment]
I also have the same problem, sdf_copy_to() works on a small dataframe (1kb) , but not on a slightly bigger one (20MB). The code runs but doesn't complete or fail.

**Comment by yl790** [comment]
@hughandersen @mariobecerra Thanks for reporting this! I'll be more than happy to look into it.

Could you try running the following to see which version of sparklyr you are working with?

```
library(sparklyr)
print(packageVersion("sparklyr"))
```

Also preferably send me the data frame you are working with (or at least describe to me how I shall generate such a data frame) that is problematic, so that I can repro it myself.

**Comment by eduardo4jesus** [comment]
I know at least 5 more people in my class having this same problem, was this solved?

**Comment by yitao-li** [comment]
@eduardo4jesus Please send me a reprex, the Spark driver log, and the error message.

There are a number of things to try:
- install the latest version of sparklyr
- install the latest version of arrow (nowadays just running install.packages("arrow") is sufficient)
- re-connect to sparklyr, check arrow_enabled(sc) is true on the spark connection, and then try copy the large data frame again
- Try installing the latest version of Apache Spark which is 3.0.1 (if you haven't done so already)
