### ISSUE TITLE
Support for dataframe operations on nested columns

### ISSUE THREAD

**Issue by kevinykuo** [sparklyr/sparklyr#1378]
E.g.
```
library(graphframes)
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local", version = "2.1.0")
motifs <- gf_friends(sc) %>%
  gf_find("(a)-[e]->(b); (b)-[e2]->(a)")

motifs %>%
  sdf_schema() %>%
  str()
List of 4
 $ a :List of 2
  ..$ name: chr "a"
  ..$ type: chr "StructType(StructField(id,StringType,true), StructField(name,StringType,true), StructField(age,IntegerType,false))"
 $ e :List of 2
  ..$ name: chr "e"
  ..$ type: chr "StructType(StructField(src,StringType,true), StructField(dst,StringType,true), StructField(relationship,StringType,true))"
 $ b :List of 2
  ..$ name: chr "b"
  ..$ type: chr "StructType(StructField(id,StringType,true), StructField(name,StringType,true), StructField(age,IntegerType,false))"
 $ e2:List of 2
  ..$ name: chr "e2"
  ..$ type: chr "StructType(StructField(src,StringType,true), StructField(dst,StringType,true), StructField(relationship,StringType,true))"
```

We'd like to be able to do something like

```
motifs %>%
  filter(b.age > 30)
```

Scala example: `motifs.filter("b.age > 30")`

Related: https://github.com/rstudio/sparklyr/issues/1311

Also see https://github.com/mitre/sparklyr.nested

**Comment by javierluraschi** [comment]
@kevinykuo is there a Spark SQL command that would actually work here?

One, not ideal, option is to convert to JSON using `to_json()` and then reference nested fields with `get_json_object()`.

**Comment by dharadhruve** [comment]
if i want to get records of nested field like  personalInfo.studentId = 1 than we can write the query like below,

String q = "select * from student where array_contains(personalInfo['studentId'], 1)";
spark.sql(q).show(); 
OR
use below to get records from data frame
dfSource.where("array_contains(personalInfo['studentId'], 1)").show();

Let me know if it is useful or not...

**Comment by mattpollock** [comment]
higher order functions are related to this I think https://github.com/rstudio/sparklyr/issues/1773

**Comment by yl790** [comment]
Hey good news: `motifs %>% filter(b.age > 30)` actually works now after several improvements to `sdf_collect`  were made to handle nested data from Spark.

**Comment by yitao-li** [comment]
Related change: https://github.com/sparklyr/sparklyr/pull/2459
