### ISSUE TITLE
spark and scala versions in java/sparkhello-%s-%s.jar in spark_dependencies method causing classpath issues 

### ISSUE THREAD

**Issue by yeshwanth43** [sparklyr/sparklyr#1422]
spark and scala versions in ```java/sparkhello-%s-%s.jar``` in spark_dependencies method causing classpath issues 
---
I am trying to build extension for sparklyr,
in spark_compile if i specify jar name as sparkhello-1.6.0-2.10.5.jar with spark and scala version,
during spark_connect, it throws below warning, and when i invoke scala method, spark throws Classnotfound exception

```
path[1]="" No Such File or Directory
```
if i don't specify spark and scala version, after compile ,build jar and then extension  it works as expected.i am trying to follow the standard, but it seems sparklyr unable to pick up the jar because of spark and scala version variables in spark_dependencies method.

what did i miss here?

```
spark_version 1.6.0
sparklyr version  0.6.4
CDH version 5.14.0
```

**Comment by yitao-li** [comment]
There isn't no need to include patch component of the Scala version in the file name (e.g., 2.10.5 -> 2.10)

Also see existing sparklyr extensions (e.g., https://github.com/rstudio/mleap) for concrete examples of this.
