### ISSUE TITLE
setting the timezone?

### ISSUE THREAD

**Issue by randomgambit** [sparklyr/sparklyr#1423]
Hi the `sparklyr` team.

I came across an important question when I was playing with time and dates. According to https://stackoverflow.com/questions/49355077/how-to-convert-a-timestamp-into-string-without-changing-timezone, when using the important `hive` question, the **timezone** used is the default of the JVM.

Is there an option we can provide `sparklyr` with at the beginning of the `spark` session so that we can choose the timezone (say `UTC`)? That is important because running `spark_apply` as suggested in the example (to go around the default timezone) is very costly.

Thanks!

**Comment by yitao-li** [comment]
If I'm understanding this correctly you simply need to set spark.sql.session.timeZone in config passed to spark_connect()
