### ISSUE TITLE
spark can't recognize tally

### ISSUE THREAD

**Issue by harryzyming** [sparklyr/sparklyr#1426]
---
I'm trying to count the number of unique elements in each column in the spark dataset s.

However It seems that spark doesn't recognize tally()
```r
k<-collect(s%>%group_by(grouping_type)%>%summarise_each(funs(tally(distinct(.)))))
Error: org.apache.spark.sql.AnalysisException: undefined function TALLY
```

It seems that spark doesn't recognize simple r functions either, like "unique" or "length". I can run the code on local data, but when I try to run the exact same code on spark table it doesn't work.

```r
d<-data.frame(cbind(seq(1,10,1),rep(1,10)))
d$group<-rep(c("a","b"),each=5)
d%>%group_by(group)%>%summarise_each(funs(length(unique(.))))
# A tibble: 2 × 3
  group    X1    X2
  <chr> <int> <int>
1     a     5     1
2     b     5     1
k<-collect(s%>%group_by(grouping_type)%>%summarise_each(funs(length(unique(.)))))
Error: org.apache.spark.sql.AnalysisException: undefined function UNIQUE;...
```

**Comment by javierluraschi** [comment]
@harryzyming `tally()` is supported but not as a nested function, same for length but not yet in summaries.

Would you mind opening a bug in [dplyr](github.com/tidyverse/dplyr) to add support for this in `dbplyr`?

You would want to mention that the following is supported:

```r
data.frame(x = floor(runif(100, 0, 2)), y = runif(100)) %>%
  group_by(x) %>%
  summarise_each(funs(length(unique(.))))
```
```
# A tibble: 2 x 2
      x     y
  <dbl> <int>
1  0       47
2  1.00    53
```

But the following is not:

```r
memdb_frame(x = floor(runif(100, 0, 2)), y = runif(100)) %>%
  group_by(x) %>%
  summarise_each(funs(length(unique(.))))
```
```
Error in result_create(conn@ptr, statement) : near "UNIQUE": syntax error
```

CC: @edgararuiz

**Comment by harryzyming** [comment]
Hi @javierluraschi, thank you for your suggestion. I have opened an issue with them here
https://github.com/tidyverse/dplyr/issues/3529

**Comment by edgararuiz** [comment]
Issue https://github.com/tidyverse/dplyr/issues/3529 offered a solution
