### ISSUE TITLE
Arrow

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#1457]
Related

- https://github.com/rstudio/sparklyr/issues/1327
- https://github.com/rstudio/sparklyr/issues/1289
- https://github.com/rstudio/sparklyr/issues/1457
- https://github.com/rstudio/sparklyr/issues/1536 (`copy_to` with nested data)

**Comment by mattpollock** [comment]
Will this work apply both to `spark_apply` and to an R version of `toPandas`? My (limited) understanding is that `toPandas` uses arrow but that the python version of `collect` does basically the same thing the R version does.

**Comment by russellpierce** [comment]
@javierluraschi Is the expectation then that copy_to() would become suitable for bulk data transfer or would be best pattern still be to get the data off in to a disk storage format for Spark?

**Comment by javierluraschi** [comment]
@russellpierce `copy_to()` will never be as efficient as dedicated tools for loading data into a cluster; however, currently, `copy_to()` has narrow application since it can't really handle even "medium" size data, a few megabytes seems to be the limit. So my hope is that among many improvements introduced by a single data representation with Arrow, we can improve performance and support higher loads. I'm planning to spend this week doing some investigation, should be able to open a WIP PR and share progress and take feedback.

**Comment by randomgambit** [comment]
@javierluraschi that looks really amazing. will this be shipped with  sparklyr `0.9`?

**Comment by awblocker** [comment]
Wanted to check in out timeline for arrow serialization for `spark_apply`. Glad to help with testing or other open items. My team has a set of workloads (far more groups than executors) where this looks like it will have a very large impact.

**Comment by javierluraschi** [comment]
@awblocker `arrow` is already implemented; however, we are waiting for the Arrow 0.12 release to make this a bit more official. For now, you can test this out using the instructions from:

https://github.com/rstudio/sparklyr/pull/1611

**Comment by skattoor** [comment]
After reading the various issues related to this, I'm not quite sure what's the current status : I've installed SparklyR v1.0.1.9004 along with Arrow v0.13.0 and spark_apply still shows the described slowness.

Is there a version I should upgrade to to solve this issue?

Any help much appreciated!
