### ISSUE TITLE
Support sparklyr + sf

### ISSUE THREAD

**Issue by harryprince** [sparklyr/sparklyr#1475]
relate to https://github.com/r-spatial/sf/issues/699, I've found spark + geomesa + hbase + kafka could be a good tech stack for sparksql style processing data like sf on dplyr.

Currently, geomesa support scala/python to call sparksql using st_* function, I think sf/dplyr  will be a better way to play the spatial data than others.

* https://github.com/geomesa/geomesa-tutorials/tree/master/geomesa-quickstart-python
* https://github.com/locationtech-labs/geopyspark

**Comment by kevinykuo** [comment]
I look at geospatial+spark stuff once every few months, but haven't had the time to digest all the technologies available in the ecosystem, e.g. https://github.com/DataSystemsLab/GeoSpark and https://github.com/harsha2010/magellan. It'd be helpful if someone can provide use cases and describe how these tools apply.

**Comment by harryprince** [comment]
GeoSpark seems not mature than Geomesa(2013-now) family products. I found a comparison like this:
![image](https://user-images.githubusercontent.com/5362577/39672010-10416900-5155-11e8-98aa-8427d67b439f.png)

**Comment by harryprince** [comment]
Here is my current solution, migrate my local R sf function to Spark ESRI function without any code modification.

```
library(sparklyr)
config = sparklyr::spark_config()
config$`sparklyr.jars.default` = c("esri-geometry-api-2.1.0.jar",
                                   "spatial-sdk-hive-2.1.0-SNAPSHOT.jar",
                                   "spatial-sdk-json-2.1.0-SNAPSHOT.jar")
                                   
sc <- sparklyr::spark_connect(master = "yarn-client", version = "1.6.0",config = config)

# add UDF
DBI::dbGetQuery(sc,"add jar esri-geometry-api-2.1.0.jar") 
DBI::dbGetQuery(sc,"add jar spatial-sdk-hive-2.1.0-SNAPSHOT.jar")
DBI::dbGetQuery(sc,"add jar spatial-sdk-json-2.1.0-SNAPSHOT.jar")
  
DBI::dbGetQuery(sc,"create temporary function st_point as 'com.esri.hadoop.hive.ST_Point';")
DBI::dbGetQuery(sc,"create temporary function st_polygon as 'com.esri.hadoop.hive.ST_Polygon';")
DBI::dbGetQuery(sc,"create temporary function st_contains as 'com.esri.hadoop.hive.ST_Contains';")

# geofence computing

dplyr::tbl(sc,"ai.financer_tbl") %>% 
    filter(dt=="20180420") %>% 
    mutate(point_a = st_points(c(lat,lng)) %>%
    mutate(polygon_b = st_polygon(c(lat1,lng1,lat2,lng2))) %>%
    transmute(geohash= st_contains(polygon_b, point_a))
```

**Comment by harryprince** [comment]
@kevinykuo 

GeoSpark seems to be a light way to implement.

these complied jars can be downloaded from here directly:
https://github.com/DataSystemsLab/GeoSpark/releases

spark-shell --jars geospark-sql_2.3-1.1.3.jar,geospark-1.1.3.jar,geospark-viz-1.1.3.jar

```
// load library
import org.apache.log4j.{Level, Logger}
import org.apache.spark.serializer.KryoSerializer
import org.apache.spark.sql.SparkSession
import org.datasyslab.geospark.formatMapper.shapefileParser.ShapefileReader
import org.datasyslab.geospark.spatialRDD.SpatialRDD
import org.datasyslab.geospark.utils.GeoSparkConf
import org.datasyslab.geosparksql.utils.{Adapter, GeoSparkSQLRegistrator}
import org.datasyslab.geosparkviz.core.Serde.GeoSparkVizKryoRegistrator

// init sql

val sqlContext = new org.apache.spark.sql.SQLContext(sc)

GeoSparkSQLRegistrator.registerAll(sqlContext)

// create table
var csvPolygonInputLocation = "file://my_path/citycode-adcode.csv"

var polygonCsvDf = sqlContext.read.format("csv").option("delimiter",",").option("header","false").load(csvPolygonInputLocation)
polygonCsvDf.createOrReplaceTempView("polygontable")

// trying to gis query
sqlContext.sql("SELECT st_point(1.0,1.0)").show()

```

And st_geomFromWKT also works for me, it looks like very promising in recent release version.

**Comment by harryprince** [comment]
Very exciting result! I am trying to use `geospark` with Quadtree index to accelerate join query, which significantly 100x than Hive ESRI UDF no index version. And the indexing function seems to be a particular part of `sdf_repartition` which partition hash function by a Quadtree algorithm instead of default Murmur hash.

**Comment by jnh5y** [comment]
@harryprince cool!  Admittedly, GeoSpark is has more implemented in terms of in-memory indexing.  If you just needed geospatial Spark UDFs, you can get those via GeoMesa as well with these instructions: https://www.geomesa.org/documentation/user/spark/spark_jts.html#configuration.

**Comment by metasim** [comment]
@harryprince To build on @jnh5y 's point, the GeoMesa implementation not only supports SQL and dataframe APIs (in both JVM and Python), it'll work in the lightweight "in memory" mode like GeoSpark yet scale up to with its various connectors to [several big data data stores](https://www.geomesa.org/documentation/user/datastores/index.html). IOW, IMHO, it has a broader "big picture" view of geospatial querying than GeoSpark.

**Comment by etiennebr** [comment]
I think the main piece is to register the geomesa (or any other library) along with the Spark DataFrame API so that when the query is executed spark finds the UDF. Should that be `sf`'s role? @kevinykuo any  examples of packages registering UDFs?

**Comment by metasim** [comment]
@etiennebr To the best of my knowledge, Spark (sadly) doesn't have any kind of "SPI loader" to automatically register UDFs found in the classpath. In RasterFrames we declare an extension method on `SparkSession` called [`withRasterFrames`](https://github.com/locationtech/rasterframes/blob/46c8e8f186ab955aa5c6f6fa25856ef2a4237674/core/src/main/scala/astraea/spark/rasterframes/extensions/SparkSessionMethods.scala#L31) that handles the requisite registration (including optimization rules). GeoMesa Spark SQL has a similar `withJTS` extension method.

**Comment by harryprince** [comment]
I am trying to register GIS SQL context, however, it fails to find the class or method when I upload all geospark related jars with same spark version.

```
sc %>% sparklyr::invoke_static(class = "org.datasyslab.geosparksql.utils.GeoSparkSQLRegistrator",method = "registerAll")
```

ERROR:

```
Error: java.lang.Exception: No matched method found for class org.datasyslab.geosparksql.utils.GeoSparkSQLRegistrator.registerAll at sparklyr.Invoke.invoke(invoke.scala:136) at sparklyr.StreamHandler.handleMethodCall(stream.scala:123) at sparklyr.StreamHandler.read(stream.scala:66) at sparklyr.BackendHandler.channelRead0(handler.scala:51) at sparklyr.BackendHandler.channelRead0(handler.scala:4) at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336) at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911) at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131) at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) at java.lang.Thread.run(Thread.java:748)
```

SessionInfo:
```
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /data/opt/R/3.4.2/lib64/R/lib/libRblas.so
LAPACK: /data/opt/R/3.4.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_0.9.3.9000 mapview_2.3.0       sf_0.7-2            bindrcpp_0.2.2      dplyr_0.7.8        

loaded via a namespace (and not attached):
 [1] xfun_0.4          tidyselect_0.2.5  forge_0.1.0       purrr_0.2.5       lattice_0.20-35   colorspace_1.3-2  viridisLite_0.3.0 htmltools_0.3.6   stats4_3.4.2     
[10] yaml_2.2.0        base64enc_0.1-3   rlang_0.3.0.1     R.oo_1.21.0       e1071_1.7-0       later_0.7.5       pillar_1.1.0      withr_2.1.2.9000  glue_1.3.0       
[19] DBI_1.0.0         R.utils_2.7.0     sp_1.3-1          dbplyr_1.2.2      foreach_1.4.4     bindr_0.1.1       munsell_0.5.0     raster_2.8-4      R.methodsS3_1.7.1
[28] htmlwidgets_1.3   codetools_0.2-15  knitr_1.21        httpuv_1.4.5      crosstalk_1.0.0   class_7.3-14      gdalUtils_2.0.1.7 broom_0.5.0       r2d3_0.2.2       
[37] Rcpp_1.0.0.1      xtable_1.8-3      openssl_1.1       scales_1.0.0      promises_1.0.1    backports_1.1.2   classInt_0.3-1    satellite_1.0.1   webshot_0.5.0    
[46] leaflet_2.0.2     jsonlite_1.6      mime_0.6          png_0.1-7         digest_0.6.18     shiny_1.2.0       grid_3.4.2        rprojroot_1.3-2   rgdal_1.3-6      
[55] tools_3.4.2       magrittr_1.5      lazyeval_0.2.1    tibble_1.4.2      tidyr_0.8.2       pkgconfig_2.0.2   assertthat_0.2.0  httr_1.4.0        rstudioapi_0.8   
[64] iterators_1.0.9   R6_2.3.0          units_0.6-2       nlme_3.1-131      compiler_3.4.2   
```

**Comment by vecchiocarmelo** [comment]
this works for me:
`polygons<-read.table(text="california area|POLYGON ((-126.4746 32.99024, -126.4746 42.55308, -115.4004 42.55308, -115.4004 32.99024, -126.4746 32.99024))
new york area|POLYGON ((-80.50781 36.24427, -80.50781 41.96766, -70.75195 41.96766, -70.75195 36.24427, -80.50781 36.24427))
texas area |POLYGON ((-106.5234 25.40358, -106.5234 36.66842, -91.14258 36.66842, -91.14258 25.40358, -106.5234 25.40358))
dakota area|POLYGON ((-106.084 44.21371, -106.084 49.66763, -95.71289 49.66763, -95.71289 44.21371, -106.084 44.21371))
", sep="|",col.names=c("area","geom"))
points<-read.table(text="New York|NY|POINT (-73.97759 40.74618)
New York|NY|POINT (-73.97231 40.75216)
New York|NY|POINT (-73.99337 40.7551)
West Nyack|NY|POINT (-74.06083 41.16094)
West Point|NY|POINT (-73.9788 41.37611)
West Point|NY|POINT (-74.3547 41.38782)
Westtown|NY|POINT (-74.54593 41.33403)
Floral Park|NY|POINT (-73.70475 40.7232)
Floral Park|NY|POINT (-73.60177 40.75476)
Elmira|NY|POINT (-76.79217 42.09192)
Elmira|NY|POINT (-76.75089 42.14728)
Elmira|NY|POINT (-76.84497 42.12927)
Elmira|NY|POINT (-76.80393 42.07202)
Elmira|NY|POINT (-76.83686 42.08782)
Elmira|NY|POINT (-76.75089 42.14728)
Alcester|SD|POINT (-96.63848 42.97422)
Aurora|SD|POINT (-96.67784 44.28706)
Baltic|SD|POINT (-96.74702 43.72627)
Beresford|SD|POINT (-96.79091 43.06999)
Brandon|SD|POINT (-96.58362 43.59001)
Minot|ND|POINT (-101.2744 48.22642)
Abercrombie|ND|POINT (-96.73165 46.44846)
Absaraka|ND|POINT (-97.21459 46.85969)
Amenia|ND|POINT (-97.25029 47.02829)
Argusville|ND|POINT (-96.95043 47.0571)
Arthur|ND|POINT (-97.2147 47.10167)
Ayr|ND|POINT (-97.45571 47.02031)
Barney|ND|POINT (-96.99819 46.30418)
Blanchard|ND|POINT (-97.25077 47.3312)
Buffalo|ND|POINT (-97.54484 46.92017)
Austin|TX|POINT (-97.77126 30.32637)
Austin|TX|POINT (-97.77126 30.32637)
Addison|TX|POINT (-96.83751 32.96129)
Allen|TX|POINT (-96.62447 33.09285)
Carrollton|TX|POINT (-96.89163 32.96037)
Carrollton|TX|POINT (-96.89773 33.00542)
Carrollton|TX|POINT (-97.11628 33.20743)
Celina|TX|POINT (-96.76129 33.32793)
Carrollton|TX|POINT (-96.89328 33.03056)
Carrollton|TX|POINT (-96.77763 32.76727)
Los Angeles|CA|POINT (-118.2488 33.97291)
Los Angeles|CA|POINT (-118.2485 33.94832)
Los Angeles|CA|POINT (-118.276 33.96271)
Los Angeles|CA|POINT (-118.3076 34.07711)
Los Angeles|CA|POINT (-118.3085 34.05891)
Los Angeles|CA|POINT (-118.2943 34.04835)
Los Angeles|CA|POINT (-118.2829 34.02645)
Los Angeles|CA|POINT (-118.3371 34.00975)
Los Angeles|CA|POINT (-118.2987 33.78659)
Los Angeles|CA|POINT (-118.3148 34.06271)", sep="|",col.names=c("city","state","geom"))


library(sparklyr)
library(dplyr)
conf=spark_config()
conf$spark.jars.packages<-"org.datasyslab:geospark-sql_2.3:1.1.3,com.vividsolutions:jts-core:1.14.0,org.datasyslab:geospark:1.1.3"
conf$spark.serializer<-"org.apache.spark.serializer.KryoSerializer"
conf$spark.kryo.registrator<-"org.datasyslab.geospark.serde.GeoSparkKryoRegistrator"
sc <- spark_connect(master = "local",config = conf)
sparklyr::invoke_static(sc,"org.datasyslab.geosparksql.utils.GeoSparkSQLRegistrator","registerAll",spark_session(sc))

polygons_tbl <-copy_to(sc, polygons)
polygons_tbl <-copy_to(sc, points)


ex1<-spark_session(sc) %>% invoke("sql", "  SELECT  area,state,count(*) cnt from
       (select area,ST_GeomFromWKT(polygons.geom ,'4326') as y  from polygons)  polygons,
       (SELECT ST_GeomFromWKT (points.geom,'4326') as x,state,city from points) points
       where  ST_Contains(polygons.y,points.x) group by area,state")

ex2<-copy_to(sc,tbl(sc, sql("  SELECT  area,state,count(*) cnt from
                            (select area,ST_GeomFromWKT(polygons.geom ,'4326') as y  from polygons)  polygons,
                            (SELECT ST_GeomFromWKT (points.geom,'4326') as x,state,city from points) points
                            where  ST_Contains(polygons.y,points.x) group by area,state")),"test2")

collect(ex2)
spark_disconnect_all()
`

**Comment by harryprince** [comment]
thanks for `vecchiocarmelo`'s job. Now, geospark works on my cluster.

**Comment by yitao-li** [comment]
Also see https://github.com/apache/incubator-sedona/tree/master/R
