### ISSUE TITLE
Consider adding repositories setting to dependencies for extensions

### ISSUE THREAD

**Issue by kevinykuo** [sparklyr/sparklyr#1476]
Currently, not every spark package is on Central, e.g. https://github.com/tensorflow/ecosystem/issues/29#issuecomment-386852952. The ideal scenario is for upstream dependencies to publish artifacts there, but as a fallback we could consider letting sparklyr extension authors specify resolvers.

**Comment by jakubhava** [comment]
We are hitting this limitations in RSparkling https://github.com/h2oai/rsparkling. It would unblock us if this can be done. Or I can even give it a try and provide a PR for it

**Comment by kevinykuo** [comment]
@jakubhava go for it, will be happy to review :)

**Comment by yitao-li** [comment]
This has been supported in recent versions of sparklyr.
