### ISSUE TITLE
what is equivalent to isLocalIterator() in sparklyr?

### ISSUE THREAD

**Issue by sparkcassuser** [sparklyr/sparklyr#1524]
greetings!!

i found GC overhead limit exeeded error during collect() operation. i found that  the local interator  will pull one spark partition at a time to the driver using isLocalIterator() function in scala. how to perform same in sparklr?

**Comment by harryprince** [comment]
using `sparklyr::invoke` function to call native scala function

**Comment by sparkcassuser** [comment]
for example,
trees_tbl
# Source:   table<trees> [?? x 3]
# Database: spark_connection
   Girth Height Volume
   <dbl>  <dbl>  <dbl>
 1   8.3     70   10.3
 2   8.8     63   10.2
 3  10.7     81   18.8
 4  11.0     66   15.6
 5  11.1     80   22.6
 6  11.3     79   24.2
 7  11.4     76   21.4
 8  12.0     75   19.1
 9  12.9     85   33.8
10  13.7     71   25.7
# ... with 21 more rows
> class(trees_tbl)
[1] "tbl_spark" "tbl_sql"   "tbl_lazy"  "tbl"
> trees_tbl %>% arrange(Volume) %>% filter(Volume <= 15.0) %>% invoke("toLocalIterator") %>% sdf_register()
Error in UseMethod("invoke") :
  no applicable method for 'invoke' applied to an object of class "c('tbl_spark', 'tbl_sql', 'tbl_lazy', 'tbl')"
why i am getting this error?

**Comment by javierluraschi** [comment]
@sparkcassuser why do you need to pull data into the driver? If it's to execute an R function, I would rather recommend you try `spark_apply()`.
