### ISSUE TITLE
copy_to fails on nested data

### ISSUE THREAD

**Issue by mattpollock** [sparklyr/sparklyr#1536]
Spark has good support for nested structures using the `struct` and `array` types. Here I've nested `iris` in a way that would naturally map to a spark data.frame with one character column and one array column where each element in the array is a struct (i.e., row of the nested data.frame)
```
iris_nst <- iris %>%
  rename_all(function(x){gsub("\\.", "_", x)}) %>%
  tidyr::nest(Sepal_Length, Sepal_Width, Petal_Length, Petal_Width)
iris_nst
# # A tibble: 3 x 2
#   Species    data                 
#   <fct>      <list>               
# 1 setosa     <data.frame [50 × 4]>
# 2 versicolor <data.frame [50 × 4]>
# 3 virginica  <data.frame [50 × 4]>
```

However, `copy_to` only supports basic types
```
copy_to(sc, iris_nst)
 Error: java.lang.IllegalArgumentException: Invaid type list
	at sparklyr.SQLUtils$.getSQLDataType(sqlutils.scala:61)
	at sparklyr.SQLUtils$.createStructField(sqlutils.scala:66)
	at sparklyr.SQLUtils.createStructField(sqlutils.scala)
	at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sparklyr.Invoke.invoke(invoke.scala:137)
```

The clunky work-arounds that I've used are (1) map the nested columns to JSON before strings before calling `copy_to` and (2) writing the entire data.frame to JSON (locally or on HDFS) and reading it in using `spark_read_json`. Option (1) changes the data and makes the data hard to use in spark-land, option (2) is more functional, but requires an extra step.

Are there any plans to support list-types in `sparklyr.SQLUtils$.createStructField`?

**Comment by harryprince** [comment]
hive can process the complex structure data type by `explode` hive function.

**Comment by mattpollock** [comment]
I agree, but don't follow how that helps here. `explode` is useful once data is already represented as a Spark dataframe, but isn't useful for taking a local nested `data.frame` and pushing it to spark.

**Comment by javierluraschi** [comment]
We might be able to add support for nested data in `copy_to()` as we trsansition to use Arrow... https://github.com/rstudio/sparklyr/issues/1457.

**Comment by yl790** [comment]
This is working as expected now:

```
> iris_nst
# A tibble: 3 x 2
  Species    data             
  <fct>      <list>           
1 setosa     <tibble [50 × 4]>
2 versicolor <tibble [50 × 4]>
3 virginica  <tibble [50 × 4]>
> copy_to(sc, iris_nst)
# Source: spark<iris_nst> [?? x 2]
  Species    data                                                               
  <chr>      <chr>                                                              
1 setosa     "[{\"Sepal_Length\":5.1,\"Sepal_Width\":3.5,\"Petal_Length\":1.4,\…
2 versicolor "[{\"Sepal_Length\":7,\"Sepal_Width\":3.2,\"Petal_Length\":4.7,\"P…
3 virginica  "[{\"Sepal_Length\":6.3,\"Sepal_Width\":3.3,\"Petal_Length\":6,\"P…

```

**Comment by mattpollock** [comment]
Is that really as expected? The local `tibble` is a nested structure. The spark data frame has two character columns. My expectation would have been that the spark data frame would have a character `Species` column and that the column `data` would have an array of struct-types.

**Comment by yl790** [comment]
Hmm I see... Looks like there are still some inconsistencies.

**Comment by yl790** [comment]
This will no longer be the case after https://github.com/sparklyr/sparklyr/pull/2392
