### ISSUE TITLE
Spark Streaming from oracle to Cassandra

### ISSUE THREAD

**Issue by nirmalb06** [sparklyr/sparklyr#1545]
Hi,

I have moved data from Oracle to Cassandra using spark, Now i want to Stream it to get those data as real time.

I just used a sample table in HR schema from oracle and moved the data to Cassandra table which has same structure. Now i want to Stream the date in real time to process the records and show it in reports. Please guide me in completing this live stream.

Thanks,
Nirmal.B

**Comment by javierluraschi** [comment]
@nirmalb06 Implementing Spark streaming in the next couple weeks, keep track of progress with https://github.com/rstudio/sparklyr/issues/1131

**Comment by nirmalb06** [comment]
@javierluraschi Thanks for your help. Will keep on track !

**Comment by javierluraschi** [comment]
@nirmalb06 streaming is now implemented; however, the cassandra connector does not seem to support structured streaming yet. So my guess is that you would be able to get a stream out of oracle using `stream_read_jdbc()` but pushing this to cassandra would be enable until this is implemented: https://datastax-oss.atlassian.net/browse/SPARKC-510

If you want to learn more about streaming in sparklyr, the best writeup I currently have is here: https://javierluraschi.github.io/the-r-in-spark/streaming.html
