### ISSUE TITLE
Opt out of return value conversion

### ISSUE THREAD

**Issue by lawremi** [sparklyr/sparklyr#1557]
Sometimes we want to disable the automatic conversion of a return value from `invoke()`, particularly in the case of collections, when the data can be large. For example, we might want to push a vector to a Java array, or an environment to a `java.util.Map`, and use it multiple times.

**Comment by harryprince** [comment]
it's the Hive story, please check the settings of hive preferences.

**Comment by yitao-li** [comment]
This was part of the recently released sparklyr 1.7. See https://spark.rstudio.com/reference/j_invoke.html for details.
