### ISSUE TITLE
spark_apply() of spaklyr does not work with tm library

### ISSUE THREAD

**Issue by sahosa03** [sparklyr/sparklyr#1621]
Hello,
I am trying to use 'tm' library functionalities with spark_apply() function of sparklyr. 
I have created a sparkdataframe named as train from a text file:

train details:

 Source:   table<sparklyr_tmp_53c4b4abfe> [?? x 1]
 Database: spark_connection
  line                                     
1 Thank you. To Mama Gra�a Machel,
2 "On Tuesday, xyz abc " 

Then I have defined my customised function as:

**myfunction<-function(data){
test<-tm::Corpus(VectorSource(data))
test<-Corpus(VectorSource(test))
test<-tm_map(test,content_transformer(stripWhitespace))
dtm<-DocumentTermMatrix(test)
dtm<-as.matrix(dtm)
dtm<-as.data.frame(dtm)
return(dtm)
}**

But when I am running the spark_apply function as follows:
**spark_apply(train,myfunction)** , it is throwing the below error ,

**Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\hp\AppData\Local\Temp\RtmpIzVe9J\file53c76462a6c_spark.log': Permission denied**

I have verified the cmd files in spark bin ,and I have all the required permissions as it is my own local machine.

Just to cross  verify I ran the below code and it works fine:

**myfunction1<-function(data){
test<-tm::MC_tokenizer(data)
}**

**spark_apply(train,myfunction1)**

**Result:**
Source:   table<sparklyr_tmp_53c119568d> [?? x 1]
Database: spark_connection
   line   
 1 Thank  
 2 you    
 3 To     
 4 Mama   
 5 Gra    
 6 a      
 7 Machel 

Note:
spark_version(spark_conn)
[1] ‘2.3.0’
packageVersion('sparklyr')
[1] ‘0.8.4’
Attached the sample text file as well. Would be great if anyone can look into this issue .

[test.txt](https://github.com/rstudio/sparklyr/files/2216731/test.txt)

**Comment by harryprince** [comment]
you are expanding the original data frame to a long-format, which might occur some memory error at  some spark executors.

**Comment by sahosa03** [comment]
Thank you for the suggestion.But I am running it in my local machine.
And the data set has only 2 rows,so I do not think memory issue is happening here.

Can you please suggest if you have any other solution for this issue.

**Comment by javierluraschi** [comment]
Tried this:

```r
library(sparklyr)
sc <- spark_connect(master = "local")

train <- sdf_copy_to(sc, data.frame(lines = c(
  "Thank you. To Mama Graa Machel",
  "On Tuesday, xyz abc"
)))

myfunction<-function(data){
test<-tm::Corpus(VectorSource(data))
test<-Corpus(VectorSource(test))
test<-tm_map(test,content_transformer(stripWhitespace))
dtm<-DocumentTermMatrix(test)
dtm<-as.matrix(dtm)
dtm<-as.data.frame(dtm)
return(dtm)
}

spark_apply(train, myfunction)
```

but get in the logs:

```
18/07/25 09:56:47 INFO sparklyr: RScript (3534) computing closure 
18/07/25 09:56:47 ERROR sparklyr: RScript (3534) terminated unexpectedly: could not find function "VectorSource" 
```

Which I replaced with:

```r
myfunction<-function(data){
    library(tm)
    test<-Corpus(VectorSource(data))
    test<-Corpus(VectorSource(test))
    test<-tm_map(test,content_transformer(stripWhitespace))
    dtm<-DocumentTermMatrix(test)
    dtm<-as.matrix(dtm)
    dtm<-as.data.frame(dtm)
    return(dtm)
}
```

and correctly then successfully ran:

```r
spark_apply(lines_tbl, myfunction)
```

```
# Source:   table<sparklyr_tmp_4dac32893afb> [?? x 10]
# Database: spark_connection
    abc  graa machel  mama thank tuesday   xyz   you language  list
  <dbl> <dbl>  <dbl> <dbl> <dbl>   <dbl> <dbl> <dbl>    <dbl> <dbl>
1     1     1      1     1     1       1     1     1        0     0
2     0     0      0     0     0       0     0     0        1     1
3     0     0      0     0     0       0     0     0        0     1
```

Does this help?

**Comment by sahosa03** [comment]
Thanks a lot !!I can see you have got the output I am looking for.

But when I run the below code in my laptop
myfunction<-function(data){
     library(tm)
     test<-Corpus(VectorSource(data))
      test<-tm_map(test,content_transformer(stripWhitespace))
      dtm<-DocumentTermMatrix(test)
      dtm<-as.matrix(dtm)
      dtm<-as.data.frame(dtm)
   return(dtm)
 }
> spark_apply(train,myfunction)

**The below error is thrown:**
Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 35.0 failed 1 times, most recent failure: Lost task 0.0 in stage 35.0 (TID 36, localhost, executor driver): java.lang.RuntimeException: Error while encoding: java.lang.ArrayIndexOutOfBoundsException: 5

Could you please tell me what is the issue here.

**Comment by sahosa03** [comment]
Thanks a lot for the help!! :)
When I run the below code,
myfunction<-function(data){
+     library(tm)
+     test<-Corpus(VectorSource(data))
+     test<-tm_map(test,content_transformer(stripWhitespace))
+     dtm<-DocumentTermMatrix(test)
+     dtm<-as.matrix(dtm)
+     dtm<-as.data.frame(dtm)
+     return(dtm)
+ }
> spark_apply(train,myfunction)
**Result is :**
line    X2    X3    X4    X5    X6    X7    X8    X9
  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1     1     1     1     1     1     1     1     1     1
But I am not getting the words as columns ,rather X1,X2,.... What could possibly be wrong here.Can you please help?

**Comment by javierluraschi** [comment]
The current version of `sparklyr` requires you to specify each column manually, you can run the latest version of sparklyr using:

```
devtools::install_github("rstudio/sparklyr")
```

**Comment by javierluraschi** [comment]
One note... `spark_apply()` requires each partition to return a data frame with the same columns, in this case, seems like it could be possible that each partition would generate a different document term matrix; if that's the case, you want to return tidy data, something like:

```
entry name value
1     abc  1
1     graa 1
2     abc  0
2     abc  0

```

Instead of,

```
abc graa
1   1
0   0
```

You can perform this transformation in R inside `spark_apply()`, in this case, the column would be constant so you can run `spark_apply()` with:

```
spark_apply(lines_tbl, myfunction, columns = c("entry", "name", "value"))
```

This last approach would be much more recommended.
