### ISSUE TITLE
copy_to doesn't copy entire data

### ISSUE THREAD

**Issue by jadermcs** [sparklyr/sparklyr#1625]
When I try to import a data set to spark it does not copy entire data.

```r
library(nycflights13)

spark_version <- "2.1.0"

sc <- spark_connect(master = "yarn-client",
                    app_name = "jader_test",
                    version =spark_version,
                    spark_home ="/opt/spark")

flights_s <- copy_to(sc, flights, "flights", overwrite = T)

flights %>% tally()
# 336776
flights_s %>% tally()
# 39999
```

I'm using rstudio-server and a single node hadoop/spark enviroment.

**Comment by kevinykuo** [comment]
`copy_to()` will be redone with https://github.com/rstudio/sparklyr/pull/1611 which should resolve this. In the meantime, you can `spark_read_csv()` the input file directly.
