### ISSUE TITLE
Nested Data

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#1628]
Got feedback on JSM 2018 to have much better support for nested data, some investigation needed to define exactly what this means and what features are needed.

**Comment by mattpollock** [comment]
I use `sparklyr` extensively with nested data. My swing at it is here https://mitre.github.io/sparklyr.nested/. Would be happy to move functionality into the main repo if you want though. I should get my act together and release to CRAN.

One of the biggest remaining holes I think is that after a `collect` on a nested dataframe, the result is a bit of a mess with a local `tibble` where list columns contain references to uncollected data. I don't have a solution for that one yet.

**Comment by tdsmith** [comment]
Although I was at JSM I missed this conversation :) We have lots of nested data structures at Mozilla; I tend to resort to writing Spark SQL to extract and normalize fields and then operate on the resulting SDFs with dplyr syntax. This was my motivation in #1585, though I'd rather have a native syntax for accessing struct fields in select and filter. I hadn't seen Matt's extension and I'll look forward to giving it a spin.

link #1284, #1378, #1311

**Comment by yl790** [comment]
Another required change was https://github.com/sparklyr/sparklyr/pull/2420 to support array of struct types

**Comment by yl790** [comment]
All required changes are tested and merged into master now
