### ISSUE TITLE
Support Window Frame in Sparklyr

### ISSUE THREAD

**Issue by harryprince** [sparklyr/sparklyr#1638]
I am using sparklyr sql to call window frame like this:

```
SELECT
user_id,dt, value,SUM(VALUE) OVER(PARTITION BY user_id ORDER BY order RANGE BETWEEN 29 PRECEDING AND  CURRENT ROW ) as sum_value
FROM sdf
```

I've also found `dbplyr` can support these window functions in here: https://dbplyr.tidyverse.org/articles/dbplyr.html.

However, how to connect `dbplyr` and `sparklyr` togather in R code instead of SQL? Currently fail to find the answer, the most of answers point out `Rollcpp` or `zoo` package, Need help.

**Comment by kevinykuo** [comment]
Does http://spark.rstudio.com/dplyr/#window-functions help?

**Comment by harryprince** [comment]
@kevinykuo it seems does not support more complex expression like `window_frame` and `range_between`.

Assuming if I want to rolling count each user recent 30 days events for one year in each day, currently can not find the `sparklyr` directly way.

**Comment by kevinykuo** [comment]
Could you provide an example that works with dplyr on local data frames? We're limited by what Spark SQL supports, but if we haven't covered something we'll add it.

**Comment by harryprince** [comment]
it seems dplyr does not support directly, the current solution point out `RcppRoll` library.
https://stackoverflow.com/questions/30153835/r-dplyr-rolling-sum

**Comment by harryprince** [comment]
The sliding window is very powerful when I extract these features into my xgb model, hope it can be added into `dplyr` or `sparklyr`.

**Comment by fabiangehring** [comment]
I'm also interested in the sliding window functionality

**Comment by yl790** [comment]
@fabiangehring @harryprince @tdsmith Please check out [sparklyr.flint](https://github.com/r-spark/sparklyr.flint)

It's a sparklyr extension powered by [Flint](https://github.com/twosigma/flint) and currently supports sum and count summarizations within a moving time window. It's still under active development and should be able to support more complicated summarizers such as EWMA and also hopefully streaming use cases in future.

**Comment by markbaas** [comment]
Hi @yitao-li, I don't think flint implements the exact functionality that is requested here. Why is this request closed? Flint looks interesting, but the library hasn't got any updates for the past 2 years.

**Comment by yitao-li** [comment]
@markbaas Flint does support summarization over a sliding time window.

Please see the R example in the "Intro to sparklyr.flint
" section of https://blogs.rstudio.com/ai/posts/2020-09-07-sparklyr-flint/#Intro-to-sparklyr.flint
