### ISSUE TITLE
zero-length key name in map type fails

### ISSUE THREAD

**Issue by mattpollock** [sparklyr/sparklyr#1643]
It is possible for maps to have zero-length keys. Although such a map is of limited value, I've run into real cases where this is the case and `sparklyr` gets angry about it. This can be reproduced via

```
iris_spk <- copy_to(sc, iris) # where sc is a spark connection
iris_spk %>%
  mutate(Species=if_else(Species=="setosa", "", Species)) %>% # drum up some empty keys
  group_by(Species) %>% 
  mutate(width_map=map(Species, Petal_Width)) %>% 
  collect() 
# Error in env[[key]] <- value : attempt to use zero-length variable name
```

It looks like maps are translated in the R as named lists. In the event of a zero-length name could that list entry simply not get a name?

I'm using `sparklyr` 0.8.4 with spark 2.3.1.

**Comment by mattpollock** [comment]
`pyspark` handles this like so:

![image](https://user-images.githubusercontent.com/9449081/44222142-a526b380-a151-11e8-925a-0c8ff8fd16e2.png)

**Comment by yitao-li** [comment]
`sparklyr` currently collects Spark map type with string keys as R environment. It can alternatively also collect maps as list in R.

- Collecting Spark map type as environment:
  - pro: correctly signifies the key-value pairs are unordered
  - con: empty string cannot be present as key (as observed above)
 
- Collecting Spark map type:
  -  pro: empty string can be key
  - con: keys take on some arbitrary order within a `list`, which is a container that is considered as ordered in R :shrug: 

I guess the 2nd option is better overall for correctness. None of them is ideal though.
