### ISSUE TITLE
Creating table in teradata: Error: Data Type "TEXT" does not match a Defined Type name.

### ISSUE THREAD

**Issue by rblenin** [sparklyr/sparklyr#1661]
# Reporting an Issue with sparklyr
When I try to push iris_tbl to teradata database, I get the following error:
Error: java.sql.SQLException: [Teradata Database] [TeraJDBC 16.10.00.05] [Error 3706] [SQLState 42000] Syntax error: Data Type "TEXT" does not match a Defined Type name.

```r
spark_version <- ‘2.2.1’
Sys.setenv(SPARK_HOME = "/usr/local/spark")
config <- spark_config()
config$sparklyr.cores.local <- 20
config$spark.sql.shuffle.partitions.local <- 5
config$spark.executor.cores <- 1
config$spark.executor.memory <- "4G"
config$spark.driver.memory <- "40G"
config$`sparklyr.shell.driver-memory` <- "16G"
config$`sparklyr.shell.executor-memory` <- "16G"
sc <- spark_connect(master = "local",
                    spark_home = "/usr/local/spark",
                    deployMode="client",
                    config = config)

# your reproducible example here
```
iris_tbl <- copy_to(sc, iris, 'iris', overwrite = TRUE)
spark_write_jdbc('iris_tbl',
                   name    = dbTableName,
                   options = list(url      = myurl,
                                  user     = myUserId,
                                  password = myPassword), mode = "append")

**Comment by javierluraschi** [comment]
I would try to figure out which column is introducing this issue, by saving subsets of the data. Seems like this could be a JDBC issue, the JDBC driver might provide a way to tweak the configuration for `TEXT` types.

Related: https://kylo-io.atlassian.net/browse/KYLO-1766
