### ISSUE TITLE
Collecting dates do not use provided timezone

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#1693]
```
mydata <- data_frame(t = c(419547405,
                           1418469714,
                           1419126103),
                     text = c('ja',
                              'vier',
                              'luraschi'))

mydata_spark <- copy_to(sc, mydata, name = 'mydata_spark')

mydata_spark %>%
  mutate(unix_t = from_utc_timestamp(timestamp(t) ,'UTC'),
       date_str = date_format(unix_t, 'yyyy-MM-dd HH:mm:ss z'),
       date_alt = to_date(from_utc_timestamp(timestamp(t) ,'UTC')))



# Source:   lazy query [?? x 5]
# Database: spark_connection

           t text     unix_t              date_str                date_alt 
       <dbl> <chr>    <dttm>              <chr>                   <date>   
1  419547405 ja       1983-04-18 20:56:45 1983-04-18 15:56:45 EST 1983-04-18
2 1418469714 vier     2014-12-13 11:21:54 2014-12-13 06:21:54 EST 2014-12-13
3 1419126103 luraschi 2014-12-21 01:41:43 2014-12-20 20:41:43 EST 2014-12-20
```

Last row expected to be of `date_alt`:  `2014-12-21` not `2014-12-20`.

**Comment by randomgambit** [comment]
@javierluraschi thanks! I think the second column is also problematic. Why is `date_format` returning a timestamp is `EST`? Even if this is the correct one, I would have expected to see `UTC` here because unix_t is `UTC`

**Comment by randomgambit** [comment]
ha @javierluraschi you found the fix actually?

**Comment by javierluraschi** [comment]
@randomgambit actually, I think the problem is `to_date()` in Spark assumes local timestamp or something around those lines... after some debugging I arrived to this problematic example:

```r
sdf_len(sc, 1) %>% transmute(date_alt = as.character(to_date(from_utc_timestamp(timestamp(1419126103) ,'UTC'))))
```
```
# Source: spark<?> [?? x 1]
  date_alt  
* <chr>     
1 2014-12-20
```

Which takes `sparklyr` out of the picture by casting to `character` even before `sparklyr` has a chance to process date and serialize them. So yeah, not much we can do here, I think, apart from recommending to manually convert to the local time zone while using `to_date()`, `PST` for me but this would change based on the cluster configuration:

```
sdf_len(sc, 1) %>%
      transmute(
          date_alt = to_date(to_utc_timestamp(from_utc_timestamp(timestamp(1419126103) ,'UTC'), 'PST'))
      )
```

**Comment by yitao-li** [comment]
I can confirm this seems to be a Spark issue and there is not much `sparklyr` can do about it.

**Comment by tsengj** [comment]
It becomes a problem when i tried to join a date column to a datetime column. A date column has no issue with timezone as it will just use the local timezone of that date. but when i tried the to_date() from a datetime, it turns it into local timezone, and the join is no longer successful
