### ISSUE TITLE
GIS

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#1700]
Someone in the community could consider building an extension for GIS functions, some projects that look relevant:
- https://spark-packages.org/package/geotrellis/geotrellis
- https://spark-packages.org/package/DataSystemsLab/GeoSpark
- https://spark-packages.org/package/drubbo/SparkGIS

**Comment by goriliukasbuxton** [comment]
where is a big need to query PostGIS thru Spark with its spatial functions:
https://stackoverflow.com/questions/48305560/how-to-enable-postgis-query-in-spark-sql

**Comment by kevinykuo** [comment]
Related https://github.com/rstudio/sparklyr/issues/1475

**Comment by harryprince** [comment]
here is the package that I build:

https://github.com/harryprince/geospark

**Comment by javierluraschi** [comment]
Right, we recommend using https://github.com/harryprince/geospark
