### ISSUE TITLE
Nested data in Spark with Arrow

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#1734]
Tracks work to revert 73815ce7dd4735a5b37b056aadbe2ccf52189dfb and ee226007a18bf2cc3f188f24bd1866cc59f55993 while https://issues.apache.org/jira/browse/ARROW-2969 is implemented.

Also revert e583c15caf09f01a9bdbc1b39f3365c5ad4e8da3.

Tests:

```
── 12. Error: spark_read_json() can load data using column types (@test-read-write.R#49)  ─────────────────────────────
cannot handle Array of type struct

```

**Comment by yl790** [comment]
All of those are based on arrow version now
