### ISSUE TITLE
Dates out of control

### ISSUE THREAD

**Issue by andreysharapov** [sparklyr/sparklyr#1743]
Hi

I have installed today sparkly 0.9.2 and previously was using the GitHub version that you pointed me to. I get very strange behaviour with dates. It happened somehow over the weekend. Dates are shifted now by one day when I query using date ranges. When I query for a specific date, it gives the same numbers as in Hive. But when I query <,> for dates, then they are shifted. What could be the reason for that. Does  sparklyr read the timezone from somewhere on the cluster. 

We had some cluster restart in the weekend and on Monday, the code that worked on Friday started giving really weird bugs.

The weirdest of all in that it happens for very specific dates

1 2015-03-29 
2 2017-03-26 
3 2016-03-27 
4 2018-03-25 
5 2014-03-30 

for all dates set we have.

For instance, the date 2018-03-25 has two records (for 2018-03-25  and 2018-03-26) and the record for 2018-03-26 has value for 2018-03-27. This stuff happens now for all years and dates I mentioned

I would appreciate your help here.

Thank you

**Comment by andreysharapov** [comment]
By the way the dates are here https://www.timeanddate.com/time/change/germany?year=2016

**Comment by andreysharapov** [comment]
why is it shifted after Daylight Saving dates every year)) ? and only in spring

**Comment by javierluraschi** [comment]
@andreysharapov could you please attach runnable code to attempt to reproduce this? Thanks!

**Comment by andreysharapov** [comment]
Hi 

There is really no runnable code per se. 

I run the following query

SELECT client_id, orig_item_nr, dat_formdate, abverkauf, umsatz_brutto, is_weight,   bon_count, preis_brutto, anzahl_filialen, pct_vat, price_buying, exchange_rate FROM qa01ch_data.PVT_SALES_AGG WHERE client_id = 3   AND year <= 2018   AND dat_formdate <= '2018-09-22'

and examine results.

In Hive I get no date shifts and so no duplicates when I group by  orig_item_nr and dat_formdate.
When I run it using sparklyr sql invoke and then collect, the dates  are shifted after very specific dates - time saving dates I mentioned above. The above query produces date shifts when using sparklyr 0.9.2

We now discovered that sparklyr 0.8.4 also created date shifts but in a different place. There we run a join between a hive table and a data set procomputed in R and sent to spark via copy_to. In this case sparklyr 0.8.4 creates more date shifts that sparklyr 0.6.4. But again, after the daylight saving dates I mentioned above.
 

The strangest thing is that it started being noticable right after that time change on 28.10.2018
As I said, the code build with sparklyr 0.9.2 ran on 26.11.2018 but resulted into date shifts on 29.11.2018

We are trying to use other sparklyr versions but they do not seem to fix all problems

I am very scared now that everything we compute in totally incorrect since we cannot track such date shifts. We are using sparklyr in production.

Thank you

**Comment by andreysharapov** [comment]
Well, I looked again. All dates are shifted by one day in sparklyr 0.8.4.

**Comment by omzeybek** [comment]
Hi, we are experiencing the smar problem. Is there any progress on this issue. Thanks a lot.

**Comment by yitao-li** [comment]
One can try setting `spark.sql.session.timeZone`. Also, see https://issues.apache.org/jira/browse/SPARK-18936
