### ISSUE TITLE
support spark 2.4

### ISSUE THREAD

**Issue by mattpollock** [sparklyr/sparklyr#1749]
Spark 2.4 brings lots of nice functionality (e.g., https://jira.apache.org/jira/browse/SPARK-23899) and seems to be released (https://archive.apache.org/dist/spark/spark-2.4.0/). Can sparklyr support this version?

Thanks much.

**Comment by kevinykuo** [comment]
We have to wait until it's officially out (i.e. announced on https://spark.apache.org/) before supporting it but are there draft release notes somewhere?

**Comment by mattpollock** [comment]
Makes sense. I have not seen release notes yet. Just some indicators from watching their Jira.

**Comment by kevinykuo** [comment]
2.4 dropped today. We'll get issues open to track new features in the coming days.

**Comment by mattpollock** [comment]
Any movement on this? Thanks much.

**Comment by h-vetinari** [comment]
Any update on this?

**Comment by kevinykuo** [comment]
Hey @h-vetinari I plan to get back to sparklyr development next month and will start filling in missing features and also the sparknlp package and tidyr-style reshaping. One thing that would be helpful from the community (other than sending PRs ;) ) is commenting on feature requests and opening new ones to track so we can prioritize.

**Comment by csetzkorn** [comment]
I am also getting: sparklyr does not currently support Spark version: 2.4.2. I am mainly interested in using Spark and R for NLP stuff. Will this work soon? Shall I downgrade my Spark? Shall I wait for a couple of weeks? What would be your suggested approach please? Thanks.

**Comment by jkylearmstrong** [comment]
I see in [1.0.2](https://github.com/rstudio/sparklyr/blob/master/NEWS.md#sparklyr-102) that support for 2.4.3 was added - can we confirm support for Spark 2.4.x ? 

Thanks,

**Comment by chezou** [comment]
Seems that [NEWS.md](https://github.com/sparklyr/sparklyr/blob/master/NEWS.md#misc) status 
> Support for Spark 2.3.3 and 2.4.3.

is it the time to close this issue?
