### ISSUE TITLE
Feature Request: spark_read_excel

### ISSUE THREAD

**Issue by awwsmm** [sparklyr/sparklyr#1777]
sparklyr currently doesn't have a `read_excel` functionality. But this would be a very nice additional feature.

**Comment by javierluraschi** [comment]
@awwsmm do you have large Excel files in a cluster environment? Otherwise you could do:

```r
your_dataset <- readxl::readxl_example("datasets.xlsx")
excel_df <- readxl::read_excel(your_dataset)
excel_tbl <- dplyr::copy_to(sc, excel_df)
```

**Comment by awwsmm** [comment]
Yes. Like it or not, Excel files are a de-facto standard for data collection in lots of scenarios, and we have a lot of them to analyse. We'd like to move to a Hadoop/Spark based analysis environment and that means either parsing all of those files and converting them to some other format, or just reading them directly as xls/xlsx from HDFS. It would be great if `sparklyr` could eventually provide this functionality.

**Comment by yitao-li** [comment]
Recent version of `sparklyr` supports passing a custom reader functino to `spark_read()` to run the reader distributively. Combining `spark_read()` with `readxl::read_excel()` seems to be the best solution here, assuming you have R and `readxl` installed on all your Spark workers.

**Comment by skylernorgaard** [comment]
@yitao-li is it possible to post an example of how to combine spark_read with readxl::read_excel()? I have been trying to do this but am finding very little documentation.
