### ISSUE TITLE
The spark_apply function uses R extension packages very slowly

### ISSUE THREAD

**Issue by lucyhome2018** [sparklyr/sparklyr#1781]
Hello! 
         Everyone! I need some help, my problems are as follows: 
I use this command:
`time_jy_hr<-spark_apply(jydat_hr,function(e) lubridate::ymd_hms(e$data_time),packages = TRUE)`
          when there are about 600 rows,it takes 5 seconds;But, when I run this command with more than a dataset of 40 thousand rows,it takes more than 3 hours. It is very slowly. This is my first time to use spark_apply function with sparklyr ,maybe I don't  understand completely the usage of this function, please tell me how to use this function when I need to use other R packages. 
          Thank you very much!

**Comment by harryprince** [comment]
before call `spark_apply`,  you might consider call the `sdf_repartition` function, which will help you rebalance your dataframe in each work.

Your job was running 3 hours, which seems only running on only one worker and skewed dataset.

**Comment by javierluraschi** [comment]
@lucyhome2018 repartitioning as @harryprince mentions would help.

Additionally, we are working on making `spark_apply()` about `100X` faster with `arrow`, if you feel adventurous to try a feature not yet released, you can find instructions on using `arrow` here: https://github.com/rstudio/sparklyr/pull/1611.
