### ISSUE TITLE
Help to create loops with sparklyr

### ISSUE THREAD

**Issue by hanfernandes** [sparklyr/sparklyr#1821]
I created a function:

```
sdf_ks2 = function(.x, target, var){
  target_groups = .x %>% group_by(!!enquo(target)) %>% count() %>% ungroup() %>% pull(!!enquo(target))
  target_total = .x %>% group_by(!!enquo(target)) %>% count() %>% ungroup() %>% pull(n)
  return(
  .x %>% select(!!enquo(target), !!enquo(var)) %>% arrange(!!enquo(var)) %>% mutate(scoreks = if_else(!!enquo(target) == target_groups[1], 1/target_total[1],-1/target_total[2]), ks = abs(cumsum(scoreks))) %>%
    summarise(ks2 = max(ks, na.rm = TRUE)) %>% pull(ks2)
  )
}
```

and it works.

> > data %>% sdf_ks2(TARGET, SCORE)
> [1] 0.1858847

I wanted to create a function that had loops containing many variables, similar to summarise_at.

Ex:
```
vars = c("SCORE1", "SCORE2", "SCORE3")

data %>% sdf_ks2_at(vars, funs(sdf_ks2(TARGET,.))
```

Can someone help me?

**Comment by edgararuiz** [comment]
Hi, I proposed a solution for something similar that uses `union()` to concatenate all of the cycles into a single SQL call: https://stackoverflow.com/questions/49497844/using-purrrmap2-with-dbplyr/52461187#52461187
