### ISSUE TITLE
 Failed while connecting to sparklyr to port (8880)

### ISSUE THREAD

**Issue by prildi** [sparklyr/sparklyr#1828]
# Reporting an Issue with sparklyr

Hi,
I have an error posted by several users before, but with a different Output log: 

`spark_version <- "2.3.2"
sc <- spark_connect(master = "local", version = spark_version)
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (37248): Gateway in localhost:8880 did not respond.
    Path: C:\Users\<username>\AppData\Local\spark\spark-2.3.2-bin-hadoop2.7\bin\spark-submit2.cmd
    Parameters: --class, sparklyr.Shell, "C:\Program Files\R\R-3.5.2\library\sparklyr\java\sparklyr-2.3-2.11.jar", 8880, 37248
    Log: C:\Users\<username>\AppData\Local\Temp\RtmpQBVALJ\file10d072c71a7_spark.log

---- Output Log ----
The command "<username>\AppData\Local\spark\spark\spark-2.3.2-bin-hadoop2.7\jars""\" is either misspelled orcould not be found.
Failed to find Spark jars directory.
You need to build Spark before running this program.

---- Error Log ----

> utils::sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_0.9.3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       dbplyr_1.2.2     compiler_3.5.2   pillar_1.3.1     later_0.7.5      bindr_0.1.1      r2d3_0.2.3       base64enc_0.1-3 
 [9] tools_3.5.2      digest_0.6.18    jsonlite_1.6     tibble_1.4.2     nlme_3.1-137     lattice_0.20-38  pkgconfig_2.0.2  rlang_0.3.0.1   
[17] shiny_1.2.0      DBI_1.0.0        rstudioapi_0.8   parallel_3.5.2   yaml_2.2.0       bindrcpp_0.2.2   withr_2.1.2      dplyr_0.7.8     
[25] httr_1.4.0       rappdirs_0.3.1   generics_0.0.2   htmlwidgets_1.3  rprojroot_1.3-2  grid_3.5.2       tidyselect_0.2.5 glue_1.3.0      
[33] forge_0.1.0      R6_2.3.0         tidyr_0.8.2      purrr_0.2.5      magrittr_1.5     backports_1.1.3  promises_1.0.1   htmltools_0.3.6 
[41] assertthat_0.2.0 mime_0.6         xtable_1.8-3     httpuv_1.4.5.1   config_0.3       openssl_1.1      lazyeval_0.2.1   broom_0.5.1     
[49] crayon_1.3.4  
`
I guess this is due to a space character in the user name. Any idea how to fix this?

**Comment by javierluraschi** [comment]
Since this is a local installation, try uninstalling spark with `spark_uninstall()` then set an alternate installation path with `options(spark.install.dir = "c:/other/path/no/spaces/")`, reinstall Spark and retry connecting.

It is our intention to support spaces and this is something we have tested in the past, but perhaps not for this particular version of Windows.

**Comment by Bakti-Siregar** [comment]
It does not working for me,,, Is there any other method how to fix it?

**Comment by SieSiongWong** [comment]
Hi, I'm getting "Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId, : Gateway in localhost:8880 did not respond.". I have tried many way like getting the JAVA_HOME setup in the environment variable, install JAVA JDK, etc. but still no luck. Anyone can help?

JAVA_HOME   C:\Program
            Files\Java\jdk1.8.0_251
Spark version 2.4.3

**Comment by SieSiongWong** [comment]
By the way, I'm using my local pc to connect, spark_conn <- spark_connect(master = "local") and got the localhost:8880 error. This is the path spark installed: AppData\\Local/spark/spark-2.4.3-bin-hadoop2.7

**Comment by yl790** [comment]
@SieSiongWong Hey more than happy to help. Did you try the following:
```
library(sparklyr)
spark_version <- "2.4.3"
spark_uninstall(version = spark_version)
spark_install(version = spark_version)
```
to re-install the Spark distribution?

Also, try specifying the Spark version explicitly

```
spark_conn <- spark_connect(master = "local", version = "2.4.3")
```

and finally, try logging everything to console to see what was the problem:

```
options(sparklyr.log.console = TRUE)
spark_disconnect(sc)
sc <- spark_connect(master = "local", version = "2.4.3")
```

(you can clear the console (ctrl+l) after spark_disconnect(sc) to ignore all console log from `spark_disconnect`, and then only check what happens after you re-run `spark_connect(...)`)

**Comment by SieSiongWong** [comment]
@yl790 Thanks so much for helping.

I run the uninstall and reinstall script you're given and got below.
> spark_uninstall(version = spark_version)
Error in spark_versions_info(version, hadoop_version) : argument "hadoop_version" is missing, with no default

> spark_install(version = spark_version)
Spark 2.4.3 for Hadoop 2.7 or later already installed.

I run by specifying Spark version explicitly and got below.
> spark_conn <- spark_connect(master = "local", version = "2.4.3")
Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId,  :  Gateway in localhost:8880 did not respond.

I run by specifying spark_home explicitly and also got the same error message.
> spark_conn <- spark_connect(master = "local", spark_home = "......\\AppData\\Local\\spark\\spark-2.4.3-bin-hadoop2.7")
Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId,  : 
  Gateway in localhost:8880 did not respond.

I try to run the "try logging everything to console to see what was the problem", but getting below. Could it be that sc never successfully connected that is why there is no such sc object exist. I also try to use spark_log() to retrieve the log but because sc does not exist so getting same error.

> options(sparklyr.log.console = TRUE)
> spark_disconnect(sc)
Error in spark_disconnect(sc) : object 'sc' not found
> sc <- spark_connect(master = "local", version = "2.4.3")
Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId,  : 
  Gateway in localhost:8880 did not respond.

**Comment by yl790** [comment]
@SieSiongWong 

OK forget about `sc` for now. If you just run

```
library(sparklyr)
options(sparklyr.log.console = TRUE)
spark_connect(master = "local", version = "2.4.3")
```

from a fresh R session, then you should be able to see at least some console log. Please consider installing the latest version of sparklyr as well (sparklyr 1.3)

**Comment by yl790** [comment]
Also, did you follow something like https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html for setting the JAVA_HOME env variable when the path contains a space character? I don't know if that's related to the issue you have, but maybe it's worth looking into as well.

**Comment by SieSiongWong** [comment]
@yl790 Yes, i have the latest Sparklyr version 1.3 installed but still don't see  any log related to sparklyr in the console. Below is what my console display.

R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData] 


I have follow https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html by setting up the JRE_HOME but still no luck.  I did not try the JAVA_HOME as I have uninstalled JDK because I tried this solution before mentioned in another post but also not working.

**Comment by SieSiongWong** [comment]
@yl790 Yes, I have the latest Sparklyr 1.3 installed. Regarding the log, I restart close and reopen my R and below is what displayed in the console.

R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

I follow what is mentioned in the  https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html by setting up the JRE_HOME but still no luck. I did not try the JAVA_HOME as I have uninstalled the JDK which solution mentioned in another post but also not working.

**Comment by yl790** [comment]
@SieSiongWong Alright. Sounds like we'll have to run spark-submit manually and see whether it's working at all.

Would you be able to try to do the following?

- Download https://cran.r-project.org/bin/windows/contrib/4.0/sparklyr_1.3.0.zip
- Unzip `sparklyr_1.3.0.zip` into some directory (let's say <my_directory>)
- Store your spark_home path (which you mentioned was something like ".....\AppData\Local\spark\spark-2.4.3-bin-hadoop2.7") into a environment variable named "SPARK_HOME" -- I'm not really familiar with Windows and don't exactly know how to do this, so, you'll have to figure this out
- Run `%JAVA_HOME%\bin\java.exe %SPARK_HOME%\conf\;%$SPARK_HOME%\jars\* -Xmx2g org.apache.spark.deploy.SparkSubmit --conf spark.driver.memory=2g --class sparklyr.Shell <my_directory>\sparklyr\java\sparklyr-2.4-2.11.jar 8880 12345` and see whether SparkSubmit is working as expected (again this is my best guess of what it might be on Windows and I don't have a Windows env handy with R and Sparklyr etc, so, you'll have to double-check this and possibly fix some minor typos... but hopefully I'm not too far off

The expected outcome after the last step should be `sparklyr: Gateway (12345) is waiting for sparklyr client to connect to port 8880` being printed out on the console. If that's not the case then you'll be able to see whether it's something wrong with the Spark installation you have.

**Comment by SieSiongWong** [comment]
@yl790 

I have followed your step download, extract the sparklyr folder (in my case I put in my Document), then create the SPARK_HOME environment variable, then the last step I modified to as below BUT GOT ACCESS DENIED. I don't have the JDK installed so I changed to JRE_HOME. Will this okay or I need to install JDK and also set environment variable "JAVA_HOME"? Just wonder will an username with space between causing a problem because I have username like "Doug Lenz".

%JRE_HOME%\bin\java.exe %SPARK_HOME%\conf\;%$SPARK_HOME%\jars\* -Xmx2g org.apache.spark.deploy.SparkSubmit --conf spark.driver.memory=2g --class sparklyr.Shell <"C:\Users\.....\Documents\sparklyr">\sparklyr\java\sparklyr-2.4-2.11.jar 8880 12345

**Comment by SieSiongWong** [comment]
![image](https://user-images.githubusercontent.com/52974088/86631960-c6d6f100-bf9c-11ea-8d54-b431cdc95aa8.png)

**Comment by yl790** [comment]
@SieSiongWong Please try removing `<` `>` around "C:\Users\...\Document\sparklyr" (sorry was not clear enough... I didn't meant `<` `>` should be part of that path)

**Comment by SieSiongWong** [comment]
@yl790 

This time I'm getting below error. The strange thing is after the Users\ only show one word of my username without my last name. Again, wonder this has anything to do with the space in my username.

Error: Could not find or load main class C:\Users\Lenz

**Comment by yl790** [comment]
@SieSiongWong I think so. I believe path containing space needs to be surrounded by `" "`s in Windows (e.g., see https://superuser.com/questions/432980/how-to-call-a-program-that-contains-space-in-filename)

**Comment by SieSiongWong** [comment]
Yes, I do put quote " " in the path:

%JRE_HOME%\bin\java.exe %SPARK_HOME%\conf\;%$SPARK_HOME%\jars\* -Xmx2g org.apache.spark.deploy.SparkSubmit --conf spark.driver.memory=2g --class sparklyr.Shell "C:\Users\......\Documents\sparklyr" \sparklyr\java\sparklyr-2.4-2.11.jar 8880 12345

**Comment by yl790** [comment]
@SieSiongWong I think you need to replace `"C:\Users......\Documents\sparklyr" \sparklyr\java\sparklyr-2.4-2.11.jar` with the following:

`"C:\Users......\Documents\sparklyr\sparklyr\java\sparklyr-2.4-2.11.jar"`

(i.e., it should be 1 single path surrounded by quotes). Also, seeing that "sparklyr" appeared twice in that path, I'll assume the directory structure you have is such that there is a directory named "sparklyr" inside "C:\Users\...\sparklyr". Please double-check those details.

**Comment by SieSiongWong** [comment]
@yl790 

I update the path to below and still getting same error. It might be wrong syntax somewhere in these command lines. Sorry that I am not familiar with writing the command lines so not sure where to check.

%JRE_HOME%\bin\java.exe %SPARK_HOME%\conf\;%$SPARK_HOME%\jars\* -Xmx2g org.apache.spark.deploy.SparkSubmit --conf spark.driver.memory=2g --class sparklyr.Shell "C:\Users\...\Documents\sparklyr\java\sparklyr-2.4-2.11.jar" 8880 12345

**Comment by yl790** [comment]
@SieSiongWong I think it should be 
%JRE_HOME%\bin\java.exe %SPARK_HOME%\conf;%$SPARK_HOME%\jars\* -Xmx2g org.apache.spark.deploy.SparkSubmit --conf spark.driver.memory=2g --class sparklyr.Shell "C:\Users...\Documents\sparklyr\java\sparklyr-2.4-2.11.jar" 8880 12345

(path separator `\` needed between `jars` and `*`)

**Comment by SieSiongWong** [comment]
@yl790 

If I understand you correctly, below is what I have changed putting \ between jar and * in the path but getting same error.

%JRE_HOME%\bin\java.exe %SPARK_HOME%\conf;%$SPARK_HOME%\jars\* -Xmx2g org.apache.spark.deploy.SparkSubmit --conf spark.driver.memory=2g --class sparklyr.Shell "C:\Users\...\Documents\sparklyr\java\sparklyr-2.4-2.11.jar\*" 8880 12345

**Comment by SieSiongWong** [comment]
sorry for the typo but same result.

%JRE_HOME%\bin\java.exe %SPARK_HOME%\conf;%$SPARK_HOME%\jar\* -Xmx2g org.apache.spark.deploy.SparkSubmit --conf spark.driver.memory=2g --class sparklyr.Shell **"C:\Users\Gang Zhang\Documents\sparklyr\java\sparklyr-2.4-2.11.jar\*"** 8880 12345

**Comment by SieSiongWong** [comment]
Pasting the code here it automatically removes the backslash \ between jar and * but I do include \ when do the command line.

**Comment by SieSiongWong** [comment]
I found a strange thing that when I run the spark_home_dir() the result is as below. Is this normal that the directory syntax is mixed with forward slash and backward slash?

C:\\Users\\....\\AppData\\Local/spark/spark-2.4.3-bin-hadoop2.7

But the SPARK_HOME is as below.

 "C:\\Users\\...\\AppData\\Local\\spark\\spark-2.4.3-bin-hadoop2.7"

**Comment by SieSiongWong** [comment]
I see another post mentioned to check the spark-submit and I run in cmd as given below but getting "Local\spark\spark-2.4.3-bin-hadoop2.7\bin\..\conf] was unexpected at this time."

"C:\Users\...\AppData\Local\spark\spark-2.4.3-bin-hadoop2.7\bin\spark-submit2.cmd" --class sparklyr.Shell "C:\Users\...\Documents\R\win-library\3.6\sparklyr\java\sparklyr-2.4-2.11.jar" 8880 12345

And this one 

"C:\Users\...\AppData\Local\spark\spark-2.4.3-bin-hadoop2.7\bin\spark-submit.cmd" --class org.apache.spark.examples.SparkPi C:\Users\...\AppData\Local\spark\spark-2.4.3-bin-hadoop2.7\examples\jars\spark-examples_2.11-2.4.3.jar" 10

**Comment by yl790** [comment]
@SieSiongWong Please considering trying the following:

- Just install another version of Spark and then see what happens, e.g.,:

```
library(sparklyr)
spark_install(version = "2.4.4")
```
There are many versions to choose from, 2.4.4, 2.4.5, 3.0.0, etc, all of which are known to be supported by sparklyr.

- If after completing the above, `spark_connect(master = "local", version = "2.4.4")` still doesn't work with the new version of Spark, then please read through https://dzone.com/articles/working-on-apache-spark-on-windows -- I quickly glanced through it and realized apparently one could encounter some additional hurdles while trying to get Apache Spark working as expected on Windows. This is unfortunate.
- Also, `spark_connect(master = "local")` relies on the loopback interface working as expected. This is not a problem for most off-the-shelf standard OS distributions (including Windows), but if the network interfaces in your OS is configured in a non-standard way, you might want to look into it (but that would have showed up in Apache Spark console log previously mentioned, but we were not able to see any console log which was also strange...). Anyhow, google and stackoverflow are your best friends for things like that.

**Comment by SieSiongWong** [comment]
@yitao-li 

I think I have to give up as already spent hours trying to get it to work. Thanks for your help.

**Comment by GitHunter0** [comment]
I tried to install many local versions of Spark (3.03, 3.1.1, 3.1.2) and still receives the same error message.

@yitao-li , did you guys find a solution to that?

Thank you

PS: I also installed 2.4.8 but could not test it because my JAVA version is too recent to be compatible.

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
 [1] sparklyr_1.7.5 
```

**Comment by SieSiongWong** [comment]
Hi Yitao,

Based on my experience of installing it, I spent quite a lot of time trying
to make it work in Windows but no luck.

So I tried it in the Linux environment and it just worked perfectly there.
I would suggest you try in Linux rather than in Windows for Spark related
packages.

Sincerely,
Sie Siong Wong

**Comment by GitHunter0** [comment]
What solved for me was:
- following the suggestion to install JDK 8 in a directory without any space.
- setting the appropriate environment variables: JAVA_HOME and SPARK_HOME
- add swinutils.exe and hadoop.dll in the appropriate folders
