### ISSUE TITLE
sdf_collect is very slow

### ISSUE THREAD

**Issue by solunsteve** [sparklyr/sparklyr#1853]
sparklyr::sdf_collect is super slow on large (but not too large) tables, anybody knows additional options?
Please advise.

**Comment by Jassy1994** [comment]
Hi @solunsteve 
    do you fetch data to your local？it may much slower when your local memory are not big enough and collect causes a lot of GC，it may spend much time，you can observe your GC log。

**Comment by nik-maheshwari** [comment]
Maybe select columns that you want before calling sdf_collect? Something like -
df = sdf %>% select(col1, col2) %>% sdf_collect()

**Comment by solunsteve** [comment]
@Jassy1994 @nik-maheshwari @dalloliogm I have around 250 parquet files on S3.
I have connected to S3a and used `spark_read_parquet` but when I am applying the sdf_collect to bring it back to R and analyze it takes ages. Sometimes it runs in parallel, sometimes it runs on one processor.

Can you please advise how to parallelize the process and make it faster? @hadley

**Comment by nik-maheshwari** [comment]
@solunsteve Can you show us the output of your Spark connection, sc?

**Comment by solunsteve** [comment]
@nik-maheshwari Thanks for the answer and here is what you asked for:

$master
[1] "local[16]"

$method
[1] "shell"

$app_name
[1] "sparklyr"

$config
$config$spark.env.SPARK_LOCAL_IP.local
[1] "127.0.0.1"

$config$sparklyr.connect.csv.embedded
[1] "^1.*"

$config$spark.sql.catalogImplementation
[1] "hive"

$config$sparklyr.connect.cores.local
[1] 16

$config$spark.sql.shuffle.partitions.local
[1] 16

$config$sparklyr.defaultPackages
[1] "com.databricks:spark-csv_2.10:1.5.0"    "com.amazonaws:aws-java-sdk-pom:1.10.34" "org.apache.hadoop:hadoop-aws:2.7.3"    

$config$`sparklyr.shell.driver-memory`
[1] "32G"

$config$spark.memory.fraction
[1] 0.9

attr(,"config")
[1] "default"
attr(,"file")
[1] "/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.5/sparklyr/conf/config-template.yml"

$state
<environment: 0x14281410>

$spark_home
[1] "/home/ubuntu/spark/spark-2.3.2-bin-hadoop2.7"

$backend
A connection with                              
description "->localhost:8881"
class       "sockconn"        
mode        "wb"              
text        "binary"          
opened      "opened"          
can read    "yes"             
can write   "yes"             

$monitoring
A connection with                              
description "->localhost:8881"
class       "sockconn"        
mode        "wb"              
text        "binary"          
opened      "opened"          
can read    "yes"             
can write   "yes"             

$gateway
A connection with                              
description "->localhost:8880"
class       "sockconn"        
mode        "rb"              
text        "binary"          
opened      "opened"          
can read    "yes"             
can write   "yes"             

$output_file
[1] "/tmp/RtmpLL7SVc/file22cc27c28f2a_spark.log"

$sessionId
[1] 97154

attr(,"class")
[1] "spark_connection"       "spark_shell_connection" "DBIConnection"

**Comment by nik-maheshwari** [comment]
@solunsteve Can you try invoking your spark connection like this? And then read your parquet files.

```
conf = spark_config()
conf$spark.driver.memory="32g"
sc <- spark_connect(master = "local[*]", config = conf)
```

**Comment by solunsteve** [comment]
Error:
`Error: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2195) at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654) at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667) at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94) at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703) at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685) at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373) at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295) at org.apache.spark.sql.execution.datasources.DataSource$.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:709) at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:390) at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:390) at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241) at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241) at scala.collection.immutable.List.foreach(List.scala:381) at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241) at scala.collection.immutable.List.flatMap(List.scala:344) at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:389) at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227) at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:622) at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:621) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at sparklyr.Invoke.invoke(invoke.scala:139) at sparklyr.StreamHandler.handleMethodCall(stream.scala:123) at sparklyr.StreamHandler.read(stream.scala:66) at sparklyr.BackendHandler.channelRead0(handler.scala:51) at sparklyr.BackendHandler.channelRead0(handler.scala:4) at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2101) at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193) ... 54 more`

**Comment by jkylearmstrong** [comment]
you could not collect - analyze with sparklyr api....

**Comment by dalloliogm** [comment]
How is your data partitioned? How much data are you trying to collect?

The error you posted seems to indicate that you cannot read amazon S3A files..

**Comment by jkylearmstrong** [comment]
@dalloliogm how does partitioning change the behavior of collect? More or fewer partitions speed up the behavior?

**Comment by jkylearmstrong** [comment]
I also kept running into issues, here's a solution that I cooked up:

```r
spark_tbl_1 <- sdf_repartition(spark_tbl,1)

spark_write_csv(spark_tbl_1, 'spark_tbl_1_csv.csv')

system('hdfs dfs -copyToLocal /hdfs/spark_tbl_1_csv.csv /local/spark_tbl_1_csv.csv')

file_to_read <- list.files(path = "/local/spark_tbl_1_csv.csv", pattern= "part")

demo_cct_Pre_Post <- read_csv(paste0("/local/spark_tbl_1_csv.csv", file_to_read))
```

**Comment by dalloliogm** [comment]
> @dalloliogm how does partitioning change the behavior of collect? More or fewer partitions speed up the behavior?

It depends on which query you are running. If you collect data and all the data is stored in the same partition, performances will be good. But if you collect data after doing several operations that move data across worker nodes, it will be slower. 

Try also looking at sdf_coalesce which will move the data into a smaller number of nodes before pulling it.

That being said, 763 Mb is not a big datasets and collecting it should be fast enough.

**Comment by jkylearmstrong** [comment]
```r
sdf_dim(data.spark)
[1] 382272     78

tic <- Sys.time()
tic
[1] "2019-03-13 13:51:50 EDT"
data.spark_1 <- sdf_repartition(data.spark,1)
spark_write_csv(data.spark_1,
                '/hdfs/data.spark_csv.csv',
               mode='overwrite')
system('hdfs dfs -copyToLocal /hdfs/data.spark_csv.csv local/data.spark_csv.csv')

#copyToLocal: `DATA/Pre_Match/demo_cct_Pre_Post_csv.csv/demo_cct_Pre_Post_csv.csv/_SUCCESS': File exists

file_to_read <- list.files(path = "local/data.spark_csv.csv", pattern= "part")
data_dt <- data.table::fread(paste0("local/data.spark_csv.csv/",file_to_read), 
                  header = T, sep = ',')
|--------------------------------------------------|
|==================================================|

data_tibble <- tibble::as_tibble(data_dt) %>%
  distinct()
saveRDS(data_tibble, 'data_tibble.RDS')
toc <- Sys.time()
toc
[1] "2019-03-13 13:55:16 EDT"
toc - tic
Time difference of 3.441812 mins
```

I also tried with using ```r sdf_coalesce(x,1)``` followed by ```r sdf_collect(x)``` however, I stopped it after 30 minutes - again size of data is not that big only 764 MB

**Comment by sdanielzafar** [comment]
I have been waiting for 75 minutes for `sdf_collect` to finish. My code is pretty simple:

```
# read it in to save out as RDS
hourly_data <- spark_read_parquet(sc, "hourly_data", 
                   "hdfs://.../my_file.parquet")

# collect doesn't work
row_count <- 0
hourly_data_mem <- hourly_data %>%
  sdf_collect(callback = ~(row_count <<- row_count + nrow(.x)))
```
 Funny thing is that it hasn't really been working on any tasks for the last 1.3 hours. What's going on? Is this some strange GC?

My configs are basic:
```
conf$spark.executor.instances <- 7
conf$spark.executor.cores <- 3
conf$spark.executor.memory <- "8G"
```

![image](https://user-images.githubusercontent.com/15932833/60059479-fb398100-96a9-11e9-88a9-aebd1c270f73.png)

**Comment by yitao-li** [comment]
The performance of `sdf_collect()` without `arrow` has been improved in recent versions of `sparklyr`.
However, for use cases involving collection of large amounts of data from Spark to R, enabling `arrow` is highly recommended if you also want `sdf_collect()` to be as fast as possible. See https://spark.rstudio.com/guides/arrow/ .
