### ISSUE TITLE
How to prevent long Spark jobs in sparklyr from being aborted?

### ISSUE THREAD

**Issue by RUsr558** [sparklyr/sparklyr#1880]
Hey,

I am accessing a Spark Cluster via YARN and sparklyr. I have a problem with a very simple Spark job that has a long run time. The job is simply reading a parquet file, repartitioning it and then writing it back to disc:

```r
df_1 <- spark_read_parquet(sc,path="parquet_path", name="df_1", memory=FALSE)
df_1_repart <- sdf_repartition(df_1, partitions = 512, partition_by = c("field_1", "field_2"))
spark_write_parquet(df_1_repart, path="new_parquet_path")
```
(sorry for not providing reproducible code, but the data is very large)

This job runs fine for ~2 hours and then throws an error:
```
ERROR YarnClientSchedulerBackend: Yarn application has already exited with state FINISHED!
ERROR FileFormatWriter: Aborting job null.
org.apache.spark.SparkException: Job 2 cancelled because SparkContext was shut down
```

If I run the equivalent Scala commands in the Spark Shell on the same yarn queue with the same config-parameters the job sucessfully finishes within 3-4 hours. This makes me assume that not Yarn but sparklyr is causing the abort. Furthermore the job (if run from sparklyr) consistently aborts after ~2 hours which I have tested for different times of the day and also weekends which rules out ressource problems on the cluster. 

My web search has so far not provided me with helpful hints. However, a very similar error occurs if I try to use SparkR to start this job. In SparkR this problem seems to be known but is appearently not adressed since 2016: https://issues.apache.org/jira/browse/SPARK-1260

My question is: am I missing some hidden configuration in sparklyr that causes long jobs to abort after a fixed time? And is there a way to change this behavior?

```r
spark_version <- "2.1.0"

config <- spark_config()
config$spark.driver.bindAddress <-"XXX.XX.X.X"
config$spark.driver.host <-"XX.XX.XX.XXX"
config$spark.driver.port <-"XXXXX"
config$spark.blockManager.port <-"XXXXX"
config$spark.driver.blockManager.port <-"XXXXX"
config$spark.yarn.queue <- "xxx"
config$spark.executor.memory="16G"
config$spark.executor.cores=4
config$spark.executor.instances=2

sc <- spark_connect(master="yarn", config = config)

**Comment by harryprince** [comment]
might be your queue is full, and the job is pending.

**Comment by RUsr558** [comment]
@harryprince Thanks for the suggestion. My job is not pending, as I can see it being executed in the Spark Applications. After 2 hours the job is then aborted (I assume by sparklyr sind the identical query with identical settings is running fine when executed from the Spark Shell)

**Comment by harryprince** [comment]
spark2.1 is not stable version, spark2.2+ is preferred.
