### ISSUE TITLE
Investigate performance on `spark_apply()` context

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#1881]
With 2Gb passing `40GB` of data as the `context` seemed to work just fine:

```r
config <- spark_config()
config["sparklyr.shell.driver-memory"] <- "2G"

sc <- spark_connect(master = "local", config = config)
```

```r
df <- data.frame(x = seq_len(10^7))
sdf_len(sc, 10) %>% spark_apply(function(df, context) nrow(context), context = df)
object.size(df)
```
```
40000728 bytes
```

However, jumping to 400GB seems to hit additional performance bottlenecks, probably since we are hitting GC, etc. but worth investigating.

```r
df <- data.frame(x = seq_len(10^8))
sdf_len(sc, 10) %>% spark_apply(function(df, context) nrow(context), context = df)
object.size(df)
```

**Comment by harryprince** [comment]
when data size is more than 4G, the performance of spark_apply will sharply deteriorate. It seems the deadlock mechanism is the reason.

**Comment by yitao-li** [comment]
`context` is now a broadcast variable -- not entirely sure whether this will allow us to avoid hitting GC, etc, but that seems to be the best we can do
