### ISSUE TITLE
Cannot Open Local Connection | Permission Denied

### ISSUE THREAD

**Issue by djhernanv** [sparklyr/sparklyr#1898]
# Cannot Open Local Connection | Permission Denied

Hi! I have been trying to run a local instance of Spark on my Windows 10 laptop but without success. I get the following error promt:

```
* Using Spark: 2.3.0
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\<UserName>\AppData\Local\Temp\*******\********_spark.log': Permission denied
```
I have tried all suggested solutions I have found online, including installing sparklyr from github, running R and RStudio as an administrator, running only 64 Bit java, and checking that all .cmd files have the correct permissions. Still, the connection fails.

The commands I run to launch Spark are straigthforward:
`
library(sparklyr)
sc <- spark_connect(master = "local")
`

Please briefly describe your problem and, when relevant, the output you expect.
Please also provide the output of `utils::sessionInfo()` or
`devtools::session_info()` at the end of your post.

---

- Session info --------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language EN                          
 collate  German_Austria.1252         
 ctype    German_Austria.1252         
 tz       Europe/Berlin               
 date     2019-02-12  

----
sparklyr    * 0.9.9006 2019-02-12 [1] Github (rstudio/sparklyr@6b41c4a)

**Comment by benmwhite** [comment]
The "Permission denied" error sometimes occurs on Windows if another app is accessing the file, for example if you try to compile a markdown document to Word or PowerPoint while it's already open. That may not be the case here, but I feel it's worth pointing out since it can happen often and has an easy fix.

**Comment by djhernanv** [comment]
Hi Ben!

Thanks. But this is certainly not the case since this files are temporary files that are not needed by any other application.

**Comment by dageomark** [comment]
hi, how can i do to solve this error

Error in system2(file.path(spark_home, "bin", "spark-submit"), "--version",  : 
  '"C:\Users\AEN\AppData\Local\spark\spark-2.1.0-bin-hadoop2.7\bin/bin/spark-submit"' not found

**Comment by yitao-li** [comment]
Try setting spark_home to C:/Users/AEN/AppData/Local/spark/spark-2.1.0-bin-hadoop2.7 and also double-check Spark is installed correctly.

**Comment by Afr063426** [comment]
Has the question of djhernanv been answered? How can it be solved?
