### ISSUE TITLE
Spark 2.4 Avro file reading

### ISSUE THREAD

**Issue by dkincaid** [sparklyr/sparklyr#1910]
There doesn't seem to be any way to read Avro files in Spark 2.4. This version is supposed to be able to read Avro files natively now (without needing any extensions). The `chezou/sparkavro` package is no longer working with 2.4 and I can't find any function in sparklyr that might work.

1) Is there a function in `sparklyr` today that will let me read an Avro file in Spark 2.4?
2) We will need a `spark_read_avro()` function added to `sparklyr` to add this functionality.

**Comment by bhogan-mitre** [comment]
For reference: https://spark.apache.org/docs/latest/sql-data-sources-avro.html

It looks like the implementation for `spark_read_avro` will need to be slightly different, than for example `spark_read_parquet` (or as it is called now, [`spark_load_parquet`](https://github.com/rstudio/sparklyr/blob/master/R/sdf_saveload.R#L81)).

**Comment by chezou** [comment]
JFYI, I've released sparkavro 0.3.0 on CRAN https://cran.r-project.org/web/packages/sparkavro/index.html
Might be good to be merged into sparklyr, though.

**Comment by yitao-li** [comment]
We have `spark_read_avro()` now.
