### ISSUE TITLE
spark_config cannot set spark parameters

### ISSUE THREAD

**Issue by isaac2lord** [sparklyr/sparklyr#1920]
I am trying to set spark configuration parameters from RStudio like this

```r
Sys.setenv(SPARK_HOME = "/opt/mapr/spark/spark-2.2.1")
Sys.setenv(HADOOP_CONF_DIR = "/opt/mapr/hadoop/hadoop-2.7.0/etc/hadoop")
Sys.setenv(SPARK_CONF_DIR = "<...>/spark/conf")


conf <- spark_config()

conf$spark.num.executors <- 10
conf$spark.executor.memory <- "16g"
conf$spark.executor.cores <- 6
conf$spark.yarn.queue <- "<smth>"

sc <- spark_connect(master = "yarn", config = conf)
```

After the connection is established, I looked into Saprk UI and found the nothings actually happened. Seems the config is set at program level which makes it way to the spark environment after job is initialized, but physically it does not add the executors or cores. 

![image](https://user-images.githubusercontent.com/7535009/53115312-87c11080-350b-11e9-8bc3-9b70e31d4196.png)

Appreciate any words of wisdom on this!

─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                                      
 version  R version 3.5.1 (2018-07-02)               
 os       Red Hat Enterprise Linux Server 7.3 (Maipo)
 system   x86_64, linux-gnu                          
 ui       RStudio                                    
 language (EN)                                       
 collate  en_US.UTF-8                                
 ctype    en_US.UTF-8                                
 tz       America/Chicago                            
 date     2019-02-20

**Comment by benmwhite** [comment]
YARN uses `spark.executor.instances` instead of `spark.num.executors` , maybe also try turning dynamic allocation off manually (sometimes this is enabled by default):

```
conf$spark.dynamicAllocation.enabled <- FALSE
conf$spark.executor.instances <- 10
```

[List of YARN-specific Spark config values](https://spark.apache.org/docs/latest/running-on-yarn.html.)

**Comment by Isaacsh** [comment]
Thanks @benmwhite that was the root cause of the issue.
