### ISSUE TITLE
spark_connect() should handle openjdk 11 gracefully

### ISSUE THREAD

**Issue by sz-cgt** [sparklyr/sparklyr#1922]
**Error:**
``` r
sc <- sparklyr::spark_connect(master = "local[*]")
#> Error in validate_java_version_line(master, version): Java version detected but couldn't parse version from: openjdk version "11.0.2" 2019-01-15
```

<sup>Created on 2019-02-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Root Cause:**
The version string for openjdk 10 and above includes a release date.  Starting with openjdk 11.0.2, that release date is in 2019.  `validate_java_version_line()` fails to handle dates in 2019 (and presumably earlier release dats with a 9 in the month or the day) due to the following code

```
splatVersion <- splat[grepl("9|[0-9]+\\.[0-9]+\\.[0-9]+", splat)]
```
if the intention of that regexp is to match jdk 9 versions strings, it should either have a caret (^) before the 9 or something after it to prevent matches against a ISO date string.

Given that java 9 is end of life, a better answer is simply to remove the `9|` from the regexp entirely

**Comment by zero323** [comment]
@sz-cgt At the moment (Spark 2.4) running Spark on JDK9 or later is not supported. 

AFAIK [SPARK-24417](https://issues.apache.org/jira/browse/SPARK-24417) _Build and Run Spark on JDK11_ - serves as an umbrella ticket for different JDK compatibility issues, and informally supporting new JDKs should happen in 3.0 ([time for Apache Spark 3.0?](http://apache-spark-developers-list.1001551.n3.nabble.com/time-for-Apache-Spark-3-0-td23755.html), and target versions for remaining sub-tasks).
