### ISSUE TITLE
Flint

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#1946]
https://www.twosigma.com/insights/article/introducing-flint-a-time-series-library-for-apache-spark/

**Comment by yl790** [comment]
Note to myself: looks like the best way to port these time series functionalities into sparklyr is to create a sparklyr extension for them.

**Comment by yl790** [comment]
The only maven artifact available in https://mvnrepository.com/artifact/com.twosigma/flint/0.6.0 appears to be compatible with Spark 2.3.1 and incompatible with Spark 2.4.0... I think we might need to re-build flint library from source using jars from different Spark versions if we want this extension to work with multiple Spark versions.

**Comment by yl790** [comment]
Update: I managed to spend some time making sure Flint functionalities are usable from sparklyr after converting Spark dataframes to TimeSeriesRDDs and other Flint-specific constructs. 

Meanwhile I'm also looking into how to make Flint compatible with Spark 3.0. Looks like there will be some code changes needed to make it build with Spark 3.0 but hopefully the changes should be trivial. Also, for each Spark version we work with I need to generate a build.sbt file that is fully compatible with Spark compile-time dependencies which might take some time. The artifacts built using those build.sbt specs also need to be published separately into the maven repo.

But anyways, assuming all this is done and Flint is definitely compatible with all Spark versions we work with and also confirmed to be reasonably future-proof, then I will get started on creating a sparklyr extension that makes Flint functionalities easily accessible from R.

**Comment by yl790** [comment]
Update: this is currently blocked by https://github.com/twosigma/flint/issues/83

**Comment by yl790** [comment]
Update: the previously mentioned blocker was resolved and Sparklyr.flint is now actually in a reasonably usable state: https://github.com/r-spark/sparklyr.flint

I believe the next steps would be creating a vignette file and other necessary documentation for existing functionalities and releasing an initial version to CRAN.

**Comment by yitao-li** [comment]
The 1st version is on CRAN now. Looking forward to releasing more versions supporting larger number of flint & sparklyr functionalities in feature.
