### ISSUE TITLE
Exact comparison method between <dttm> and <chr> fields differs depending on whether `=` or `>=`/`<=` logical operator is used

### ISSUE THREAD

**Issue by BenCarlsen** [sparklyr/sparklyr#1947]
_dttm_ fields seem to get logically compared to character fields inconsistently - sometimes with date-type comparison and sometimes with string-type comparison, depending on the operator used.

Reprex:

```
## local table
test_dt_1 <- tibble(
    a = c(1, 2, 3),
    b = c(123.12, 234.23, NA),
    c = c("apple", "banana", "carrot"),
    d = c(TRUE, FALSE, FALSE),
    e = c("2018-01-01", "2018-01-01", "2018-01-01") 
)

## remote table
test_spark <- copy_to(
    sc,
    test_dt_1
)
```

**Exact equivalence comparison between parent chr field and dttm works. It looks like this is being performed as a date comparison.**
```
test_spark %>% mutate(f = to_timestamp(as.Date(e))) %>% filter(e == f)
# Source:   lazy query [?? x 6]
# Database: spark_connection
      a     b c      d     e          f                  
  <dbl> <dbl> <chr>  <lgl> <chr>      <dttm>             
1     1  123. apple  TRUE  2018-01-01 2018-01-01 00:00:00
2     2  234. banana FALSE 2018-01-01 2018-01-01 00:00:00
3     3  NaN  carrot FALSE 2018-01-01 2018-01-01 00:00:00
```
**Greater-than-or-equal-to comparison between parent chr and dttm field reports that these fields are NOT equivalent.** (Note that the schema is also reported incorrectly, although the empty table will be correctly evaluated if piped to `sdf_schema()`).
```
test_spark %>% mutate(f = to_timestamp(as.Date(e))) %>% filter(e >= f)
# Source:   lazy query [?? x 6]
# Database: spark_connection
# ... with 6 variables: a <dbl>, b <dbl>, c <chr>, d <lgl>, e <chr>, f <dbl>
```

**... parent chr is < dttm. It looks like this is being performed as a string comparison.**
```
test_spark %>% mutate(f = to_timestamp(as.Date(e))) %>% filter(e < f)
# Source:   lazy query [?? x 6]
# Database: spark_connection
      a     b c      d     e          f                  
  <dbl> <dbl> <chr>  <lgl> <chr>      <dttm>             
1     1  123. apple  TRUE  2018-01-01 2018-01-01 00:00:00
2     2  234. banana FALSE 2018-01-01 2018-01-01 00:00:00
3     3  NaN  carrot FALSE 2018-01-01 2018-01-01 00:00:00
```

**Comment by yitao-li** [comment]
I don't think type casts when comparing different types is something that is well-defined in Spark SQL. E.g., see https://spark.apache.org/docs/2.3.0/api/sql/index.html#_13. The documentation simply says both expressions will be casted to some common type, but does not specify what that common type is if left-hand-side expression is chr and the right-hand-side expression is dttm.
