### ISSUE TITLE
sdf_pivot not compatible with enquo

### ISSUE THREAD

**Issue by jkylearmstrong** [sparklyr/sparklyr#1949]
sdf_piviot is not compatible with enquo, in general, I am trying to write a function to pivot different columns in a spark dataframe 

```r
library(sparklyr)
library(dplyr)
```
```r
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union
```
```r
library(rlang)
```
```r
Attaching package: ‘rlang’

The following object is masked from ‘package:sparklyr’:

    invoke
```
```r
sc <- spark_connect(master = "yarn-client")
iris_tbl <- copy_to(sc, iris)
iris_tbl2 <- iris_tbl %>%
  mutate(Petal_Width = ifelse(Petal_Width > 1.5, "High", "Low" ))
iris_tbl2 %>%
  sdf_pivot(Petal_Width ~ Species,
            fun.aggregate = list(Petal_Length = "mean"))
```
```r
# Source: spark<?> [?? x 4]
  Petal_Width setosa versicolor virginica
  <chr>        <dbl>      <dbl>     <dbl>
1 High        NaN          4.82      5.57
2 Low           1.46       4.20      5.23
```
```r
iris_pivot <- function(lhs){
  lhs_enquo <- enquo(lhs)
  
  result <- iris_tbl2 %>% 
    sdf_pivot(lhs_enquo ~ Species, 
              fun.aggregate = list(Petal_Length = "mean"))
return(result)
}
iris_pivot(Petal_Width)
```
```r
Error in sdf_pivot(., lhs_enquo ~ Species, fun.aggregate = list(Petal_Length = "mean")) : 
  missing variables in dataset: "lhs_enquo"
```

possibly related or solved by applying solution to #252 or #1231

**Comment by harryprince** [comment]
Does it seem the `tidyeval` related topic?

**Comment by benmwhite** [comment]
@jkylearmstrong @harryprince this is definitely a tidy eval topic and not a `sparklyr` one:

```
mtcars_lm <- function(rhs){
  rhs_enquo <- enquo(rhs)
  lm(mpg ~ rhs_enquo, data = mtcars) %>% 
    broom::tidy() %>% 
    return()
}
mtcars_lm(disp)
```
```
Error in model.frame.default(formula = mpg ~ rhs_enquo, data = mtcars,  : 
  invalid type (language) for variable 'rhs_enquo'
```

Why not just make your function take a formula as input instead of trying to coerce it through tidy eval?

```
iris_pivot <- function(formula) {
  iris_tbl2 %>%
    sdf_pivot(formula, fun.aggregate = list(Petal_Length = "mean")) %>%
    return()
}
iris_pivot(Petal_Width ~ Species)
```

**Comment by jkylearmstrong** [comment]
Thanks for the advice @benmwhite I'll try it out!

**Comment by yitao-li** [comment]
FYI the next release of sparklyr will feature the full `tidyr::pivot_wider` interface for spark data frames (already implemented in https://github.com/sparklyr/sparklyr/pull/2668 where there is a `pivot_wider.tbl_spark` S3 method translating everything `tidyr::pivot_wider` entails to a Spark data frame, taking into consideration the full set of pivoting parameters such as `names_from`, `values_from` (well, obviously), and also other customization points like `name_prefix`, `names_sort`, `values_fill`, `values_fn`, and so on).

I'll aim to implement the same for `tidyr::pivot_longer` as well.
