### ISSUE TITLE
sprark_apply spark.r.libpaths config max 1 path

### ISSUE THREAD

**Issue by mattpollock** [sparklyr/sparklyr#1956]
If I attempt to run spark with more than one shared library path (e.g., a user path and a system path) things don't work.

This fails
```
library(sparklyr)

spark_disconnect_all()
config <- list(spark.r.libpaths = c("/path/one", "/path/two"))
sc <- spark_connect(master = "local", config = config)
```
In local mode I get the following error
```
Error in force(code) : 
  Failed during initialize_connection: java.lang.IllegalArgumentException: length and stream do not match
	at sparklyr.Serializer.readStringBytes(serializer.scala:77)
	at sparklyr.Serializer.readString(serializer.scala:84)
	at sparklyr.Serializer.readTypedObject(serializer.scala:37)
       ....
```

against my yarn cluster I get
```
Error in force(code) : 
  Failed during initialize_connection: Result 12 must be a single string, not a character vector of length 2
    Log: /tmp/Rtmpntdl41/file47b7587451a8_spark.log
```

This is fine
```
spark_disconnect_all()
config <- list(spark.r.libpaths = "/path/two")
sc <- spark_connect(master = "local", config = config)
```

**Comment by harryprince** [comment]
```
config <- list(spark.r.libpaths = c("/path/one;/path/two"))
```

this means set LIBPATHS environment variable as "/path/one;/path/two"

**Comment by mattpollock** [comment]
@harryprince I'm not quite following. I had not tried to collapse the paths with a `;` delimiter, but tried that this morning without success. Using 
```
config <- list(spark.r.libpaths = c("/path/one;/path/two"))
```
in the configuration results in calling
```
.libPaths("/path/one;/path/two")
```
in the R process on the spark executor, which fails and I'm left with only the default package library paths on the worker node.

**Comment by mattpollock** [comment]
It seems to me the this could be solved either by choosing a delimiter and `strsplit` (or similar) on the worker side to split the paths into a character vector or by enabling character vectors in the configuration. Not which which of these @javierluraschi would prefer.

**Comment by mattpollock** [comment]
Proposed solution (in the PR) is to use a comma separator, so users would use something like
```r
config <- list(spark.r.libpaths = c("/path/one,/path/two"))
```
