### ISSUE TITLE
Broken URL in README

### ISSUE THREAD

**Issue by jrtechs** [sparklyr/sparklyr#1957]
On the main README and the [home page](https://spark.rstudio.com/) for this project there is a broken link in the Connecting to Spark Section. The link's text is "spark_connect" and it links to this broken URL:
[https://spark.rstudio.com/reference/sparklyr/latest/spark_connect.html](https://spark.rstudio.com/reference/sparklyr/latest/spark_connect.html)

This should be a very easy fix for anyone who is hip to the documentation for this project.

**Comment by yitao-li** [comment]
Done (https://github.com/rstudio/spark.rstudio.com/pull/121)
