### ISSUE TITLE
Rstudio crashes after many jobs successfully done in Sparklyr

### ISSUE THREAD

**Issue by Greezy07** [sparklyr/sparklyr#1976]
I got some trouble with Spark and Rstudio which runs in EMR cluster. I got a very long  data processing code  that I run 4 times in a loop. First loop works fine: I do some caching using "tbl_cache()" and I drop it when I don't need it by calling "db_drop_table()" .   I also do many "writing and reading parquet" operations. After each loop I call garbage collector in R, I disconnect the current Spark session and I start a new one for the next loop step. In a middle of the second loop, sometimes my Spark jobs hangs indefinitely or sometimes my R session got disconnected and I get a "fatal error " messages related to the JVM.  The tables are not huge at all (at around 7000 rows and  170 columns) and I got enough memory (at around 90 GB for my 2 worker nodes)... My Spark configuration is by default:
`
Sys.setenv(SPARK_HOME="/usr/lib/spark")

config <- spark_config()

sc <- spark_connect(master = "yarn-client", config = config, version = '2.2.1')
`
How can I solve this problem? Thanks for your help  !

Down-below is the fatal error I got sometimes: 
`
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb16cce2968, pid=27872, tid=0x00007fb16d64e940
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
`

**Comment by harryprince** [comment]
@Greezy07 please provide a more reproducible example
