### ISSUE TITLE
Sparklyr ML Flow integartion

### ISSUE THREAD

**Issue by Sharathmk99** [sparklyr/sparklyr#1983]
Hi Team,

I have trained the Logistic Regression using ML Pipeline.
pipeline = ml_pipeline(sc)
.....
pipeline <- ml_logistic_regression(pipeline, features_col="features", label_col="label")
pipelineModel <- ml_fit(pipeline, train)

Now i'm trying to log the model to ML Flow.
mlflow_install()
mlflow_start_run()
mlflow_log_model(pipelineModel, "BinaryModel")

I'm getting below error,
Error in UseMethod("mlflow_save_flavor") : 
  no applicable method for 'mlflow_save_flavor' applied to an object of class "c('ml_pipeline_model', 'ml_transformer', 'ml_pipeline_stage')"

I tried mlflow_save_model(pipelineModel, path="BinaryModel"), still i get the same error.

Please help.

**Comment by harryprince** [comment]
@Sharathmk99 could you provide a more reproducible example with `reprex` R package.

**Comment by kevinykuo** [comment]
This isn't implemented yet, do you mind filling an issue in the mlflow repo?

**Comment by kevinykuo** [comment]
In the meantime you can call ml_save() and log the artifact

**Comment by chengyineng38** [comment]
How does one load the model back in then? I thought `mlflow_download_artifacts(model_uri, run_id, client = mlflow_client())` would work, but I got the following error: 
```
Error in run(mlflow_bin, args = unlist(args), echo = echo, echo_cmd = verbose, : Error in run(mlflow_bin, args = unlist(args), echo = echo, echo_cmd = verbose,  : 
  System command 'mlflow' failed, exit status: 1
```

**Comment by chengyineng38** [comment]
> How does one load the model back in then? I thought `mlflow_download_artifacts(model_uri, run_id, client = mlflow_client())` would work, but I got the following error:
> 
> ```
> Error in run(mlflow_bin, args = unlist(args), echo = echo, echo_cmd = verbose, : Error in run(mlflow_bin, args = unlist(args), echo = echo, echo_cmd = verbose,  : 
>   System command 'mlflow' failed, exit status: 1
> 
> mlflow.exceptions.MlflowException: 404 Client Error: Not Found for url
> ```

Seems like we need to get out of the MLflow ecosystem and use sparklyr

```
model_loaded <- ml_load(sc, model_path)
predictions <- ml_transform(model_loaded, test_df)
```

**Comment by chengyineng38** [comment]
It would be great if the API `mlflow_log_model` and `mlflow_load_model` can be implemented. It somewhat defeats the purpose to be using `sparklyr`'s native function when we hope to use `mlflow_load_model` to load in the model from a specific run and experiment id.

**Comment by yitao-li** [comment]
@chengyineng38 This feature should be available in the next version of mlflow R client (see https://github.com/mlflow/mlflow/pull/3819)

cc @kevinykuo

**Comment by chengyineng38** [comment]
@yitao-li Seems like the pull request you linked is specific to MLeap, but not sparklyr trained models?

**Comment by yitao-li** [comment]
@chengyineng38 I think the MLeap serialization format supports arbitrary Spark ML pipelines (see https://github.com/combust/mleap/wiki/Serializing-a-Spark-ML-Pipeline-and-Scoring-with-MLeap), so, it should work with any pipeline that is built with `ml_*` family of functions in `sparklyr`.

Example of serializing a `sparklyr` pipeline and re-using it later: https://github.com/mlflow/mlflow/blob/5f6018a3c50bf04c29fa8f5d07ee17d76977a8f2/mlflow/R/mlflow/tests/testthat/test-model-mleap.R#L15
