### ISSUE TITLE
[Feature Request] spark_read_csv() with the "adl://" or "abfs://" file path for Azure Data Lake

### ISSUE THREAD

**Issue by alexhallam** [sparklyr/sparklyr#1991]
Right now only S3, HDFS, and local filesystems are supported. It would be nice to have  "adl://" or "abfs://" options for `spark_read_csv()`

**Comment by kevinykuo** [comment]
What error are you seeing?

**Comment by yitao-li** [comment]
It's up to Spark to support (or not support) those systems. Sparklyr is for the most part only an R interface for Apache Spark.
