### ISSUE TITLE
Spark_apply takes multiple attempts to collect all the results with closures

### ISSUE THREAD

**Issue by sreejithpg112** [sparklyr/sparklyr#2017]
I have a use case where I have to call a function 10,000 times, which will compute different results based on the index. 

The following code doesn't throw any error. However, results for some indexes are missing in the spark_result. If I check the logs, I can see that function is called for all the indexes and results for all indexes are printed in the log.

**data <- copy_to( sc, data.frame(idx = c(1:10000)))
spark_result <- data.frame(spark_apply(data,closure_function(variable1,variable2,...,variable20), group_by = 'idx'))**

After running the above code, if I wait for some time (say 2 mins)  without closing the spark connection and try to collect the result again, I get all the 10,000 results.

**spark_res <- spark_apply(data,closure_function(variable1,variable2,...,variable20), group_by = 'idx')
spark_result <- sparklyr::collect(spark_res)**

**Comment by javierluraschi** [comment]
We would need a reproducible example to help... or you could try to scope this a bit more. For instance,

1) Is this a problem with `collect()`? Can you try counting the rows instead of collecting them? Does this transformation have the correct number of rows in Spark?
2) Would this be reproducible with a simpler `closure`? Say, one that simply maps to the same dataset? As in, `spark_apply(function(x) x)`?
3) How are you logging how many rows get processed? Is the logging code correct? etc.

**Comment by sreejithpg112** [comment]
**Please use the code given below the reproduce the issue**

`closure_function <- function(var1,var2,var3) {
  force(var1)
  force(var2)
  force(var3)
  function(index) {
    ## function contains complex R calculations
    return (index * var1 * var2 * var3)
  }
}

data <- copy_to(sc,data.frame(idx = c(1:10000)))

- Expected dimension of result 10000, 2

**##Attempt 1**
spark_res <- data.frame(spark_apply(data,closure_function(10,20,30),group_by = 'idx')) 

- spark_res missing some indexes, but no error produced by Spark. Dimension of the result is given below
- dim(spark_res)
- [1] 6902    2

Sys.sleep(20)

**##Attempt 2**
spark_res <- data.frame(spark_apply(data,closure_function(10,20,30),group_by = 'idx')) 

- Same call, different number of results
- dim(spark_res)
-  [1] 9896    2

Sys.sleep(20)

**##Attempt 3**
spark_res <- data.frame(spark_apply(data,closure_function(10,20,30),group_by = 'idx')) 

-  Same call, different number of results
-  dim(spark_res)
-  [1] 9944    2

Sys.sleep(20)

**##Attempt 4**
spark_res <- data.frame(spark_apply(data,closure_function(10,20,30),group_by = 'idx')) 

-  Same call, different number of results
-  dim(spark_res)
-  [1] 7855    2

`

**Comment by yitao-li** [comment]
It would be helpful to know what the "complex computation" above actually is and whether it introduces non-deterministic number of rows into the result.
