### ISSUE TITLE
Save a value from an sdf_sql statement in a variable

### ISSUE THREAD

**Issue by Scotturbina** [sparklyr/sparklyr#2037]
Hello,

I am trying to save in a variable called id the result of a query like this :

```
id<-sdf_sql(spark,"SELECT MAX(batchid) FROM  TABLE ")

```

But when I see the id variable it it seems a spark dataframe like this:

```
id
# Source: spark<?> [?? x 1]
  `max(batchid)`
           <dbl>
1              1
```

Do you know how can I extract that "1" and save it into the variable called id?

Regards

**Comment by benmwhite** [comment]
[`dplyr::pull()` should do the trick](https://dplyr.tidyverse.org/reference/pull.html), but you may need to write some sort of check to make sure that the column you're pulling has exactly one value.
