### ISSUE TITLE
Problem translating to SQL expression when expression contain an index

### ISSUE THREAD

**Issue by suren-rathnayake** [sparklyr/sparklyr#2040]
When I use a `dplyr` expression which contains (an indexed) element of a vector, it seems
there is a problem in translating the expression to a SQL query.  

However, if I assign this value to a new variable, and then use it in the expression, the SQL query works fine.

```r
library(sparklyr)
library(dplyr)

# setting up
sc <- spark_connect(master = "local")
spark_version(sc)
# [1] ‘2.4.3’

iris_tbl <- copy_to(sc, iris)
spark_write_parquet(iris_tbl, "temp")
tbl <- spark_read_parquet(sc, "data", "temp")

unique_values <- tbl %>% distinct(Species) %>% collect
unique_values$Species[1]
#[1] "versicolor"
class(unique_values$Species[1])
#[1] "character"

tbl %>% filter(Species ==  unique_values$Species[1] ) %>% show_query()
#<SQL>
#>Error in UseMethod("escape") : 
#no applicable method for 'escape' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"

var_name <- unique_values$Species[1]
tbl %>% filter(Species ==  var_name) %>% show_query()
#<SQL>
#SELECT *
#FROM `data`
#WHERE (`Species` = "versicolor")
```

**Comment by yitao-li** [comment]
This seems to be a dplyr issue not a sparklyr issue.

In my opinion, dplyr can only make some educated guesses about which part of your expression should be evaluated in the local R env and which part to translate to Spark SQL and evaluated by the Spark SQL query engine. Such guesses are usually correct, but when they are not, then you will need some workaround (such as storing some expressions in a variable as you mentioned above),
