### ISSUE TITLE
Visualizations in Spark Dataframes

### ISSUE THREAD

**Issue by Scotturbina** [sparklyr/sparklyr#2041]
Hello,

Is there a way or package that could help me by doing visualizations with sparklyr?
I saw that SparkR suppports ggplot.

I do really appreciate your help

**Comment by harryprince** [comment]
From my best practice experience, I suggest you collect the sample data, and viz them locally.

**Comment by Scotturbina** [comment]
@harryprince  What about if I want to link a shiny app with hive and make some visualizations?

**Comment by edgararuiz** [comment]
Hi, have you looked at `dbplot`? It pushes the calculations to Spark and plots locally: https://github.com/edgararuiz/dbplot

**Comment by harryprince** [comment]
@Scotturbina 
hive is not a good query engine, which is optimized for the batch query.
I suggest you dump the data into MySQL or HBase, and then query this data into the Shiny App.

**Comment by yl790** [comment]
I agree with Edgar that dbplot seems to be a good fit -- Looks like it also minimizes the overhead of connecting with the data source, which is important for working with distributed data in Spark.
