### ISSUE TITLE
Why is "tbl_spark" faster than "SparkDataFrame" ?

### ISSUE THREAD

**Issue by nik-maheshwari** [sparklyr/sparklyr#2047]
I am benchmarking `R` and `Spark` for my particular dataset. I benchmarked random forest ML method on both `R` `dataframe` and `SparkR` `SparkDataFrame`. Long story short, `R` is faster than `SparkR` on small dataset, and `SparkR` is faster than `R` on large dataset. I was happy with this benchmark (as this is a known fact).
Out of curiosity, I ran the same benchmark on `Sparklyr` `tbl_spark` object, and it was faster than both `R` and `SparkR` by 40x and 30x respectively. `Sparklyr` definitely called more number of garbage collectors (~15) than `R` (~4) or `SparkR` (0). And used more memory than `SparkR` (but less than `R`).

Before I go into the specifics of the code and dataset, why is this so? Does `tbl_spark` get loaded into memory? I am asking this because it takes longer to load the same file in `Sparklyr` than in `SparkR` (this might be a different question). 

I am quite confused.

Things to note - 
1. I kept the Spark's configuration same.
2. Same dataset used (`bench::press` and `bench::mark` used for benchmarking over different combination of rows and columns).
3. Random forest parameters were kept the same.
4. Each benchmark was run 5 times, and the median time was compared.

**Comment by benmwhite** [comment]
>Does `tbl_spark` get loaded into memory?

If you used one of the `spark_read_*` functions to load it then yes, the table gets cached in your Spark executors' memory by default. You can change this by setting `memory = FALSE` in your `spark_read_*` call.

**Comment by nik-maheshwari** [comment]
So does that also explain why I am unable to load a 11Gb csv file into Sparklyr using default Spark configuration?
`conf$spark.yarn.executor.memoryOverhead <- "8g"` helps in this matter (as I am working on a 300Gb RAM server), but not all system will!

**Comment by benmwhite** [comment]
Use `spark.executor.memory` (not `spark.yarn.memoryOverhead`) if you want to expand the amount of space available for caching tables in your executors. The exact value available for storage and execution will be `spark.executor.memory` times `spark.memory.fraction`, see [the Spark config docs](https://spark.apache.org/docs/2.4.0/configuration.html#memory-management) for a more detailed explanation.

**Comment by nik-maheshwari** [comment]
Ok thanks for clearing that up. I am keeping track using the Web UI. SparkR has no trouble loading the file, but Sparklyr just runs out memory and kills the session. If I am benchmarking, the full dataset keeps going for hours and I have to kill the job.

**Comment by benmwhite** [comment]
Is your session created by sparklyr still running while that's happening? You can check this with the Hadoop/YARN web UI.

I've had sessions crash due to overloading the driver memory while R sits waiting for the results, i.e. R still "sees" the Spark session but it's actually not running at all. You can fix this by setting `conf$`sparklr.shell.driver-memory` to a larger value, I believe the default is 1GB minus a little overhead.

If the session is actually still active and not crashed then I would check to see that it's actually getting executors allocated to it (also viewable on the Hadoop/YARN UI). This can happen if your cluster is occupied with other YARN applications. You can try turning off dynamic allocation and manually requesting a specific number of executors to test this out.

You can also use the Hadoop/YARN UI to see what the differences are between your SparkR sessions and your sparklyr sessions (executors, memory usage, queues, etc.).

**Comment by nik-maheshwari** [comment]
I made some modifications and it has no trouble loading 11Gb datafile from HDFS.

`conf = spark_config()`
`conf$spark.r.backendConnectionTimeout = 60000000`
`conf$sparklyr.shell.driver-memory <- "8G"`
`conf$sparklyr.shell.executor-memory <- "8G"`
`conf$spark.yarn.executor.memoryOverhead <- "8G"`
`sc <- spark_connect(master = "local[*]", config = conf)`

But when I am benchmarking it on a `test` dataset of 400000 x 42 (with combinations of different set of rows and columns), it crashes everytime when it reaches the last combination of 400000 x 42 (sometimes at 400000 x 21). See the code below - 

```r
resultSparklyr <- bench::press(
  rows = c(1000, 2000, 5000, 10000, 20000, 50000, 100000, 200000, nrows),
  cols = c(ncols/2, ncols),
  {
    # no direct way to subset in Spark, as SDF doesn't store row numbers
    dat <- test[1:rows, 1:cols] # create R df
    datSp <- copy_to(sc, dat, overwrite = TRUE) # convert R df to SDF
    bench::mark(iterations = 5, check = TRUE, min_time = Inf,
                Sparklyr = ml_random_forest_regressor(datSp, Yield ~ .)
    )
  }
)
```

It is not a memory issue as all previous runs used between 8-15 Mb of RAM (this is from the output of `bench::mark`
