### ISSUE TITLE
`mutate_at`, `summarise_all`,  not working 

### ISSUE THREAD

**Issue by moouad** [sparklyr/sparklyr#2050]
```
set.seed(.1210)
my_df <- data.frame(letters_col = sample(letters, 50, replace  = TRUE),
                    numbers_col =  rnorm(50), 
                    stringsAsFactors = FALSE)  %>% 
  copy_to(sc,., 'my_df_spark', overwrite = TRUE)


my_df %>%  head 


# # Source: spark<?> [?? x 2]
# letters_col numbers_col
# <chr>             <dbl>
# 1 x                0.504 
# 2 g                1.09  
# 3 j               -0.691 
# 4 o               -1.28  
# 5 x                0.0467
# 6 f               -0.236 


my_df %>%  mutate_at('letters_col', toupper)

## Error in (function (x)  : object 'letters_col' not found

my_df %>%  mutate(letters_col = toupper(letters_col))


# # Source: spark<?> [?? x 2]
# letters_col numbers_col
# <chr>             <dbl>
# 1 X                0.504 
# 2 G                1.09  
# 3 J               -0.691 
# 4 O               -1.28  
# 5 X                0.0467
# 6 F               -0.236 
# 7 X               -0.543 
# 8 Y               -0.433 
# 9 R               -0.649 
# 10 Q                0.727 
# # … with more rows



sessionInfo()

# R version 3.4.1 (2017-06-30)
# Platform: x86_64-redhat-linux-gnu (64-bit)
# Running under: Amazon Linux AMI 2018.03
# 
# Matrix products: default
# BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so
# 
# locale:
# [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
# [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
# [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
# [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
# [9] LC_ADDRESS=C               LC_TELEPHONE=C            
# [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
# 
# attached base packages:
#   [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] lubridate_1.7.4 DBI_1.0.0       scales_1.0.0    ggplot2_3.2.0  
# [5] sparklyr_1.0.0  tibble_2.1.3    tidyr_0.8.3     dplyr_0.8.1    
# 
# loaded via a namespace (and not attached):
# [1] Rcpp_1.0.1       pillar_1.4.1     compiler_3.4.1   dbplyr_1.2.1    
# [5] r2d3_0.2.3       base64enc_0.1-3  tools_3.4.1      zeallot_0.1.0   
# [9] digest_0.6.15    jsonlite_1.5     gtable_0.3.0     pkgconfig_2.0.2 
# [13] rlang_0.3.4      cli_1.0.0        rstudioapi_0.7   parallel_3.4.1  
# [17] yaml_2.1.19      stringr_1.3.1    withr_2.1.2      httr_1.3.1      
# [21] vctrs_0.1.0      generics_0.0.2   htmlwidgets_1.3  rprojroot_1.3-2 
# [25] grid_3.4.1       tidyselect_0.2.5 glue_1.3.1       forge_0.2.0     
# [29] R6_2.4.0         fansi_0.4.0      purrr_0.2.5      magrittr_1.5    
# [33] backports_1.1.2  htmltools_0.3.6  ellipsis_0.1.0   assertthat_0.2.1
# [37] colorspace_1.4-1 config_0.3       utf8_1.1.4       stringi_1.2.3   
# [41] openssl_1.0.1    lazyeval_0.2.1   munsell_0.5.0    crayon_1.3.4 






```

**Comment by javierluraschi** [comment]
@edgararuiz is this familiar to any `dbplyr` known issue?

**Comment by moouad** [comment]
the same error is triggered by `summarise_all`

**Comment by str-amg** [comment]
Is there an open or closed issue in dplyr related to this? Where is the proper place to track progress on it?

**Comment by dkincaid** [comment]
Any updates on this issue or a workaround? We're running into it as well.

**Comment by yl790** [comment]
I just tried the same query and saw it working with sparklyr 1.2.0 and dplyr 0.8.5. The version of R I'm running is 4.0.0.

Maybe try replacing `mutate_at` with `dplyr::mutate_at`, in case namespace disambiguation matters? (unlikely, but one never knows...)

**Comment by wanting0wang** [comment]
I'm still getting into this issue with sparklyr 1.4.0 & dplyr 1.0.2 on R 3.6.1.

<img width="446" alt="Screen Shot 2021-05-13 at 15 08 01" src="https://user-images.githubusercontent.com/25274600/118175210-cea5c400-b3fd-11eb-91d9-93c341751610.png">

As an alternative, `mutate(across())` is able to recognize the column names. However I see the result of `length()` function is different when I don't specify new column name vs. when I specify:
<img width="537" alt="Screen Shot 2021-05-13 at 15 16 08" src="https://user-images.githubusercontent.com/25274600/118175537-39ef9600-b3fe-11eb-833d-fc66b5c6a88f.png">

The result with `.names` specified is the one I'm looking for. Probably need to fix the one without `.names`?

**Comment by yitao-li** [comment]
@wanting0wang `length` will not work well in this case because the `length` function in R returns the number of elements in a character vector (e.g., `length(c("abc", "def", "ghi"))` will return `3`, whereas `length("abc")` returns 1, etc), whereas `nchar` is the correct function in R that returns the number of characters in a string.

In sparklyr 1.6, either of the following will work as expected:

`tbl %>% dplyr::mutate(across(c("col0", "col1"), nchar))`   (in this case `dplyr` translate a R function `nchar` to its equivalent in Spark SQL)

`tbl %>% dplyr::mutate(across(c("col0", "col1"), ~ length(.x)))` (in this case `dplyr` does not perform R-to-Spark-SQL translation for the function being applied, and a function named `length` in Spark SQL will be run (which is, of course, very different from the `length` function in R)

**Comment by wanting0wang** [comment]
@yitao-li What you said totally makes sense. It just looks weird to me that using `length` in the same way could have different results based on whether the user specifies the `.names` parameter or not. I would expect them returning the same result, no matter it's the number of elements or the number of characters. In my work I switched to `nchar` to ensure there is no confusion.
