### ISSUE TITLE
Error in library(sparklyr) : there is no package called ‘sparklyr’

### ISSUE THREAD

**Issue by anaidv57** [sparklyr/sparklyr#2063]
Hi,

Sparkly was working fine for me, suddenly It stopped working.
This is happening:
> library(sparklyr)
Error in library(sparklyr) : there is no package called ‘sparklyr’

So I installed sparkly again.  

> install.packages("sparklyr")
Installing package into ‘C:/Users/anaid/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/sparklyr_1.0.1.zip'
Content type 'application/zip' length 3364716 bytes (3.2 MB)
downloaded 3.2 MB

package ‘sparklyr’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘sparklyr’

The downloaded binary packages are in
	C:\Users\anaid\AppData\Local\Temp\3\Rtmpgz5SlN\downloaded_packages
> library(sparklyr)
Error in library(sparklyr) : there is no package called ‘sparklyr’

Thanks for your help!!

> utils::sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sessioninfo_1.1.1 stringi_1.4.3     SparkR_2.4.3     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        rstudioapi_0.10   magrittr_1.5      usethis_1.5.0     devtools_2.0.2   
 [6] pkgload_1.0.2     R6_2.4.0          rlang_0.4.0       tools_3.6.0       pkgbuild_1.0.3   
[11] cli_1.1.0         withr_2.1.2       remotes_2.1.0     yaml_2.2.0        assertthat_0.2.1 
[16] digest_0.6.19     rprojroot_1.3-2   crayon_1.3.4      processx_3.3.1    callr_3.2.0      
[21] fs_1.3.1          ps_1.3.0          memoise_1.1.0     glue_1.3.1        compiler_3.6.0   
[26] desc_1.2.0        backports_1.1.4   prettyunits_1.0.2
> devtools::session_info()
- Session info ---------------------------------------------------------------------------------       
 date     2019-07-01                  

- Packages -------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 backports     1.1.4   2019-04-10 [1] CRAN (R 3.6.0)
 callr         3.2.0   2019-03-15 [1] CRAN (R 3.6.0)
 cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.0)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
 devtools      2.0.2   2019-04-08 [1] CRAN (R 3.6.0)
 digest        0.6.19  2019-05-20 [1] CRAN (R 3.6.0)
 fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
 glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
 pkgbuild      1.0.3   2019-03-20 [1] CRAN (R 3.6.0)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.0)
 processx      3.3.1   2019-05-08 [1] CRAN (R 3.6.0)
 ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.0)
 R6            2.4.0   2019-02-14 [1] CRAN (R 3.6.0)
 Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.6.0)
 remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.0)
 rlang         0.4.0   2019-06-25 [1] CRAN (R 3.6.0)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi    0.10    2019-03-19 [1] CRAN (R 3.6.0)
 sessioninfo * 1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
 SparkR      * 2.4.3   2019-05-09 [1] CRAN (R 3.6.0)
 stringi     * 1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
 usethis       1.5.0   2019-04-07 [1] CRAN (R 3.6.0)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
 yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)

**Comment by javierluraschi** [comment]
> cannot remove prior installation of package ‘sparklyr’

might indicate that some other used (maybe an admin) installed `sparklyr` previously, maybe launching R/RStudio in administrator mode and reinstalling will fix this?

**Comment by filipwastberg** [comment]
Are you using R on a computer with a shared network?
