### ISSUE TITLE
error in spark_connect on Windows10: system2 returns character(0)

### ISSUE THREAD

**Issue by mkoohafkan** [sparklyr/sparklyr#2085]
I am trying to use `sparklyr` from outside RStudio (in this case, through standard R console) with a pre-existing installation of Spark (since `spark_install` repeatedly fails to download). I am getting the following cryptic error message

>Error in if (!is.null(output) && grepl("error", output)) { : 
  missing value where TRUE/FALSE needed

Which I have traced down to these lines in [`prepare_windows_environment`](https://github.com/rstudio/sparklyr/blob/1a4401ab75d80985bf185742dd6e8bb35e357887/R/install_spark_windows.R#L128):

```r
 output <- system2(
    winutils,
    c("ls", shQuote(hivePath)),
    stdout = TRUE)

  if (!is.null(output) && grepl("error", output)) {
    stop(output)
}
```

winutils is supposed to return either `0` or `1`, but in my case the value of `output` is `character(0)`, which causes the `if` statement to error. If I change argument `stdout` to  `FALSE`, I get a value of `0`.

Is this a bug, or is there something else going on here?

```r
sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_1.0.1.9004

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       rstudioapi_0.10  magrittr_1.5     tidyselect_0.2.5 R6_2.4.0         rlang_0.4.0      httr_1.4.0       dplyr_0.8.3      tools_3.6.0      parallel_3.6.0   config_0.3       DBI_1.0.0        withr_2.1.2     
[14] dbplyr_1.4.2     askpass_1.1      htmltools_0.3.6  ellipsis_0.2.0.1 openssl_1.4      yaml_2.2.0       assertthat_0.2.1 rprojroot_1.3-2  digest_0.6.20    tibble_2.1.3     forge_0.2.0      crayon_1.3.4     purrr_0.3.2     
[27] base64enc_0.1-3  htmlwidgets_1.3  glue_1.3.1       compiler_3.6.0   pillar_1.4.2     generics_0.0.2   r2d3_0.2.3       backports_1.1.4  jsonlite_1.6     pkgconfig_2.0.2 

```

**Comment by javierluraschi** [comment]
@mkoohafkan could you share the `spark_install()` installation error?

My guess is that since it was not installed by `sparklyr`, there are folder/permission issues when we use `winutils`. So ideally, I would try first to install using `spark_install()`.

**Comment by mkoohafkan** [comment]
Sure, although I don't understand how this would change the issue with the `system2` call:


```r
spark_install()
```
```r
Installing Spark 2.4.3 for Hadoop 2.7 or later.
Downloading from:
- 'https://archive.apache.org/dist/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz'
Installing to:
- 'C:\Users\mkoohafk\AppData\Local/spark/spark-2.4.3-bin-hadoop2.7'
trying URL 'https://archive.apache.org/dist/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz'
Error in download.file(installInfo$packageRemotePath, destfile = installInfo$packageLocalPath,  : 
  cannot open URL 'https://archive.apache.org/dist/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz'
```

This error may be caused by organization's firewall, I am completely unable to access `archive.apache.org` from R or via a browser. I instead downloaded Spark from https://spark.apache.org/downloads.html.

**Comment by javierluraschi** [comment]
Yes, probably blocked since I was just able to check it works properly and we have automated tests that validate this continuously.

Try to download the Spark version manually (seems like you might already have), but instead of manually extracting the contents, use:

```
sparklyr::spark_install_tar("<path-to-your-spark-tar>")
```

**Comment by mkoohafkan** [comment]
Using `spark-2.4.3-bin-hadoop2.7.tgz` downloaded from https://spark.apache.org/downloads.html:

```r
spark_install_tar("C:/Users/mkoohafk/Downloads/spark-2.4.3-bin-hadoop2.7.tgz")
# success
spark_installed_versions()
## spark      hadoop    dir
## 1 2.4.3    2.7       C:\\Users\\mkoohafk\\AppData\\Local/spark/spark-2.4.3-bin-hadoop2.7

spark_connect(master="local")
## Error: 
## 
## To run Spark on Windows you need a copy of Hadoop winutils.exe:
## 
## 1. Download Hadoop winutils.exe from:
## 
##    https://github.com/steveloughran/winutils/raw/master/hadoop-2.6.0/bin/
## 
## 2. Copy winutils.exe to C:\Spark\spark-2.4.3-bin-hadoop2.7\tmp\hadoop\bin
## 
## Alternatively, if you are using RStudio you can install the RStudio Preview Release,
## which includes an embedded copy of Hadoop winutils.exe:
## 
##   https://www.rstudio.com/products/rstudio/download/preview/
```
After doing that, try again:
```r
spark_connect(master="local")
## Error in if (!is.null(output) && grepl("error", output)) { : 
##   missing value where TRUE/FALSE needed
```
which is the same error.

**Comment by mkoohafkan** [comment]
Wait, i realize I copied winutils to the wrong folder. Will try again tomorrow morning.

**Comment by mkoohafkan** [comment]
Hmm, it seems like even though the Spark install is located at `C:\Users\mkoohafk\AppData\Local\spark\spark-2.4.3-bin-hadoop2.7` it still expects winutils to live in `C:\Spark\spark-2.4.3-bin-hadoop2.7\tmp\hadoop\bin`. Anyway, we are back to square one.

**Comment by sabrishami** [comment]
Hi, can you solve this problem?
