### ISSUE TITLE
Databricks Connect

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#2089]
Related to:
- https://github.com/rstudio/sparklyr/issues/2088

**Comment by ryan-daly-AgFCS** [comment]
Q: is there an update for this feature request? We're in progress to roll out Databricks, but still want to leverage client IDE of RStudio. SparkR works, but having sparklyr would be extremely beneficial for local development!

**Comment by falaki** [comment]
Hi, we are working on this and you can expect some good news soon.

**Comment by kohleth** [comment]
saw the ticket got moved to 'done' on sparklyboard. Can't wait to test this out.

**Comment by ryan-daly-AgFCS** [comment]
@kohleth I noticed as well! 

Does anyone know if there is documentation on initial config and use?

**Comment by kohleth** [comment]
> @kohleth I noticed as well!
> 
> Does anyone know if there is documentation on initial config and use?

found this recently https://blog.rstudio.com/2020/05/06/sparklyr-1-2/

**Comment by yl790** [comment]
@kohleth @ryan-daly-AgFCS Hey glad to hear you are interested in this feature!
I believe it's documented in https://docs.databricks.com/dev-tools/databricks-connect.html#install-configure-and-use-sparklyr

I don't think there is any Databrick-specific parameter needed for instantiating the connection other than `method = "databricks"`. @falaki, et al can correct me if I'm wrong.
