### ISSUE TITLE
Support Map Type Data in Sparklyr

### ISSUE THREAD

**Issue by harryprince** [sparklyr/sparklyr#2094]

**Comment by javierluraschi** [comment]
@harryprince you happen to have a reprex or more details? I'm assuming you are thinking of `invoke()`?

**Comment by harryprince** [comment]
construct a Map type in scala like this:
```
scala> Map((1,2))
res0: scala.collection.immutable.Map[Int,Int] = Map(1 -> 2)
```
However, I fail to find how to pass the `(key,value)` format parameter by `sparklyr::invoke` function

**Comment by yitao-li** [comment]
See https://github.com/sparklyr/sparklyr/blob/fe0bdec59ce1fe4980d0ae14e16ae9d90ffe5e03/tests/testthat/test-serialization.R#L351-L366 for an example.

Please note `sparklyr` only supports collecting `Map`s with String keys into R envs at the moment.
