### ISSUE TITLE
Parallel connections to the gateway fail

### ISSUE THREAD

**Issue by lorenzolightsgdwarf** [sparklyr/sparklyr#2096]
Hi,
I setup Spark to run in Standalone mode. Both Master and 1 Worker are located in the same machine and binds to localhost.

Now what I want to do is to start in parallel multiple sparklyr applications that should not share anything using gnu parallel. If I start them sequentially everything is fine, but if I lunch multiple of them at the same time some of the connections hang. On the masterweb page I don't see any application. the submit processes are spawned but either they do nothing or some of the connection attempts return 

> Error in force(code) : Failed while connecting to sparklyr to port (65530) for sessionid (73922): Sparklyr gateway did not respond while retrieving ports information after 60 seconds

As I understood, the backend is reused if already available, but maybe in this case a race condition rises. 
> If the port is already in use, the Backend will attempt to use the existing service running in this port as a sparklyr gateway and register itself. Therefore, the gateway socket serves not only as an interface to connect to the current instance, but also as bridge to other sparklyr backend instances running in this machine. This mechanism is the replacement of the ports file which used to communicate ports information back to the sparklyr client, in this model, one and only one gateway runs and provides the mapping between sessionids and ports. 

Or maybe my way of setting it up is wrong. Maybe in this scenario, I need one backend for eqach application. Here the code for reproducing

```r
library("sparklyr")
connect_to_spark <- function() {
  print(Sys.time())
  SPARK_MASTER <- "spark://127.0.0.1:7077"
  SPARK_HOME <- "/home/lorenzolucignano/spark-2.4.3-bin-hadoop2.7/"
  configuration <- spark_config()
  configuration$spark.sql.catalogImplementation <- "in-memory"
  configuration$sparklyr.gateway.timeout <- 5
  configuration$spark.driver.memory <- "1g"
  configuration$sparklyr.gateway.port <- 65530 
  configuration$spark.cores.max <- 1
  configuration$spark.driver.host <- "127.0.0.1"
  configuration$sparklyr.log.console <- TRUE
  configuration$spark.executor.memory<- "500m"
  return(spark_connect(master = SPARK_MASTER, spark_home = SPARK_HOME, config = configuration))
} 
sc<-connect_to_spark()
Sys.sleep(sample(seq(0.1,2,0.1), 1))
spark_disconnect(sc)
```

```sh
parallel Rscript spark_test.R ::: {1..100}
```

Using sparklyr 1.0.1.9004

**Comment by javierluraschi** [comment]
If you want to connect in parallel better assign the port to a random number yourself, something like that should work for cases where several parallel connections are started concurrently. Even if one port ends up being the same, `sparklyr` is smart enough to reroute; however, there are race conditions when connection starts exactly at the same time, which is probably what you are experiencing.

```
configuration$sparklyr.gateway.port <- 8880 + round(runif(1, 1, 1000))
```

**Comment by lorenzolightsgdwarf** [comment]
Thanks. This was exactly my workaround. I guess it's not possible to start in advance a gateway without any application and than let the other connection to go on that one, right?
