### ISSUE TITLE
Failed while connecting to sparklyr to port (41**) for sessionid (4****): ignoring SIGPIPE signal 

### ISSUE THREAD

**Issue by patnes-ttl** [sparklyr/sparklyr#2114]
# Reporting an Issue with sparklyr
Error in force(code) :
  Failed while connecting to sparklyr to port (4***) for sessionid (4****): ignoring SIGPIPE signal
    Path: /usr/lib/spark/bin/spark-submit
    Parameters: --class, sparklyr.Shell, '/usr/lib64/R/library/sparklyr/java/sparklyr-2.3-2.11.jar', 4***, 4****
    Log: /tmp/Rtmpe8i2os/file14e0464f0a93b_spark.log

---- Output Log ----
19/08/06 23:31:55 INFO sparklyr: Session (4****) is starting under 127.0.0.1 port 4***
19/08/06 23:31:55 INFO sparklyr: Session (4****) found port 4*** is available
19/08/06 23:31:55 INFO sparklyr: Gateway (4****) is waiting for sparklyr client to connect to port 4***

---- Error Log ----
Calls: spark_connect ... tryCatchOne -> <Anonymous> -> abort_shell -> <Anonymous> -> force
Execution halted

Please suggest solution

**Comment by yitao-li** [comment]
FYI configurable retries are added around that failing code paths starting from sparklyr 1.4.0 (to be released soon)
