### ISSUE TITLE
Long time to Launch Cluster using Amazon EMR

### ISSUE THREAD

**Issue by hanfernandes** [sparklyr/sparklyr#2123]
I use to launch cluster this tutorial: [Running sparklyr – RStudio’s R Interface to Spark on Amazon EMR](https://aws.amazon.com/pt/blogs/big-data/running-sparklyr-rstudios-r-interface-to-spark-on-amazon-emr/). It takes about 20 minutes or more. 

Is there another faster way?

**Comment by benmwhite** [comment]
This doesn't sound like sparklyr issue. EMR clusters will always require some amount of time to spin up, but once it's in place you can just leave it running for whatever duration you want assuming the cost isn't a factor.
