### ISSUE TITLE
Latest Spark releases 2.4.4 and 2.3.4 not in `spark_versions()`

### ISSUE THREAD

**Issue by katossky** [sparklyr/sparklyr#2136]
`spark_versions()` is not up-to-date, and does not contain information about the 2 latest Spark releases

This causes my attempts to use `spark_connect` to fail with the wrong message "Spark version not installed." The version 2.4.4 **is** installed but **unknown** of `sparklyr`. Perhaps this message could be updated to hint at other possible sources of errors ("Spark version not installed, unknown or unsupported").

This is especially annoying on Mac. `brew` does the job of linking Spark to an alternative version of Java 8, since Java 9 is installed by default and not compatible with Spark. On the contrary, `spark_install()` fails. On the other hand, `brew` is already at version 2.4.4.

**Comment by jkylearmstrong** [comment]
Is this related to #1749 ?  I am also wondering if Spark 2.4 is supported by sparklyr

**Comment by yl790** [comment]
Fixed
