### ISSUE TITLE
Configuration via `sparklyr.shell.*` or `spark.*`

### ISSUE THREAD

**Issue by wangyuchen** [sparklyr/sparklyr#2142]
I was trying to connect in YARN client mode and wanted to configure my executor and driver memory. I followed [this chapter](https://therinspark.com/tuning.html#tuning-configuring) in the R in Spark book and tried to configure `sparklyr.shell.*` options instead of `spark.*` options. See a minimal connection setting below.

```r
library(sparklyr)
conf <- spark_config()
conf$`sparklyr.shell.executor-memory` <- "2g"
conf$`sparklyr.shell.driver-memory` <- "2g"

sc <- spark_connect(master = "yarn-client", config = conf)
```

After connected, in the web UI under executors, it seemed that **the driver took the memory setting but the executors didn't**. The 2 default executors had 384M storage memory while the driver had 956M. 

On the environment page, it shows the following spark-submit info:
```
org.apache.spark.deploy.SparkSubmit --conf spark.driver.memory=2g --class sparklyr.Shell --executor-memory 2g /had/home/a377324/R/x86_64-pc-linux-gnu-library/3.5/sparklyr/java/sparklyr-2.0-2.11.jar 8880 11555
```

It seems like the `sparklyr.shell.driver-memory` was taken and then passed as `sparklyr.shell.driver-memory` in the `--conf` flag, but executor memory is passed as a spark-submit flag and wasn't honored. I didn't quite understand the difference here... When I try to set `spark.executor.memory` instead (as suggested [here](https://spark.rstudio.com/guides/connections/)), it seems to be getting 2g correctly. Should I be using the `sparklyr.shell.*` options, or the `spark.*` options, or both?

```
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.6 (Maipo)

Matrix products: default
BLAS: /opt/microsoft/ropen/3.5.0/lib64/R/lib/libRblas.so
LAPACK: /opt/microsoft/ropen/3.5.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_1.0.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2       rstudioapi_0.10  magrittr_1.5     tidyselect_0.2.5
 [5] R6_2.4.0         rlang_0.4.0      httr_1.4.0       dplyr_0.8.3     
 [9] tools_3.5.0      packrat_0.4.9-3  DBI_1.0.0        dbplyr_1.4.2    
[13] ellipsis_0.2.0.1 htmltools_0.3.6  assertthat_0.2.1 rprojroot_1.3-2 
[17] digest_0.6.19    tibble_2.1.3     forge_0.2.0      crayon_1.3.4    
[21] purrr_0.3.2      base64enc_0.1-3  htmlwidgets_1.3  glue_1.3.1      
[25] compiler_3.5.0   pillar_1.4.2     generics_0.0.2   r2d3_0.2.3      
[29] backports_1.1.4  jsonlite_1.6     pkgconfig_2.0.2 
```

**Comment by javierluraschi** [comment]
Correct setting is,

```
# Memory per Worker
config["spark.executor.memory"] <- "2G" 
```

Updating book with https://github.com/r-spark/the-r-in-spark/issues/77

**Comment by wangyuchen** [comment]
Hi @javierluraschi , thanks for replying. I saw you fixed it in the book, great!

Besides executor memory, I think executor cores may have the same issue. In the book, it's suggested to do:

```
config["sparklyr.shell.executor-cores"] <- 1
```

But it doesn't work for me. Instead, this does work:
```
config["spark.executor.cores"] <- 1
```


Also, both of these worked:

```
config["sparklyr.shell.num-executors"] <- 3
config["spark.executor.instances"] <- 1
```

Would it make any difference which way we set it? 

Thanks!

**Comment by javierluraschi** [comment]
Actually, both settings should work, including:

```
config["sparklyr.shell.executor-memory"] <- "2g"
config["sparklyr.shell.num-executors"] <- 3
```

However, some providers like Amazon EMR, might set defaults on their own, see:

https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark-configure.html

which then might requires the `sparklyr` settings to be configured at a higher level using:

```
config["spark.executor.memory"] <- "2G" 
config["spark.executor.cores"] <- 1
```

Regardless, this is probably particular to each cluster. I tried these settings in Amazon EMR and was able to use both of them, so I would suggest using the one that works for your cluster.
