### ISSUE TITLE
Support for convert = FALSE in invoke()

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#2156]
See https://github.com/rstudio/sparklyr/pull/2155

**Comment by kevinykuo** [comment]
This would also make things like https://github.com/rstudio/sparklyr/issues/2151 easier to deal with, as we can provide a common set of converters e.g. `numeric_to_float()` that extension developers to use.

**Comment by yitao-li** [comment]
https://github.com/sparklyr/sparklyr/pull/3063 introduced `j_invoke*` family of functions that essentially do what's required in this issue.

Reason for creating a separate family of invoke functions: there is no reasonably user-friendly way to introduce an additonal `convert` param defaulting to `TRUE` for existing family of `invoke`* functions that already take a variable number of additional params.
