### ISSUE TITLE
Inconsistent dates depending on whether arrow package is loaded

### ISSUE THREAD

**Issue by caewok** [sparklyr/sparklyr#2173]
Importing dates from Spark results in erroneous dates unless the arrow package is loaded. This is probably related to #1954 and #1517. I suspect it is also related to timezones, but it is not obvious to me why a timezone difference between Spark and the R session would affect dates in this manner. 

```r
library(sparklyr)
sc <- spark_connect(master = "local")
if ("arrow" %in% .packages()) detach("package:arrow")
Sys.timezone() # America/Los_Angeles
df <- data.frame(date_orig = as.character(seq(as.Date("2019-01-01"), by = "month", length.out = 12)))

sdf <- copy_to(sc, df, overwrite = TRUE) %>%
  dplyr::mutate(date_class = as.Date(date_orig)) %>%
  dplyr::mutate(date_internal = as_date(date_orig)) %>%
  dplyr::mutate(date_class_chr = as.character(date_class)) %>%
  dplyr::mutate(date_internal_chr = date_format(date_internal, "yyyy-MM-dd z"))

sdf %>% collect() # April through November are wrong for the date_class, date_internal

library(arrow)
sdf %>% collect() # Correct result
```
Running the above code without the arrow library gives me this:

|date_orig  |date_class |date_internal |date_class_chr |date_internal_chr |
|:----------|:----------|:-------------|:--------------|:-----------------|
|2019-01-01 |2019-01-01 |2019-01-01    |2019-01-01     |2019-01-01 GMT    |
|2019-02-01 |2019-02-01 |2019-02-01    |2019-02-01     |2019-02-01 GMT    |
|2019-03-01 |2019-03-01 |2019-03-01    |2019-03-01     |2019-03-01 GMT    |
|2019-04-01 |2019-03-31 |2019-03-31    |2019-04-01     |2019-04-01 GMT    |
|2019-05-01 |2019-04-30 |2019-04-30    |2019-05-01     |2019-05-01 GMT    |
|2019-06-01 |2019-05-31 |2019-05-31    |2019-06-01     |2019-06-01 GMT    |
|2019-07-01 |2019-06-30 |2019-06-30    |2019-07-01     |2019-07-01 GMT    |
|2019-08-01 |2019-07-31 |2019-07-31    |2019-08-01     |2019-08-01 GMT    |
|2019-09-01 |2019-08-31 |2019-08-31    |2019-09-01     |2019-09-01 GMT    |
|2019-10-01 |2019-09-30 |2019-09-30    |2019-10-01     |2019-10-01 GMT    |
|2019-11-01 |2019-10-31 |2019-10-31    |2019-11-01     |2019-11-01 GMT    |
|2019-12-01 |2019-12-01 |2019-12-01    |2019-12-01     |2019-12-01 GMT    |

Using the arrow library (arrow .15.1.1), I get the expected result:

|date_orig  |date_class |date_internal |date_class_chr |date_internal_chr |
|:----------|:----------|:-------------|:--------------|:-----------------|
|2019-01-01 |2019-01-01 |2019-01-01    |2019-01-01     |2019-01-01 GMT    |
|2019-02-01 |2019-02-01 |2019-02-01    |2019-02-01     |2019-02-01 GMT    |
|2019-03-01 |2019-03-01 |2019-03-01    |2019-03-01     |2019-03-01 GMT    |
|2019-04-01 |2019-04-01 |2019-04-01    |2019-04-01     |2019-04-01 GMT    |
|2019-05-01 |2019-05-01 |2019-05-01    |2019-05-01     |2019-05-01 GMT    |
|2019-06-01 |2019-06-01 |2019-06-01    |2019-06-01     |2019-06-01 GMT    |
|2019-07-01 |2019-07-01 |2019-07-01    |2019-07-01     |2019-07-01 GMT    |
|2019-08-01 |2019-08-01 |2019-08-01    |2019-08-01     |2019-08-01 GMT    |
|2019-09-01 |2019-09-01 |2019-09-01    |2019-09-01     |2019-09-01 GMT    |
|2019-10-01 |2019-10-01 |2019-10-01    |2019-10-01     |2019-10-01 GMT    |
|2019-11-01 |2019-11-01 |2019-11-01    |2019-11-01     |2019-11-01 GMT    |
|2019-12-01 |2019-12-01 |2019-12-01    |2019-12-01     |2019-12-01 GMT    |

`utils::sessionInfo()`
> R version 3.6.1 (2019-07-05)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Debian GNU/Linux 9 (stretch)
> 
> Matrix products: default
> BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
>  [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
> [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] arrow_0.15.1.1  bench_1.0.4     dplyr_0.8.3     testthat_2.2.1  Databases_0.3.0
> 
> loaded via a namespace (and not attached):
>  [1] tidyselect_0.2.5  forge_0.2.0       purrr_0.3.3       h2o_3.26.0.2      sparklyr_1.0.4   
>  [6] colorspace_1.4-1  generics_0.0.2    vctrs_0.2.0       htmltools_0.4.0   yaml_2.2.0       
> [11] base64enc_0.1-3   utf8_1.1.4        rlang_0.4.1       pillar_1.4.2      glue_1.3.1       
> [16] withr_2.1.2       DBI_1.0.0         bit64_0.9-7       dbplyr_1.4.2      lifecycle_0.1.0  
> [21] plyr_1.8.4        stringr_1.4.0     munsell_0.5.0     gtable_0.3.0      htmlwidgets_1.5.1
> [26] parallel_3.6.1    fansi_0.4.0       profmem_0.5.0     r2d3_0.2.3        Rcpp_1.0.2       
> [31] openssl_1.4.1     backports_1.1.5   scales_1.0.0      jsonlite_1.6      config_0.3       
> [36] fs_1.3.1          bit_1.1-14        ggplot2_3.2.1     askpass_1.1       digest_0.6.22    
> [41] stringi_1.4.3     rprojroot_1.3-2   grid_3.6.1        cli_1.1.0         tools_3.6.1      
> [46] bitops_1.0-6      magrittr_1.5      lazyeval_0.2.2    RCurl_1.95-4.12   tibble_2.1.3     
> [51] tidyr_1.0.0       crayon_1.3.4      pkgconfig_2.0.3   zeallot_0.1.0     ellipsis_0.3.0   
> [56] data.table_1.12.6 ggridges_0.5.1    lubridate_1.7.4   assertthat_0.2.1  httr_1.4.1       
> [61] rstudioapi_0.10   R6_2.4.0          compiler_3.6.1

**Comment by nealrichardson** [comment]
#2519 should resolve this. See #2439 for more context.
