### ISSUE TITLE
spark_read_... fail if a named character is provided as the `name` argument

### ISSUE THREAD

**Issue by jozefhajnala** [sparklyr/sparklyr#2174]
When reading data using spark_read_..., providing a named character as the `name` argument to the functions will fail.

### Reproducible example

```r
# Attach sparklyr, create dummy csv, connect
library(sparklyr)
objDef <- c(objName = "mtcars", filePath = path.expand("~/mtcars.csv"))
write.csv(mtcars, objDef["filePath"])
sc <- spark_connect("local")

# This does not work
tbl_mtcars <- spark_read_csv(sc, objDef["objName"], objDef["filePath"])

# Error: org.apache.spark.sql.catalyst.parser.ParseException:
#   mismatched input '`objName`' expecting {'(', 'SELECT', 'FROM', 'WITH', 'VALUES', 'TABLE', 'INSERT', 'MAP', 'REDUCE'}(line 1, pos 24)
#
# == SQL ==
#   CACHE TABLE `mtcars` AS `objName`
#------------------------^^^

# While this works fine
tbl_mtcars <- spark_read_csv(sc, unname(objDef["objName"]), objDef["filePath"])

# Cleanup
unlink(objDef["filePath"])
spark_disconnect(sc)
```
## Cause analysis

The cause is that the read functions call `spark_partition_register_df` with `memory=TRUE` by defaultwhich will try to send `dbSendQuery(sc, paste("CACHE TABLE", escape(ident(name), con = sc)))`. The issue arises because `dbplyr:::escape.ident()` will use `dbplyr:::names_to_as()` and thus create SQL such as the above `CACHE TABLE `mtcars` AS `objName`` that will cause a ParseExepction.

## Suggested fix

In PR: https://github.com/rstudio/sparklyr/pull/2175

**Comment by yitao-li** [comment]
Great. Looks like this is fixed. Closing the issue now.
