### ISSUE TITLE
Behavior changes in test-invoke with spark 3.0

### ISSUE THREAD

**Issue by lu-wang-dl** [sparklyr/sparklyr#2192]
With spark 3.0, I got the following failure:

```r
test-invoke.R:18: failure: we can invoke_static with 1 scalar argument
`invoke_static(sc, "sparklyr.Test", "unaryInteger", NULL)` did not throw an error.
```

**Comment by yl790** [comment]
This is because of a weird compiler behavior change in scalac 2.12.

The default compilation spec for sparklyr uses lower versions of scalac to compile everything else but uses scalac 2.12 to compile sparklyr-related jars for Spark 3.0.0-preview.

**Comment by yl790** [comment]
Meanwhile the following is still valid in all scalac versions we use for sparlyr so far:

```
scala> var t1 : Integer = null
t1: Integer = null

scala> var t2 : Integer = 0  # notice Integer is aliased to java.lang.Integer in scala 
t2: Integer = 0

scala> t1 == 0
res17: Boolean = false

scala> t2 == 0
res18: Boolean = true
```

so maybe we  should replace the failing test case involving nullable java.lang.Integer with the above instead.
