### ISSUE TITLE
Behavior changes in ml-feature-imputer with spark 3.0

### ISSUE THREAD

**Issue by lu-wang-dl** [sparklyr/sparklyr#2196]
The following test fails

```r
test-ml-feature-imputer.R:28: failure: ft_imputer() works properly
pull(imputed_tbl, imputed)[[3]] not equal to 3.
1/1 mismatches
[1] 0 - 3 == -3
```

**Comment by yl790** [comment]
Looks like this failure no longer happens after the serialization bug fix in https://github.com/sparklyr/sparklyr/issues/2185

I'll double-check after all relevant changes are merged and then hopefully close this issue soon.

**Comment by yl790** [comment]
Test is passing with Spark 3.0 after serialization bug fix.
