### ISSUE TITLE
Behavior changes in test-ml-feature-word2vec with spark 3.0

### ISSUE THREAD

**Issue by lu-wang-dl** [sparklyr/sparklyr#2198]
The following test fails
```r
test-ml-feature-word2vec.R:51: failure: ml_find_synonyms works properly
"models" %in% synonyms isn't true.
```

**Comment by yl790** [comment]
Note to myself: `ml_find_synonyms(model, "java", 4)` evaluates to

```
# Source: spark<?> [?? x 2]
  word       similarity
  <chr>           <dbl>
1 models          0.967
2 regression      0.949
3 could           0.936
4 logistic        0.383
```
with spark 2.4.4 and

```
# Source: spark<?> [?? x 2]
  word     similarity
  <chr>         <dbl>
1 could         0.961
2 logistic      0.905
3 about         0.786
4 spark         0.482
```

with spark 3.0.0-preview.

**Comment by yl790** [comment]
@javierluraschi I wonder if it makes sense to modify this test to use the same corpus in https://github.com/apache/spark/blob/master/mllib/src/test/scala/org/apache/spark/mllib/feature/Word2VecSuite.scala instead (?) -- i.e., something like https://gist.github.com/yl790/ae54ee80cfe60a56b229879b02e5a081

**Comment by yl790** [comment]
Proposed change to the test case: https://github.com/sparklyr/sparklyr/pull/2281
