### ISSUE TITLE
spark_write_table - spaces in column names replaced with underscores

### ISSUE THREAD

**Issue by dah33** [sparklyr/sparklyr#2205]
When I run this:
```
spark_write_table(df_tbl)
```
and then query the resulting Spark table with SQL, I can see the spaces in the column names have been replaced by underscores. Is this intended behaviour, due to a limitation of Spark? I am running on Databricks, Spark 6.1.

**Comment by samuel-bohman** [comment]
You can try using backticks to wrap the column name, e.g. `column name`, or try the `sparklyr.sanitize.column.names` configuration setting.

**Comment by yl790** [comment]
100% agree on the suggestion of quoting column names with backticks.

But given that there was not really any code path within `sparklyr::spark_write_table` I could find where one could ensure column names are quoted using backticks, I don't think there is anything sparklyr can do about this. So, closing this issue now.
