### ISSUE TITLE
Unable to connect to local cluster

### ISSUE THREAD

**Issue by pman1971** [sparklyr/sparklyr#2206]
Hi,

I had a previous version of spark installed which was corrupted so I reinstalled it. The installation looked to have been successful but I am now unable to create a connection. Prior to the folders being lost in the previous installation there was no issue creating a spark connection.

**utils::sessionInfo()**

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

**Custom install path**
options(spark.install.dir = "C:\\Users\\petros.koulouris\\spark_install")
spark_install()

**Installation message from console**
Installing Spark 2.4.3 for Hadoop 2.7 or later.
Downloading from:
- 'https://archive.apache.org/dist/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz'
Installing to:
- 'C:\Users\petros.koulouris\spark_install/spark-2.4.3-bin-hadoop2.7'
trying URL 'https://archive.apache.org/dist/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz'
Content type 'application/x-gzip' length 229988313 bytes (219.3 MB)
downloaded 219.3 MB

Installation complete.

**Attempted spark connection**
sc <- spark_connect(master = "local")

**Error message from console**
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (43960): Gateway in localhost:8880 did not respond.
    Path: D:\spark\spark23\bin\spark-submit2.cmd
    Parameters: --driver-memory, 2g, --class, sparklyr.Shell, "C:\Users\petros.koulouris\Documents\R\win-library\3.5\sparklyr\java\sparklyr-2.3-2.11.jar", 8880, 43960
    Log: C:/Users/petros.koulouris/Documents\RtmpkD744N\file6a9c6e5810ef_spark.log

---- Output Log ----
The system cannot find the path specified.
The system cannot find the file C:\Users\PETROS~1.KOU\AppData\Local\Temp\8\spark-class-launcher-output-9694.txt.
The system cannot find the file specified.

---- Error Log ----

Do I need to update any environment files?

Thanks and regards 
Petros

**Comment by caewok** [comment]
This folder looks potentially problematic: PETROS~1.KOU. Maybe check the folders in C:\Users to see if there are more than should be there, or maybe this folder is corrupted?
