### ISSUE TITLE
R RF translation to Sparklyr RF

### ISSUE THREAD

**Issue by Scotturbina** [sparklyr/sparklyr#2229]
Hello,

Quick question,

I got these parameters in my random forest in caret:

```
grid<-expand.grid(mtry= c(69), splitrule= c("gini"), min.node.size=1)

RFFirstNorm <- train(Is_Commercial~.,  data = train, method = "ranger",
                   trControl = cv.cntrl,tuneGrid=grid, num.trees = 1500,
                   importance = "permutation")
```

How can I translate these parameter to the random forest in Sparklyr?

And another question will be:

min_instances_per_node sets the depth in the tree as same as min.node.size in R random forest?

Why max.depth in sparklyr random forest does not allow me to put values >30?

Thank you 

Regards

**Comment by samuelmacedo83** [comment]
Hi @Scotturbina,

Here is an example about tunning your hyper parameters in Random Forest using sparklyr 
https://samuelmacedo.netlify.com/2018/06/sparklyr-tuning-your-hyperparameters/

`min_instances_per_node` has the same idea than `min.node.size` but they have a little difference of implementation. Please, look here for [spark](https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.ml.classification.RandomForestClassifier@minInstancesPerNode:org.apache.spark.ml.param.IntParam)  and the "details" in [Ranger package](https://cran.r-project.org/web/packages/ranger/ranger.pdf).

The maxDepth on Spark has the upper limit in 30 https://github.com/apache/spark/blob/5264164a67df498b73facae207eda12ee133be7d/mllib/src/main/scala/org/apache/spark/ml/tree/impl/RandomForest.scala#L140

**Comment by samuelmacedo83** [comment]
I'll close this issue. Feel free to reopen if you have more questions.
