### ISSUE TITLE
FR: Sliding Window on Stream

### ISSUE THREAD

**Issue by fabiangehring** [sparklyr/sparklyr#2231]
Hi,

I'm not sure if this is already supported but I was not able to find it, therefore this feature request. It would be nice to define sliding windows on a stream. This seems to be possible when using pyspark:

```
# Group the data by window and word and compute the count of each group
windowedCounts = words.groupBy(
    window(words.timestamp, "10 minutes", "5 minutes"),
    words.word
).count()
```

I'm not aware of an equivalent of the "window" function within sparklyr. In the pyspark example the desired measure is calculated every 5 seconds over a sliding window of 10 seconds.

**Comment by HikaGenji** [comment]
hi,

there is such a function in sparklyr.confluent.avro package:

https://github.com/r-spark/sparklyr.confluent.avro

Assuming output stream has a timestamp, an id  and a side column:

tbl(sc, "output") %>%
groupBy(c(window(., "timestamp", "10 seconds", "5 seconds"), col(., "id"))) %>%
agg(avg(side), avg(id))

**Comment by yl790** [comment]
In addition to what HikaGenji mentioned, please also check out sparklyr.flint -- It's under active development though and doesn't have anything directly supporting streaming yet, but it definitely already supports some summary of data points within a moving time window (e.g., sum and count, and more supported summarizers to come)
