### ISSUE TITLE
Remove JARs and license header file

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#2239]
See https://lfscanning.org/reports/lfai/sparklyr-2020-01-10-9a66b8bb-5c91-4415-987f-9d8afe4aaf93.html

**Comment by javierluraschi** [comment]
One caveat, we do need to download JARs for LIVY, but perhaps those should be GitHub release files, would make so much more sense.

**Comment by yl790** [comment]
For sparklyr 1.3, the only jar files that were shipped were the `sparklyr-*.jar` files, which was definitely an improvement over sparklyr 1.2. However, if I read lfsscanning.org's recommendation correctly, ideally we shouldn't be shipping any jar file in the source repo, but that would mean we need to find some reasonably reliable and simple way to distribute the `sparklyr-*.jar` files as well.
