### ISSUE TITLE
Group_by and mutate

### ISSUE THREAD

**Issue by JLSMforPYR** [sparklyr/sparklyr#2245]
Hi, 
 I'm trying to make a cummulative product by groups and add in each step the result. When I do this with a R dataframe all goes OK, but when I have tried to do it with sparklyr this operations add the same result (the final comproduct) at all rows.

Example:
I create a simple dataframe
df_prueba <- data.frame(
    id = rep(c(1,2), each = 5),
    values = rep(1:5, 2))

**With a data.frame:**

df_prueba %>%
  group_by(id) %>%
  mutate(acumulacion = cumprod(values))

 1     1      1           1
 2     1      2           2
 3     1      3           6
 4     1      4          24
 5     1      5         120
 6     2      1           1
 7     2      2           2
 8     2      3           6
 9     2      4          24
10     2      5         120
`

but...
with **sparklyr**

 1     2      1        120.
 2     2      2        120.
 3     2      3        120.
 4     2      4        120.
 5     2      5        120.
 6     1      1        120.
 7     1      2        120.
 8     1      3        120.
 9     1      4        120.
10     1      5        120.`

**Comment by benmwhite** [comment]
Spark tables are distributed, so you need to be explicit about the orderings.

```
spark_df_prueba %>%
  group_by(id) %>%
  arrange(values) %>% 
  mutate(acumulacion = cumprod(values))
```

```
# Source:     spark<?> [?? x 3]
# Groups:     id
# Ordered by: values
      id values acumulacion
   <dbl>  <int>       <dbl>
 1     1      1         1  
 2     1      2         2  
 3     1      3         6  
 4     1      4        24.0
 5     1      5       120. 
 6     2      1         1  
 7     2      2         2  
 8     2      3         6  
 9     2      4        24.0
10     2      5       120.
```

I do think there needs to be a warning for `cumprod` though. When you attempt a similar operation with `cumsum` without specifying the arrangement then sparklyr returns the warning that there is no explicit ordering and suggests arrange() or window_order(). This doesn't look like it happens at all for `cumprod`.

**Comment by JLSMforPYR** [comment]
Works, thanks! 
I think it may be useful to add a message as warning of this.

**Comment by samuelmacedo83** [comment]
This [warning message](https://github.com/tidyverse/dbplyr/blob/a86d88805fdc130da5841c77537dce79ddd0106c/R/translate-sql-window.R#L56) comes from `dbplyr`  package. I didn't find references for cumprod in there, but I might be wrong. 
Thanks for @benmwhite  for your answer. It's very complete.
I'll close this issue, but I can reopen if you disagree with this resolution. 
Thanks for your feedback :)
