### ISSUE TITLE
BucketedRandomProjectionLSH

### ISSUE THREAD

**Issue by jkylearmstrong** [sparklyr/sparklyr#2257]
Is there a function for this in sparklyr? 

https://spark.apache.org/docs/latest/ml-features.html#approximate-nearest-neighbor-search

**Comment by benmwhite** [comment]
`ft_lsh()`

In general the `ft_*` functions in sparklyr all invoke the Spark MLlib feature transformations on the page you linked, and the `ml_*` functions map invoke the other models in the MLlib doc pages. This has helped me a couple times when trying to match Spark code written in Scala or Python to sparklyr.
