### ISSUE TITLE
Failed while connecting to sparklyr to port (8880)

### ISSUE THREAD

**Issue by EphaneZhong** [sparklyr/sparklyr#2259]
Hi all. I'm trying to connect a new spark cluster on my local machine but I keep getting a connection error. Here are my specs:

OS Windows 10
R Version 3.6.1
Rstudio 1.2.1335

```r
Sys.setenv(JAVA_HOME='C:/Program Files/Java/jre1.8.0_241')
sc <- spark_connect(master = "local")
```

* Using Spark: 2.3.3
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (11828): Gateway in localhost:8880 did not respond.
    Path: C:\Users\Ephane Liu\AppData\Local\spark\spark-2.3.3-bin-hadoop2.7\bin\spark-submit2.cmd
    Parameters: --driver-memory, 2g, --class, sparklyr.Shell, "F:\R\R-.6.1\library\sparklyr\java\sparklyr-2.3-2.11.jar", 8880, 11828
    Log: C:\Users\JIACHE~1\AppData\Local\Temp\RtmpwVW6Mb\file3d685d603dfa_spark.log

---- Output Log ----
'Liu\AppData\Local\spark\spark-2.3.3-bin-hadoop2.7\jars""\' is not recognized as an internal or external command,
operable program or batch file.
Failed to find Spark jars directory.
You need to build Spark before running this program.

---- Error Log ----

**Comment by rychien-official** [comment]
Is Spark installed? Can you launch the spark shell? For example, if I open up Windows Powershell and nav to my spark install directory, I can launch spark shell:
```
PS C:\Users\rvc5634\AppData\Local\spark\spark-2.3.3-bin-hadoop2.7\bin> ./spark-shell

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.3.3
      /_/

Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_241)
Type in expressions to have them evaluated.
Type :help for more information.

scala>
```
If the Spark is not installed, you can use R command spark_install(...) to install Spark,[ details here](https://therinspark.com/starting.html). That's the easy way, or if you can follow these instructions: https://www.ics.uci.edu/~shantas/Install_Spark_on_Windows10.pdf.

BR,
Ryan
