### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#2274]
We should spend some time benchmarking against PySpark and improving the R interface to be at a par or better. Part of this work involves defining what to benchmark since we can't benchmark everything. We should probably use a proper Spark cluster for this etc.

I don't think there is much value in benchmarking Spark operations, like joins, merges, etc... since those should be the same from Python, R or Scala; however, R-related operations like `copy_to()`, `collect()`, `spark_apply()`, etc. is something worth benchmarking.

**Comment by javierluraschi** [comment]
We can also consider benchmarking against other R cluster technologies like SNOW, would be quite interesting to run a comparison between SNOW and Spark using R, this has been done in the past but without considering Spark.

We could write a follow up paper with a comparison that includes Spark and SNOW similar to: http://dirk.eddelbuettel.com/papers/parallelR_techRep.pdf

**Comment by yl790** [comment]
There are ongoing feature work & possible perf improvements at the moment. Probably best to wait for all the dust to settle before doing this comparison.

**Comment by yl790** [comment]
Update: some of this work is now in progress (see https://github.com/yl790/sparklyr-pyspark-benchmarks)

**Comment by yl790** [comment]
Results so far indicate some improvement is needed to make sdf_import as efficient as the equivalent of it in PySpark. Even with Arrow enabled, there is still non-trivial overhead. Will need to do some more research on this.

**Comment by yl790** [comment]
I'm also contemplating whether to implement a new type of data frame serializer for sdf_import using https://www.rdocumentation.org/packages/protolite/versions/2.1/topics/serialize_pb (so far can confirm at least the serialization part on R side is super-fast). It has been surprisingly difficult to find any binary protocol that can work in a portable manner in both R and Java and can possibly do better than Arrow.

**Comment by yl790** [comment]
We have some basic benchmark workloads runnable on EC2 instances now, and should be able to measure how protobuf or other alternative serialization formats might offer us better performance when serialization is in R/C++ and deserialization is in Java/Scala.
