### ISSUE TITLE
ggvis

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#2275]
At some we were considering adding support for `ggvis`, as in, better support to plot datasets with Spark. However, it is my understanding that `ggvis` is no longer undeer active development.

Historically, we've recommended using `dbplot`, see https://github.com/edgararuiz/dbplot

However, `dbplot` requires users to learn additional functions like `dbplot_histogram()` which we should ideally avoid and something like `ggplot2` should just work.

That said, maybe this is not possible with the current interfaces that `ggplot2` provides, working in this involves talking with the `tidyverse` folks and figure out if there is something we should consider implementing or contributing to.

See https://ggvis.rstudio.com/

**Comment by samuel-bohman** [comment]
The ggplot2 package is now supported on Databricks: https://docs.databricks.com/notebooks/visualizations/matplotlib-and-ggplot.html

**Comment by yl790** [comment]
I briefly looked into this as well and found the current ggplot interface can work directly with Spark data frames without any issue, .e.g.,  

```
library(dplyr)
library(sparklyr)
sc <- spark_connect(master = "local")
flights_tbl <- copy_to(sc, nycflights13::flights, "flights")
delay <- flights_tbl %>% 
  group_by(tailnum) %>%
  summarise(count = n(), dist = mean(distance), delay = mean(arr_delay)) %>%
  filter(count > 20, dist < 2000, !is.na(delay))  # delay is still a Spark data frame

library(ggplot2)
ggplot(delay, aes(dist, delay)) +
  geom_point(aes(size = count), alpha = 1/2) +
  geom_smooth() +
  scale_size_area(max_size = 2)
```
