### ISSUE TITLE
Spark 3.0

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#2276]
We can already use Spark 3.0, implemented by Databricks; however, we are missing to enable tests and fix issues and finish up installing Spark 3.0 (not the preview) once it releases.

**Comment by yl790** [comment]
Update: I think we are very close to enabling all test cases for Spark master / 3.0.0-preview by now.

**Comment by yl790** [comment]
Now all sparklyr tests are working with Spark master / 3.0.0-preview and I think all known issues have been fixed.
