### ISSUE TITLE
Type date becomes double after sdf_copy_to()

### ISSUE THREAD

**Issue by samuel-bohman** [sparklyr/sparklyr#2313]
It seems type `date` becomes `double` when using `sparklyr::sdf_copy_to()` or `dplyr::copy_to()`. 

```r
library(sparklyr)
sc <- sparklyr::spark_connect(master = "local", version = "2.4.3")

economics <- ggplot2::economics
economics
# A tibble: 574 x 6
   date         pce    pop psavert uempmed unemploy
   <date>     <dbl>  <dbl>   <dbl>   <dbl>    <dbl>
 1 1967-07-01  507. 198712    12.6     4.5     2944
 2 1967-08-01  510. 198911    12.6     4.7     2945
 3 1967-09-01  516. 199113    11.9     4.6     2958
 4 1967-10-01  512. 199311    12.9     4.9     3143
 5 1967-11-01  517. 199498    12.8     4.7     3066
# … with 564 more rows

sparklyr::sdf_copy_to(sc, economics, overwrite = TRUE)
# Source: spark<economics> [?? x 6]
date   pce    pop psavert uempmed unemploy
<dbl> <dbl>  <dbl>   <dbl>   <dbl>    <dbl>
1  -915  507. 198712    12.6     4.5     2944
2  -884  510. 198911    12.6     4.7     2945
3  -853  516. 199113    11.9     4.6     2958
4  -823  512. 199311    12.9     4.9     3143
5  -792  517. 199498    12.8     4.7     3066
# … with more rows

dplyr::copy_to(sc, economics, overwrite = TRUE)
# Source: spark<economics> [?? x 6]
date   pce    pop psavert uempmed unemploy
<dbl> <dbl>  <dbl>   <dbl>   <dbl>    <dbl>
1  -915  507. 198712    12.6     4.5     2944
2  -884  510. 198911    12.6     4.7     2945
3  -853  516. 199113    11.9     4.6     2958
4  -823  512. 199311    12.9     4.9     3143
5  -792  517. 199498    12.8     4.7     3066
# … with more rows
```

**Comment by yl790** [comment]
@samuel-bohman Hey thanks for reporting this issue! Looks like a bug. Somewhere in the sparklyr serialization/deserialization implementation there was handling for timestamp types, but not date types. I'm happy to look into it soon.

**Comment by yl790** [comment]
Update: PR to address this issue is in progress.
Also I somehow managed to find yet another bug (#2314) with date being "1970-01-01" while playing around with ggplot2::economics.

I'll try to merge the bug fix for #2314 first because it's more involved and also the PR for this issue potentially depends on the one for #2314.

**Comment by yl790** [comment]
All bug fixes are in master now

**Comment by samuel-bohman** [comment]
What is the purpose of `as.list()` in the above test?

**Comment by yl790** [comment]
I think as.list is needed to only compare actual data columns from both dataframes. I think there is some metadata in the dataframe that won't be preserved after sdf_copy_to and sdf_collect, so the 2 dataframes are still not identical, even though they both have identical columns.
