### ISSUE TITLE
Question: Arrow with Livy

### ISSUE THREAD

**Issue by rychien-official** [sparklyr/sparklyr#2323]
Hey Javier et al.,

Is Arrow enabled when connecting to Spark via Livy? For example, if I connect with:
```
# Conn to spark
# Configure connection parameters
base_config = spark_config()
base_config$spark.sql.catalogImplementation <- "hive"
base_config$spark.sql.execution.arrow.enabled <- TRUE
base_config$spark.sql.execution.arrow.maxRecordsPerBatch <- "1000000"
base_config$spark.speculation <- "true"
base_config$spark.speculation.interval <- "1000ms"
base_config$spark.sql.execution.arrow.enabled <- TRUE
config <- 
    livy_config(
        config=base_config,
        username="rstudio-user", password="nittanylion",
        executor_memory="9g", num_executors=24, executor_cores=2)
sc <- 
  spark_connect(
    master = "http://aaa-bbb-master.some-website.edu:8998",
    method = "livy",
    config = config,
    version = "2.3")
```
Is Arrow enabled?

I ask because I am looking at the Spark Environment page (after connecting), and do not see the parameter "spark.sql.execution.arrow.enabled", although I can see the other settings, such as 'spark.sql.catalogImplementation'. 

I connect to my cluster directly, by logging onto an edge node where RStudio Server is installed, I can see the setting 'spark.sql.execution.arrow.enabled' set to True.

Thanks in advance for your knowledge.

BR,
Ryan

**Comment by yl790** [comment]
Hi @rychien-official  It looks like currently arrow is only used in sparklyr when the arrow package is loaded *or* if "sparklyr.arrow" is set to true in the connection config: https://github.com/yl790/sparklyr/blob/master/R/arrow_data.R#L2

So whether the connection is a livy connection or not is irrelevant.
