### ISSUE TITLE
Read Avro Data in Kafka Stream

### ISSUE THREAD

**Issue by tusharmajhi9** [sparklyr/sparklyr#2352]
Hi,

I am reading a kafka stream but the 'key' and 'value' column is in avro format. How do I parse these columns?

```
config$sparklyr.shell.packages <- "org.apache.spark:spark-sql-kafka-0-10_2.11:2.2.0"

read_options <- list(kafka.bootstrap.servers = "xxx", subscribe = "xxx")
stream <- stream_read_kafka(sc, options = read_options)
```

Schema:
![image](https://user-images.githubusercontent.com/45931375/77659416-09e8f780-6f9e-11ea-8ebd-d1b98bd9eb0d.png)

Sample Stream Output:
```
> stream
# Source: spark<?> [inf x 7]
  key    value   topic                    partition offset timestamp           timestampType
  <list> <list>  <chr>                        <int>  <dbl> <dttm>                      <int>
1 < [9]> < [94]> analytics_post_phase1_qa         1 488647 1970-01-01 00:00:00            -1
2 < [9]> < [92]> analytics_post_phase1_qa         1 488648 1970-01-01 00:00:00            -1
3 < [9]> < [88]> analytics_post_phase1_qa         1 488649 1970-01-01 00:00:00            -1
4 < [9]> < [88]> analytics_post_phase1_qa         1 488650 1970-01-01 00:00:00            -1
5 < [9]> < [92]> analytics_post_phase1_qa         1 488651 1970-01-01 00:00:00            -1
6 < [9]> < [94]> analytics_post_phase1_qa         1 488652 1970-01-01 00:00:00            -1
```

**Comment by yl790** [comment]
@tusharmajhi9 I don't think there is support for Avro format yet.
I'm happy to look into how to implement such support in sparklyr.

**Comment by tusharmajhi9** [comment]
Thanks for the reply @yl790 . In that case is there any way I can deal with json string in a column. I have a spark dataframe where one column is a large string in json format. I need to explode the column 'value' which is a json string into separate columns

Example:
```

key | value
-- | --
173460692 | {"section":"NEWS","lastUpdatedEventTime":1585641217000,"counts":{"cardclick":346,"swipeview":956,"deep":236,"cardview":26949,"bounce":51,"timespent_15_20":51,"timespent_20_30":57,"timespent_60_120":51,"swipeclick":422,"scoremagnitude":268,"timespent_45_60":31,"timespent_30_45":43,"timespent_5_10":320,"timespent_gt120":11,"timespent_0_5":671,"shallow":38,"share":1,"complete":22,"timespent_10_15":92}

```

**Comment by yl790** [comment]
@tusharmajhi9 Sure! The short answer is that is definitely possible assuming you have a known set of attributes you want to extract out of the JSON string column.

I created a minimal example of extracting values out of a json string using `dplyr` along with the `get_json_object` Hive UDF. Let me know if it helps.

Minimal example:

```
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local")

df <- data.frame(
  key = c(173460692),
  value = c('{"section":"NEWS","lastUpdatedEventTime":1585641217000}')
)  # my example data frame with a JSON column

sdf <- sdf_copy_to(sc, df, overwrite = TRUE) # my example data frame copied into Spark -- now sdf is a Spark data frame

post_processed_sdf <- sdf %>%
  dplyr::mutate(
    section = get_json_object(value, '$.section'),
    lastUpdatedEventTime = get_json_object(value, '$.lastUpdatedEventTime')
  )   # post_processed_sdf is now a separate Spark data frame with 'section' and 'lastUpdatedEventTime' extracted from the JSON string column  
```

The strings such as '$.section' and '$.lastUpdatedEventTime' are known as JSON path strings which specify where to extract those attributes from in the JSON input.
If you need to extract attributes from more structurally complicated nested JSONs, then I recommend reading more about JSON path string in https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-get_json_object .
There is some caveat though -- IIRC if the JSON input is invalid, or if the JSON path string is formulated incorrectly, then the result will contain NA values. So, watch out for those as well.

**Comment by tusharmajhi9** [comment]
I do have a known set of attributes in the JSON string. Thanks @yl790 , this is a massive help.

**Comment by javierluraschi** [comment]
From Gitter chat:

There seems to be a non-R example here: https://sparkbyexamples.com/spark/spark-streaming-consume-and-produce-kafka-messages-in-avro-format/

My guess is that `from_avro()` is defined in the `spark-avro_2.11` package.

So I think that instead of doing only:

```
 config$sparklyr.shell.packages <- "org.apache.spark:spark-sql-kafka-0-10_2.11:2.2.0"
``

You might need to include AVRO with something like

```
 config$sparklyr.shell.packages <- c("org.apache.spark:spark-sql-kafka-0-10_2.11:2.2.0", "org.apache.spark:spark-avro_2.11:2.4.0")
```

**Comment by HikaGenji** [comment]
back to the original question, i am also trying to decode avro messages coming from kafka stream.

My setup is:
- spark-3.0.0-preview-bin-hadoop2.7
- sparklyr latest built from master

Using spark-shell i am able to decode the messages. I am passing the following arguments:

--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.0-preview,org.apache.spark:spark-avro_2.12:3.0.0-preview

In sparklyr, i am doing this:
`config <- spark_config()
config[["sparklyr.shell.conf"]] <- "spark.driver.extraJavaOptions=-Djava.net.useSystemProxies=true"
config[["sparklyr.shell.packages"]] <- c("org.apache.spark:spark-avro_2.12:3.0.0-preview", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.0-preview")`

then i try to decode the messages:

`# sql query on parameter stream
query <- str_interp('select from_avro(value, \'${schema}\') as value from parameter')
# does not work
query %>%
dbplyr::sql() %>%
tbl(sc, .)`

this gives me the following error: Error: org.apache.spark.sql.AnalysisException: Undefined function: 'from_avro'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.;

I also tried using invoke:

`expr <- str_interp("'${schema}'")

parameter%>%
  spark_dataframe() %>%
  invoke("select", invoke_static(sc, "org.apache.spark.sql.avro.functions", "from_avro", "value", expr), list())`

which gives me the following error:

Error: java.lang.Exception: No matched method found for class org.apache.spark.sql.avro.functions.from_avro
	at sparklyr.Invoke.invoke(invoke.scala:144)

So it really looks like the from_avro method is not imported properly into sparklyr. Any idea what i am doing wrong ? i have tried setting packages arguments in different ways but could not figure it out.

**Comment by HikaGenji** [comment]
i have setup a git repo to replicate my setup using vagrant and docker-compose:
[https://github.com/HikaGenji/sparklyr-avro](url)

**Comment by HikaGenji** [comment]
i have tried modifying the invoke as such:

parameter%>%
spark_dataframe() %>%
invoke("select", 
  invoke_static(sc, "org.apache.spark.sql.avro.functions", 
               "from_avro",
  			     invoke_static(sc, "org.apache.spark.sql.functions", "col", "value"),
			     expr),
	list())

i am getting the following:

Invoking sql
Invoking select
Invoking org.apache.spark.sql.avro.functions from_avro
Invoking org.apache.spark.sql.functions col
Invoking as
Error: java.lang.Exception: No matched method found for class org.apache.spark.sql.Dataset.select
	at sparklyr.Invoke.invoke(invoke.scala:144)

**Comment by javierluraschi** [comment]
I was able to get us closer with an extension, but there is some more work to clean this up and make the interface a bit cleaner to support Spark 2.4:

```
 sparklyr::invoke_static(sc, "sparkavroudf.AvroUtils", "toAvro", spark_dataframe(sdf_len(sc, 3)), invoke_new(sc, "org.apache.spark.sql.Column", "id")) %>% sdf_register()
# Source: spark<?> [?? x 1]
  `to_avro(id)`
  <list>       
1 <raw [1]>    
2 <raw [1]>    
3 <raw [1]>
```

It requires a sparklyr extension, I have the start here: https://github.com/r-spark/sparkavroudf

Now the good news, Spark 3.0 supports `from_avro` and `to_avro` natively, so something we should probably also support natively in `sparklyr`. Ideally by registering those functions as UDFs with something like https://docs.databricks.com/spark/latest/spark-sql/udf-scala.html

CC: @yl790

**Comment by javierluraschi** [comment]
@HikaGenji started creating an extension, would make sense to help out with the extension or support this natively in Spark. AVRO is commonly used so maybe worth supporting it with `spark_connect(packages = "avro")`, see https://github.com/r-spark/sparklyr.confluent.avro

**Comment by yl790** [comment]
re: registering `from_avro` and `to_avro` as UDF -- most likely won't be feasible because currently there is no support for UDF with generic input types, which means one can only register a UDF for each possible concrete input type, which seems messy and not very useful.

re: support all avro-related operations with `spark_connect(packages = "avro")` -- that's an awesome idea, and it's in progress
