### ISSUE TITLE
spark_read_jdbc cannot convert column to integer error

### ISSUE THREAD

**Issue by kennedyshane10** [sparklyr/sparklyr#2358]
I have successfully connected to a spark cluster. I now would like to read in tables from HIVE. I have tried doing this using spark_read_jdbc however, I get an error which includes the following comment:

java.sql.SQLException: Cannot convert column 1 to integerjava.lang.NumberFormatException: For input string: "tablename.tablecolumn".

I am confident that spark_read_jdbc is connecting with HIVE and attempting to read from the table I have selected (i.e. tablename) since in the error it correctly identifies the first column in the table (i.e.tablecolumn)

```r
#---------Create a Spark connection-----------------
install.packages("sparklyr")
library(sparklyr)
spark_install(version = "2.2.1")
Sys.setenv(SPARK_HOME="/.../spark/spark-2.2.1")
config <- spark_config()
config$spark.yarn.queue <- "queue"
sc <- spark_connect(master="yarn-client", config=config)

#--------Read a table from Hive----------------------
username = rstudioapi::askForPassword("Username")
password = rstudioapi::askForPassword("Password")

spark_read_jdbc(sc,"tablename_jdbc",options=list(
        url="jdbc:hive2://node:port/node",
        user=username, password=password,
        dbtable="tablename",
        memory=FALSE,
        columns= "integer"))
```

**Comment by yl790** [comment]
@kennedyshane10  While I don't have an easy way to repro what you ran into, my best guess is you need to replace `columns = "integer"` with `columns = c(tablecolumn = "integer")` (that is assuming the name of that integer column is "tablecolumn"), i.e., try

```
spark_read_jdbc(sc,"tablename_jdbc",options=list(
        url="jdbc:hive2://node:port/node",
        user=username, password=password,
        dbtable="tablename",
        memory=FALSE,
        columns = c(tablecolumn = "integer"))
```

instead?
