### ISSUE TITLE
spark_apply and data.table

### ISSUE THREAD

**Issue by morganvill** [sparklyr/sparklyr#2389]
Hello,

I tried to use data.table in spark_apply since I have data management pipeline done with data.table and I wanted to apply it to a spark dataframe with spark_apply but it doesn't seem to work, am I doing something wrong ?

```r
library(sparklyr)

sc <- spark_connect(master = "local")
iris_tbl <- copy_to(sc, iris)
                    
y <- spark_apply(
  iris_tbl,
  function(e) {
    library(data.table)
    x <- collect(e)

    x <- setDT(x)
    
    x <- x[
      , log := log(Sepal_Length)
    ]
    
    x
  },
  group_by = "Species"
)
```

I know I can use dyplyr instead of data.table but I would like to know why it doesn't work ?

Thanks you !

**Comment by yl790** [comment]
@morganvill Hey happy to help!

I installed data.table and ran your code and saw this error in spark_apply worker: 'terminated unexpectedly: could not find function "collect" '

In general, after `spark_apply` fails, one thing you should consider to do is to run `spark_log(sc, filter = "RScript")` to check whether there was any error inside the R function you passed to `spark_apply`.

For example, when I first tried to run your code, the error from `spark_log(sc, filter = "RScript")` was "there is no package called ‘data.table’", so I installed data.table and re-ran your code, and then saw the 'could not find function "collect"' error mentioned above.

**Comment by yl790** [comment]
^^ although if I modify the code to fix the 'could not find function "collect"' error (as shown below, because apparently sparklyr library needs to be imported again inside the worker function)

```
library(sparklyr)

sc <- spark_connect(master = "local")
iris_tbl <- copy_to(sc, iris, overwrite = TRUE)

y <- spark_apply(
  iris_tbl,
  function(e) {
    library(data.table)
    library(sparklyr)

    x <- collect(e)

    x <- setDT(e)

    x <- x[
      , log := log(Sepal_Length)
    ]

    x
  },
  group_by = "Species"
)

```
then I would still end up with a different error effectively saying returning a list from Spark back to R is not supported yet. This is a known issue and it's something we are still working on.

**Comment by morganvill** [comment]
Hey yl790

Thanks you very much, I forgot to library(sparklyr) and also I understood that I have to  add a data.frame conversion of my data.table to return the result as a spark dataframe.

For those interested, here the final code:
```

library(sparklyr)

sc <- spark_connect(master = "local")
iris_tbl <- copy_to(sc, iris)

y <- spark_apply(
  iris_tbl,
  function(e) {
    library(data.table)

    x <- setDT(e)
    
    x <- x[
      , log := log(Sepal_Length)
    ]
    
    x <- data.frame(x)
  },
  group_by = "Species"
)

```
