### ISSUE TITLE
deserialize array of Spark SQL structs correctly in sdf_collect

### ISSUE THREAD

**Issue by yl790** [sparklyr/sparklyr#2419]
As helpfully pointed out in https://github.com/sparklyr/sparklyr/issues/1615#issuecomment-613598856 apparently while `sdf_collect` can now correctly read a single Spark SQL struct and create an equivalent named list in R, something is still missing when it tries to handle an array of such structs.

**Comment by dkincaid** [comment]
Did this make it into the 1.2 release?

**Comment by yl790** [comment]
@dkincaid Yes indeed! 🙂

**Comment by dkincaid** [comment]
Wonderful! This is so awesome. I really appreciate you getting it done.
