### ISSUE TITLE
Problem with Spark_apply not working with packages over Yarn cluster , only base r functions working 

### ISSUE THREAD

**Issue by NZambranoc** [sparklyr/sparklyr#2422]
So I'm trying to use packages using spark_apply over a yarn cluster.
```r
bundle <- paste(getwd(), list.files()[grep("\\.tar$",list.files())][1], sep = "/")
hdfs_path <-"hdfs:///user/xxxxxxx/"
hdfs_bundle <- paste0(hdfs_path, basename(bundle))
system(paste("hdfs dfs -put", bundle, hdfs_path))


conf <- spark_config()   # Load variable with spark_config()

conf$spark.executor.memory <- "64G" 
conf$spark.driver.maxResultSize <- "18G" #
conf$`sparklyr.shell.driver-memory`="18G" #
conf$spark.rpc.message.maxSize =512 #
conf$sparklyr.shell.files <- hdfs_bundle

sc <- spark_connect(master = "yarn-client", config = conf)
iris_tbl <- copy_to(sc,iris,"iris")

#this wont work
iris_tbl %>% spark_apply(function(e) stringr::str_sub(e$Species,1,1),packages = bundle)
```

I can run base r functions perfectly yet I can't use any of the packages I've loaded through the .tar at "conf$sparklyr.shell.file"

When I try to run the code above I get the following error:

> Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 5, xxxxxx.xxxx.xxx, executor 1): java.lang.Exception: sparklyr worker rscript failure with status 255, check worker logs for details.
> 	at sparklyr.Rscript.init(rscript.scala:83)
> 	at sparklyr.WorkerApply$$anon$2.run(workerapply.scala:123)

**Comment by sbottelli** [comment]
I think you have to recall "library(stringr)" inside the function

**Comment by NZambranoc** [comment]
@sbottelli I tried that, didn't work.

As mentioned in #2135 I may need to update the R version on my workers.

I've tried accessing the workers logs to make sure but the come out empty. 

How can I update my workers' R version?

**Comment by NZambranoc** [comment]
My executors' R version seemed to be the problem
```r
conf$spark.r.command <- paste0("/opt/R/", version$major, ".", version$minor, "/bin/Rscript")
```

Fixed the issue!
