### ISSUE TITLE
Set timezone when sending POSIXt data to Spark

### ISSUE THREAD

**Issue by nealrichardson** [sparklyr/sparklyr#2439]
https://issues.apache.org/jira/browse/ARROW-8566 was reported on `arrow`. In brief, in the latest release of `arrow`, we [fixed a bug in datetime data handling](https://github.com/apache/arrow/commit/507762fa51d17e61f08d36d3626ab8b8df716198): previously, a "GMT" timezone was hardcoded everywhere, while now we send the actual timezone. It appears that when this timezone is not set, at least in the version of Spark that the user was on, Spark crashes. 

I'm not sure where exactly the bug lies--it's possible that the Arrow Java library Spark is using doesn't have the same expectations as the C++ library that R is using--though I'll dig a bit more. Regardless, we can be defensive and protect against this failure in `sparklyr`. Since R interprets POSIXt data without a timezone set as being in the system's current timezone, doing something like this on columns of data before sending to Spark should fix the issue:

```r
if (inherits(x, "POSIXt") && is.null(attr(x, "tzone"))) {
  attr(x, "tzone") <- Sys.timezone()
}
```

Would you be interested in a PR?

**Comment by javierluraschi** [comment]
Definitely worth investigating/fixing so assigned 1.3 milestone (next release, ~2-3 months).

**Comment by javierluraschi** [comment]
@nealrichardson for sure! If you have bandwidth for a PR we will take it! :) But otherwise I'm sure we will also get to investigate/fix this one before the next sparklyr release.

**Comment by nealrichardson** [comment]
Well, I'm planning on sending you another PR updating some of the arrow code anyway, so I'll fold this in there :)
