### ISSUE TITLE
spark_apply avoid infer schema

### ISSUE THREAD

**Issue by sbottelli** [sparklyr/sparklyr#2449]
Hi guys,
I'm using the new version of sparklyr.
How can I avoid the infer schema passage to spark_apply? Because when I start a spark_apply it runs twice. 
Can you report a practical example in order to learn how to manage this trouble?
And is spark_apply lazy?
Thanks in advance
Stefano

**Comment by yl790** [comment]
@sbottelli You can specify the schema of your result explicitly like so: `spark_apply(input_sdf, transformation_function, columns = list(result_col1 = "integer", result_col2 = "double", ... ,etc))`

**Comment by sbottelli** [comment]
Perfect, thanks.
Stefano
