### ISSUE TITLE
filter is not working inside for loop in sparklyr

### ISSUE THREAD

**Issue by abdkumar** [sparklyr/sparklyr#2455]
I want to filter inside for loop like 

```
sc <- spark_connect(master = "local")
data <- spark_read_csv(sc, name = "trans_data", path = fname1, header = TRUE, delimiter = ",")
for (alternative in 1:6){
 new_data<- data %>% filter(y == alternative)
}
```
I'm getting the following error
```
Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "c('tbl_spark', 'tbl_sql', 'tbl_lazy', 'tbl')
```

**Comment by benmwhite** [comment]
What kind of output are you aiming for? Are there multiple filtering conditions and you want one final output table, or do you want separate tables for each filtering condition? Your code snippet would overwrite `new_data` at every step in the loop.

I'm not able reproduce the issue either, the following code runs as expected:
```
iris_tbl <- iris %>% 
  mutate(species_index = case_when(
    Species == "setosa" ~ 1,
    Species == "versicolor" ~ 2,
    Species == "virginica" ~ 3
  )) %>% 
  sdf_import(sc)

iris_tbl
```

```
# Source: spark<?> [?? x 6]
   Sepal_Length Sepal_Width Petal_Length Petal_Width Species species_index
          <dbl>       <dbl>        <dbl>       <dbl> <chr>           <dbl>
 1          5.1         3.5          1.4         0.2 setosa              1
 2          4.9         3            1.4         0.2 setosa              1
 3          4.7         3.2          1.3         0.2 setosa              1
 4          4.6         3.1          1.5         0.2 setosa              1
 5          5           3.6          1.4         0.2 setosa              1
 6          5.4         3.9          1.7         0.4 setosa              1
 7          4.6         3.4          1.4         0.3 setosa              1
 8          5           3.4          1.5         0.2 setosa              1
 9          4.4         2.9          1.4         0.2 setosa              1
10          4.9         3.1          1.5         0.1 setosa              1
# … with more rows
```
```
for (alternative in 1:3) {
  new_data <- iris_tbl %>% filter(species_index == alternative)
}

new_data
```

```
# Source: spark<?> [?? x 6]
   Sepal_Length Sepal_Width Petal_Length Petal_Width Species   species_index
          <dbl>       <dbl>        <dbl>       <dbl> <chr>             <dbl>
 1          6.3         3.3          6           2.5 virginica             3
 2          5.8         2.7          5.1         1.9 virginica             3
 3          7.1         3            5.9         2.1 virginica             3
 4          6.3         2.9          5.6         1.8 virginica             3
 5          6.5         3            5.8         2.2 virginica             3
 6          7.6         3            6.6         2.1 virginica             3
 7          4.9         2.5          4.5         1.7 virginica             3
 8          7.3         2.9          6.3         1.8 virginica             3
 9          6.7         2.5          5.8         1.8 virginica             3
10          7.2         3.6          6.1         2.5 virginica             3
# … with more rows
```

**Comment by abdkumar** [comment]
@benmwhite basically I want to pass spark dataframes to R function, do processing, and return objects. Can you tell me how to it ?

**Comment by yl790** [comment]
@abdkumar With `dplyr` any transformation you pass will need to be translatable to Spark SQL (e.g., `mean` gets translated to `avg` and so on)

If you want to apply an arbitrary R function to your Spark dataframe and get the transformed data back as another Spark dataframe, you should use `spark_apply` instead (there are still some limitations though with `spark_apply` such as your transformation function must be self-contained and cannot reference objects outside of its own environment, can only return objects that can be stored in a Spark dataframe, etc, but some of those limitations will be removed in the next sparklyr release)

**Comment by yl790** [comment]
^^ also worth mentioning is the performance overhead of `spark_apply` when using it to apply an arbitrary R function on a Spark dataframe -- the data needs to ve shipped from Spark to R, transformed, and then gets shipped back from R to Spark. Some of that overhead gets reduced with efficient serializers and deserializers when `arrow` is enabled, but is still non-negligible.

**Comment by benmwhite** [comment]
@yogi-srcc-iimb `ft_string_indexer()` should do the trick.
