### ISSUE TITLE
Setting maxRecordsPerBatch when using Arrow and spark_apply does not work as expected

### ISSUE THREAD

**Issue by lalas** [sparklyr/sparklyr#2503]
Hello sparklyr team,

The issue is that when setting value of maxRecordsPerBatch to anything larger than **10,000** spark_apply uses 10,000 instead of the specified value in the configuration.

This problem is related to the closed issue #2243. The solution provided in the closed ticket doesn't seem to work. 

Below is a reproducible example

```r
# Setting enviroment variable: JAVA_HOME and SPARK_HOME
Sys.setenv(JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/")
Sys.setenv(SPARK_HOME = "~/spark/spark-2.4.3-bin-hadoop2.7/")

# Loading libraries
library(sparklyr)
library(arrow)

# disconnecting all spark connection
sparklyr::spark_disconnect_all()

# Use case 1: maxRecordsPerBatch < 10,000
conf <- spark_config()
conf$spark.r.libpaths = c("~/Documents/Rpackages,/Library/Frameworks/R.framework/Versions/3.6/Resources/library")
conf$spark.sql.execution.arrow.maxRecordsPerBatch <- 5000 # less than 10,000

sc <- spark_connect(master = "local", config = conf)
sdf_len(sc, 2 * 10^4) %>% spark_apply(nrow) #result IS as expected

sparklyr::spark_disconnect(sc)

# Use case 2: maxRecordsPerBatch > 10,000, passed as numeric
conf2 <- spark_config()
conf2$spark.r.libpaths = c("~/Documents/Rpackages,/Library/Frameworks/R.framework/Versions/3.6/Resources/library")
conf2$spark.sql.execution.arrow.maxRecordsPerBatch <- 20000 # more than 10,000

sc2 <- spark_connect(master = "local", config = conf2)
sdf_len(sc2, 2 * 10^4) %>% spark_apply(nrow) #result NOT as expected: 10000 per batch

sparklyr::spark_disconnect(sc2)

# Use case 3: maxRecordsPerBatch > 10,000, passed as text
conf3 <- spark_config()
conf3$spark.r.libpaths = c("~/Documents/Rpackages,/Library/Frameworks/R.framework/Versions/3.6/Resources/library")
conf3$spark.sql.execution.arrow.maxRecordsPerBatch <- "20000" # passed as character

sc3 <- spark_connect(master = "local", config = conf3)
sdf_len(sc3, 2 * 10^4) %>% spark_apply(nrow) #result NOT as expected: 10000 per batch
```
Output of sessionInfo() is
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] arrow_0.17.0   sparklyr_1.2.0 magrittr_1.5  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4        pillar_1.4.4      compiler_3.6.3    dbplyr_1.4.2      r2d3_0.2.3        base64enc_0.1-3   tools_3.6.3      
 [8] digest_0.6.25     packrat_0.5.0     bit_1.1-15.2      evaluate_0.14     jsonlite_1.6.1    lifecycle_0.2.0   tibble_3.0.1     
[15] pkgconfig_2.0.3   rlang_0.4.6       reprex_0.3.0      DBI_1.1.0         cli_2.0.2         rstudioapi_0.11   yaml_2.2.1       
[22] parallel_3.6.3    xfun_0.11         knitr_1.26        withr_2.2.0       dplyr_0.8.5       httr_1.4.1        fs_1.4.1         
[29] generics_0.0.2    htmlwidgets_1.5.1 vctrs_0.2.4       askpass_1.1       rprojroot_1.3-2   bit64_0.9-7       tidyselect_1.0.0 
[36] glue_1.4.0        forge_0.2.0       R6_2.4.1          processx_3.4.2    fansi_0.4.1       rmarkdown_1.18    callr_3.4.2      
[43] whisker_0.4       clipr_0.7.0       purrr_0.3.4       ps_1.3.2          backports_1.1.6   ellipsis_0.3.0    htmltools_0.4.0  
[50] assertthat_0.2.1  config_0.3        utf8_1.1.4        openssl_1.4.1     crayon_1.3.4 
```

**Comment by yl790** [comment]
@lalas Hey thanks for asking!!

I double-checked how `maxRecordsPerBatch` is processed in `sparklyr` and found it is indeed handled correctly everywhere.

For example, tweaking your example code a bit, I would see `sdf_len(sc, 4 * 10^4)` gets split into 2 partitions each with 20k records:

```
library(sparklyr)
library(arrow)

config <- spark_config()
config$spark.sql.execution.arrow.maxRecordsPerBatch <- 20000L  # actually doesn't matter whether you set it to `"20000"`, `20000`, or `20000L`, so to be as pedantic as possibly can be, I shall set it to `20000L`
sc <- spark_connect(master = "local", version = "2.4", config = config)

sdf_len(sc, 4 * 10^4) %>% spark_apply(nrow)

#  # Source: spark<?> [?? x 1]
#    result
#     <int>
#  1  20000
#  2  20000

```

So 4 observations here:

- Apparently Spark 2.4 decided it's better to split a non-trivial-sized data frame into at least 2 partitions (presumably because of parallelism-related reasons). Sparklyr doesn't really directly influence how many partitions are in your dataframe here.
- Once `spark.sql.execution.arrow.maxRecordsPerBatch` is set to `20000L` it's indeed possible to have a partition with 20K records, so, the configuration is honored by `sparklyr` as expected.
- But notice as the name suggests, `spark.sql.execution.arrow.maxRecordsPerBatch` is an *uppe rbound* on number of records per partitions. It says number of records per partition won't exceed a certain number, but AFAIK it doesn't guarantee once you have more than 1 partitions then some partition will have exactly that many rows (e.g., as you saw from your own example)
- You can choose the coalesce multiple partitions into 1 if it's really necessary to do so, .e.g,:

```
library(sparklyr)
library(arrow)

config <- spark_config()
config$spark.sql.execution.arrow.maxRecordsPerBatch <- 20000L

sdf_len(sc, 2 * 10^4) %>%
  sdf_coalesce(partitions = 1) %>%
  spark_apply(nrow)

#  # Source: spark<?> [?? x 1]
#    result
#     <int>
#  1  20000

# ^^ Great! After `sdf_coalesce`, all records will definitely be within 1 partition.
```

**Comment by lalas** [comment]
Hello yl790,

Thank you for the quick reply.. Much appreciated! :)
One side question I had that I was wondering if you can answer. Looking through the source code of spark_apply, the _records_per_batch_ is defined as:

`records_per_batch <- as.integer(spark_session_config(sc)[["spark.sql.execution.arrow.maxRecordsPerBatch"]] %||% 10000)`

I was wondering where is the function `%||%` defined? I know `||` is the logical or in R, but couldn't find any documentation on `%||%`.

Thanks for your help.

**Comment by yl790** [comment]
@lalas It was imported from a package named `rlang` by `sparklyr`. You can read about that operator in https://rdrr.io/cran/rlang/man/op-null-default.html

**Comment by lalas** [comment]
Hi @yl790... It's was very hard to search for this symbol online, or in Rstudio help, as nothing came up! :)

I've been wanting to read/learn more about `rlang`... Any good tutorial/document you recommend?
Thanks again for your help.

**Comment by yl790** [comment]
@lalas I think in general if you encounter some unknown symbol in source code of `sparklyr` (e.g., let's say `%||%`) one thing to do is to go to an interactive R prompt (could be inside RStudio or launching R binary directly from bash, doesn't matter), and then run the following

```
library(sparklyr)
?`%||%`
```

(notice the backticks surrounding `%||%` to ensure it's quoted properly) which will open up something that is analogous to a UNIX man page describing what `%||%` is.

Aside from that and pdf reference manuals like https://cran.r-project.org/web/packages/rlang/rlang.pdf, there is also a book named 'The R in Spark' that can be read online for free at https://therinspark.com which I found to be quite helpful when I was learning about sparklyr while knowing almost nothing about it.

**Comment by lalas** [comment]
@yl790 Thanks for the references... "The R in Spark" is indeed a great book/resource that is essential for r users... I hope its author keep it constantly updated with all changes that happen with Spark :)

Thanks again for all your help. Much appreciated.
