### ISSUE TITLE
work around some dbplyr::translate_sql limitations in hof_*

### ISSUE THREAD

**Issue by yl790** [sparklyr/sparklyr#2514]
would be interesting to see if there is any workaround for the issue in https://github.com/sparklyr/sparklyr/issues/2513 with accessing struct fields from lambda body (aside from the `mutate(dest_col = sql(...))` workaround)

**Comment by mattpollock** [comment]
Since periods are allowed in R variable names, why not make it a little more R-specific using the `$` operator? In `sparklyr.nested` I was a bit hand-wavy and allowed `x.value` or `x$value` to be used interchangeably in `sdf_select`.

Something like:
```r
new_frame <- test_frame %>%
   group_by(patients) %>%
   summarise(analyteDates = collect_list(analyteDate),
             valuesList = collect_list(struct(value))) %>%
   hof_transform(dest_col = value, expr = valuesList, x %->% (x$value))
```

**Comment by yl790** [comment]
Update: actually no work around needed -- `dbplyr::translate_sql` already translates `$` to `.`
