### ISSUE TITLE
support new built-in higher-order functions in Spark 3

### ISSUE THREAD

**Issue by yl790** [sparklyr/sparklyr#2552]
I think there are a quite few new ones such as array_sort with custom comparator, map filter, forall, transform keys, transform values, map zip with but I don't think they have been documented yet.

**Comment by yl790** [comment]
Note to myself: the latest list is at https://docs.databricks.com/spark/latest/spark-sql/language-manual/select.html

**Comment by benmwhite** [comment]
@yl790 I had that link open on a Firefox tab on my work computer for like 5 straight months once

**Comment by yl790** [comment]
@benmwhite I believe the `docs/latest/` link is updated with some recent new built-in higher-order functions that are only in Spark 3.0, e.g., `array_sort` with custom comparator, among others. I do refresh that page of course to see what's new.
