### ISSUE TITLE
more sparklyr/pyspark benchmarks for common ml algorithms and other real-world big data workloads

### ISSUE THREAD

**Issue by yitao-li** [sparklyr/sparklyr#2601]
https://databricks.com/blog/2018/05/03/benchmarking-apache-spark-on-a-single-node-machine.html and https://github.com/CODAIT/spark-bench (for data generation) may be good starting points

Also, although I was running into some random issues trying to get SparkR working, there was no issue at all when SparkR is run through tidyspark. So, tidyspark deserves the credit for making my life simpler when dealing with SparkR.

**Comment by yl790** [comment]
also, https://codait.github.io/spark-bench/workloads/data-generator-kmeans etc as examples
