### ISSUE TITLE
sparklyr Delta table read using Arrow (0.17.1) and spark_read_delta fails

### ISSUE THREAD

**Issue by rportilla-databricks** [sparklyr/sparklyr#2602]
When using sparklyr command spark_read_delta with a Delta Lake table (Spark version 3.0, Arrow version 0.17.1), the command fails when importing arrow. When the arrow import is removed, the Delta table read works. Code to reproduce below.

There may be an incompatibility issue which needs to be addressed in order for this read to work. The same Delta Lake table read works in SparkR even after the library(arrow) import.

```
library(sparklyr) 
library(arrow)

conf <- spark_config()   # Load variable with spark_config()

sc <- spark_connect(method = "databricks", 
                    config = conf)  # Pass the conf variable 

delta_test <- read.df("/home/user/rwork/delta-test", source = "delta")
sdf <- spark_read_delta(sc, name="perf", "/home/ricardo/rwork/delta-test", memory=FALSE)
head(sdf)
```

---

your brief description of the problem

```r
spark_version <- "2.1.0"
sc <- spark_connect(master = "local", version = spark_version)

# your reproducible example here
```

**Comment by yitao-li** [comment]
This seems to be a databricks-specifc issue, unfortunately. I tried running `sparklyr` with `arrow` locally with `sc <- spark_connect(master = "local", version = "3.1.1", packages = "io.delta:delta-core_2.12:1.0.0")` and everything seems to work just fine. BTW maybe explicitly specifying the version of delta library you want to work with will help  (e.g., `packages = "io.delta:delta-core_2.12:1.0.0"`), as there may be compatbility issues between some Spark versions and some external libraries.

**Comment by yitao-li** [comment]
I also made a change in https://github.com/sparklyr/sparklyr/pull/3134 that may (or may not) help with the issue you ran into, but I think it's best to post the full error message so that I can get a sense of what the actual problem was.
