### ISSUE TITLE
get Spark web ui to work for rstudio.cloud

### ISSUE THREAD

**Issue by yitao-li** [sparklyr/sparklyr#2617]
> I was looking because there have been a couple of posts on Community with folks having issues launching the spark web UI on rstudio.cloud.
> https://community.rstudio.com/t/spark-web-interface-does-not-open/74007/2
> https://community.rstudio.com/t/spark-web-ui-access-on-rstudio-cloud/65240
> I have shared a work around, but I was wondering if there was something that Sparklyr itself could be doing to be a better citizen when there is a proxy involved.

**Comment by yl790** [comment]
This is currently blocked by the fact that Spark web UI is not easily proxyable by design.

**Comment by yitao-li** [comment]
After looking into possible workarounds for this and not succeeding for various reasons, I think the path of least resistance might be rendering this UI on server-side altogether.

**Comment by yitao-li** [comment]
@jspiewak I spent more time trying to get this to work in some shape for form, but no luck so far : /

One thing I observed: after I launch Apache Spark in rstudio.cloud, running `httr::GET("http://localhost:4040")` would give me the html of Spark web UI as expected (so localhost is allowing me to connect to 4040 to get http content), but running `rstudioapi::viewer("http://localhost:4040")` would cause the viewer pane to say "localhost refused to connect", even though according to rstudioapi documentation the expected behavior is the web UI getting rendered on viewer pane.

I think if there is some way to making `rstudioapi::viewer` do what `httr::GET` does on rstudio.cloud, then we should have a really simple solution there.
