### ISSUE TITLE
https://spark.rstudio.com/guides/arrow/ needs updating

### ISSUE THREAD

**Issue by nealrichardson** [sparklyr/sparklyr#2686]
https://spark.rstudio.com/guides/arrow/#installation is almost 2 years stale. I'm not sure you need to give any special installation instructions anymore, but if you want to include something, I'd recommend just saying saying `install.packages("arrow")` and see https://arrow.apache.org/docs/r/ for any questions.

**Comment by yitao-li** [comment]
@javierluraschi Could you sanity-check and merge the update at https://github.com/rstudio/spark.rstudio.com/pull/105? I can confirm with recent versions of `arrow` that are available on CRAN, only `install.packages("arrow")` is necessary.

**Comment by yitao-li** [comment]
Merged!
