### ISSUE TITLE
Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId,  :    Gateway in localhost:8880 did not respond.

### ISSUE THREAD

**Issue by AlwaysThinkofAvery** [sparklyr/sparklyr#2719]
When trying to connect to spark as local, I get the following error: 
Error in spark_connect_gateway(gatewayAddress, gatewayPort, sessionId,  : 
  Gateway in localhost:8880 did not respond.

I have tried installing sparklyr from CRAN and GitHub, but get same error.  I have Java 11.0.8 and Spark 3.0.0 installed

`spark_install(version = "3.0.0")`
Spark 3.0.0 for Hadoop 2.7 or later already installed.

`library(sparklyr)`
`library(dplyr)`

`sc <- spark_connect(master = "local")`

`utils::sessionInfo()`
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_1.4.0

loaded via a namespace (and not attached):
 [1] rstudioapi_0.11   magrittr_1.5      rappdirs_0.3.1    tidyselect_1.1.0  R6_2.4.1          rlang_0.4.7       blob_1.2.1       
 [8] httr_1.4.2        dplyr_1.0.2       tools_4.0.2       parallel_4.0.2    config_0.3        DBI_1.1.0         withr_2.2.0      
[15] dbplyr_1.4.4      askpass_1.1       htmltools_0.5.0   ellipsis_0.3.1    openssl_1.4.3     yaml_2.2.1        assertthat_0.2.1 
[22] rprojroot_1.3-2   digest_0.6.25     tibble_3.0.3      lifecycle_0.2.0   forge_0.2.0       crayon_1.3.4      tidyr_1.1.2      
[29] purrr_0.3.4       base64enc_0.1-3   htmlwidgets_1.5.1 vctrs_0.3.4       glue_1.4.2        compiler_4.0.2    pillar_1.4.6     
[36] r2d3_0.2.3        generics_0.0.2    backports_1.1.10  jsonlite_1.7.1    pkgconfig_2.0.3

**Comment by yitao-li** [comment]
@AlwaysThinkofAvery 

I think you can try 1 of (at least) 2 things to help `sparklyr` locate your Spark installation:

- Run `sparklyr::spark_install(version = "3.0.0")` to install a copy of Apache Spark 3 in `~/spark`, a location well known by `sparklyr`
- Locate your existing Spark installation and specify it in the `spark_home` parameter to `spark_connect()`, e.g., say if the `bin` directory from your Spark installation is at `/home/user/spark/spark-3.0.0-bin-hadoop2.7/bin`, then you should specify `spark_home` as `"/home/user/spark/spark-3.0.0-bin-hadoop2.7"`:

```
sc <- spark_connect(master = "local", spark_home = "/home/user/spark/spark-3.0.0-bin-hadoop2.7")
```

**Comment by AlwaysThinkofAvery** [comment]
Thank you for the reply.  I've tried what you have suggested, but still get the same error. I've tried many different things to try and solve this issue, but can't seem to fix it.  I'm out of ideas myself.  Do you have more suggestions?

**Comment by yitao-li** [comment]
@AlwaysThinkofAvery Sorry to hear it. Did you try running `options(sparklyr.log.console = TRUE)` before `spark_connect(...)`? Was there no Spark driver log printed to console at all?

**Comment by yitao-li** [comment]
Also see https://dzone.com/articles/working-on-apache-spark-on-windows It says something named "winutils" is needed to run Apache Spark successfully on Windows.

**Comment by yitao-li** [comment]
I suggest aside from options(spark.log.console = TRUE) also try launching spark-shell yourself and run the word-count example following the steps in https://dzone.com/articles/working-on-apache-spark-on-windows just to see whether your spark installation is working.

**Comment by AlwaysThinkofAvery** [comment]
I'll give your suggestions a try. Thanks for the replies!

**Comment by AlwaysThinkofAvery** [comment]
I think I found the answer to the error message.  When I try to run `spark-shell` from Command Prompt, it gives this error message:

'Cool' is not recognized as an internal or external command,
operable program or batch file.
Failed to find Spark jars directory.
You need to build Spark before running this program.

My account name has 'Cool" in the name and also contains spaces.  I'll try creating another local account name with no spaces.

**Comment by yitao-li** [comment]
@AlwaysThinkofAvery Nice find! When you set your PATH env variable in Windows did you surround any path containing space with quotes? I seem to vaguely recall that's needed in Windows. Another place where space might happen is C:\Program Files 😅 btw
