### ISSUE TITLE
Connect sparklyr to an existing session

### ISSUE THREAD

**Issue by gdepalma** [sparklyr/sparklyr#2744]
It would be nice if sparklyr was able to connect to an existing Spark session similar to SparkR.

**Comment by yitao-li** [comment]
@gdepalma Thanks for your interest in sparklyr!

Having multiple connections to the same Spark session is in fact a supported by sparklyr. Please see the minimal example below and let me know if it answers your question:

```
library(sparklyr)

master <- "local"  # or an actual Spark cluster
app_name <- "example_app"
config <- spark_config()
config$`sparklyr.gateway.port` <- 8880L  # choose a port number for the gateway

sc <- spark_connect(master = master, app_name = app_name, config = config)

secondary_sc <- spark_connect(sprintf("sparklyr://localhost:8880/%d", sc$sessionId))


# The secondary connection should have the same Spark session and Spark context the first
# connection has, e.g.,

spark_session(sc)
# <jobj[10]>
#   org.apache.spark.sql.SparkSession
#   org.apache.spark.sql.SparkSession@4389c52c

spark_session(secondary_sc)
# <jobj[9]>
#   org.apache.spark.sql.SparkSession
#   org.apache.spark.sql.SparkSession@4389c52c

spark_context(sc)
# <jobj[11]>
#   org.apache.spark.SparkContext
#   org.apache.spark.SparkContext@3942f4af
#
#   appName: example_app
#   master: local[2]
#   files:
#   jars:  file:/mnt/sda7/lib/R/library/sparklyr/java/sparklyr-3.0-2.12.jar

spark_context(secondary_sc)
# <jobj[1]>
#   org.apache.spark.SparkContext
#   org.apache.spark.SparkContext@3942f4af
#
#   appName: example_app
#   master: local[2]
#   files:
#   jars:  file:/mnt/sda7/lib/R/library/sparklyr/java/sparklyr-3.0-2.12.jar
```

**Comment by gdepalma** [comment]
@yitao-li 

Thanks for the feedback.  However, the problem is not to connect to multiple sessions but to retrieve a provided/existing session (e.g. `SparkSession#getOrCreate()`) such as `SparkR.session()` method (docs: https://spark.apache.org/docs/2.4.3/api/R/sparkR.session.html).

So something along the lines of replacing spark_connect() with something similar to SparkR.session().

**Comment by yitao-li** [comment]
@gdepalma You can check for any existing Spark connection in `sparklyr` with the following:

```
spark_connection_find(app_name = "example_app")
```

Because everything is single-threaded within a R session, you can implement the get-or-create a Spark connection with simply the following in sparklyr (or something to that effect)

```
get_or_create_sc <- (app_name, ...) {
  list_of_conns <- spark_connection_find(app_name = app_name)
  if (length(list_of_conns) > 0) {
     # presumably there is only 1 such connection
    list_of_conns[[1]]
  }
  # otherwise create a new connection
  config <- spark_config()
  config$app_name <- app_name
  spark_connect(..., config = config)
}
```

Notice you can also call `spark_connection_find()` with both `app_name` and `method` as criteria, e.g., `spark_connection_find(app_name = "sparklyr", method = "shell")`.

The reason `sparklyr` doesn't have the get-or-create type of method is it has a slightly different design philosophy compared to SparkR. Sparklyr supports the presence of multiple Spark connections (so it should not have some kind of global state that contains at most 1 active connection, and it's up to the user to decide whether to have this type of at-most-1-active-connection constraint for a given Spark application).

**Comment by gdepalma** [comment]
@yitao-li 

Thanks, I think we're getting close, but we are trying to connect to an existing Spark Session created by a SparkR job in Mesos. However, `spark_find_connection()` returns an empty list.  I've tried a variety of `app_name` values, and used 'shell' for method or left it blank.

**Comment by yitao-li** [comment]
@gdepalma SparkR and sparklyr will submit separate applications (application as in a jar file that gets launched) to the cluster manager. However, if you create a dataframe or some other resource in SparkR, there should be still be ways to make those accessible through sparklyr.

Sparklyr currently only supports "client mode" under mesos though (see https://therinspark.com/connections.html#connections-mesos)

**Comment by gdepalma** [comment]
@yitao-li 

Thanks again.  Unfortunately, in our setup spark jobs can only be run using the spark-submit command and therefore we are looking for a way to connect sparklyr to the already created Spark session.

**Comment by yitao-li** [comment]
@gdepalma Both SparkR and `sparklyr` will run `spark-submit` to launch some form of "server process" which runs as a Spark application, while the R process acts as client. I don't think there is any way `sparklyr` can talk with the "server process" launched by SparkR yet.

Please let me know if you see any significant benefit of not running `sparklyr` session separately from the `SparkR` one.
