### ISSUE TITLE
How to parallelize database calls with registerDoSpark()?

### ISSUE THREAD

**Issue by JakeRuss** [sparklyr/sparklyr#2760]
Does `sparklyr` need a function which is analogous to `doParallel::clusterEvalQ`?

I am trying to parallelize some database queries, where each worker would pull a single day's worth of data from the database, perform some calculations and then return the combined results. When I attempt to set this up, I receive an object not found error message for the database connection object. doParallel [has a similar problem](https://stackoverflow.com/questions/36759058/fetching-data-in-parallel-from-mysql-using-r-doparallel-or-foreach), which is solved by using `doParallel::clusterEvalQ` to initialize the database connection object onto the workers. 

```
library(tidyverse)
library(sparklyr)
library(foreach)

analysis_end_date   <- Sys.Date() - 1
analysis_start_date <- analysis_end_date - 60

creds <- config::get()

config <- spark_config()

sc <- spark_connect(master = "local", config = config)

jdbc_read_url <- config %>%
  glue::glue_data("jdbc:redshift://{host_url}:{port}/{db_name}") %>%
  as.character()

data_query <- glue::glue_sql(
  "SELECT * FROM sample_table
   WHERE date >= {analysis_start_date} AND date <= {analysis_end_date}",
   .con = DBI::ANSI()) %>% # Use ANSI connection for proper date quotes
  as.character()

database_tbl <- sc %>%
  spark_read_jdbc(sc      = .,
                  name    = "sample_table",
                  options = list(url      = jdbc_read_url,
                                 user     = creds$user_name,
                                 password = creds$password,
                                 query    = data_query,
                                 driver   = "com.amazon.redshift.jdbc42.Driver"),
                  memory  = FALSE)

analysis_calendar <- analysis_start_date %>%
  seq.Date(analysis_end_date, by = "day") %>%
  magrittr::extract(1:10)

registerDoSpark(sc)

foreach_results <- foreach(i = analysis_calendar,
          .export   = c("jdbc_read_url", "database_tbl"), 
          .packages = c("dplyr")) %dopar% {
          
  database_tbl %>%
                filter(date %in% i) %>%
                summarise(max_date = max(date, na.rm = TRUE),
                avg_mpg  = mean(mpg, na.rm = TRUE)) %>%
               collect()
}
```

When I run the code above, I get...
```
Error in <bytecode> : 
  task 1 failed - "java.lang.IllegalArgumentException: Object not found 18
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:110)
	at sparklyr.StreamHandler.read(stream.scala:61)
```
Which, I think, means spark is looking for the `database_tbl` object and is unable to find it. 

Does `sparklyr` have (need?) a way to create database connections on all of the worker nodes, so that the foreach loop can retrieve the queries?

**Comment by yitao-li** [comment]
@JakeRuss I think the problem here is `database_tbl` cannot be serialized in a sensible way into an array of bytes that can be passed on to Spark workers -- in your code `database_tbl` is an object in `sparklyr` that serves as a reference to some Spark dataframe, it encapsulates a Spark connection object, and a Spark connection object is not really something that can be serialized in a sensible way and work as expected in the Spark worker processes.

RegisterDoSpark currently can only support use cases that pass serializable objects to Spark workers (e.g., strings or raw bytes)

**Comment by JakeRuss** [comment]
@yitao-li Thanks for your response. I agree the connection object cannot be serialized. This is the same limitation of `doParallel`.

Is there a way to create the database connection on the worker nodes (and, if not, should this become a feature request)? The doParallel solution is to run `clusterEvalQ` first then proceed with the foreach call after the workers have the connection initialized
```
doParallel::clusterEvalQ(cluster, {connection_object <- dbConnect()})

foreach(i in 1:10, ...) %dopar% {
 connection_object, etc..
}
```
which allows each worker node to have their own `connection_object` for queries.

**Comment by yitao-li** [comment]
@JakeRuss There is no equivalent of `clusterEvalQ` in `sparklyr` yet. I'll make this a feature request for `sparklyr`.

I assume the purpose of `clusterEvalQ` is to make sure some expression is evaluated exactly once by each worker, and whatever results from that evaluation will be available in subsequent `foreach` iterations, correct?

**Comment by JakeRuss** [comment]
Yes, I believe that is correct. Thank you

**Comment by JakeRuss** [comment]
I'll close this since you opened a new issue #2761 Many thanks!
