### ISSUE TITLE
sdf_seq() error: `repartition` cannot be casted to an integer vector

### ISSUE THREAD

**Issue by nathaneastwood** [sparklyr/sparklyr#2765]
`sparklyr::sdf_seq()` will not work with the default `repartition` parameter. This is because it gets passed `type` which by default is one of `"integer"` or `"integer64"`, a character string.

```r
sparklyr::sdf_seq(sc)                                                                                                                                                       
# Error: `repartition` cannot be casted to an integer vector.
```

Also, "casted" is not a word; it should say "cast" - though this is a problem for the forge package.

Looking into the code, `repartition` gets passed to `cast_scalar_integer()` which in turn passes it to `case_integer()`.

```
r$> devtools::session_info()                                                                                                                                                  
Session info ------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, linux-gnu           
 ui       vscode                      
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Etc/UTC                     
 date     2020-10-28

Packages ------------------------------------------------------------------------------------------------------------------------------------
 package       * version    date       source   
 forge           0.2.0      2019-02-26 CRAN (R 3.4.4)
 sparklyr        1.3.0      2020-06-27 url
```

Spark 2.4.4

**Comment by yitao-li** [comment]
@nathaneastwood Thanks for reporting this bug!

I'm not entirely sure what happened to the `sdf_seq()` code path in `sparklyr` and why `repartition` has its default value being a string when it actually needs to be an integer in all circumstances (as `repartition` specifies the number of Spark partitions you want to use to distribute your data within the cluster) .

For the moment please replace `sdf_seq(sc)` with `sdf_seq(sc, repartition = 1L)` instead (assuming you want all records to be in 1 partition)

**Comment by nathaneastwood** [comment]
No problem, I actually set `repartition = NULL` and that works (looking at the source code at least), but `repartition = 1L` is also sensible. I can create a quick PR if you like to set the default as `1L`?

**Comment by yitao-li** [comment]
@nathaneastwood Sure! Looking forward to your PR 👍
