### ISSUE TITLE
create Spark equivalent of expand.grid

### ISSUE THREAD

**Issue by yitao-li** [sparklyr/sparklyr#2768]
Seems like a good idea to implement this as a convince helper method as part of the sparklyr sdf interface. Thanks to @nathaneastwood for suggesting it!

We need to be mindful of the following though:
- Things that exist for R dataframes but not for Spark dataframes: factors and attributes
- Decisions that are potentially important (performance-wise) in Spark but have no equivalent in R: whether to cache the resulting Spark dataframe in memory (or at least attempt to do so and give up if the resulting dataframe is too large), whether to include hints for broadcast hash join on some non-large dataframes in the crossjoin operation

**Comment by yitao-li** [comment]
@nathaneastwood So this functionality is now implemented as `sdf_expand_grid` in `sparklyr`.

There is also a slight change in https://github.com/sparklyr/sparklyr/pull/2788 to make the ordering of tuples resulted from `sdf_expand_grid` match that from `expand.grid` with all known versions of Apache Spark (e.g., `expand.grid(seq(3), letters[1:3], letters[1:3])` will output (1, "a", "a"), (2, "a", "a"), ..., (1, "b", "a"), ..., (1, "b", "b"), ... etc where the 1st variable varies the fastest, 2nd variable varies the 2nd fastest and so on)

However I think the ordering of output in Apache Spark is highly implementation dependent and there is no formal guarantee that future versions of Apache Spark will have the same ordering in its cross join output.

**Comment by nathaneastwood** [comment]
This is brilliant @yitao-li. Thanks very much for taking this on board. I will give it a try hopefully this evening and if I come across any issues I will either note them here or raise a separate issue.
