### ISSUE TITLE
Failed to find 'spark-submit2.cmd'

### ISSUE THREAD

**Issue by englianhu** [sparklyr/sparklyr#2769]
# Reporting an Issue with sparklyr

For general programming questions with `sparklyr`, please ask on
[Failed to find 'spark-submit2.cmd'](https://stackoverflow.com/questions/64632416/failed-to-find-spark-submit2-cmd) instead.

Here I noticed similar issue https://github.com/sparklyr/sparklyr/issues/305, https://github.com/sparklyr/sparklyr/issues/229

```diff
> library('BBmisc')
> library('sparklyr')
> sc <- spark_connect(master = 'local')
- Error in start_shell(master = master, spark_home = spark_home, spark_version = version,  : 
-   Failed to find 'spark-submit2.cmd' under 'C:\Users\Owner\AppData\Local\spark\spark-3.0.0-bin-hadoop2.7', please verify - SPARK_HOME.
> spark_home_dir()
[1] "C:\\Users\\Owner\\AppData\\Local/spark/spark-3.0.0-bin-hadoop2.7"
> spark_installed_versions()
  spark hadoop                                                              dir
1 3.0.0    2.7 C:\\Users\\Owner\\AppData\\Local/spark/spark-3.0.0-bin-hadoop2.7
> spark_home_set()
Setting SPARK_HOME environment variable to C:\Users\Owner\AppData\Local/spark/spark-3.0.0-bin-hadoop2.7
> sc <- spark_connect(master = 'local')
- Error in start_shell(master = master, spark_home = spark_home, spark_version = version,  : 
-   Failed to find 'spark-submit2.cmd' under 'C:\Users\Owner\AppData\Local\spark\spark-3.0.0-bin-hadoop2.7', please verify - SPARK_HOME.
> spark_version <- '3.0.0'
> sc <- spark_connect(master = "local", version = spark_version)
- Error in start_shell(master = master, spark_home = spark_home, spark_version = version,  : 
-   Failed to find 'spark-submit2.cmd' under 'C:\Users\Owner\AppData\Local\spark\spark-3.0.0-bin-hadoop2.7', please verify - SPARK_HOME.
```
*source : https://github.com/englianhu/binary.com-interview-question/issues/1#issue-733943885*

May I know how to how to solve `Failed to find 'spark-submit2.cmd' under 'C:\Users\Owner\AppData\Local\spark\spark-3.0.0-bin-hadoop2.7', please verify - SPARK_HOME.`?

**Reference :**

- https://community.rstudio.com/t/need-help-getting-started-with-spark-and-sparklyr/22910
- [Error while connecting sparklyr to remote sparkR in Rstudio](https://stackoverflow.com/questions/39837056/error-while-connecting-sparklyr-to-remote-sparkr-in-rstudio)

```r
> devtools::session_info()
- Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 8.1 x64             
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       Asia/Tokyo                  
 date     2020-11-01
```

**Comment by yitao-li** [comment]
@englianhu `sparklyr` expect `spark-submit2.cmd` to exist within the C:\Users\Owner\AppData\Local\spark\spark-3.0.0-bin-hadoop2.7 directory. Please double-check that file exists and is readable by `sparklyr`. The file should be there if your spark installation is complete.

**Comment by englianhu** [comment]
> @englianhu `sparklyr` expect `spark-submit2.cmd` to exist within the C:\Users\Owner\AppData\Local\spark\spark-3.0.0-bin-hadoop2.7 directory. Please double-check that file exists and is readable by `sparklyr`. The file should be there if your spark installation is complete.

I can use `sparklyr` by 1-click installation and able to use it 2 years ago, wonder why make simple things trouble?

**Comment by yitao-li** [comment]
@englianhu Sorry to hear it. I'm not sure what happens with Apache Spark installation process on Windows. I think that's a question best addressed to Spark folks.

**Comment by englianhu** [comment]
I tried to refer to https://phoenixnap.com/kb/install-spark-on-windows-10 and https://www.tutorialspoint.com/apache_spark/apache_spark_installation.htm since my local pc using windows...

**Comment by yitao-li** [comment]
@englianhu Your reference looks good to me.

If you can find `C:\Spark\spark-<version>-bin-hadoop2.7\bin\spark-shell` after following through that reference and your Spark installation is complete, then you should be also able to find `C:\Spark\spark-<version>-bin-hadoop2.7\spark-submit2.cmd`.

After that `sparklyr` should work as expected assuming
1. You set the `SPARK_HOME` env variable or the `spark_home` parameter of `spark_connect()` to be `C:\Spark\spark-<version>-bin-hadoop2.7`
2. The R process running `sparklyr` has the right priviledge/permission to read and execute the `C:\Spark\spark-<version>-bin-hadoop2.7\spark-submit2.cmd` file.

**Comment by englianhu** [comment]
**Solved**

1) https://spark.apache.org/downloads.html
2) extract zipped file to `'C:/Users/scibr/AppData/Local/spark/spark-3.0.1-bin-hadoop3.2'`.
3) manually choose latest version : `spark_home_set('C:/Users/scibr/AppData/Local/spark/spark-3.0.1-bin-hadoop3.2')`

---

```r
library('sparklyr')
spark_home_set('C:/Users/scibr/AppData/Local/spark/spark-3.0.1-bin-hadoop3.2')
sc <- spark_connect(master = 'local')
connection_is_open(sc)
# TRUE
smp2_sc <- copy_to(sc, smp2)
smp2_sc
# A tibble: 137 x 9
   Date       Type        Bettor Turnover   Won        Cancelled Rebates Profit   Profit_rate
   <date>     <chr>        <dbl> <chr>      <chr>      <chr>     <chr>   <chr>    <chr>      
 1 2020-05-27 1分快3         698 7994708.00 7649465.34 85262.00  10892.~ 334350.~ 4.18%      
 2 2020-05-27 极速快3        150 1817943.00 1788182.30 0.00      3426.23 26334.47 1.45%      
 3 2020-05-27 3分快3         117 279209.00  264210.09  4180.00   392.13  14606.78 5.23%      
 4 2020-05-27 龙虎斗          45 201525.00  196699.20  0.00      748.04  4077.76  2.02%      
 5 2020-05-27 5分快3          44 121834.00  117366.68  77.00     60.53   4406.80  3.62%      
 6 2020-05-27 传统1分赛车     15 83977.00   79449.58   3656.00   33.35   4494.07  5.35%      
 7 2020-05-27 骰宝            10 81745.00   68456.00   0.00      779.70  12509.30 15.30%     
 8 2020-05-27 传统1分彩       19 76025.00   75857.69   0.00      125.99  41.33    0.05%      
 9 2020-05-27 1分六合         29 55400.00   58311.08   4.00      12.89   -2923.97 -5.28%     
10 2020-05-27 1分彩           38 53185.52   54269.48   5020.00   110.61  -1194.56 -2.25%     
# ... with 127 more rows
spark_available_versions()
  spark
1   1.6
2   2.0
3   2.1
4   2.2
5   2.3
6   2.4
7   3.0
```

**Comment by englianhu** [comment]
https://github.com/englianhu/binary.com-interview-question/issues/1#issue-733943885
 step :
1) https://floatsdsds.github.io/sparklyr-install-connect-spark
2) https://www.oracle.com/java/technologies/javase-downloads.html

```diff
> Sys.setenv(JAVA_HOME="C:/Program Files/Java/jdk-15.0.1/bin")
> library('sparklyr')
> spark_home_set('C:/Users/user/AppData/Local/spark/spark-3.0.1-bin-hadoop3.2')
> sc <- spark_connect(master = 'local')
- Error in spark_get_java(throws = TRUE) : 
-   Java is required to connect to Spark. JAVA_HOME is set to 'C:/Program Files/Java/jdk-15.0.1/bin' but does not point to a valid version. Please fix JAVA_HOME or reinstall from: https://www.java.com/en/
> connection_is_open(sc)
- Error in connection_is_open(sc) : object 'sc' not found
```
