### ISSUE TITLE
spark_apply() behavior limited by arrow

### ISSUE THREAD

**Issue by FelixCW** [sparklyr/sparklyr#2770]
Hi there,
I encountered an spark_apply() issue when I loaded package arrow.
The result from
diamonds %>% spark_apply(somefunction, group_by=“cut”) %>% collect()
Is different from
diamonds %>% group_by(cut) %>% summarise(somefunction)

When arrow is not loaded, the two results coincide.
And It seems that that the discrepancy comes from the value spark.sql.execution.arrow.maxRecordsPerBatch set to
10000 so any partition is limited to have maximum of 10000 rows, which blows up the results when dealing with large data sets.

However, when I set this parameter above 10000 then I fail to connect to spark.
Is there any ways to remove this limitation of max row per partition?

**Comment by sbottelli** [comment]
Hi @FelixCW,
I've also encountered this issue. 
I solved used conf$spark.sql.execution.arrow.maxRecordsPerBatch <- 600000L
and then connect to spark.
For me it works!

**Comment by FelixCW** [comment]
Hi @sbottelli 

Thank you for the reply.
Turns out that the value I set was not integer and adding the literal ‘L’ at the end of the value  solved the problem !!
