### ISSUE TITLE
Using multiple functions with spark_apply

### ISSUE THREAD

**Issue by ThomasGrivaz** [sparklyr/sparklyr#2792]
Hello everyone, I'm applying a custom-made R function on a Spark dataframe using ```spark_apply``` but the issue that I'm facing is that the main function uses several other custom-made functions implemented in another local R script, in pseudo-code, my use-case looks like the following:

```
# where my sub-functions are located
source(functions.R)

# my main function that needs to be parrallelized
main_function <- function(data) {
   # calling a bunch of functions defined in functions.R
   call sub_function_1(data)
   call sub_function_2(data)
   ...
   call sub_function_n(data)
}

result <- spark_apply(spark_df, main_function)
```
My job crashes because worker nodes do not have a reference to the sub-functions. Indeed checking the worker nodes logs yields:

20/11/10 12:56:42 ERROR sparklyr: RScript (8197) terminated unexpectedly: could not find function "sub_function_1" 

By looking at the documentation, it seems that one possible way to cope with this is to supply the functions to the argument ```context``` of spark_apply but I've seen no examples with multiples functions and it doesnt'feel very practical given the fact that I have in total 8 sub-functions called within my main function which sums up to about 800 lines of code.

I saw that you can run a custom script before launching Rscript using ```sparklyr.apply.options.rscript.before``` so I've tried adding the following line to ```config-template.yml``` : 

```
sparklyr.apply.options.rscript.before:  "path/to/functions.R"
```
But this fails with the error message:
java.io.IOException: Cannot run program "path/to/functions.R" (in directory "."): error=2, No such file or directory

Can you please advise on what the best course of action is? 

Many thanks

**Comment by benmwhite** [comment]
Try making your `context` object a list of functions, then call them inside your main main function like `context$sub_function_1()`, etc. You'd probably need to make sure the sub functions are compatible with `spark_apply()` with all external package functions declared explicitly for instance.

See some `context` examples [here](https://therinspark.com/distributed.html#context)

**Comment by ThomasGrivaz** [comment]
@benmwhite , I proceeded as indicated in the example you provided:

```
func_a <- function() 40
func_b <- function() func_a() + 1
func_c <- function() func_b() + 1

sdf_len(sc, 1) %>% spark_apply(function(df, context) {
  for (name in names(context)) assign(name, context[[name]], envir = .GlobalEnv)
  func_c()
}, context = list(
  func_a = func_a,
  func_b = func_b,
  func_c = func_c
))
```

And it's working fine. Thank you very much for your help! I really appreciate. Marking this issue as closed now.
