### ISSUE TITLE
dbplyr 2.0.0 schema handling

### ISSUE THREAD

**Issue by wangyuchen** [sparklyr/sparklyr#2805]
When using sparklyr 1.4.0 with dbplyr 2.0.0, some basic table operations fail, possibly due to the change in schema handling from dbplyr. 

It used to be able to access a Hive table using a character string specifying schema and table, but now it fails:

```r
tbl(sc, "schema_name.table_name") 
Error: org.apache.spark.sql.AnalysisException: Table or view not found: ...
```

The workaround I found was:

```r
tbl(sc, dbplyr::in_schema("edw_enc", "edw_product_line"))
tbl(sc, dbplyr::in_schema(sql("edw_enc"), sql("edw_product_line")))
```

Also `tbl_cache` is another one that I found. It used to work with:

```r
tbl_cache(sc, dbplyr::in_schema("edw_enc", "edw_product_line"))
```

But now it fails. 

Using character still works for `tbl_cache()`, i.e. 
```r
tbl_cache(sc, "schema_name.table_name")
```

The relevant dbplyr feature seems to be from [this commit](https://github.com/tidyverse/dbplyr/commit/b420776d116141f4ab7bafc77dd4465d9843b5e7), where the return of `in_schema` is now a list instead of a character vector. 

Thanks!

**Comment by yitao-li** [comment]
@wangyuchen Good to know. Thanks!!

BTW there is also the change in https://github.com/sparklyr/sparklyr/pull/2775 that fixes another incompatibility between `sparklyr` and `dbplyr` 2.0 (it was previously not an issue).
I think that fix only matters when you are summarizing a Spark dataframe in `sparklyr` with an empty list of grouping variables.

So I recommend either installing `sparklyr` from source from the main branch of github or wait for the upcoming `sparklyr` 1.5 release if you plan to stick with dbplyr 2.0 or above.

**Comment by yitao-li** [comment]
It's debatable whether simply splitting the identifier by '.' if '.' is present and then interpreting the 2 components as schema and table name is the technically correct thing to do, as '.' is valid within Spark table names if surrounded by backticks.

**Comment by wangyuchen** [comment]
Yeah, I'll stick to the last version of `dbplyr` for now, as that has been working great. I'll wait for `sparklyr` 1.5. Thanks again!
