### ISSUE TITLE
Connect sparklyr to remote Spark master

### ISSUE THREAD

**Issue by aissaelouafi** [sparklyr/sparklyr#282]
I want to connect `sparklyr` to the master node of a Spark cluster, the problem is R studio running on Windows machine and the master node of my Spark cluster is running on RedHat OS. The `sc_connect` function require to specify the `SPARK HOME`. Should I specify the `SPARK HOME` of my Spark master node ?

**Comment by kykuo** [comment]
@aissaelouafi I've learned that this isn't a great idea; see https://github.com/rstudio/sparklyr/issues/280

**Comment by javierluraschi** [comment]
@aissaelouafi you would have to install a local version of Spark in the RStudio machine running Windows. You can use `spark_install(version = "")` with a version that matches the cluster. However, this will only work out appropiately as long as the Windows machine has full bidirectional access to the cluster, which effectively means, the Windows machine should be in the cluster for this to work efficiently. Is the Windows machine in the Spark cluster?

**Comment by varshney016** [comment]
@javierluraschi please tell me after installing local version of spark, what i have to configure, i have cloudera CDH as my cluster and since client is external to cluster i have to use yarn-client to get results of each query i ran (my aim is to run SQL queries)
Thanks in advance

**Comment by javierluraschi** [comment]
@varshney016 since client is external to cluster, your only option today is to use https://livy.incubator.apache.org/ by installing Livy in the Cloudera cluster. However, Livy is really slow compared to using Spark from within the cluster. The best solution would be to ask you cluster administrator to install RStudio Server or RStudio Server Pro in a edge node.

**Comment by varshney016** [comment]
@javierluraschi thanks for your reply. But sorry i don't understand what do you mean by only options, driver program can be outside the cluster in spark? ( i have full access to the cluster)
Thanks in advance
