### ISSUE TITLE
process_tbl_name

### ISSUE THREAD

**Issue by joscani** [sparklyr/sparklyr#2836]
Hi. 
I've installed sparklyr over a amazon linux using `devtools::install_github("sparklyr/sparklyr")` But I get this code in process_tbl_name 

```R
> sparklyr:::process_tbl_name
function (x) 
{
    components <- strsplit(x, "\\\\.")
    num_components <- length(components)
    if (identical(num_components, 1L)) {
        x
    }
    else if (identical(num_components, 2L)) {
        dbplyr::in_schema(components[[1]], components[[2]])
    }
    else {
        stop("expected input to be <table name> or <schema name>.<table name>")
    }
}
<environment: namespace:sparklyr>

```
the problem is with `    components <- strsplit(x, "\\\\.")` using 4 \ instead 2. And I get a error to read spark table . Any workaround? 
Thanks

**Comment by joscani** [comment]
It's strange, installin in ubuntu it looks fine.

**Comment by yitao-li** [comment]
Oops I think there is a bug in that code path : / (but splitting by "\\." was not part of the bug)

**Comment by yitao-li** [comment]
@joscani Thanks! It has been corrected now. You can re-run `remotes::install_github("sparklyr/sparklyr")` to see the schema name and table name being parsed correctly.

**Comment by joscani** [comment]
Thanks. It works now.  It looks this in aamzon linux.
```r
> sparklyr:::process_tbl_name
function (x) 
{
    components <- strsplit(x, "\\\\.")[[1]]
    num_components <- length(components)
    if (identical(num_components, 1L)) {
        x
    }
    else if (identical(num_components, 2L)) {
        dbplyr::in_schema(components[[1]], components[[2]])
    }
    else {
        stop("expected input to be <table name> or <schema name>.<table name>")
    }
}
<environment: namespace:sparklyr>
```
