### ISSUE TITLE
String Encoding

### ISSUE THREAD

**Issue by sbottelli** [sparklyr/sparklyr#2837]
Hi!
Maybe this question is not related directly to sparklyr but could be useful to the community.
I have strings like this:
b'yyyy\xf2'
and I want to obtain a string like this yyyyò. 
Is there in sparklyr, HIVE or maybe changing some configs that could help the encoding/decoding of characters?
Thanks for your attention
Stefano

**Comment by yitao-li** [comment]
@sbottelli In `sparklyr` version 1.5 (submitted to CRAN 1 day ago) unicode characters are indeed preserved through serialization, e.g., the following outputs yyyyò as expected:

```
library(sparklyr)

sc <- spark_connect(master = "local")
unicode_df <- data.frame(x = 'yyyy\u00f2')
unicode_sdf <- copy_to(sc, unicode_df)

unicode_sdf %>% collect() %>% print()
```

outputs

```
# A tibble: 1 x 1
  x
  <chr>
1 yyyyò
```

**Comment by yitao-li** [comment]
I'm wondering whether your question is more about how to have unicode characters displayed correctly, but that's something that depends on multiple factors such as whether the shell or UI you are using has unicode support and whether you are displaying the content in a font that supports unicode well.

**Comment by sbottelli** [comment]
Thanks for the insight! yes is an encoding problem with some specific
characters. I solved it in another way!
Thanks!

*[image: Logo-ShopFully-Mail]
<http://logos.shopfully.com/Logo-ShopFully-Mail.png>*

Stefano Bottelli
*Data Scientist*

Web:    https://corporate.shopfully.com

*Notice. The information contained in this message is intended only for use
of the individuals named above. The message may contain confidential,
proprietary or legally privileged information. If you are not the intended
recipient of this message, you must not use, disseminate or copy it in any
form or take any action in reliance of it. If you have received this
message in error, please delete it and notify the sender immediately. This
e-mail address is not a private address and, therefore, its use is
regulated.*


Il giorno ven 27 nov 2020 alle ore 12:09 Yitao Li <notifications@github.com>
ha scritto:
