### ISSUE TITLE
stream_write_delta - specify partitions

### ISSUE THREAD

**Issue by martindut** [sparklyr/sparklyr#2839]
Hi. How can I specify partitions when calling stream_write_delta? With spark_write_delta I can just specify  partition_by = c("X", "Y"), but it does not seem to work for stream_write_delta

**Comment by yitao-li** [comment]
@martindut This looks like something that is missing in the sparklyr API.

**Comment by yitao-li** [comment]
The required change is now in `sparklyr` master branch and will be released to CRAN in the upcoming `sparklyr` 1.6 release.

**Comment by martindut** [comment]
Cool, thanks
