### ISSUE TITLE
spark_tbl throws error when using summarise()

### ISSUE THREAD

**Issue by sriram221189** [sparklyr/sparklyr#2842]
The spark_tbl does not provide a summarised result when used without a group_by(). Kindly refer to the issue raised in tidyverse.
https://github.com/tidyverse/dplyr/issues/5613

**Comment by benmwhite** [comment]
What sparklyr version are you running? This seems like it's related to the issue referenced [here](https://github.com/sparklyr/sparklyr/issues/2805#issuecomment-726136002), which was patched in the last month for the latest CRAN release from the last week.

**Comment by yitao-li** [comment]
Yep can confirm this is in fact not a tidyverse issue and it appears to be fixed in recent versions of `sparklyr` as well.
