### ISSUE TITLE
Jar dependencies listed in `livy_config(jars=...)` are ignored

### ISSUE THREAD

**Issue by pgramme** [sparklyr/sparklyr#2843]
Hi

I'm using sparklyr v1.5.0 with a Livy connection to an existing remote Spark cluster (old Spark 2.3.0, Cloudera HDP) and I've had troubles specifying jar dependencies for my code, as in the code below. Because the cluster has no outgoing access to internet (Github), I have prealably uploaded the required jars to HDFS.

```r
library(sparklyr)
SPARK_VERSION <- "2.3.0"
LIVY_SERVER <- "http://some.server:8999"

lcfg <- livy_config(
  negotiate = TRUE, custom_headers = list("X-Requested-By"=toupper(USER)), 
  jars = c(
    "hdfs:///users/pierre/jar/spark-sql-kafka-0-10_2.11-2.3.0.jar",  # Some Spark extension
    "hdfs:///users/pierre/jar/my-custom-package.jar" # Some personal code specific to my data model
))
lcfg$sparklyr.livy.jar = "hdfs:///users/pierre/jar/sparklyr-2.3-2.11.jar"  # Sparklyr server jar (from Github)

sc <- spark_connect(
  master = LIVY_SERVER, method = "livy", 
  version = SPARK_VERSION,
  config = lcfg)
```

As such, the jars listed in `livy_config(...)` are ignored and only `sparklyr.livy.jar` is actually included in the REST request creating the session. If I understand correctly the doc of `livy_config(...)`, this seems like a bug (?) 

Related issues about the link between livy.jars and sparklyr.livy.jar: #2722 and #2776 

I could find a simple fix, see PR below. Does it seem OK?

Thanks
Pierre

**Comment by yitao-li** [comment]
@pgramme Nice. Thanks for the fix! It will be shipped as part of `sparklyr` 1.5.1 soon.

**Comment by ying1** [comment]
@yitao-li @pgramme 
Can you explain the difference between using `livy_config( ... jars=c( ) )`  vs `sparklyr.livy.jar=c()` ? are they just same ways of adding jars to be loaded?  A bit confused here.

**Comment by yitao-li** [comment]
@ying1 The only difference is setting `config$sparklyr.livy.jar < c(...)` is documented in [here](https://github.com/sparklyr/sparklyr/blob/8a5f00f830cfdfd1718a4673abed30a644eefcbe/R/config_settings.R#L44) and should be preferred, whereas setting `config$livy.jar` is part of implementation detail in `sparklyr` rather than a documented config parameter.

**Comment by yitao-li** [comment]
Also what's in `config$sparklyr.livy.jar` will eventually be merged into `config$livy.jars`, and then the Livy session looks at the value `config$livy.jars` to determine the `"jars"` session parameter.

**Comment by yitao-li** [comment]
Another difference (as pointed out in the description of this issue) is once `sparklyr.livy.jar` is set, then `sparklyr` won't attempt to fetch the requested `sparklyr-<Spark version>-<Scala version>.jar` file from GitHub.

Other jar files should be listed in `livy_config(jars = c(...))`.

**Comment by pgramme** [comment]
Indeed, they both end up in the `jars` parameter of the Livy session creation, with the difference explained by Yitao-Li above. My interpretation was that `config$livy.jar` should be used for application jars (e.g. Kafka or some domain-specific package) whereas `sparklyr.livy.jar` should be used only for the SparklyR-specific jar, when the default value on GitHub doesn't work.

Would the doc be clearer by adding an argument to `livy_config(..., sparklyr_jar = NULL)` which would set `config$sparklyr.livy.jar` (defaulting to GitHub when null)?
