### ISSUE TITLE
spark_read_csv extremely slow in comparison to read.df

### ISSUE THREAD

**Issue by markbaas** [sparklyr/sparklyr#2858]
I have a storage account on Azure with enormous amount of csv files. I have configured spark to be able to access the storage account.

The following code takes hours and never ends:

```r
tic()
raw <- sc %>% spark_read_csv(
  "df",
  url,
  columns = schema,
  memory = F,
  headers = F,
  infer_schema = F)
toc()
```
and the corresponding sparkR (and scala) code has no problems:
```r
tic(); raw <- read.df(url, schema = schema, inferSchema = "false", source = "csv", header = "false"); toc()
```

Am I doing something wrong or is sparklyr unable to handle multiple files?

**Comment by yitao-li** [comment]
@markbaas I believe `spark_read_csv()` caches the resulting Spark dataframe into memory by default and that is why it is slower, whereas `SparkR::read.df()` doesn't do that.

You can disable the caching-into-memory behavior with `spark_read_csv(memory = FALSE)`, but doing so may cause subsequent algorithms running on that dataframe to be slow.

**Comment by markbaas** [comment]
@yitao-li see my code, I already set the ‘memory = F’ parameter. That’s why I believe this might be a big.

**Comment by markbaas** [comment]
I’m using spark because I have a lot of data. Won’t make sense loading it in memory. In that case I would just use regular R.

**Comment by markbaas** [comment]
Seems there was a typo: I head `headers` instead of `header`.

**Comment by yitao-li** [comment]
@markbaas How large are the CSV files? It may be worthwhile to do a quick sanity check on a small subset of them to see on average how many megabytes the Spark process is ingesting per second, and compare that with the max speed for sequential read of the underlying medium those CSV files are stored on. There should not be too much discrepancy between those 2 rates.

Another factor to consider is JIT (https://en.wikipedia.org/wiki/Just-in-time_compilation). Each Spark process will be initially slow while it's interpreting byte code but will eventually become faster once frequently accessed byte code gets compiled into native code.
