### ISSUE TITLE
Unable to use glimpse function

### ISSUE THREAD

**Issue by PinkAppleFlower** [sparklyr/sparklyr#2863]
**Brief description of the problem**
Unable to use glimpse on Spark tibble after update.

Did you do an update yesterday? It looks like you have a new published date of 12-11-2020... 
https://cran.r-project.org/web/packages/sparklyr/index.html, 

I was able to use the glimpse function to successfully view the information of a remote data set in Spark yesterday.  Now I am unable to do so and think I updated this package.  Attached is my session info; it did not show up correctly when trying to copy and paste; same situation with error output from the tryCatch call in which the glimpse is wrapped.

**Code**
spark_conn <- spark_connect(master = "local")

EU_tibl <- ts_tbl(EuStockMarkets)

EU_Spark_link_cp <- copy_to(spark_conn, EU_tibl, "EU_Spark_cp", overwrite = TRUE)

tryCatch({
  glimpse(EU_Spark_link_cp)
  },
  error = print
)

[Session Info 12-12-2020.txt](https://github.com/sparklyr/sparklyr/files/5684165/Session.Info.12-12-2020.txt)

[Glimpse Error Info 12-12-2020.txt](https://github.com/sparklyr/sparklyr/files/5684173/Glimpse.Error.Info.12-12-2020.txt)

**Comment by PinkAppleFlower** [comment]
It might be due to some sort of package conflict that is not just simple masking.  I just loaded only sparklyr, dplyr, and tsbox and was able to use glimpse.

**Comment by yitao-li** [comment]
@PinkAppleFlower I was able to run `dplyr::glimpse()` on a spark dataframe with `sparklyr` 1.5.2, and there was no `sparklyr`-related change I'm aware of that could break this.

I noticed there is an Arrow-related error in the stack trace you uploaded, so it might be some Arrow-specific problem.

**Comment by yitao-li** [comment]
I wonder what's the schema of the R dataframe you were trying to import to Spark, and what's its schema once it's imported to Spark successfully without using `arrow`.

The latter schema can be printed by running the following:

```
# import the R dataframe
EU_Spark_link_cp <- copy_to(spark_conn, EU_tibl, "EU_Spark_cp", overwrite = TRUE)

# print the schema of the resulting Spark dataframe
EU_Spark_link_cp %>% sdf_schema() %>% print()
```

**Comment by PinkAppleFlower** [comment]
@yitao-li Here is the output from the code you asked for me to run:

$id
$id$name
[1] "id"

$id$type
[1] "StringType"


$time
$time$name
[1] "time"

$time$type
[1] "TimestampType"


$value
$value$name
[1] "value"

$value$type
[1] "DoubleType"

So you think the error wasn't due to the glimpse() function interacting with arrow, but instead was due to the fact that copy_to() function didn't work with arrow loaded?

**Comment by yitao-li** [comment]
@PinkAppleFlower Yes correct. The error appears to be entirely caused by `arrow` being unable to collect some data from Spark to R and is unrelated to `dplyr` stuff.

**Comment by PinkAppleFlower** [comment]
@yitao-li where in the stack trace are you seeing that the error is entirely related to arrow being unable to collect some data from Spark?  Could you highlight so I can possibly bring this to the attention of the arrow team and confirm it is not a sparklyr issue and close?

**Comment by yitao-li** [comment]
@PinkAppleFlower It's near the top of the stack trace you included in "Glimpse Error Info ... .txt" in the issue description

org.apache.spark.sql.vectorized.ArrowColumnVector.<init>(ArrowColumnVector.java:174)
	at sparklyr.ArrowConvertersImpl$$anon$3.$anonfun$nextBatch$1(arrowconverters.scala:212)

**Comment by PinkAppleFlower** [comment]
Okay. Closing this issue.
