### ISSUE TITLE
New idea for spark_apply function

### ISSUE THREAD

**Issue by sbottelli** [sparklyr/sparklyr#2871]
Dear sparklyr develop group,
I'm thinking about the possibility to modify the spark_apply function by making it more dynamic.
Maybe could be useful to insert a parameter that manage "max_records_per_batch" that I think is very important because is case-specific.
Now you can manage it through two ways:

- in the config session: through "spark.sql.execution.arrow.maxRecordsPerBatch"
- default of spark_apply

What about to substitute the deafult number inside spark_apply with a parameter that a user can define?
Let me know and thanks for your very great work with new outstanding sparklyr release!

Regards
Stefano

**Comment by yitao-li** [comment]
Sounds like a good idea! I guess it will make a difference when Spark worker nodes have more memory available than driver node does and therefore can have a larger maxRecordsPerBatch.

**Comment by sbottelli** [comment]
Also because results are affected by this value.
If I have to run a computation (let's say a quantile), I need my data serialized on the same batch altough I will find biased results.
It's a simple example but could be also a problem when in a spark_apply situation we have to group_by a certain field an compute same statistics or run some algorithm
