### ISSUE TITLE
Error using sparklyr on a Big Data Appliance

### ISSUE THREAD

**Issue by lucioDeLucaR** [sparklyr/sparklyr#2878]
Hi,

we are using sparklyr on a kerberized Oracle Big Data Appliance cluster from an edge node, but we can't use the two different methods tu submit jobs to spark (yarn-cluster and yarn-client) because we receive an error in both cases. In particular when we try to use the cluster-mode we receive the following error, and it is impossible to establish a connection:

```
Error in spark_yarn_cluster_get_resource_manager_webapp() :
  Failed to find online resource manager under High Availability cluster.
In addition: Warning messages:
1: In value[[3L]](cond) :
  Failed to open bda1node03.ced.it:8090/ws/v1/cluster/info. Error in curl::curl_fetch_memory(url, handle = handle): Failed connect to bda1node03.ced.it:8090; Connection refused
 
2: In value[[3L]](cond) :
  Failed to open bda1node05.ced.it:8090/ws/v1/cluster/info. Error in curl::curl_fetch_memory(url, handle = handle): Failed connect to bda1node05.ced.it:8090; Connection refused
 
3: In doTryCatch(return(expr), name, parentenv, handler) :
  Failed to open bda1node03.ced.it:8088/ws/v1/cluster/info with status 401.
4: In doTryCatch(return(expr), name, parentenv, handler) :
  Failed to open bda1node05.ced.it:8088/ws/v1/cluster/info with status 401.
5: In doTryCatch(return(expr), name, parentenv, handler) :
  Failed to open bda1node03.ced.it:8033/ws/v1/cluster/info with status 404.
6: In doTryCatch(return(expr), name, parentenv, handler) :
  Failed to open bda1node05.ced.it:8033/ws/v1/cluster/info with status 404.
```
  
  
When we use the yarn-client submission we manage to create the connection and start the elaboration, but when we try to collect data to the driver we obtain the following error:
`Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 3.0 failed 4 times, most recent failure: Lost task 1.3 in stage 3.0 (TID 25, bda1node04.ced.it, executor 2): TaskResultLost (result lost from block manager)`

In this case we managed to complete the collect if we strongly limit the data that we are processing.

The cluster uses a CDH 5.14.3 with spark 2.2.0, R 4.0.2 and we are using the last version of sparklyr, the 1.5.1. Can you give us support into understanding what is the problems that we are facing?

We report some of the configurations that we tested in client-mode:
library(tidyverse)
library(sparklyr)
Sys.setenv("SPARK_HOME" = '/opt/cloudera/parcels/SPARK2/lib/spark2')
Sys.setenv("YARN_CONF_DIR" = '/opt/cloudera/parcels/CDH/lib/spark/conf/yarn-conf')
conf <- spark_config()
conf$spark.yarn.keytab <- "pathToKeytab"
conf$spark.yarn.principal <- "PrincipalName"
conf$spark.dynamicAllocation.enabled<-FALSE
conf$spark.dynamicAllocation.minExecutors<-1
conf$spark.dynamicAllocation.maxExecutors<-1
conf$spark.executor.instances<-1
conf$'sparklyr.shell.executor-memory'<- "20g"
conf$'sparklyr.shell.driver-memory'<- "50g"
conf$spark.memory.fraction<- "0.9"
conf$spark.driver.maxResultSize<- 0
conf$sparklyr.verbose<- TRUE
conf$spark.driver.extraJavaOptions <- "append -XX:MaxPermSize=30G"
sc <- spark_connect(master = "yarn-client", config = conf)
an00tb01_t <- tbl(sc, 'dl_023.an00tb01')
an00tb01_df_lim <- sample_n(an00tb01_t, 10000)
an00tb01_df_coll <- an00tb01_df_lim %>% collect()(ERRORE!)
an00tb01_df_lim <- sample_n(an00tb01_t, 10)
an00tb01_df_coll <- an00tb01_df_lim %>% collect()(Funziona!)
an00tb01_df_lim <- sample_n(an00tb01_t, 1000)
an00tb01_df_coll <- an00tb01_df_lim %>% collect()(ERRORE!)
spark_disconnect(sc)

library(tidyverse)
library(sparklyr)
Sys.setenv("SPARK_HOME" = '/opt/cloudera/parcels/SPARK2/lib/spark2')
Sys.setenv("YARN_CONF_DIR" = '/opt/cloudera/parcels/CDH/lib/spark/conf/yarn-conf')
conf <- spark_config()
conf$spark.yarn.keytab <- "pathToKeytab"
conf$spark.yarn.principal <- "PrincipalName"
conf$'sparklyr.shell.executor-memory'<- "20g"
conf$'sparklyr.shell.driver-memory'<- "50g"
conf$spark.memory.fraction<- "0.9"
conf$spark.driver.maxResultSize<- 0
conf$sparklyr.verbose<- TRUE
conf$spark.driver.extraJavaOptions <- "append -XX:MaxPermSize=30G"
sc <- spark_connect(master = "yarn-client", config = conf)
an00tb01_t <- tbl(sc, 'dl_023.an00tb01')
an00tb01_df_lim <- sample_n(an00tb01_t, 10000)
an00tb01_df_coll <- an00tb01_df_lim %>% collect()(ERRORE!)
an00tb01_df_lim <- sample_n(an00tb01_t, 10)
an00tb01_df_coll <- an00tb01_df_lim %>% collect()(Funziona!)
an00tb01_df_lim <- sample_n(an00tb01_t, 1000)
an00tb01_df_coll <- an00tb01_df_lim %>% collect()(ERRORE!)
spark_disconnect(sc)

library(tidyverse)
library(sparklyr)
Sys.setenv("SPARK_HOME" = '/opt/cloudera/parcels/SPARK2/lib/spark2')
Sys.setenv("YARN_CONF_DIR" = '/opt/cloudera/parcels/CDH/lib/spark/conf/yarn-conf')
conf <- spark_config()
conf$spark.submit.deployMode<- "client"
conf$spark.yarn.keytab <- "pathToKeytab"
conf$spark.yarn.principal <- "PrincipalName"
conf$spark.driver.memory <- "30g"
conf$spark.yarn.driver.memoryOverhead <- "5g"
conf$spark.executor.memory <- "10g"
conf$spark.yarn.executor.memoryOverhead <- "2g"
conf$spark.dynamicAllocation.enabled <- TRUE
conf$spark.executor.cores <- 5
conf$spark.port.maxRetries<- 100
conf$'sparklyr.shell.executor-memory'<- "10g"
conf$'sparklyr.shell.driver-memory'<- "30g"
conf$spark.driver.maxResultSize<- 0
conf$spark.master <- "yarn"
conf$sparklyr.verbose<- TRUE
conf$spark.driver.extraJavaOptions <- "append -XX:MaxPermSize=30G"
spark.network.timeout <- 600
sc <- spark_connect(master = "yarn-client", config = conf)
an00tb01_t <- tbl(sc, 'dl_023.an00tb01')
an00tb01_df_lim <- sample_n(an00tb01_t, 10000)
an00tb01_df_coll <- an00tb01_df_lim %>% collect()(ERRORE!)
an00tb01_df_lim <- sample_n(an00tb01_t, 10)
an00tb01_df_coll <- an00tb01_df_lim %>% collect()(Funziona!)
an00tb01_df_lim <- sample_n(an00tb01_t, 1000)
an00tb01_df_coll <- an00tb01_df_lim %>% collect()(ERRORE!)
spark_disconnect(sc)

Thank you,
Lucio

**Comment by yitao-li** [comment]
@lucioDeLucaR I'm not entirely sure how a Oracle Big Data Appliance cluster should be configured, but I know the `Failed to find online resource manager under High Availability cluster.` error is because `sparklyr` tried looking up host:port of each YARN resource manager under `yarn.resourcemanager.webapp.https.address.<resource manager ID>`, `yarn.resourcemanager.webapp.address.<resource manager ID>`, and `yarn.resourcemanager.admin.address.<resource manager ID>`and the lookup failed in all 3 attempts.

Do you think your cluster has the resource manager host:port exported under a different configuration key?

**Comment by lucioDeLucaR** [comment]
Hi,
yes the cluster is configured to use the http and not https, is there a way to force sparklyr into use this protocol?

thanks

**Comment by yitao-li** [comment]
@lucioDeLucaR possibly, but I'm wondering whether you can find any configuration key that contains host:port or address of the resource manager(s) -- at the moment `sparklyr` only tries to perform that lookup under 3 of the known configuration keys I mentioned and gives up if none of them was present.

**Comment by lucioDeLucaR** [comment]
Hi,
the properties you mentioned are configured in a file inside the "YARN_CONF_DIR" that we export before launching the jobs in sparklyr. I report the three properties:
` <property>
    <name>yarn.resourcemanager.admin.address.rm122</name>
    <value>bdanode05.ced.it:8033</value>
  </property>
  <property>
    <name>yarn.resourcemanager.webapp.address.rm122</name>
    <value>bdanode05.ced.it:8088</value>
  </property>
  <property>
    <name>yarn.resourcemanager.webapp.https.address.rm122</name>
    <value>bdanode05.ced.it:8090</value>
  </property>`

Do you find any misconfiguration?

May I ask if you have any suggestion about the client-mode?

Thank you,
Lucio

**Comment by yitao-li** [comment]
@lucioDeLucaR It looks like your cluster's configuration is exactly what `sparklyr` expected so it most likely isn't a config issue.

The only other possible way to get the error message you mentioned is if the resource manager host:port is offline or inaccessible by `sparklyr`, hence failing the `spark_yarn_cluster_resource_manager_is_online()` check (this is a simple check that tries to query the `/ws/v1/cluster/info` endpoint of the resource manager and would emit a warning message if such query fails -- in your R prompt you can just type `sparklyr:::spark_yarn_cluster_resource_manager_is_online` followed by enter to see what that check does, and you can also run it yourself manually for debugging purposes.

Let me know if this helps.

**Comment by lucioDeLucaR** [comment]
Thank you @yitao-li,
we managed to test it but we received the same error that we posted before:
`sparklyr:::spark_yarn_cluster_resource_manager_is_online(rm_webapp = "bdanode05.ced.it:8088")
Warning message:
In value[[3L]](cond) :
 Failed to open bdanode05.ced.it:8090/ws/v1/cluster/info. Error in curl::curl_fetch_memory(url, handle = handle): Failed connect to bdanode05.ced.it:8090; Connection refused
`
Is it possible that because of the fact that  the cluster is configured to use kerberos authentication also on web/http connections it is not possible to simply use curl to interact with it? Is there a way to force sparklyr to use a curl with the option `--negotiate` ?

Thank you,
Lucio

**Comment by yitao-li** [comment]
@lucioDeLucaR I believe you can try setting the authentication option for `httr` with something like the following:

```
httr::set_config(httr::authenticate("<user>", "<password>", type = "gssnegotiate"))  # I'm actually not sure what should be the authentication type here, just guessing -- possible values are ones supported by curl (so, "basic", "digest", "digest_ie", "gssnegotiate", "ntlm", "any")
```
and then try re-running `sparklyr:::spark_yarn_cluster_resource_manager_is_online()` from above.

**Comment by lucioDeLucaR** [comment]
Thank you @yitao-li,

we will try and update you.

What about the client mode, have you ever faced a problem like this?

Thanks,
Lucio

**Comment by yitao-li** [comment]
@lucioDeLucaR I know at the moment sparklyr works fine with a standard EMR 6.x cluster on Amazon EC2 in YARN-client mode. That's all experience I have. You can see the relevant configurations documented in https://github.com/sparklyr/sparklyr/wiki/EMR (don't run `config$`sparklyr.shell.deploy-mode` <- "cluster"` and also replace `master = "yarn-cluster"` with `master = "yarn-client"`). It looks like the Spark cluster you are working with more or less has the same configurations. Let me know how it goes for you.
