### ISSUE TITLE
Unable to specify URL in spark_dependency jars argument

### ISSUE THREAD

**Issue by dkincaid** [sparklyr/sparklyr#2882]
For the [sparknlp](https://github.com/r-spark/sparknlp) extension I am maintaining there is a requirement that a URL is specified when creating the spark session for the `spark.jars` config parameter. (see example here: https://nlp.johnsnowlabs.com/docs/en/licensed_install#start-spark-nlp-for-healthcare-session-from-python)

Inside the package I have a `spark_dependencies()` function that returns a `spark_dependency` object containing packages and jars that need to be included in a spark session when it is created. That function looks something like this:

```r
spark_dependencies <- function(spark_version, scala_version, ...) {
   sparklyr::spark_dependency(jars = c("https://pypi.johnsnowlabs.com/######/spark-nlp-jsl-x.x.x.jar"),
                              packages = c("com.johnsnowlabs.nlp:spark-nlp_2.11:2.7.0"))
}
```
(note that a secret key is actually in the place of the ####### above)

when I try to open a spark connection I get this warning:

```
path[2]="https://pypi.johnsnowlabs.com/#######/spark-nlp-jsl-x.x.x.jar": No such file or directory
Backtrace:
 1. testthat::setup(...) testthat-tokenizer.R:1:0
 3. testthat_spark_connection() testthat-tokenizer.R:2:2
 4. sparklyr::spark_connect(...) helper-initialize.R:42:4
 5. sparklyr:::shell_connection(...)
 6. sparklyr:::start_shell(...)
 7. base::normalizePath(unlist(unique(all_jars)))
 ```

and then an error: `Error: Gateway in localhost:8880 did not respond`

It seems like something inside of sparklyr is assuming that the specification for the `jars` parameter to `spark_dependency` is a local file. 

If I specify this URL in the spark config (using `spark.jars`) when a user creates the spark connection it does work, but since it's a dependency of the sparknlp package the user should not have to do this.

**Comment by yitao-li** [comment]
@dkincaid I'll look into what it takes to add jar URLs as dependencies.

Meanwhile do you think `spark_dependency(packages = c(<maven coordinate strings>)` is more reasonable? E.g., see https://github.com/r-spark/sparklyr.flint/blob/59a8a14ba9bf049e0de1cec3b6581f55f25c0018/R/init.R#L27-L28

**Comment by yitao-li** [comment]
@dkincaid The "no such file or directory" message is a warning, not an error.

I was able to run the following to download a jar file from a https location into a Spark session

```
library(sparklyr)

config <- spark_config()
config$`sparklyr.jars.default` <- "https://github.com/r-spark/sparkwarc/raw/main/inst/java/sparkwarc-3.0-2.12.jar"
sc <- spark_connect(master = "local", config = config)
```

In spark-submit log:

```
21/01/11 15:49:25 INFO SparkContext: Added JAR https://github.com/r-spark/sparkwarc/raw/main/inst/java/sparkwarc-3.0-2.12.jar at https://github.com/r-spark/sparkwarc/raw/main/inst/java/sparkwarc-3.0-2.12.jar with timestamp 1610380165350
```

So the "gateway did not respond" failure is most likely unrelated to the jar URL (unless it was because the spark-submit process could not download that jar file)

**Comment by dkincaid** [comment]
Yes, it does work if specified in the Spark config that's passed to `spark_connect` as I mentioned in my report. The problem is that it is not working if it's specified in the `spark_dependencies()` function of an extension package.

**Comment by yitao-li** [comment]
@dkincaid I repeated the exercise with `sparklyr::spark_dependencies(jar = "https://...")` with a sparklyr extension. It worked for me as well (as in `spark-submit` says it downloaded the same file again).

I think the best way to debug the "gateway did not respond" problem is to run the following interactively:

```
options(sparklyr.log.console = TRUE)
library(sparklyr)
library(sparknlp)

sc <- spark_connect(master = "local", config = ..., version = ...)
```

I can try the same with `sparknlp` as well (assuming the latest version from CRAN is fine unless you say otherwise)

**Comment by dkincaid** [comment]
I can't explain it, but since it worked for you I tried it again myself here in the sparknlp package and today it is working. I don't understand what may have been wrong on Friday when I was working on this. Thank you for taking the time to look at it. I'm sorry I wasted your time today.

**Comment by yitao-li** [comment]
Glad to know everything worked out OK :slightly_smiling_face:
