### ISSUE TITLE
Implement weights in sdf_quantile & ft_quantile_discretizer (feature request)

### ISSUE THREAD

**Issue by Zhuk66** [sparklyr/sparklyr#2915]
Function :            sdf_quantile & ft_quantile_discretizer 
Request  :            both functions do not have weight as a parameter. Due to the prevalence of need for weighted quantile in different model building exercise, this would be an important feature.

**Comment by yitao-li** [comment]
Sounds like a good idea to have this feature. Thanks for the suggestion!! :+1:

**Comment by yitao-li** [comment]
Interesting idea. The non-weighted version of quantile summarization functionality in Spark is based on Greenwald-Khanna algorithm. There is a weighted variant of the same algorithm, but implementing it in a way that will work efficiently with Spark may be non-trivial. IMHO this probably will fit better in the Spark roadmap.
