### ISSUE TITLE
problem with replacing summarise_all() with summarise(across()) in sparklyr

### ISSUE THREAD

**Issue by arashHaratian** [sparklyr/sparklyr#2932]
I've tried to change the `summarise_all()` with `summarise(across())` equivalent in the following code, but I've got an error.

``` r
library(sparklyr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

sc <- spark_connect('local', version = '2.4')
data <- copy_to(sc, mtcars)

# 1st query
data %>%
  mutate(transmission = ifelse(am == 0, "automatic", "manual")) %>%
  group_by(transmission) %>%
  summarise_all(mean)
#> Warning: Missing values are always removed in SQL.
#> Use `mean(x, na.rm = TRUE)` to silence this warning
#> This warning is displayed only once per session.
#> # Source: spark<?> [?? x 12]
#>   transmission   mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>   <chr>        <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1 manual        24.4  5.08  144.  127.  4.05  2.41  17.4 0.538     1  4.38  2.92
#> 2 automatic     17.1  6.95  290.  160.  3.29  3.77  18.2 0.368     0  3.21  2.74

# 2nd query
data %>%
  mutate(transmission = ifelse(am == 0, "automatic", "manual")) %>%
  group_by(transmission) %>%
  summarise(across(.fns = mean))
#> Error: Can't rename variables in this context.
```

<sup>Created on 2021-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yitao-li** [comment]
@arashHaratian The support for summarise(across(...), ...) is in the master branch of sparklyr, but it is has not been published to CRAN yet. Are you running sparklyr 1.5 or some earlier version of sparklyr installed from CRAN?

**Comment by yitao-li** [comment]
Btw you are more than welcome to try `remotes::install_github("sparklyr/sparklyr")` which will install a more cutting-edge version of sparklyr from the main branch of its github repo, and then you should be able to run the summarise(across(...), ...) type of query on Spark dataframes 🙂

**Comment by arashHaratian** [comment]
@yitao-li thanks for your answer.
yes I installed the `sparklyr 1.5.2` from CRAN.

**Comment by arashHaratian** [comment]
should I close this issue?

**Comment by yitao-li** [comment]
@arashHaratian Alright 🙂 I'll leave it up to you whether you want to re-install sparklyr from its current main branch now, or wait until the next CRAN release. Both of those options will get you support for across() on Spark dataframes, and the next CRAN release for sparklyr may be in 1 month or so.

**Comment by arashHaratian** [comment]
thank you again for your response.
