### ISSUE TITLE
Error with spark_install()

### ISSUE THREAD

**Issue by Naeemkh** [sparklyr/sparklyr#2936]
Trying to install sparkly on macOS Catalina. I installed `apache-spark` and `scala` via Homebrew.

```r
library(sparkly)
```
Loads without a problem.

```r
spark_install(version = "2.1.1")
```
Gives the following error. 

```r 
Installing Spark 2.1.1 for Hadoop 2.7 or later.
Downloading from:
- 'https://d3kbcqa49mib13.cloudfront.net/spark-2.1.1-bin-hadoop2.7.tgz'
Installing to:
- '~/spark/spark-2.1.1-bin-hadoop2.7'
trying URL 'https://d3kbcqa49mib13.cloudfront.net/spark-2.1.1-bin-hadoop2.7.tgz'
Content type 'application/x-tar' length 201142612 bytes (191.8 MB)
=================================
downloaded 129.4 MB

Error in download.file(installInfo$packageRemotePath, destfile = installInfo$packageLocalPath,  : 
  download from 'https://d3kbcqa49mib13.cloudfront.net/spark-2.1.1-bin-hadoop2.7.tgz' failed

```

Session info:
─ Session info ────────────────────────────────────
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       macOS Catalina 10.15.7      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Chicago             
 date     2021-02-11                  

─ Packages ────────────────────────────────────────
 package      * version date       lib
 assertthat     0.2.1   2019-03-21 [1]
 base64enc      0.1-3   2015-07-28 [1]
 cachem         1.0.3   2021-02-04 [1]
 callr          3.5.1   2020-10-13 [1]
 cli            2.3.0   2021-01-31 [1]
 config         0.3.1   2020-12-17 [1]
 crayon         1.4.1   2021-02-08 [1]
 DBI            1.1.1   2021-01-15 [1]
 dbplyr         2.1.0   2021-02-03 [1]
 desc           1.2.0   2018-05-01 [1]
 devtools       2.3.2   2020-09-18 [1]
 digest         0.6.27  2020-10-24 [1]
 dplyr          1.0.4   2021-02-02 [1]
 ellipsis       0.3.1   2020-05-15 [1]
 fastmap        1.1.0   2021-01-25 [1]
 forge          0.2.0   2019-02-26 [1]
 fs             1.5.0   2020-07-31 [1]
 generics       0.1.0   2020-10-31 [1]
 glue           1.4.2   2020-08-27 [1]
 htmltools      0.5.1.1 2021-01-22 [1]
 htmlwidgets    1.5.3   2020-12-10 [1]
 httr           1.4.2   2020-07-20 [1]
 jsonlite       1.7.2   2020-12-09 [1]
 lifecycle      0.2.0   2020-03-06 [1]
 magrittr       2.0.1   2020-11-17 [1]
 memoise        2.0.0   2021-01-26 [1]
 nnls           1.4     2012-03-19 [1]
 pillar         1.4.7   2020-11-20 [1]
 pkgbuild       1.2.0   2020-12-15 [1]
 pkgconfig      2.0.3   2019-09-22 [1]
 pkgload        1.1.0   2020-05-29 [1]
 prettyunits    1.1.1   2020-01-24 [1]
 processx       3.4.5   2020-11-30 [1]
 ps             1.5.0   2020-12-05 [1]
 purrr          0.3.4   2020-04-17 [1]
 r2d3           0.2.5   2020-12-18 [1]
 R6             2.5.0   2020-10-28 [1]
 rappdirs       0.3.3   2021-01-31 [1]
 remotes        2.2.0   2020-07-21 [1]
 rlang          0.4.10  2020-12-30 [1]
 rprojroot      2.0.2   2020-11-15 [1]
 rstudioapi     0.13    2020-11-12 [1]
 sessioninfo    1.1.1   2018-11-05 [1]
 sparklyr     * 1.5.2   2020-12-11 [1]
 SuperLearner   2.0-26  2019-12-10 [1]
 testthat       3.0.1   2020-12-17 [1]
 tibble         3.0.6   2021-01-29 [1]
 tidyr          1.1.2   2020-08-27 [1]
 tidyselect     1.1.0   2020-05-11 [1]
 tinytex        0.29    2021-01-21 [1]
 usethis        2.0.0   2020-12-10 [1]
 vctrs          0.3.6   2020-12-17 [1]
 withr          2.4.1   2021-01-26 [1]
 xfun           0.20    2021-01-06 [1]
 yaml           2.2.1   2020-02-01 [1]
 source        
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.3)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)
 CRAN (R 4.0.2)

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

**Comment by yitao-li** [comment]
@Naeemkh Is the download processing failing because of a timeout? You can set the timeout duration to more than the default value of 60 seconds with `options(timeout=100)`.

I suggest try `options(timeout=300)`, and then re-run `spark_install(...)`.

**Comment by Naeemkh** [comment]
Thank you so much, @yitao-li . It resolved the problem.
