### ISSUE TITLE
R interface for GraphFrames README links don't seem to work

### ISSUE THREAD

**Issue by kammitama5** [sparklyr/sparklyr#2945]
Hi, I am going through the "R interface for GraphFrames documentation" [here](https://spark.rstudio.com/graphframes/)
and clicked on the first and second bullets which read:
- Support for GraphFrames which aims to provide the functionality of GraphX.
- Perform graph algorithms like PageRank, ShortestPaths and many others.`
All of these links except GraphX (ie. GraphFrames, PageRank, ShortestPath, others) return a 404.
It looks like the urls just have to be updated (for example, GraphFrames points to [this](https://graphframes.github.io/) when [this](https://graphframes.github.io/graphframes/docs/_site/index.html) is the updated link. I can do that if that's preferable. Thank you!

**Comment by yitao-li** [comment]
Thanks for the feedback.
The links are updated now (see https://github.com/rstudio/spark.rstudio.com/pull/113)
