### ISSUE TITLE
registerDoSpark fails with large objects

### ISSUE THREAD

**Issue by saadaslam** [sparklyr/sparklyr#2959]
Hi, I'm trying to use the distributed R capabilities with `registerDoSpark()` and `tidymodels`. I'm getting success on smaller datasets, but when I use a larger dataset as an example, I end up running into issues.

Here's a reprex, where the process works:

``` r
library(foreach)
library(tidymodels)
#> ── Attaching packages ────────────────────────────────────── tidymodels 0.1.2 ──
#> ✓ broom     0.7.2      ✓ recipes   0.1.15
#> ✓ dials     0.0.9      ✓ rsample   0.0.8 
#> ✓ dplyr     1.0.2      ✓ tibble    3.0.4 
#> ✓ ggplot2   3.3.2      ✓ tidyr     1.1.2 
#> ✓ infer     0.5.3      ✓ tune      0.1.2 
#> ✓ modeldata 0.1.0      ✓ workflows 0.2.1 
#> ✓ parsnip   0.1.4      ✓ yardstick 0.0.7 
#> ✓ purrr     0.3.4
#> ── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::accumulate() masks foreach::accumulate()
#> x purrr::discard()    masks scales::discard()
#> x dplyr::filter()     masks stats::filter()
#> x dplyr::lag()        masks stats::lag()
#> x recipes::step()     masks stats::step()
#> x purrr::when()       masks foreach::when()
library(modeldata)
library(sparklyr)
#> 
#> Attaching package: 'sparklyr'
#> The following object is masked from 'package:purrr':
#> 
#>     invoke

options(
  warn = 2
)

sc <- spark_connect("local")

data(credit_data)

mars_mod <- mars(num_terms = tune(), prod_degree = tune()) %>%
  set_mode("classification") %>%
  set_engine("earth")

wflow <- workflow() %>%
  add_model(mars_mod) %>%
  add_formula(Status ~ .)

wflow_parms <- parameters(wflow) %>%
  update(num_terms = num_terms(c(5, 10)))

metrics <- metric_set(roc_auc, mn_log_loss)

set.seed(22)

grid_for_tuning <- grid_max_entropy(wflow_parms, size = 10)
folds <- credit_data %>%
  tidyr::drop_na() %>%
#  slice_sample(n = 1e7, replace = TRUE) %>%
  vfold_cv(strata = "Status")

registerDoSpark(sc)
tuned <- tune_grid(
  wflow,
  resamples = folds,
  grid = grid_for_tuning,
  metrics = metrics,
  param_info = wflow_parms
  # control = control_grid(
  #   parallel_over = "everything"
  # )
)
```

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

However, when I increase the dataset size to 10 million rows by random sampling with replacement, I get the following warning (which I converted to an error):

```
> library(foreach)

> library(tidymodels)
── Attaching packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidymodels 0.1.2 ──
✓ broom     0.7.2      ✓ recipes   0.1.15
✓ dials     0.0.9      ✓ rsample   0.0.8 
✓ dplyr     1.0.2      ✓ tibble    3.0.4 
✓ ggplot2   3.3.2      ✓ tidyr     1.1.2 
✓ infer     0.5.3      ✓ tune      0.1.2 
✓ modeldata 0.1.0      ✓ workflows 0.2.1 
✓ parsnip   0.1.4      ✓ yardstick 0.0.7 
✓ purrr     0.3.4      
── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidymodels_conflicts() ──
x purrr::accumulate() masks foreach::accumulate()
x purrr::discard()    masks scales::discard()
x dplyr::filter()     masks stats::filter()
x dplyr::lag()        masks stats::lag()
x recipes::step()     masks stats::step()
x purrr::when()       masks foreach::when()

> library(modeldata)

> library(sparklyr)

Attaching package: ‘sparklyr’

The following object is masked from ‘package:purrr’:

    invoke


> options(
+   warn = 2
+ )

> sc <- spark_connect("local")

> data(credit_data)

> mars_mod <- mars(num_terms = tune(), prod_degree = tune()) %>%
+   set_mode("classification") %>%
+   set_engine("earth")

> wflow <- workflow() %>%
+   add_model(mars_mod) %>%
+   add_formula(Status ~ .)

> wflow_parms <- parameters(wflow) %>%
+   update(num_terms = num_terms(c(5, 10)))

> metrics <- metric_set(roc_auc, mn_log_loss)

> set.seed(22)

> grid_for_tuning <- grid_max_entropy(wflow_parms, size = 10)

> folds <- credit_data %>%
+   tidyr::drop_na() %>%
+   slice_sample(n = 1e7, replace = TRUE) %>% ## new line to increase dataset size
+   vfold_cv(strata = "Status")

> registerDoSpark(sc)

> tuned <- tune_grid(
+   wflow,
+   resamples = folds,
+   grid = grid_for_tuning,
+   metrics = metrics,
+   param_info = wflow_parms
+   # control  .... [TRUNCATED] 
Error in writeBin(as.integer(value), con, endian = "big") : 
  (converted from warning) NAs introduced by coercion to integer range
```

Note that if I let the warning occur, the program hangs. I also made edits to `writeInt` so that the integer value isn't converted to an integer when the value is greater than `.Machine$integer.max`, but this doesn't prevent a warning/error in `write_bin_args()` where I get a "problem writing to connection" warning from `writeBin(con, backend)`.  

My guess is this is occurring due to transfer of large objects and environments from R to Spark purely based off of the fact that the program works just fine when the dataset is smaller. 

Session Info:

```
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] sparklyr_1.5.1   yardstick_0.0.7  workflows_0.2.1  tune_0.1.2       tidyr_1.1.2      tibble_3.0.4     rsample_0.0.8    recipes_0.1.15   purrr_0.3.4      parsnip_0.1.4    modeldata_0.1.0 
[12] infer_0.5.3      ggplot2_3.3.2    dplyr_1.0.2      dials_0.0.9      scales_1.1.1     broom_0.7.2      tidymodels_0.1.2 foreach_1.5.1    shiny_1.5.0     

loaded via a namespace (and not attached):
  [1] colorspace_2.0-0   ellipsis_0.3.1     class_7.3-18       rprojroot_2.0.2    base64enc_0.1-3    fs_1.5.0           rstudioapi_0.13    listenv_0.8.0      furrr_0.2.1        remotes_2.2.0     
 [11] earth_5.3.0        prodlim_2019.11.13 fansi_0.4.1        lubridate_1.7.9.2  codetools_0.2-18   splines_4.0.4      knitr_1.30         config_0.3         pkgload_1.1.0      Formula_1.2-4     
 [21] jsonlite_1.7.1     pROC_1.16.2        dbplyr_2.0.0       compiler_4.0.4     httr_1.4.2         backports_1.2.0    assertthat_0.2.1   Matrix_1.2-18      fastmap_1.0.1      cli_2.2.0         
 [31] later_1.1.0.1      htmltools_0.5.0    prettyunits_1.1.1  tools_4.0.4        gtable_0.3.0       glue_1.4.2         Rcpp_1.0.5         DiceDesign_1.8-1   vctrs_0.3.5        iterators_1.0.13  
 [41] timeDate_3043.102  gower_0.2.2        xfun_0.19          globals_0.14.0     ps_1.4.0           testthat_3.0.0     mime_0.9           miniUI_0.1.1.1     lifecycle_0.2.0    devtools_2.3.2    
 [51] future_1.20.1      MASS_7.3-53.1      ipred_0.9-9        promises_1.1.1     parallel_4.0.4     yaml_2.2.1         memoise_1.1.0      forge_0.2.0        TeachingDemos_2.12 rpart_4.1-15      
 [61] desc_1.2.0         plotrix_3.7-8      lhs_1.1.1          pkgbuild_1.1.0     lava_1.6.8.1       rlang_0.4.9        pkgconfig_2.0.3    evaluate_0.14      lattice_0.20-41    htmlwidgets_1.5.2 
 [71] processx_3.4.5     tidyselect_1.1.0   parallelly_1.21.0  plyr_1.8.6         magrittr_2.0.1     R6_2.5.0           generics_0.1.0     DBI_1.1.0          pillar_1.4.7       whisker_0.4       
 [81] withr_2.3.0        survival_3.2-7     nnet_7.3-14        crayon_1.3.4       uuid_0.1-4         rmarkdown_2.5      usethis_1.6.3      grid_4.0.4         callr_3.5.1        plotmo_3.6.0      
 [91] reprex_0.3.0       digest_0.6.27      xtable_1.8-4       httpuv_1.5.4       r2d3_0.2.3         openssl_1.4.3      GPfit_1.0-8        munsell_0.5.0      askpass_1.1        sessioninfo_1.1.1 
```

**Comment by yitao-li** [comment]
@saadaslam I'm wondering whether enabling `arrow` serialization could help (see https://spark.rstudio.com/guides/arrow)

Also it looks like training data is never copied from R to Spark in this case, correct? The workload is simply distributed to Spark workers, each of which launches its own R process to work on its own share of the hyper parameter tunning tasks.

**Comment by saadaslam** [comment]
@yitao-li i did some debugging and found that the environment that R transfers over with `registerDoSpark` via `spark_apply` is really large. For my example above, the environment took about 11GBs of memory and it contains the `rsample` object created by `vfold_cv`. So in a way, the training dataset is copied over, but in the form of the V-fold cross validation object. 

I too wonder if `arrow` serialization helps, but I'm guessing no because it seems that `arrow` serialization is disabled for data frames with list-columns, which is what the `rsample` object is.

**Comment by yitao-li** [comment]
@saadaslam `sparklyr` may be able to handle byte buffers having more than (2^31 - 1) elements (see https://stat.ethz.ch/R-manual/R-patched/library/base/html/LongVectors.html) but it looks like that requires changes in several places:
- `writeBin()` can only write (2^31 - 1) elements in a single call, so in some `sparklyr` serialization routines a single `writeBin()` call may need to be replaced with multiple ones for long vector of bytes
- One Scala `Array[Byte]` can only store up to `2^31 - 1`bytes, so in some places in `sparklyr`'s Scala code base `Array[Byte]` will need to be replaced with `Array[Array[Byte]]`. So, one extra level of indirection. Yay!

Anyhow, I'll keep you posted.

**Comment by saadaslam** [comment]
@yitao-li thanks! Let me know if there's anything I can do to help with testing. 

In terms of serialization, do you know if its possible to use alternative serialization libraries to consider (e.g. `qs`)? I'm not too educated on this topic, so apologies if it seems like I'm suggesting something that seems out of left-field.

**Comment by yitao-li** [comment]
@saadaslam `sparklyr` currently only supports RDS format when it comes to serializing / unserializing R closures for `spark_apply()`, but modifying `spark_apply()` to add an option for alternative serialization format such as `qs` sounds like a good idea (although to make it actually work, `qs` will need to be installed on the driver node and also on all Spark worker nodes).

**Comment by saadaslam** [comment]
@yitao-li  sounds good. Given that it seems like a separate topic than this, I will create a new FR issue. Thanks!

**Comment by saadaslam** [comment]
> @saadaslam `sparklyr` may be able to handle byte buffers having more than (2^31 - 1) elements (see https://stat.ethz.ch/R-manual/R-patched/library/base/html/LongVectors.html) but it looks like that requires changes in several places:
> 
> * `writeBin()` can only write (2^31 - 1) elements in a single call, so in some `sparklyr` serialization routines a single `writeBin()` call may need to be replaced with multiple ones for long vector of bytes
> * One Scala `Array[Byte]` can only store up to `2^31 - 1`bytes, so in some places in `sparklyr`'s Scala code base `Array[Byte]` will need to be replaced with `Array[Array[Byte]]`. So, one extra level of indirection. Yay!
> 
> Anyhow, I'll keep you posted.

@yitao-li  were you able to make the changes described above? I'd be happy to test out for you.
