### ISSUE TITLE
Different behaviour by using dplyr compute with the new version of sparklyr 

### ISSUE THREAD

**Issue by sbottelli** [sparklyr/sparklyr#2969]
Hi team!
I downloaded the new version of the sparklyr package and tried to run a mini-test on a simple dataset.
By using a simple "compute" in order to cache the results, I obtain this error that never results in previous occasions.

x <- copy_to (sc, x, "x")
x <- x %>% dplyr::select (-y) %>% compute("x")

The error is:
Errore: org.apache.spark.sql.catalyst.analysis.TempTableAlreadyExistsException: Temporary view 'x' already exists;

How can I resolve that? Because this issue creates conflict with previous versions of scripts.
As my concern I think that the last version of dplyr (1.0.5) modifies the behaviour of the compute command. 

Thanks for your great support!

Regards
Stefano

**Comment by yitao-li** [comment]
@sbottelli Hey I'm not entirely sure why there is inconsistency in error reporting, but I think the error is expected because `x <- copy_to (sc, x, "x")` already creates a temp view named "x", so the result of any subsequent query based on `x` will need to be stored in a temp view with a different name.

**Comment by yitao-li** [comment]
@sbottelli Which version of sparklyr are you running? The recently released sparklyr 1.6 was built to utilize dbplyr 2.0 backend if it is available. I don't know whether that could be related to what you were seeing.

**Comment by sbottelli** [comment]
First of all , thanks for the kind reply!
I'm using dplyr 1.5.0 and sparklyr 1.6.0.
I tried with dplyr 1.3.0 and sparklyr 1.5.2 and this code run without errors. The expected results is the same table x overwrited with one column less (-y).
Also trying sparklyr 1.6.0 with dplyr  1.3.0 or 1.5.0 gave the same error.
I hope that this could be of help!
Best regards
Stefano

**Comment by yitao-li** [comment]
@sbottelli That was indeed a bug. Thanks for spotting it so quickly!
It should be addressed after we merge https://github.com/sparklyr/sparklyr/pull/2970

**Comment by sbottelli** [comment]
It's a pleasure! Thanks for your hard work!
Regards
Stefano
