### ISSUE TITLE
`tidyr::fill()` should respect ordering of the input

### ISSUE THREAD

**Issue by yitao-li** [sparklyr/sparklyr#2990]

**Comment by mzorko** [comment]
Also, looks like that

` data %>% dplyr::mutate(VAR = dbplyr::win_over(`
 `expr = dplyr::sql("first(VAR, true)"), partition = "ID", order = "DATE", frame = c(0, Inf), con = sc))`


is much, much faster for some reason than

`data %>% group_by(ID) %>% arrange(DATE) %>% sparklyr::fill(VAR, .direction = "up")`

**Comment by yitao-li** [comment]
@mzorko I know what you mean, but with the current inner workings of `dplyr`, I'm not entirely sure whether there is any simple and maintainable way to take the 'order by' operation out of the input query and "move" it into the window spec generated by `tidyr::fill()`. So, we end up with the same 'order by' clause in two places : /

Assuming there is some way to "move" the 'order by' clause from input to the `tidyr::fill()` window spec, then the resulting query would have been precisely the faster version you had.

Suggestions are welcome.

**Comment by yitao-li** [comment]
Hmm actually I guess I can at least simplify away any outer `op_arrange()` in the input. Not sure if that covers all the cases though.

**Comment by yitao-li** [comment]
@mzorko Apparently https://github.com/sparklyr/sparklyr/pull/2989/commits/778d60cf55d2025a382884ba9fe02b4cf773e02a would perform that simplification (well, at least for the simple case we are aware of so far).

I kind of expected the query optimizer in Spark to do such simplifications though, but I guess based on what you saw that's not the case.
