### ISSUE TITLE
spark_install() error on MacOS: cannot open URL

### ISSUE THREAD

**Issue by cornejom** [sparklyr/sparklyr#2991]
Similar to closed issue #2003, except on MacOS rather than Windows.

```
> install.packages("sparklyr")
<Text of progress messages truncated to spare you the details>
The downloaded binary packages are in
	/var/folders/yt/bhvxml_d3fx9v1bj2t6vp7400000gr/T//RtmpFZsFXf/downloaded_packages
> library(sparklyr)
Attaching package: ‘sparklyr’

The following object is masked from ‘package:stats’:

    filter

> spark_install(version = "2.4.7")
Installing Spark 2.4.7 for Hadoop 2.7 or later.
Downloading from:
- 'https://archive.apache.org/dist/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz'
Installing to:
- '~/spark/spark-2.4.7-bin-hadoop2.7'
trying URL 'https://archive.apache.org/dist/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz'
Error in download.file(installInfo$packageRemotePath, destfile = installInfo$packageLocalPath,  : 
  cannot open URL 'https://archive.apache.org/dist/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz' 
```
    
 
I tried the above with several versions and got similar error.  I have proxy settings in my .Renviron file.  I was able to navigate to the URL via browser and downloaded the tgz file, which I was able to install via `spark_install_tar()`.  But it would be more helpful to use `spark_install()`.

Here are the details of my session:
```
> utils::sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_1.6.1

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   magrittr_2.0.1    rappdirs_0.3.3    tidyselect_1.1.0  R6_2.5.0          rlang_0.4.10      fansi_0.4.2      
 [8] httr_1.4.2        dplyr_1.0.5       tools_4.0.4       utf8_1.2.1        DBI_1.1.1         dbplyr_2.1.0      htmltools_0.5.1.1
[15] ellipsis_0.3.1    rprojroot_2.0.2   assertthat_0.2.1  digest_0.6.27     tibble_3.1.0      lifecycle_1.0.0   forge_0.2.0      
[22] crayon_1.4.1      tidyr_1.1.3       purrr_0.3.4       base64enc_0.1-3   htmlwidgets_1.5.3 vctrs_0.3.6       curl_4.3         
[29] glue_1.4.2        compiler_4.0.4    pillar_1.5.1      r2d3_0.2.5        generics_0.1.0    jsonlite_1.7.2    pkgconfig_2.0.3  
```

**Comment by yitao-li** [comment]
@cornejom Hey sorry to hear it.

Both the link (https://archive.apache.org/dist/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz) and `sparklyr::spark_install(version = "2.4.7")` worked fine for me though.

Coud you check your DNS settings and network on your side?

**Comment by yitao-li** [comment]
Also you can try setting `options(download.file.method = <method>` in your R env, where `<method>` could be "internal", "libcurl", "wget", "curl", or "auto". Any one of them should work, really, under normal circumstances, but I guess it may be worth trying.

**Comment by cornejom** [comment]
@yitao-li  Thanks for the suggestions.  Unfortunately, I don't know how to tell if something is wrong with network or DNS settings unless it was as obvious as the network being down.

The error shown in my post is applicable for `options(download.file.method = 'libcurl')`.  Got same results for 'auto' as well.  Other options did not work.  Below are the associated error messages.
```
> options(download.file.method = 'internal')
> spark_install(version = "2.4.7")
<Some output truncated for brevity>
Error in download.file(installInfo$packageRemotePath, destfile = installInfo$packageLocalPath,  : 
  scheme not supported in URL 'https://archive.apache.org/dist/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz'
```

```
> options(download.file.method = 'wget')
> spark_install(version = "2.4.7")
<Some output truncated for brevity>
sh: wget: command not found
Error in download.file(installInfo$packageRemotePath, destfile = installInfo$packageLocalPath,  : 
  'wget' call had nonzero exit status
```

```
> options(download.file.method = 'curl')
> spark_install(version = "2.4.7")
<Some output truncated for brevity>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  
  0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0curl: (56) Received HTTP code 503 from proxy after CONNECT
Error in download.file(installInfo$packageRemotePath, destfile = installInfo$packageLocalPath,  : 
  'curl' call had nonzero exit status
```

**Comment by yitao-li** [comment]
@cornejom The error says your system does not support `https`. You will need to reconfigure `curl` or `wget` to support https for `sparklyr::spark_install()` to work.

Alternatively, copy the https://archive.apache.org/dist/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz link in your browser, download the archive manually, and then unpack the tgz file in `~/spark`. This is effectively what `sparklyr::spark_install()` does anyways.

**Comment by cornejom** [comment]
@yitao-li  Thanks for the alternate suggestion.  
For sake of thoroughness, I eliminated proxy settings in _.Renviron_ and while disconnected from usual VPN I tried the install.  The message seems to imply that the gzipped tar file was partially downloaded before failure.  Strange.

```
> options(download.file.method = 'auto')
> spark_install(version = "2.4.7")
Installing Spark 2.4.7 for Hadoop 2.7 or later.
Downloading from:
- 'https://archive.apache.org/dist/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz'
Installing to:
- '~/spark/spark-2.4.7-bin-hadoop2.7'
trying URL 'https://archive.apache.org/dist/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz'
Content type 'application/x-gzip' length 233333392 bytes (222.5 MB)
=========
downloaded 41.2 MB

Error in download.file(installInfo$packageRemotePath, destfile = installInfo$packageLocalPath,  : 
  download from 'https://archive.apache.org/dist/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz' failed
```

**Comment by yitao-li** [comment]
@cornejom Alright we are making progress :slightly_smiling_face: now try `options(timeout=300)` (or even larger than 300) -- the default timeout for `download.file()` is 60 seconds and your output says only 41.2 MB of the archive was downloaded within that duration.

**Comment by cornejom** [comment]
@yitao-li Aha!  I changed the timeout to 300 seconds and the install failed again ... with same message ... and within 20 seconds.  Strange.  So I tried again ... and this time it worked.
