### ISSUE TITLE
Computing query results causes attributes to be dropped

### ISSUE THREAD

**Issue by nathaneastwood** [sparklyr/sparklyr#3010]
Let's consider a simple example

```r
sc <- sparklyr::spark_connect(master = "local")
mtcars_spark <- dplyr::copy_to(dest = sc, df = mtcars)

blah <- dplyr::select(mtcars_spark, mpg)                                                                                                                          
attr(blah, "testAttr") <- "hello"                                                                                                                                 
attributes(blah)                                                                                                                                                  
# $names
# [1] "src" "ops"
# $class
# [1] "tbl_spark" "tbl_sql"   "tbl_lazy"  "tbl"      
# $testAttr
# [1] "hello"

blah <- dplyr::compute(blah)                                                                                                                                      
attributes(blah)                                                                                                                                                  
# $names
# [1] "src" "ops"
# $class
# [1] "tbl_spark" "tbl_sql"   "tbl_lazy"  "tbl"
```

When using `dplyr::compute()` on a `tbl_spark` object, for example, it will dispatch to `dbplyr:::compute.tbl_spark()`. I feel like this should maybe have some similar method to `dplyr::dplyr_reconstruct()` to ensure that attributes are not dropped. 

This issue is a copy-pasta of https://github.com/tidyverse/dbplyr/issues/618 which was closed.

**Comment by yitao-li** [comment]
@nathaneastwood The current implementation of `compute.tbl_spark()` is attribute-preserving, as far as I know. Please see below:

```
compute.tbl_spark <- function(x, name = random_table_name(), ...) {
  out <- NextMethod(generic = "compute", object = x, name = name, ...)
  tbl_cache(sc = spark_connection(x), name = name, force = TRUE)

  out
}
``` 

Only the `tbl_cache(...)` step is Spark-specific from the above, but that step does not mess with attributes of `out` at all.

**Comment by nathaneastwood** [comment]
I installed the very latest GitHub version this evening and the above code shows the results I got. I know that when we used dbplyr <= 2.0.0 this did not happen so it seems to be a regression but of course the `compute.tbl_spark()` is new.
