### ISSUE TITLE
Packages delta not working with Spark 3.1.1

### ISSUE THREAD

**Issue by kelnerrr** [sparklyr/sparklyr#3015]
`sc <- spark_connect(method = "databricks", packages = "delta")`

gives

> Error in spark_version_from_home(spark_home) : Error in spark_version_from_home(spark_home) : 
>   Failed to detect version from SPARK_HOME or SPARK_HOME_VERSION. Try passing the spark version explicitly.

`sc <- spark_connect(method = "databricks", version = "3.1.1", packages = "delta")`

> Error in if (version < "2.4.2") stop("Delta Lake requires Spark 2.4.2 or newer") : Error in if (version < "2.4.2") stop("Delta Lake requires Spark 2.4.2 or newer") : 
>   missing value where TRUE/FALSE needed

**Comment by kelnerrr** [comment]
I found that it works when I specify an older Spark version:
`sc <- spark_connect(method = "databricks", version = "3.0", packages = "delta")`

**Comment by yitao-li** [comment]
@kelnerrr Thanks for the feedback. There was a minor change needed to make sparklyr handle unknown Spark versions in a more reasonable manner.
