### ISSUE TITLE
spark_apply extra computation

### ISSUE THREAD

**Issue by andreidore** [sparklyr/sparklyr#3028]
Hi

I have R script with sparklyr

apply<-function(x){
	print(x)
	Sys.sleep(30)
	return(1)
}

sdf_len(sc,100,repartition=100) %>%
    spark_apply(apply,columns=list(id="double"))

When I run in my  spark cluster, I see in the SparkUI the following jobs

Submitted Duration.  Stages.  Task(for all stages)
8:26:17.   |  32 s.      |.  2/2.   |.   101/101
8:25:45.   |  31 s.      |.  1/1.   |.   9/9
8:25:13.   |  31 s.      |.  1/1.   |.   4/4 
8:24:42.   | 31 s.      |.  1/1.     |.  1/1

I don't understand the extra computation at the time: 8:24:42. , 8:25:13. and 8:25:45. 

Do you have any ideas why this extra computation appears?

The version of spark is 2.4.0 and run in Cloudera private cloud

Thanks

**Comment by yitao-li** [comment]
@andreidore You need to specify `memory = TRUE` when invoking `spark_apply()` to cache the computed result in memory. This will avoid re-computation of partitions that are already in cache.
