### ISSUE TITLE
`across()` and `mutate_at()` do not work with Spark's case insensitivity

### ISSUE THREAD

**Issue by nathaneastwood** [sparklyr/sparklyr#3029]
Let's take a look at an example

```r
sc <- sparklyr::spark_connect(master = "local")

mtcars_spark <- dplyr::copy_to(sc, mtcars)

dplyr::mutate(mtcars_spark, meanMpg = mean(MPG))
# # Source: spark<?> [?? x 12]
#      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb meanMpg
#    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>   <dbl>
#  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4    20.1
#  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4    20.1
#  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1    20.1
#  4  21.4     6  258    110  3.08  3.22  19.4     1     0     3     1    20.1
#  5  18.7     8  360    175  3.15  3.44  17.0     0     0     3     2    20.1
#  6  18.1     6  225    105  2.76  3.46  20.2     1     0     3     1    20.1
#  7  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4    20.1
#  8  24.4     4  147.    62  3.69  3.19  20       1     0     4     2    20.1
#  9  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2    20.1
# 10  19.2     6  168.   123  3.92  3.44  18.3     1     0     4     4    20.1
# # … with more rows
```

So this has worked, as expected, since Spark is case insensitive. But if we use `dplyr::mutate_at()` or `dplyr::across()` within a `dplyr::mutate()` context, it fails.

```r
dplyr::mutate_at(mtcars_spark, "MPG", ~mean(.x))
# Error: Can't subset columns that don't exist.
# ✖ Column `MPG` doesn't exist.
# Run `rlang::last_error()` to see where the error occurred.

dplyr::mutate(mtcars_spark, dplyr::across("MPG", ~mean(.x)))
# Error: Can't subset columns that don't exist.
# ✖ Column `MPG` doesn't exist.
# Run `rlang::last_error()` to see where the error occurred.
```

Now, I know what you're thinking - rename the columns. However this is a big pipeline where something out of our control has changed at source. I shouldn't really need to rename the column as Spark is case insensitive but also, doing so would be an additional computation thus making my pipeline slower (even if minimally).

Also, I don't want to rename in the `mutate_at()` call either because it may very well change back and I'd need to change my code again.

**Comment by yitao-li** [comment]
@nathaneastwood The following will work:

```
library(sparklyr)

sc <- spark_connect(master = "local")
mtcars_spark <- copy_to(sc, mtcars)
print(dplyr::mutate(mtcars_spark, dplyr::across(tidyselect::matches("MPG"), mean)))
```

Notice in `tidyselect::matches()`, the `ignore.case` parameter already defaults to `TRUE`, so `tidyselect::matches("MPG")` will perform the case insensitive match you wanted.
Alternatively, you can also explicitly say `tidyselect::matches("MPG", ignore.case = TRUE)`.

**Comment by nathaneastwood** [comment]
Hmm, I think this is a useful work around I could use. The problem is that it doesn't work with `mutate_at()`. For now, we don't want to switch to `across()` so I will have to implement something similar to `dplyr::matches()` within my function that wraps around `mutate_at()`.
