### ISSUE TITLE
`across()` does not produce expected results for formulas

### ISSUE THREAD

**Issue by nathaneastwood** [sparklyr/sparklyr#3036]
Let's consider a simple example

```r
sc <- sparklyr::spark_connect(master = "local")
mtcars <- dplyr::copy_to(sc, mtcars)

# Works as expected:
mtcars %>% mutate(across(matches("mpg"), ~mean, .names = "tmp"))
# # Source: spark<?> [?? x 12]
#      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb   tmp
#    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4  21  
#  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4  21  
#  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1  22.8
# ...

mtcars %>% mutate(across(matches("mpg"), ~mean, .names = "tmp")) %>% dbplyr::sql_render()                                                                           
# <SQL> SELECT `mpg`, `cyl`, `disp`, `hp`, `drat`, `wt`, `qsec`, `vs`, `am`, `gear`, `carb`, element_at(TRANSFORM(array(`mpg`), mean -> `mean`), 1) AS `tmp`
# FROM `mtcars`

# Doesn't work:
mtcars %>% mutate(across(matches("mpg"), ~mean(.x), .names = "tmp"))                                                                                                
# # Source: spark<?> [?? x 12]
#      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb   tmp
#    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#  1  21       6  160    110  3.9   2.62  16.5     0     1     4     4    NA
#  2  21       6  160    110  3.9   2.88  17.0     0     1     4     4    NA
#  3  22.8     4  108     93  3.85  2.32  18.6     1     1     4     1    NA
# ...

mtcars %>% mutate(across(matches("mpg"), ~mean(.x), .names = "tmp")) %>% dbplyr::sql_render()                                                                       
# <SQL> SELECT `mpg`, `cyl`, `disp`, `hp`, `drat`, `wt`, `qsec`, `vs`, `am`, `gear`, `carb`, element_at(TRANSFORM(array(`mpg`), x__6fdce52d_55ee_4975_8c01_e61f09da2737 -> AVG(`x__6fdce52d_55ee_4975_8c01_e61f09da2737`) OVER ()), 1) AS `tmp`
# FROM `mtcars`
```

This makes it difficult to perform more complex operations, e.g. the cumulative product (I'm aware of `sparklyr_cumprod()`, I'm just using this as a silly example).

```r
mtcars %>% mutate(across(matches("mpg"), ~exp(sum(log(.x))), .names = "tmp"))     
```

**Comment by nathaneastwood** [comment]
I _think_ that maybe I misinterpreted the way formulas work in `across()`. I _think_ that you're supposed to use `~mean(.x)` and not `~mean`. So some of the above examples should not be expected to work but should maybe through warnings/errors (as they do in dplyr). However the examples with `~mean(.x)` are still valid.

**Comment by yitao-li** [comment]
@nathaneastwood Re: outcome of `~mean(.x)` -- that's a good question! I think you have found something that makes sense in R but is not supported (yet) in Spark.

Currently the only way I know of for translating an R foruma into its equivalent in Spark SQL is by converting it into a lambda expression, and I don't think aggregation functions such as `avg()` are well-supported inside those lambda expressions.

R formulas transforming an individual value within a row is supported though (e.g., `~ .x^2 + .x + 1` gets translated into `x -> power(x, 2) + x + 1` in Spark SQL and works just fine.

**Comment by yitao-li** [comment]
I haven't looked into how exactly does Spark handle variables inside a lambda expression yet, but my best guess there is the variable "binds" to some specific value in a particular row, rather than an entire column of some Spark dataframe, and aggregate functions such as `avg()` will therefore not work with such variables.

**Comment by nathaneastwood** [comment]
Yeah so the translation

```
element_at(TRANSFORM(array(`mpg`), x__6fdce52d_55ee_4975_8c01_e61f09da2737 -> AVG(`x__6fdce52d_55ee_4975_8c01_e61f09da2737`) OVER ()))
```

doesn't seem to pick up actual values, right? i.e. it isn't seeing `mpg` as data but as a symbol. At least that seems to be what is happening which is why we get `NA`.
