### ISSUE TITLE
Compatibility sparklyr.flint with EMR

### ISSUE THREAD

**Issue by sbottelli** [sparklyr/sparklyr#3042]
Hi team!
I'm exploring the sparklyr.flint extension of sparklyr for using time series native methods on spark. Awesome!
I tried to install it on my local machine and all works perfectly.
On the other hand, when I tried to install it on an EMR machine and I can't work with this package due to this error
```
Error in eval(formal.args[[as.character(substitute(arg))]]) : 
  object '.sparklyr.flint.globals' not found
```
Debugging inside the package, I stated that the problem is related to the init.R script and its relationship with EMR.

In local environment, in background, some jars are installed and usable in spark.
How can I install and use correctly sparklyr.flint on an EMR machine (we use sparklyr 1.6.2)?
Thanks for the support and for your amazing work!

Stefano

**Comment by yitao-li** [comment]
@sbottelli Was the error because you tried running flint-related functionalities inside `spark_apply()` or similar, and some global constants needed by sparklyr.flint was not part of the closure being run by `spark_apply()`?

**Comment by yitao-li** [comment]
The error message has nothing to do with jar files btw

**Comment by sbottelli** [comment]
Hi! Thanks for the response. 
No, I tried the demo code in the documentation but I got this error

**Comment by yitao-li** [comment]
@sbottelli I just ran through the following example on a EMR 6.2.0 cluster. It seems to work just fine:

```
library(sparklyr)
library(sparklyr.flint)

sc <- spark_connect(master = "yarn", spark_home = "/usr/lib/spark")
df <- tibble::tibble(
  t = c(1, 3, 4, 6, 7, 10, 15, 16, 18, 19),
  v = c(4, -2, NA, 5, NA, 1, -4, 5, NA, 3)
)
sdf <- copy_to(sc, df, overwrite = TRUE)
ts_rdd <- fromSDF(sdf, is_sorted = TRUE, time_unit = "SECONDS", time_column = "t")
ts_count <- summarize_count(ts_rdd, window = in_past("3s"))
print(ts_count %>% collect())
```

**Comment by yitao-li** [comment]
Which version of EMR were you running and mind posting the example code you tried to run?

**Comment by sbottelli** [comment]
The version is 5.29.
The code is:

**Comment by yitao-li** [comment]
@sbottelli I don't see reason why it shouldn't work if package installation succeeded (regardless of during bootstrap phase or not)

**Comment by yitao-li** [comment]
@sbottelli I think there is one limitation though: the sparklyr.flint package must be attached before sc <- spark_connect(...)

Do you think that may explain the error?

**Comment by yitao-li** [comment]
If all else fails, consider running the following manually:

```
.sparklyr.flint.globals <- new.env(parent = emptyenv())

  constants <- list(
    kValidTimeUnits = c(
      "DAYS",
      "HOURS",
      "MINUTES",
      "SECONDS",
      "MILLISECONDS",
      "MICROSECONDS",
      "NANOSECONDS"
    ),
    kDefaultTimeColumn = "time"
  )
  for (x in names(constants)) {
    .sparklyr.flint.globals[[x]] <- constants[[x]]
    lockBinding(sym = x, env = .sparklyr.flint.globals)
  }
```

(of course that's not ideal at all and let's avoid this if possible)

**Comment by sbottelli** [comment]
Thanks for the answers!
I attached the package before calling the spark_connect.
Maybe I can try this solution and see if it runs.
Thanks for the support, I'll let you know!

**Comment by sbottelli** [comment]
Hi @yitao-li!
Just to return with a feedback on the solution. The solution that you gave me works! I have to modify the "init" like you posted in order to run sparklyr.flint.
Thanks for the precious help!
Stefano
