### ISSUE TITLE
spark_read_csv incorrectly read csv with long string characters

### ISSUE THREAD

**Issue by Vanderser** [sparklyr/sparklyr#3052]
I am using this dataset to reproduce the issues:
https://drive.google.com/file/d/1tH5dYyMEfCZhjtwjourbR3wqBfleJ7DS/view?usp=sharing

So, I had to read this via Spark and Base R to do comparisons, I am using this snippets to read the csv:

```
spark_read_data <- function(format="csv", filename=""){
  if(format=="csv"){
    csv <- spark_read_csv(spark_conn, name=filename, path=file.choose())
    writeLines("Spark DataFrame Dimensions")
    x <- c(sdf_nrow(csv), sdf_ncol(csv))
    print(x)
    return(csv)
  }
  else if(format=="json"){
    json <- spark_read_json(spark_conn, name=filename, path=file.choose())
    writeLines("Spark DataFrame Dimensions")
    x <- c(sdf_nrow(json), sdf_ncol(json))
    print(x)
    return(json)
  }
  else if(format=="parquet"){
    parquet <- spark_read_parquet(spark_conn, name=filename, path=file.choose())
    writeLines("Spark DataFrame Dimensions")
    x <- c(sdf_nrow(parquet), sdf_ncol(parquet))
    print(x)
    return(parquet)
  }
}
```

# then I do read with both ways
```
review_airbnb_df <- read.csv(file.choose())
review_airbnb_spark <- spark_read_data(filename="review_airbnb_spark")
```

I found out that spark fail to read this since the comments text are way too long and then somehow collapsed into a new row, but the Base R read it perfectly fine. Is this issues also from Spark core itself? or are there some parameters in `spark_read_csv `that i need to set? 

Thanks in Advance :)

**Comment by yitao-li** [comment]
@Vanderser I was able to load the csv file successfully using `sparklyr::spark_read_csv()` with Spark 3.0 and sparklyr 1.6.2. The issue you ran into may be specific to some older version of Spark.

**Comment by Vanderser** [comment]
@yitao-li Strange.. I have newer Spark version of 3.1.1 and also Sparklyr version 1.6.2

```
print(spark_version(sc=spark_conn))
[1] ‘3.1.1’
```

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
system code page: 932

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_1.6.2
``` 
Here is Screenshot of the data imported by sprk_read_csv() in my local

https://ibb.co/mTPk3k8

**Comment by Vanderser** [comment]
@yitao-li Sorry I think its a little wrong for me to state that spark failed to read the data, instead spark successfully read the file but just incorrectly read that long string column

**Comment by yitao-li** [comment]
This seems to be a Spark issue. There is not much we can do in `sparklyr` to work around it unfortunately.
