### ISSUE TITLE
release sparklyr 1.7

### ISSUE THREAD

**Issue by yitao-li** [sparklyr/sparklyr#3060]

**Comment by lresende** [comment]
@yitao-li do you have an ETA for 1.7? We are waiting for a couple of fixes that will come on that release, and if it's not going to take more than a couple of days we could wait, otherwise, I might suggest a 1.6.4 with cherry-picked fixes.

**Comment by yitao-li** [comment]
@lresende I'm aiming for by the end of next Monday.

**Comment by yitao-li** [comment]
The source package of sparklyr 1.7 is now available on CRAN.
