### ISSUE TITLE
Sparklyr doesn´t work

### ISSUE THREAD

**Issue by fcobolanos** [sparklyr/sparklyr#3143]
I am new to Sparklyr, I am trying to load it, but I get the following error

![124234921-462cd100-dada-11eb-84ed-ca4ca4b3f871](https://user-images.githubusercontent.com/49967266/124361481-10303f80-dbf5-11eb-9d44-213d1be5a374.png)
I read that this could be of the missing winutils.exe file , but I don´t understand what exactly I have to do.

Thank you for your advice

**Comment by yitao-li** [comment]
@fcobolanos You need to download and install winutils (see https://github.com/steveloughran/winutils) and copy the winutils.exe binary to spark-2.4..../tmp/hadoop/bin/

Also see answers from https://stackoverflow.com/questions/25481325/how-to-set-up-spark-on-windows that mention winutils. Hopefully those will be helpful for you.

**Comment by fcobolanos** [comment]
Thank you, but I still I am having the same error.


![error_sparklyr](https://user-images.githubusercontent.com/49967266/124699590-b196ea00-deb0-11eb-9972-7e0d1e3badda.PNG)

I double check and the winutils file is already on the bin folder

**Comment by yitao-li** [comment]
@fcobolanos Is the binary in **C:\...\spark-2.10-bin-hadoop2.7\tmp\hadoop\bin\winutils.exe** as the error message suggested? It is unlikely that the executable is in fact in that location but the `system2()` call from R complains it is not there.
