### ISSUE TITLE
compute() fails

### ISSUE THREAD

**Issue by Zhuk66** [sparklyr/sparklyr#3148]
# Reporting an Issue with sparklyr

The following code fails with an error: Error in strsplit(y, "\\.")[[1]] : subscript out of bounds

 library(dplyr)
 library(sparklyr)
 
 conf <- spark_config()
 conf$`sparklyr.cores.local` <- 2
 conf$sparklyr.connect.cores.local <- 2
 conf$`sparklyr.shell.driver-memory` <- "1G"
 conf$spark.memory.fraction <- 0.9
 
 sc <- spark_connect(master = "local",  config = conf)
 
 copy_to(sc, tibble(letters = sample(letters, 50, replace = T),  numbers = sample(1:100, 50)), 'local_table') 
 
 orderedTable <- tbl(sc, 'local_table') %>%  arrange(letters) %>%  compute(name = 'orderedTable')

Error in strsplit(y, "\\.")[[1]] : subscript out of bounds
8: (function () 
   traceback(2))()
7: tbl_quote_name(sc, name)
6: paste("CACHE TABLE", tbl_quote_name(sc, name))
5: tbl_cache_sql(sc, name, force)
4: tbl_cache(sc = spark_connection(x), name = as.character(remote_name), 
       force = TRUE)
3: compute.tbl_spark(., name = "orderedTable")
2: compute(., name = "orderedTable")
1: tbl(sc, "local_table") %>% arrange(letters) %>% compute(name = "orderedTable")
> 

We use MRO 4.0.2.

**Comment by yitao-li** [comment]
I think this error will only happen to `dplyr` queries that have `op_order` as one of the lazy ops. It should be easy to fix.

**Comment by yitao-li** [comment]
Note to myself: this had to do with some (at least from my point of view) slightly counterintuitive stuff related to https://github.com/tidyverse/dbplyr/pull/649

**Comment by yitao-li** [comment]
@Zhuk66 You can run `remotes::install_github("yitao-li/sparklyr", ref = "bugfix/sdf-remote-name-for-op-order")` to install a version of `sparklyr` that is free from this problem.

**Comment by Zhuk66** [comment]
I installed "bugfix/sdf-remote-name-for-op-order", but still getting the same error. Can you verify please that the code above runs? We are using SPARK 2.4.4

Error in strsplit(y, "\\.")[[1]] : subscript out of bounds
8: (function () 
   traceback(2))()
7: tbl_quote_name(sc, name)
6: paste("CACHE TABLE", tbl_quote_name(sc, name))
5: tbl_cache_sql(sc, name, force)
4: tbl_cache(sc = spark_connection(x), name = as.character(remote_name), 
       force = TRUE)
3: compute.tbl_spark(., name = "orderedTable")
2: compute(., name = "orderedTable")
1: tbl(sc, "local_table") %>% arrange(letters) %>% compute(name = "orderedTable")

**Comment by yitao-li** [comment]
@Zhuk66 Ok I'll take a look asap. Meanwhile quick question: did you restart your R session after remotes::install?

**Comment by yitao-li** [comment]
Also please let me know your dbplyr version (as dbplyr is actually a key piece of this puzzle).

**Comment by Zhuk66** [comment]
1. Yes I bounced the session.
2. > packageVersion('dbplyr')
[1] ‘2.1.1’
>

**Comment by Zhuk66** [comment]
My bad. Sorry. I found a duplicate 'sparklyr'. Your change works. Sorry about that.

**Comment by Zhuk66** [comment]
... and thank you for a quick response!!!
