### ISSUE TITLE
ERROR RBackend: Server shutting down: failed with exception  java.io.FileNotFoundException

### ISSUE THREAD

**Issue by amansahni1** [sparklyr/sparklyr#3159]
# Reporting an Issue with sparklyr

Hi Team,

I am facing an issue intermittently (5 sessions out of 300 fails )  All I am running is 
library(SparkR)
ss <- SparkR::sparkR.session(enableHiveSupport = FALSE)

I am getting the below error.

ERROR:
Attaching package: ‘SparkR’

The following objects are masked from ‘package:dplyr’:

    arrange, between, coalesce, collect, contains, count, cume_dist,
    dense_rank, desc, distinct, explain, expr, filter, first, group_by,
    intersect, lag, last, lead, mutate, n, n_distinct, ntile,
    percent_rank, rename, row_number, sample_frac, select, slice, sql,
    summarize, union

The following objects are masked from ‘package:plyr’:

    arrange, count, desc, join, mutate, rename, summarize, take

The following object is masked from ‘package:AdvancedAnalytics’:

    countDistinct

The following objects are masked from ‘package:xgboost’:

    predict, slice

The following objects are masked from ‘package:data.table’:

    between, first, hour, last, like, minute, month, quarter, second,
    tables, year

The following objects are masked from ‘package:stats’:

    cov, filter, lag, na.omit, predict, sd, var, window

The following objects are masked from ‘package:base’:

    as.data.frame, colnames, colnames<-, drop, endsWith, intersect,
    rank, rbind, sample, startsWith, subset, summary, transform, union

Spark package found in SPARK_HOME: /usr/local/lib/python3.6/site-packages/pyspark
21/08/02 09:50:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
21/08/02 09:50:18 ERROR RBackend: Server shutting down: failed with exception 
java.io.FileNotFoundException: /proj/analytics/tmp/Rtmp2tauQs/backend_portb4b7e900971.tmp (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.apache.spark.api.r.RBackend$.main(RBackend.scala:138)
	at org.apache.spark.api.r.RBackend.main(RBackend.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

I am unsure why it failing to access the Temp file. When I checked manually, the file did not exist. Isn't it should be able to create the file on its own. I think it's creation is handled by sparkR itself.

Following are the versions I am using

**"sparklyr","0.8.5.2"
"rsparkling","0.2.3"
R - 3.4.3**

spark-defaults.conf looks like below

spark.driver.memory=4g
spark.driver.maxResultSize=4g
spark.r.backendConnectionTimeout=600000
spark.sql.extensions au.com.coles.udfs.UdfExtensions

**Default R temp directory as set up in R profile is below:**

/proj/analytics/tmp'

Can someone help please.

Its intermittent and hard to reproduce. It just happens randomly in production

**Comment by amansahni1** [comment]
**> utils::sessionInfo()**
R version 3.4.3 (2017-11-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] graphics  grDevices datasets  stats     utils     methods   base     

other attached packages:
 [1] SparkR_2.4.4             readi_0.1.14.1           sparklyr_0.8.5.2         readr_1.1.1             
 [5] dplyr_0.7.4              plyr_1.8.4               ggplot2_2.2.1            AdvancedAnalytics_0.49.1
 [9] xgboost_0.4-4            data.table_1.10.4       

loaded via a namespace (and not attached):
 [1] httr_1.2.1         tidyr_0.7.0        jsonlite_1.5       splines_3.4.3      foreach_1.4.3     
 [6] shiny_1.0.5        assertthat_0.2.0   stats4_3.4.3       yaml_2.1.14        pillar_1.2.1      
[11] backports_1.1.0    lattice_0.20-35    quantreg_5.33      glue_1.2.0         digest_0.6.12     
[16] RColorBrewer_1.1-2 checkmate_1.8.3    minqa_1.2.4        colorspace_1.3-2   htmltools_0.3.6   
[21] httpuv_1.3.5       Matrix_1.2-12      psych_1.7.8        pkgconfig_2.0.1    broom_0.4.2       
[26] SparseM_1.77       caret_6.0-76       purrr_0.2.4        xtable_1.8-2       scales_0.5.0      
[31] lme4_1.1-13        MatrixModels_0.4-1 tibble_1.4.2       mgcv_1.8-22        car_2.1-5         
[36] nnet_7.3-12        lazyeval_0.2.1     pbkrtest_0.4-7     mnormt_1.5-5       magrittr_1.5      
[41] mime_0.5           evaluate_0.10.1    lightgbm_2.1.0     doParallel_1.0.11  nlme_3.1-131      
[46] MASS_7.3-47        foreign_0.8-69     FNN_1.1            tools_3.4.3        hms_0.3           
[51] stringr_1.2.0      munsell_0.4.3      packrat_0.4.8-1    bindrcpp_0.2       compiler_3.4.3    
[56] rlang_0.2.0        aaDevOps_0.2.13    grid_3.4.3         nloptr_1.0.4       iterators_1.0.8   
[61] rstudioapi_0.7     rmarkdown_1.10     base64enc_0.1-3    gtable_0.2.0       ModelMetrics_1.1.0
[66] codetools_0.2-15   DBI_1.1.0          reshape2_1.4.2     R6_2.2.2           ROracle_1.3-1     
[71] gridExtra_2.2.1    lubridate_1.6.0    knitr_1.20         RJDBC_0.2-5        bindr_0.1         
[76] rprojroot_1.2      rJava_0.9-8        stringi_1.1.5      parallel_3.4.3     Rcpp_0.12.13      
[81] dbplyr_1.2.1 





**> devtools::session_info()**
 Session info -------------------------------------------------------------------------------------------------------  setting  value                         version  R version 3.4.3 (2017-11-30)  system   x86_64, linux-gnu             ui       RStudio (1.3.938.2)           language (EN)                          collate  en_US.UTF-8                   tz       Australia/Melbourne           date     2021-08-02                    Packages -----------------------------------------------------------------------------------------------------------  package           * version  date       source            aaDevOps            0.2.13   2021-05-05 local             AdvancedAnalytics * 0.49.1   2021-07-28 local (@NA)       assertthat          0.2.0    2017-04-11 CRAN (R 3.4.3)    backports           1.1.0    2017-05-22 url               base              * 3.4.3    2017-11-30 local             base64enc           0.1-3    2015-07-28 CRAN (R 3.4.3)    bindr               0.1      2016-11-13 url               bindrcpp            0.2      2017-06-17 url               broom               0.4.2    2017-02-13 url               car                 2.1-5    2017-07-04 url               caret               6.0-76   2017-04-18 url               checkmate           1.8.3    2017-07-03 url               codetools           0.2-15   2016-10-05 CRAN (R 3.4.3)    colorspace          1.3-2    2016-12-14 CRAN (R 3.4.3)    compiler            3.4.3    2017-11-30 local             data.table        * 1.10.4   2017-02-01 url               datasets          * 3.4.3    2017-11-30 local             DBI                 1.1.0    2019-12-15 CRAN (R 3.4.3)    dbplyr              1.2.1    2018-02-19 url               devtools            1.13.3   2017-08-02 url               digest              0.6.12   2017-01-27 url               doParallel          1.0.11   2017-09-28 CRAN (R 3.4.3)    dplyr             * 0.7.4    2017-09-28 url               evaluate            0.10.1   2017-06-24 url               FNN                 1.1      2013-07-31 url               foreach             1.4.3    2015-10-13 url               foreign             0.8-69   2017-06-22 CRAN (R 3.4.3)    ggplot2           * 2.2.1    2016-12-30 url               glue                1.2.0    2017-10-29 url               graphics          * 3.4.3    2017-11-30 local             grDevices         * 3.4.3    2017-11-30 local             grid                3.4.3    2017-11-30 local             gridExtra           2.2.1    2016-02-29 url               gtable              0.2.0    2016-02-26 CRAN (R 3.4.3)    hms                 0.3      2016-11-22 url               htmltools           0.3.6    2017-04-28 CRAN (R 3.4.3)    httpuv              1.3.5    2017-07-04 url               httr                1.2.1    2016-07-03 url               iterators           1.0.8    2015-10-13 url               jsonlite            1.5      2017-06-01 CRAN (R 3.4.3)    knitr               1.20     2018-02-20 CRAN (R 3.4.3)    lattice             0.20-35  2017-03-25 CRAN (R 3.4.3)    lazyeval            0.2.1    2017-10-29 CRAN (R 3.4.3)    lightgbm            2.1.0    2018-03-01 local             lme4                1.1-13   2017-04-19 url               lubridate           1.6.0    2016-09-13 url               magrittr            1.5      2014-11-22 CRAN (R 3.4.3)    MASS                7.3-47   2017-02-26 CRAN (R 3.4.3)    Matrix              1.2-12   2017-11-20 CRAN (R 3.4.3)    MatrixModels        0.4-1    2015-08-22 CRAN (R 3.4.3)    memoise             1.1.0    2017-04-21 CRAN (R 3.4.3)    methods           * 3.4.3    2017-11-30 local             mgcv                1.8-22   2017-09-24 CRAN (R 3.4.3)    mime                0.5      2016-07-07 CRAN (R 3.4.3)    minqa               1.2.4    2014-10-09 CRAN (R 3.4.3)    mnormt              1.5-5    2016-10-15 CRAN (R 3.4.3)    ModelMetrics        1.1.0    2016-08-26 url               munsell             0.4.3    2016-02-13 url               nlme                3.1-131  2017-02-06 CRAN (R 3.4.3)    nloptr              1.0.4    2017-08-22 CRAN (R 3.4.3)    nnet                7.3-12   2016-02-02 CRAN (R 3.4.3)    packrat             0.4.8-1  2016-09-07 url               parallel            3.4.3    2017-11-30 local             pbkrtest            0.4-7    2017-03-15 CRAN (R 3.4.3)    pillar              1.2.1    2018-02-27 url               pkgconfig           2.0.1    2017-03-21 url               plyr              * 1.8.4    2016-06-08 CRAN (R 3.4.3)    psych               1.7.8    2017-09-09 url               purrr               0.2.4    2017-10-18 url               quantreg            5.33     2017-04-18 url               R6                  2.2.2    2017-06-17 CRAN (R 3.4.3)    RColorBrewer        1.1-2    2014-12-07 CRAN (R 3.4.3)    Rcpp                0.12.13  2017-09-28 url               readi             * 0.1.14.1 2021-07-29 local (@e86fd58)  readr             * 1.1.1    2017-05-16 CRAN (R 3.4.3)    reshape2            1.4.2    2016-10-22 url               rJava               0.9-8    2016-01-07 url               RJDBC               0.2-5    2014-12-19 url               rlang               0.2.0    2018-02-20 url               rmarkdown           1.10     2018-06-11 CRAN (R 3.4.3)    ROracle             1.3-1    2016-10-26 CRAN (R 3.4.3)    rprojroot           1.2      2017-01-16 url               rstudioapi          0.7      2017-09-07 CRAN (R 3.4.3)    scales              0.5.0    2017-08-24 url               shiny               1.0.5    2017-08-23 CRAN (R 3.4.1)    sparklyr          * 0.8.5.2  2018-08-28 local (@0.8.5.2)  SparkR            * 2.4.4    2019-08-27 local             SparseM             1.77     2017-04-23 CRAN (R 3.4.3)    splines             3.4.3    2017-11-30 local             stats             * 3.4.3    2017-11-30 local             stats4              3.4.3    2017-11-30 local             stringi             1.1.5    2017-04-07 CRAN (R 3.4.0)    stringr             1.2.0    2017-02-18 url               tibble              1.4.2    2018-01-22 CRAN (R 3.4.3)    tidyr               0.7.0    2017-08-16 url               tools               3.4.3    2017-11-30 local             utils             * 3.4.3    2017-11-30 local             withr               2.1.2    2018-03-15 CRAN (R 3.4.3)    xgboost           * 0.4-4    2016-07-12 url               xtable              1.8-2    2016-02-05 url               yaml                2.1.14   2016-11-12 url
--
 
> | >
>


</body>
</html>

**Comment by amansahni1** [comment]
**> devtools::session_info()**
Session info -------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, linux-gnu           
 ui       RStudio (1.3.938.2)         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Australia/Melbourne         
 date     2021-08-02                  

Packages -----------------------------------------------------------------------------------------------------------
 package           * version  date       source          
 aaDevOps            0.2.13   2021-05-05 local           
 AdvancedAnalytics * 0.49.1   2021-07-28 local (@NA)     
 assertthat          0.2.0    2017-04-11 CRAN (R 3.4.3)  
 backports           1.1.0    2017-05-22 url             
 base              * 3.4.3    2017-11-30 local           
 base64enc           0.1-3    2015-07-28 CRAN (R 3.4.3)  
 bindr               0.1      2016-11-13 url             
 bindrcpp            0.2      2017-06-17 url             
 broom               0.4.2    2017-02-13 url             
 car                 2.1-5    2017-07-04 url             
 caret               6.0-76   2017-04-18 url             
 checkmate           1.8.3    2017-07-03 url             
 codetools           0.2-15   2016-10-05 CRAN (R 3.4.3)  
 colorspace          1.3-2    2016-12-14 CRAN (R 3.4.3)  
 compiler            3.4.3    2017-11-30 local           
 data.table        * 1.10.4   2017-02-01 url             
 datasets          * 3.4.3    2017-11-30 local           
 DBI                 1.1.0    2019-12-15 CRAN (R 3.4.3)  
 dbplyr              1.2.1    2018-02-19 url             
 devtools            1.13.3   2017-08-02 url             
 digest              0.6.12   2017-01-27 url             
 doParallel          1.0.11   2017-09-28 CRAN (R 3.4.3)  
 dplyr             * 0.7.4    2017-09-28 url             
 evaluate            0.10.1   2017-06-24 url             
 FNN                 1.1      2013-07-31 url             
 foreach             1.4.3    2015-10-13 url             
 foreign             0.8-69   2017-06-22 CRAN (R 3.4.3)  
 ggplot2           * 2.2.1    2016-12-30 url             
 glue                1.2.0    2017-10-29 url             
 graphics          * 3.4.3    2017-11-30 local           
 grDevices         * 3.4.3    2017-11-30 local           
 grid                3.4.3    2017-11-30 local           
 gridExtra           2.2.1    2016-02-29 url             
 gtable              0.2.0    2016-02-26 CRAN (R 3.4.3)  
 hms                 0.3      2016-11-22 url             
 htmltools           0.3.6    2017-04-28 CRAN (R 3.4.3)  
 httpuv              1.3.5    2017-07-04 url             
 httr                1.2.1    2016-07-03 url             
 iterators           1.0.8    2015-10-13 url             
 jsonlite            1.5      2017-06-01 CRAN (R 3.4.3)  
 knitr               1.20     2018-02-20 CRAN (R 3.4.3)  
 lattice             0.20-35  2017-03-25 CRAN (R 3.4.3)  
 lazyeval            0.2.1    2017-10-29 CRAN (R 3.4.3)  
 lightgbm            2.1.0    2018-03-01 local           
 lme4                1.1-13   2017-04-19 url             
 lubridate           1.6.0    2016-09-13 url             
 magrittr            1.5      2014-11-22 CRAN (R 3.4.3)  
 MASS                7.3-47   2017-02-26 CRAN (R 3.4.3)  
 Matrix              1.2-12   2017-11-20 CRAN (R 3.4.3)  
 MatrixModels        0.4-1    2015-08-22 CRAN (R 3.4.3)  
 memoise             1.1.0    2017-04-21 CRAN (R 3.4.3)  
 methods           * 3.4.3    2017-11-30 local           
 mgcv                1.8-22   2017-09-24 CRAN (R 3.4.3)  
 mime                0.5      2016-07-07 CRAN (R 3.4.3)  
 minqa               1.2.4    2014-10-09 CRAN (R 3.4.3)  
 mnormt              1.5-5    2016-10-15 CRAN (R 3.4.3)  
 ModelMetrics        1.1.0    2016-08-26 url             
 munsell             0.4.3    2016-02-13 url             
 nlme                3.1-131  2017-02-06 CRAN (R 3.4.3)  
 nloptr              1.0.4    2017-08-22 CRAN (R 3.4.3)  
 nnet                7.3-12   2016-02-02 CRAN (R 3.4.3)  
 packrat             0.4.8-1  2016-09-07 url             
 parallel            3.4.3    2017-11-30 local           
 pbkrtest            0.4-7    2017-03-15 CRAN (R 3.4.3)  
 pillar              1.2.1    2018-02-27 url             
 pkgconfig           2.0.1    2017-03-21 url             
 plyr              * 1.8.4    2016-06-08 CRAN (R 3.4.3)  
 psych               1.7.8    2017-09-09 url             
 purrr               0.2.4    2017-10-18 url             
 quantreg            5.33     2017-04-18 url             
 R6                  2.2.2    2017-06-17 CRAN (R 3.4.3)  
 RColorBrewer        1.1-2    2014-12-07 CRAN (R 3.4.3)  
 Rcpp                0.12.13  2017-09-28 url             
 readi             * 0.1.14.1 2021-07-29 local (@e86fd58)
 readr             * 1.1.1    2017-05-16 CRAN (R 3.4.3)  
 reshape2            1.4.2    2016-10-22 url             
 rJava               0.9-8    2016-01-07 url             
 RJDBC               0.2-5    2014-12-19 url             
 rlang               0.2.0    2018-02-20 url             
 rmarkdown           1.10     2018-06-11 CRAN (R 3.4.3)  
 ROracle             1.3-1    2016-10-26 CRAN (R 3.4.3)  
 rprojroot           1.2      2017-01-16 url             
 rstudioapi          0.7      2017-09-07 CRAN (R 3.4.3)  
 scales              0.5.0    2017-08-24 url             
 shiny               1.0.5    2017-08-23 CRAN (R 3.4.1)  
 sparklyr          * 0.8.5.2  2018-08-28 local (@0.8.5.2)
 SparkR            * 2.4.4    2019-08-27 local           
 SparseM             1.77     2017-04-23 CRAN (R 3.4.3)  
 splines             3.4.3    2017-11-30 local           
 stats             * 3.4.3    2017-11-30 local           
 stats4              3.4.3    2017-11-30 local           
 stringi             1.1.5    2017-04-07 CRAN (R 3.4.0)  
 stringr             1.2.0    2017-02-18 url             
 tibble              1.4.2    2018-01-22 CRAN (R 3.4.3)  
 tidyr               0.7.0    2017-08-16 url             
 tools               3.4.3    2017-11-30 local           
 utils             * 3.4.3    2017-11-30 local           
 withr               2.1.2    2018-03-15 CRAN (R 3.4.3)  
 xgboost           * 0.4-4    2016-07-12 url             
 xtable              1.8-2    2016-02-05 url             
 yaml                2.1.14   2016-11-12 url             
>

**Comment by yitao-li** [comment]
@amansahni1 `SparkR` (not `sparklyr`) is a part of the Apache Spark project. Please file your issue in https://github.com/apache/spark instead, of use one of the mailing lists mentioned in https://spark.apache.org/community.html. Thanks.
