### ISSUE TITLE
Does sparklyr 1.7.0 or older support remote Spark 3.x via livy

### ISSUE THREAD

**Issue by pnayek** [sparklyr/sparklyr#3162]
Hi @yitao-li 

I am trying to access remote Spark3 via Livy using sparklyr. I am using sparklyr version 1.7.0.

This is how I am trying to create the connection:
```
spark_master="https:/mysystem:8998/livy2/v1"
method <- "livy"
proxyuser <- "user1"
custom_headers <- list("X-Requested-By"="pn_test")
custom_headers <- c(custom_headers, "Authorization"= btok)

conf <- sparklyr::livy_config(custom_headers = custom_headers, proxy_user=proxyuser)
conf$sparklyr.livy.jar <- c(
     "/user/user1/lib/sparklyr/1.7.0/sparklyr-2.4-2.12.jar"
)
conf$spark.sql.catalogImplementation <- NULL
conf$livy.session.start.timeout=3000
sc <- spark_connect(master = spark_master, config=conf, method=method, version="3.0")  ##NOTE: I tried with version="3.1" as well 
```

But, the spark_connect keeps error-ing out with:
```
Error in livy_validate_master(master, config) : 
  Failed to connect to Livy service at https:/mysystem:8998/livy2/v1. !is.null(sessions$sessions) is not TRUE
```

The above step works fine with remote Spark 2.4 and sparklyr 1.7.0 (i.e., loading jar `sparklyr-2.4-2.11.jar`) but is failing with Spark3 (used jar `sparklyr-2.4-2.12.jar`). Does sparklyr version 1.7.0 support remote Spark 3.x via Livy? If so, which sparklyr jar file should be loaded using `sparklyr.livy.jar`?
If not, then is there any sparklyr version that supports remote Spark 3 via Livy?

**Comment by yitao-li** [comment]
@pnayek Spark 3 + Livy is not supported yet by sparklyr. I'll keep you posted when this support is planned & implement in some future version of sparklyr.

**Comment by pnayek** [comment]
Thanks for the info @yitao-li .
So, just to confirm, any versions of sparklyr (e.g., 1.5.x, 1.6.x, 1.7.x) doesn't support Spark3 + Livy, right?

**Comment by yitao-li** [comment]
Yes that's correct.

**Comment by pnayek** [comment]
Thanks for confirming @yitao-li

**Comment by pnayek** [comment]
@yitao-li one more question: Could you please share a timeline or release version of sparklyr on which Spark3 + Livy would be supported?

**Comment by yitao-li** [comment]
@pnayek There is not really a timeline for this at the moment. If there is some progress I'll comment here asap to let you know.

**Comment by pnayek** [comment]
Thanks @yitao-li

**Comment by yitao-li** [comment]
@pnayek I just tried connecting to Livy on a EMR cluster (with EMR release 6.3.0 which features Spark 3.1.1). Everything seems to work just fine. For me the Livy server is running locally though, but I don't think that should make any material difference.

```
library(sparklyr)

 sc <- spark_connect(master = "local", method = "livy", version = "3.1.1")

print(sdf_len(sc, 10))  # This produces the expected result
```

Please note when I previously I mentioned Livy + Spark 3 is not "officially supported" yet I was more thinking about the fact that there is no automated CI workflow for verifying all sparklyr functionlalities with Livy + Spark 3 yet, but if you already have a Spark cluster with Spark 3 and Livy set up successfully, then most, if not all, Spark functionalities should work just fine through Livy.

I see there is https://issues.apache.org/jira/browse/LIVY-756 related to Livy support for Spark 3 btw, but looks like I need to wait until Livy 0.8 release to be able to download an open-source version of Livy that has this support.

**Comment by yitao-li** [comment]
@pnayek I don't think you should need to specify `conf$sparklyr.livy.jar`. Sparklyr is capable of figuring out which jar file to use (see my example above).

Notice my example above doesn't involve https://, authenticaltion token, or proxy user though. I think you need to focus on those 3 areas to figure out why your use case is not working.

**Comment by yitao-li** [comment]
@pnayek Do you know by any chance whether your example code above worked for Spark 2.x + Livy?

**Comment by pnayek** [comment]
Hi @yitao-li 
yes we have been using this same code with remote Spark 2.x + Livy and it works fine. But, it doesn't work when we switched to Spark 3. 

Which sparklyr version did you use in your example? is there an official sparklyr version that claims that it supports **remote Spark 3 + Livy**? In this repo https://github.com/sparklyr/sparklyr/tree/v1.7.0/inst/java I noticed that there is no jar available for Spark 3.x. If Spark version livy configures with is spark 3.1 , then which version would it pick up instead?

I am using a Cloudera CDH 7.1.6 cluster and have installed Spark 3 in it as per their document: https://docs.cloudera.com/cdp-private-cloud-base/7.1.6/cds-3/topics/spark-install-spark-3-parcel.html

**Comment by yitao-li** [comment]
@pnayek I used sparklyr 1.7 in my example (i.e., the version officially released to CRAN, not some development version or anything like that)

No there is no official sparklyr version that claims to fully support remote Spark 3 + Livy yet, simply because we currently don't have the infrastructure to verify this type of configuration will fully work (even though most likely it will, possibly with a few minor tweaks though).

Re: jar file -- there is the 'sparklyr-master-2.12.jar' which gets picked up when Spark version is 3.0 or above (master as in the master branch of Apache Spark). So don't worry, the required jar file is indeed present, just under a slightly different name.

**Comment by edgararuiz** [comment]
Merging this issue with #3164 

Spark 3.0 is expected when Livy 0.8 is released
