### ISSUE TITLE
Cannot set `sparklyr.cores.local` and `sparklyr.backend.threads` confs

### ISSUE THREAD

**Issue by joveyuan-db** [sparklyr/sparklyr#3165]
Hi, I'm running into issues setting two different and independent confs in sparklyr.

1. For a local Spark connection (`master = "local"`), it appears that `sparklyr.connect.cores.local` is set by default to `parallel::detectCores()`.  If users try to set `sparklyr.cores.local` though (e.g. per documentation https://spark.rstudio.com/guides/connections/#connection-example), `sparklyr.connect.cores.local` takes precedence.
To reproduce,
```r
conf <- spark_config()
conf$sparklyr.cores.local <- 1
sc <- spark_connect(master = "local", config = conf)
```
In the Spark UI, I confirmed that I do not see the updated number of driver cores and that `spark.master` is not set to `local[1]`.

2. Looking at the source code and at https://spark.rstudio.com/deployment/#diagnostics, `sparklyr.backend.threads` configures the number of threads used by the backend.  However, it does not seem that users can configure it, because I believe 1) it initializes a new `SparkConf` independent of the current Spark context, and 2) `SparkConf` only loads system properties prefixed with `spark.` ([SparkConf.scala](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/SparkConf.scala#L73)).  Renaming the conf to SparkR's equivalent `spark.r.numRBackendThreads` ([R.scala](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/internal/config/R.scala#L26)) does not appear to be sufficient either.  Ideally, Scala would be able to use R's `spark_config_value` in order to read the conf.  I am able to reproduce this issue both locally (by setting `conf$sparklyr.backend.threads`) and on a Databricks connection (by setting Spark confs on the cluster).

I would appreciate any insights here, thanks!

---

Session Info (local):
```
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16
```

Session info (Databricks):
```
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS
```

**Comment by jfarland** [comment]
You need to pass `conf` when you connect to the spark cluster. What happens if you retry with the following?
```
conf <- spark_config()
conf$sparklyr.cores.local <- 1
sc <- spark_connect(master = "local", config = conf)
```

**Comment by joveyuan-db** [comment]
Oh yes, sorry, I copied the wrong code block.  Passing in `conf` to `spark_connect` still exhibits the issue.

**Comment by yitao-li** [comment]
Thanks for the feedback!
I think this is a bug, and a temp workaround is to have `config$sparklyr.connect.cores.local <- 1` instead.

**Comment by yitao-li** [comment]
@joveyuan-db Re: "sparklyr.backend.threads" -- this one cannot be configured through the R interface. It can only be configured through a text file located at `$SPARK_HOME/conf/spark-defaults.conf`. Also, see https://spark.apache.org/docs/latest/configuration.html#overriding-configuration-directory.

**Comment by joveyuan-db** [comment]
@yitao-li Thanks for the fast response!  Got it, I tried setting `sparklyr.backend.threads 1` in `$SPARK_HOME/conf/spark-defaults.conf`, but when I print the value of `conf.getInt("sparklyr.backend.threads", 10)`, I still get 10.  Could you confirm if you are able to set it?

And understood, I'm currently prototyping something for the sparklyr <> Databricks connection, so wanted to test if it was possible to restrict the number of backend threads.

**Comment by yitao-li** [comment]
@joveyuan-db It looks like only properties prefixed with `"spark."` will be picked up.

What I previously mentioned was based on https://spark.apache.org/docs/latest/configuration.html but I think what that documentation forgot to mention is user-defined properties not prefixed with `"spark."` will not be picked up (e.g., `"sparklyr.backend.threads"` doesn't have the right prefix and is therefore ignored).

So I think the solution will be just the following:

- I shall make a trivial change in `sparklyr` renaming `"sparklyr.backend.threads"` to `"spark.sparklyr-backend.threads"` (this is not user-facing at all, so renaming it is OK)
- You can then install a version of `sparklyr` with the renamed config by running `remotes::install_github("sparklyr/sparklyr", ref = "rename-backend-threads-config")`
- And then re-launch your R session and verify it works with something like this:

```
library(sparklyr)

conf <- spark_config()
conf$`sparklyr.shell.conf` <- c(
  "spark.sparklyr-backend.threads=5"
)

sc <- spark_connect(
  # master = <Spark master>,
  # method = "databricks",
  master = "local",
  config = conf
)

sc$state$spark_context %>%
  invoke(
    "%>%",
    list("getConf"), list("get", "spark.sparklyr-backend.threads")
  ) %>%
  print()
```

Does that sound good?

**Comment by joveyuan-db** [comment]
Hi @yitao-li thanks for taking a look, appreciate your help!  I've tested your suggestion locally (`master = "local"`) and can confirm it works (I'm able to modify the number of backend threads).

However, on Databricks, it looks like any Spark confs added to a cluster are directly set on the `SparkConf` we initialize and therefore new `SparkConf`'s don't see the value.  Do you know if it would be possible to use `SparkEnv.get.conf` or similar?  When I tried that out, it errored building the JAR (`error: error while loading ShuffleMemoryManager, Missing dependency 'bad symbolic reference. A signature in ShuffleMemoryManager.class refers to term annotations`).
