### ISSUE TITLE
replace_na() not defined

### ISSUE THREAD

**Issue by kelnerrr** [sparklyr/sparklyr#3209]
I get an error trying to use `replace_na()` function. This code:

```r
spark_version <- "3.1.2"
sparklyr_version <- "1.7.3"
sc <- spark_connect(method = "databricks")

tibble(x = c(1, 2, 3, NA)) %>%
  copy_to(sc, ., "temp_replace_na", overwrite = TRUE) %>%
  mutate(x = replace_na(x, 0))
```

returns:

> Error : org.apache.spark.sql.AnalysisException: Undefined function: 'replace_na'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 1 pos 7

The same with `sparklyr::replace_na()` instead of `replace_na()` throws:

> Error in sparklyr::replace_na(x, 0) : object 'x' not found

In R it looks like that:

```r
tibble(x = c(1, 2, 3, NA)) %>%
  mutate(x = replace_na(x, 0))
```

```
# A tibble: 4 × 1
      x
  <dbl>
1     1
2     2
3     3
4     0
```

**Comment by harryprince** [comment]
in sparkr you can use `mutate(var = nvl(var,0))` ,which means fill var into 0

**Comment by edgararuiz** [comment]
Hi, using `replace_na()` outside `mutate()` works, and with the same results; 

``` r
suppressPackageStartupMessages(library(sparklyr))

sc <- spark_connect("local")

tibble::tibble(x = c(1, 2, 3, NA)) %>%
  copy_to(sc, ., "temp_replace_na", overwrite = TRUE) %>%
  replace_na(list(x = 0))
#> # Source: spark<?> [?? x 1]
#>       x
#>   <dbl>
#> 1     1
#> 2     2
#> 3     3
#> 4     0


spark_disconnect(sc)
```

<sup>Created on 2022-09-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
