### ISSUE TITLE
filter() does not work with R6 class slots on spark data frames

### ISSUE THREAD

**Issue by Adrian-S-D** [sparklyr/sparklyr#3216]
Trying to filter a spark data frame does not work with the content of a R6 slot.

Running on Databricks runtime 10.2
sessionInfo():
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

other attached packages:
[1] dplyr_1.0.7    R6_2.5.1       sparklyr_1.7.2

```r
library("R6")
library("dplyr")
foo <- R6Class("fooo", list(
  dataz=data.frame(letters=c("a", "b", "c"))
))
obj <- foo$new()
obj$dataz
dataToFilter <- data.frame(letters=c("a", "b", "d"), value=1:3)
dataToFilter %>% dplyr::filter(letters %in% obj$dataz$letters)
```
works as expected with base data frames.
Preparing spark stuff
```r
sc <- spark_connect(method="databricks")
copy_to(sc, dataToFilter, name="testz", overwrite = TRUE)
```
```r
test <- spark_read_table(sc, name="testz")
test %>% filter(letters %in% obj$dataz$letters)
```
fails with 
`
Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "c('fooo', 'R6')"
Some(<code style = 'font-size:10p'> Error in UseMethod(&quot;escape&quot;): no applicable method for 'escape' applied to an object of class &quot;c('fooo', 'R6')&quot; </code>)
`
```r
filterz <- obj$dataz$letters
test <- spark_read_table(sc, name="testz")
test %>% filter(letters %in% filterz)
```
works as expected

**Comment by edgararuiz** [comment]
Hi, can you try: `test %>% filter(letters %in% !! obj$dataz$letters)`, that should trigger the eval of the variables

**Comment by Adrian-S-D** [comment]
!! works as expected

**Comment by edgararuiz** [comment]
I'll go ahead and close this issue. Please let me know if you are still having problems with this.
