### ISSUE TITLE
gennerate a serise as list column  in spark

### ISSUE THREAD

**Issue by longhua8800w** [sparklyr/sparklyr#3225]
![image](https://user-images.githubusercontent.com/19342379/153991802-b38c4f8e-d807-4c22-8b41-955d6b78b877.png)
I want  cmp_terms a list column  from max_term_th to 12 by step 1  (or  at least a string  from max_term_th to 12 by step 1 seprated b  ",")  but I can't find a function useable in this context to fullfill this purpose.  is this can be done?

**Comment by harryprince** [comment]
```
target_tbl <- dplyr::tbl(sc,sql('SELECT array(1,2,3,4,5,6,7,8,9,10,11,12)'))


your_sdf %>%
mutate(new_column = split(cpm_terms,',') ) %>% # which return an array
sparklyr.nested::sdf_explode(new_column) %>%  # after that get a explode later view 
mutate(mark = 1) %>%
right_join(target_tbl) %>%
mutate(mark= nvl(mark,0)) %>%
group_by(idno,loan_no,max_srep_dt) %>% 
arrange(desc(new_column)) %>%
mutate(sum_mark = cumsum(mark)) %>%
filter(sum_mark >0)
```

# reference https://mitre.github.io/sparklyr.nested/reference/sdf_explode.html

**Comment by longhua8800w** [comment]
the problem i faced is that  i can't gennerate a serise in a  tbl ，
i tried  founctions in sparklyr and hive ,but didn't succeed.the nearest is
  concat_ws(",", max_term,12) which produce cmp_term in the picture .  but i want something  like  concat_ws(",", max_term:12)  or  concat_ws(",", seq(max_term,12,by=1)) but they were not supported

**Comment by harryprince** [comment]
sparklyr::spark_apply can implement `seq(max_term,12,by=1)`, which maybe a better choice

**Comment by longhua8800w** [comment]
thanks but we haven't  install R on nodes of our cluster.  so spark_apply can't be use maybe we should try that. 
 "gennerate a serise in a tbl " should be a very common use case ,I wandered  why I can't find a function directly support by  sparklyr  or hive?  is it exists?

**Comment by harryprince** [comment]
spark_apply do not need to install R in each node, you can make an R envroiment.zip file, and launch with spark config.

**Comment by longhua8800w** [comment]
thanks   i will  try it

**Comment by longhua8800w** [comment]
i am  sorry, I have   to much work to do and haven't try this,wish to have time to solve this.  I close  this issue and hope to goback on this soon.
