### ISSUE TITLE
CI/CD questions 

### ISSUE THREAD

**Issue by edgararuiz** [sparklyr/sparklyr#3227]
Hi @javierluraschi / @yitao-li !

I'm going through the repo, and I'm trying to figure out if these files are being currently used by anyone or any process:

- https://github.com/sparklyr/sparklyr/blob/main/ci/install_r_dependencies.sh  << I see what it does, such as install Arrow dev, but I don't see anything that activates it

- https://github.com/sparklyr/sparklyr/blob/main/Jenkinsfile / https://github.com/sparklyr/sparklyr/tree/main/ci/jenkins << Both look to be used to test Databricks integration, but they don't look to be part of any GHA process, and I don't see any CI/CD process tied to this repo

Any background is appreciated.  

**Some background:**

I want to redo the entire GHA process, but I get the sense/fear that someone else depends on these scripts, so I want to make sure that I can fully replace anything on the .github, jenkins, ci folders and remove the Jenkinsfile from the repo. 

The main impetus is that in the current GHA, the test that is supposed to sue Dev versions of the packages (https://github.com/sparklyr/sparklyr/blob/d02d20e172342b24a12e027c1d4afcadf5638707/.github/workflows/ci.yaml#L139) is actually not working. There is nothing anywhere in the repo that looks at this flag any longer. This would have prevented the CRAN failure that occurred a couple of weeks ago, because it would have failed with `tidyr`

Again, thank you for any info you can share with me

**Comment by yitao-li** [comment]
Sorry for the delayed response.

Re: install_r_dependencies.sh -- It appears to be a left-over. We revamped ci.yaml at some point to not rely on it anymore, but forgot to delete that script. I think you can safely delete it.

Re: the Jenkins file -- They were added by Databricks folks and those *should* be executed through a GitHub Jenkins plugin IIRC and not through Github Actions. Please reach out to @falaki or @Loquats re: the current status of this workflow.

**Comment by edgararuiz** [comment]
Thank you @yitao-li 

@falaki / @Loquats - Hi ! Is the Jenkins file and folder still in use? (https://github.com/sparklyr/sparklyr/blob/main/Jenkinsfile / https://github.com/sparklyr/sparklyr/tree/main/ci/jenkins) And if they are, could the be moved to a different repo?  Thanks!

**Comment by falaki** [comment]
Yitao,

I will go ahead and remove it. It is not used any more.


--Hossein

**Comment by edgararuiz** [comment]
#3230 Was part of solution as well
