### ISSUE TITLE
mmlspark -> SynapseML

### ISSUE THREAD

**Issue by niehaus59** [sparklyr/sparklyr#3251]
HI - 

https://spark.rstudio.com/guides/extensions.html lists mmlspark as a Sparklyr extension. Recently, the name of this project was changed from mmlspark to SynapseML. The old link for its Sparklyr documentation was https://github.com/Azure/mmlspark/blob/master/docs/R-setup.md. This is now a dead link. The new page is https://github.com/microsoft/SynapseML/blob/master/website/docs/reference/R-setup.md.  

Thank you for listing us on your site. We hope you will be able to update the Extensions page with this new information.  If there is a better avenue for requesting such a change, please let me know.

**Comment by edgararuiz** [comment]
Hi @niehaus59 - Moved this issue to the `sparklyr`'s website repo: https://github.com/rstudio/spark.rstudio.com/issues/134

Thank you for notifying us
