### ISSUE TITLE
Unable to download Spark 3.3.0 with `spark_install`

### ISSUE THREAD

**Issue by alberto-agudo** [sparklyr/sparklyr#3298]
I am trying to install Spark using the standard `spark_install` verb. However, when running it, it says that the tar file is not found. The example is the following: 

```r
spark_install()
```

>Installing Spark 3.3.0 for Hadoop 2 or later.
>Downloading from:
>- 'https://dlcdn.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop2.tgz'
>Installing to:
>- 'C:\Users\alberto.agudo\AppData\Local/spark/spark-3.3.0-bin-hadoop2'
>trying URL 'https://dlcdn.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop2.tgz'
>Error in download.file(...) : 
 > cannot open URL 'https://dlcdn.apache.org/spark/spark-3.3.0/spark-3.3.0-bin-hadoop2.tgz'

**I've solved it by manually downloading Spark 3.3.1 from https://dlcdn.apache.org/spark/spark-3.3.1/ and installed through `spark_install_tar`, but I think this could be fixed for other users (or, at least, giving some info in the docs about this error and how to use `spark_install_tar`).**

---
---
```{r}
My session info: 
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8 
[2] LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_1.7.8

loaded via a namespace (and not attached):
 [1] tseries_0.10-51   httr_1.4.4        tidyr_1.2.1       bit64_4.0.5      
 [5] jsonlite_1.8.2    splines_4.2.1     foreach_1.5.2     warp_0.2.0       
 [9] assertthat_0.2.1  TTR_0.24.3        yaml_2.3.5        r2d3_0.2.6       
[13] pillar_1.8.1      lattice_0.20-45   glue_1.6.2        quadprog_1.5-8   
[17] digest_0.6.29     pryr_0.1.5        gridtext_0.1.4    colorspace_2.0-3 
[21] htmltools_0.5.3   Matrix_1.4-1      timeDate_4021.104 pkgconfig_2.0.3  
[25] purrr_0.3.5       scales_1.2.1      slider_0.2.2      tibble_3.1.8     
[29] generics_0.1.3    ggplot2_3.3.6     ellipsis_0.3.2    pacman_0.5.1     
[33] urca_1.3-3        nnet_7.3-17       cli_3.4.0         quantmod_0.4.20  
[37] survival_3.3-1    magrittr_2.0.3    ggtext_0.1.1      forecast_8.17.0  
[41] evaluate_0.16     fansi_1.0.3       nlme_3.1-157      xts_0.12.1       
[45] xml2_1.3.3        mFilter_0.1-5     tools_4.2.1       lifecycle_1.0.3  
[49] eble_2.3.6        stringr_1.4.1     munsell_0.5.0     glmnet_4.1-4     
[53] compiler_4.2.1    forge_0.2.0       stinepack_1.4     rlang_1.0.6      
[57] grid_4.2.1        iterators_1.0.14  rstudioapi_0.14   rappdirs_0.3.3   
[61] imputeTS_3.3      htmlwidgets_1.5.4 base64enc_0.1-3   rmarkdown_2.17   
[65] gtable_0.3.1      codetools_0.2-18  fracdiff_1.5-1    DBI_1.1.3        
[69] curl_4.3.2        R6_2.5.1          zoo_1.8-11        lubridate_1.8.0  
[73] knitr_1.40        dplyr_1.0.10      fastmap_1.1.0     bit_4.0.4        
[77] utf8_1.2.2        rprojroot_2.0.3   shape_1.4.6       stringi_1.7.8    
[81] parallel_4.2.1    Rcpp_1.0.9        vctrs_0.4.1       dbplyr_2.2.1     
[85] tidyselect_1.2.0  xfun_0.33         lmtest_0.9-40    
```

**Comment by alberto-agudo** [comment]
After reupdating my R base installation, it seems like the spark_install function started working, calling archive.apache.org instead of dlcdn.apache.org. (Even though sparklyr's version is the same: 1.7.8).

```{r}
> spark_install()
Installing Spark 2.4.3 for Hadoop 2.7 or later.
Downloading from:
- 'https://archive.apache.org/dist/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz'
Installing to:
- 'C:\Users\alberto.agudo\AppData\Local/spark/spark-2.4.3-bin-hadoop2.7'
trying URL 'https://archive.apache.org/dist/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz'
Content type 'application/x-gzip' length 229988313 bytes (219.3 MB)
downloaded 219.3 MB

Installation complete.
```

Noticeable changes:
I've upgraded my R version from 4.2.1 to 4.2.2. Also the Windows build was upgraded from 19044 to 19045. But, given the error message, I recommend other users trying to upgrade the R version and reinstalling sparklyr? Although the previous way of installing through the TAR file still works.

---
---
─ Session info ───────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United Kingdom.utf8
 ctype    English_United Kingdom.utf8
 tz       Europe/Paris
 date     2022-11-17
 rstudio  2022.07.2+576 Spotted Wakerobin (desktop)
 pandoc   NA

─ Packages ───────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 askpass       1.1     2019-01-13 [1] CRAN (R 4.2.2)
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.2.2)
 base64enc     0.1-3   2015-07-28 [1] CRAN (R 4.2.0)
 cachem        1.0.6   2021-08-19 [1] CRAN (R 4.2.2)
 callr         3.7.3   2022-11-02 [1] CRAN (R 4.2.2)
 cli           3.4.1   2022-09-23 [1] CRAN (R 4.2.2)
 config        0.3.1   2020-12-17 [1] CRAN (R 4.2.2)
 crayon        1.5.2   2022-09-29 [1] CRAN (R 4.2.2)
 DBI           1.1.3   2022-06-18 [1] CRAN (R 4.2.2)
 dbplyr        2.2.1   2022-06-27 [1] CRAN (R 4.2.2)
 devtools      2.4.5   2022-10-11 [1] CRAN (R 4.2.2)
 digest        0.6.30  2022-10-18 [1] CRAN (R 4.2.2)
 dplyr         1.0.10  2022-09-01 [1] CRAN (R 4.2.2)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.2.2)
 fansi         1.0.3   2022-03-24 [1] CRAN (R 4.2.2)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.2)
 forge         0.2.0   2019-02-26 [1] CRAN (R 4.2.2)
 fs            1.5.2   2021-12-08 [1] CRAN (R 4.2.2)
 generics      0.1.3   2022-07-05 [1] CRAN (R 4.2.2)
 glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.2)
 htmltools     0.5.3   2022-07-18 [1] CRAN (R 4.2.2)
 htmlwidgets   1.5.4   2021-09-08 [1] CRAN (R 4.2.2)
 httpuv        1.6.6   2022-09-08 [1] CRAN (R 4.2.2)
 httr          1.4.4   2022-08-17 [1] CRAN (R 4.2.2)
 jsonlite      1.8.3   2022-10-21 [1] CRAN (R 4.2.2)
 later         1.3.0   2021-08-18 [1] CRAN (R 4.2.2)
 lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.2.2)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.2)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.2.2)
 mime          0.12    2021-09-28 [1] CRAN (R 4.2.0)
 miniUI        0.1.1.1 2018-05-18 [1] CRAN (R 4.2.2)
 openssl       2.0.4   2022-10-17 [1] CRAN (R 4.2.2)
 pillar        1.8.1   2022-08-19 [1] CRAN (R 4.2.2)
 pkgbuild      1.3.1   2021-12-20 [1] CRAN (R 4.2.2)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.2)
 pkgload       1.3.2   2022-11-16 [1] CRAN (R 4.2.2)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.2.2)
 processx      3.8.0   2022-10-26 [1] CRAN (R 4.2.2)
 profvis       0.3.7   2020-11-02 [1] CRAN (R 4.2.2)
 promises      1.2.0.1 2021-02-11 [1] CRAN (R 4.2.2)
 ps            1.7.2   2022-10-26 [1] CRAN (R 4.2.2)
 purrr         0.3.5   2022-10-06 [1] CRAN (R 4.2.2)
 r2d3          0.2.6   2022-02-28 [1] CRAN (R 4.2.2)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.2.2)
 rappdirs      0.3.3   2021-01-31 [1] CRAN (R 4.2.2)
 Rcpp          1.0.9   2022-07-08 [1] CRAN (R 4.2.2)
 remotes       2.4.2   2021-11-30 [1] CRAN (R 4.2.2)
 rlang         1.0.6   2022-09-24 [1] CRAN (R 4.2.2)
 rprojroot     2.0.3   2022-04-02 [1] CRAN (R 4.2.2)
 rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.2)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.2)
 shiny         1.7.3   2022-10-25 [1] CRAN (R 4.2.2)
 sparklyr    * 1.7.8   2022-08-16 [1] CRAN (R 4.2.2)
 stringi       1.7.8   2022-07-11 [1] CRAN (R 4.2.1)
 stringr       1.4.1   2022-08-20 [1] CRAN (R 4.2.2)
 tibble        3.1.8   2022-07-22 [1] CRAN (R 4.2.2)
 tidyr         1.2.1   2022-09-08 [1] CRAN (R 4.2.2)
 tidyselect    1.2.0   2022-10-10 [1] CRAN (R 4.2.2)
 urlchecker    1.0.1   2021-11-30 [1] CRAN (R 4.2.2)
 usethis       2.1.6   2022-05-25 [1] CRAN (R 4.2.2)
 utf8          1.2.2   2021-07-24 [1] CRAN (R 4.2.2)
 vctrs         0.5.1   2022-11-16 [1] CRAN (R 4.2.2)
 withr         2.5.0   2022-03-03 [1] CRAN (R 4.2.2)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 4.2.2)
 yaml          2.3.6   2022-10-18 [1] CRAN (R 4.2.1)

 [1] C:/Program Files/R/R-4.2.2/library

**Comment by lgeistlinger** [comment]
I have the same problem.

**Comment by edgararuiz** [comment]
Hi all, this fix should not require an update to CRAN for it to work on 1.7.8, please try `spark_install()` again and re-open if it doesn't work. Thank you
