### ISSUE TITLE
Error[Failed to launch livy session, session status is dead] on connecting to spark through livy using R

### ISSUE THREAD

**Issue by rakshitdeshpande** [sparklyr/sparklyr#3306]
# Reporting an Issue with sparklyr

I am using sparklyr version [1.7.8](https://github.com/sparklyr/sparklyr)
and latest livy version in master branch [incubator-livy](https://github.com/apache/incubator-livy)

On connecting to spark through livy using R

> library(sparklyr)
> sc <- spark_connect(master = "local", method = "livy", version ="3.1.1")

Command is throwing an error:
>Error in livy_connection(master, config, app_name, version, hadoop_version,  :
>Failed to launch livy session, session status is dead

Could anyone please help me understand what could the issue be.

**Comment by edgararuiz** [comment]
Hi, currently, Livy does not support Spark 3+, that's something that seems that will go in on version 0.8.0 of Livy. Try using an older version of spark `version="2.4.0"` https://github.com/sparklyr/sparklyr/issues/3164
