### ISSUE TITLE
`spark_submit(...)` not terminated after submission

### ISSUE THREAD

**Issue by smingerson** [sparklyr/sparklyr#3311]
[This line](https://github.com/sparklyr/sparklyr/blob/eb3e795447887908d9e795512ad08eeeb32eede5/R/shell_connection.R#L442) is supposed to terminate batch connections before going any further. However, `batch` is the file name from `spark_submit()`. Not sure if this should be switched to `isBatch` instead, or I am missing something.

**Comment by edgararuiz** [comment]
Hi @smingerson , are you seeing instances where the batch does not terminate the connection? Is that something that we can create a `reprex` for?
