### ISSUE TITLE
java_install_url not found

### ISSUE THREAD

**Issue by bhogan-mitre** [sparklyr/sparklyr#3312]
Hello, I'm curious where `java_install_url()` is defined, and if there may be an unstated namespace dependency.  

On a fresh windows system that did not have java properly available on the path, I received the following error when trying to open a connection from the RStudio IDE Connections tab, via https://github.com/sparklyr/sparklyr/blob/eb3e795447887908d9e795512ad08eeeb32eede5/inst/rstudio/shinycon/app.R#L431

![Screen Shot 2023-02-09 at 12 24 57 PM](https://user-images.githubusercontent.com/32336739/218118026-101d2f3a-fd31-452a-8019-f724d221ef1e.png)

```
> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.2 tools_4.2.2    fs_1.6.0      
```

**Comment by edgararuiz** [comment]
Hi, that is an unexported function in `sparklyr`: https://github.com/sparklyr/sparklyr/blob/1dd5c51575b6934b3841147b5a9de6fae4b08404/R/java.R#L75-L77

In the case of this app, It may be just easier to hardcode the url
