### ISSUE TITLE
Anyone interested in maintaining Apache Sedona R module?

### ISSUE THREAD

**Issue by jiayuasu** [sparklyr/sparklyr#3313]
# Anyone interested in maintaining Apache Sedona R module

Dear all,

Sorry, this is not an actual issue report. But I don't know where I can find other members in the R community. We, the Apache Sedona community (https://github.com/apache/sedona), are in urgent need of a volunteer to help maintain Sedona R module.

Apache Sedona is a cluster computing system for processing large-scale geospatial data. It extends Spark and Flink with comprehensive geospatial processing capability. It provides Scala/Java/SQL/Python/R interfaces. Currently, its R module is built on Sparklyr and connects Apache Spark. Sedona has over 10M downloads overall and receives over 800K downloads every month.

Recently, the main contributor of Apache Sedona R module no longer has time maintaining this library. The current GitHub Action of Sedona R has been failing for a few weeks and does not enjoy the new functions introduced in Sedona core.

Members in our community are familiar with Scala/Java/Python but don't know much about R. However, I believe Sedona R is still a great addition to the R geospatial community at large.

Please feel free to let me know if you are interested. My contact is Jia Yu, email: jiayu@apache.org

Thanks,
Jia

PMC Chair of Apache Sedona

**Comment by edgararuiz** [comment]
Hi @jiayuasu , I took a quick look at your GH actions (https://github.com/apache/sedona/actions/workflows/r.yml) and didn't see a failure. I think I'm looking in the wrong place, can you direct me to the right spot? I'd like to take a look and see that maybe we can work on a quick fix to get the package going, while we figure ownership of the package itself

**Comment by jiayuasu** [comment]
@edgararuiz Yes, we can close this issue. @gregleleu is actively maintaining Sedona R now.
