### ISSUE TITLE
Update documentation on extensions

### ISSUE THREAD

**Issue by gregleleu** [sparklyr/sparklyr#3315]
In the documentation, the page for extensions would need a bit of updating. e.g. sparklygraphs has been superseded, the "ensure" functions don't seem to exist anymore.
Also, can we add the apache.sedona package in the list?

Happy to do a PR, but I couldn't find the documentation packages in this repo.

**Comment by edgararuiz** [comment]
@gregleleu -  Should we close this Issue since there is a PR now in the website's repo?

**Comment by gregleleu** [comment]
Sure
