### ISSUE TITLE
Export additional functions to make extensions easier to write

### ISSUE THREAD

**Issue by gregleleu** [sparklyr/sparklyr#3316]
I'm writing additional spark_read/write_* functions in an extension (apache.sedona). They rely on the generic Spark SQL read `spark.read.format("my new format).option(...).load("my path")` like so many of the read/write functions in Sparklyr.
Would it be possible to export some of the internal functions that are used by these readers?
I'm thinking:
* `spark_data_read_generic`: invokes the generic Spark SQL read
* `spark_data_write_generic`: invokes the generic Spark SQL write
* `spark_partition_register_df`: registers the sdf and returns a tbl
* `spark_read_compat_param`: creates a default name for the table

The alternative is either to use them non-exported (:::) but that will not pass on CRAN, or to copy the copy in our package, and that's not great either.

**Comment by smingerson** [comment]
`spark_write_source()` is a light wrapper around `spark_data_write_generic()` which just checks object class before calling it. Maybe that is sufficient for your needs.

`spark_read_source()` is a bit more involved, and I noticed that it calls `spark_partition_register_df()` and `spark_read_compat_param()`, so maybe is also what you need.

**Comment by gregleleu** [comment]
@smingerson amazing thank you!
