### ISSUE TITLE
distinct error in 1.7.9 

### ISSUE THREAD

**Issue by joscani** [sparklyr/sparklyr#3317]
I have an issue with distinct verb

```r


> iris_tbl <-  sc %>% copy_to(iris) 


iris_tbl %>% distinct(Species) 

Error in `arrange()`: 
ℹ In argument: `__row_num_0e5994da_2d4a_432b_b508_ce9e4f8f8c95` 
Caused by error: 
! Object `__row_num_0e5994da_2d4a_432b_b508_ce9e4f8f8c95` not found. 

Run `rlang::last_error()` to see where the error occurred. 

> packageVersion("sparklyr")
 [1] ‘1.7.9’
```

**Comment by joscani** [comment]
I saw that exists `sdf_distinct` and it works. Should I change all my distinct code to sdf_distinct?

**Comment by biederfrau** [comment]
sdf_distinct is not a proper substitute because it does not support .keep_all

**Comment by biederfrau** [comment]
It seems like this is actually a problem in dbplyr. Downgrading to version 2.2.0 helped for me, there may be more recent versions without the error too. I was originally experiencing the error with dbplyr 2.3.1 and 2.3.0

**Comment by edgararuiz** [comment]
Fixed in https://github.com/sparklyr/sparklyr/tree/updates

```
> iris_tbl <-  sc %>% copy_to(iris) 
> 
> 
> iris_tbl %>% distinct(Species) 
# Source:     spark<?> [?? x 1]
# Ordered by: "__row_num_4730738b_277b_4e42_a083_80c85209a323"
  Species   
  <chr>     
1 versicolor
2 virginica 
3 setosa    
```
