### ISSUE TITLE
n_distinct always return 0

### ISSUE THREAD

**Issue by longhua8800w** [sparklyr/sparklyr#3322]
sparklyr 1.7.8 dplyr 1.0.10 

when i use dplyr::n_distinct  with  na.rm = T  in spark data frame    n_distinct  always return 0.
cr_appl_id is  not na  and unique  but it returned  0
![error](https://user-images.githubusercontent.com/19342379/223378009-07868879-55cd-4072-962a-55fad4d205f5.jpeg)
![session](https://user-images.githubusercontent.com/19342379/223378067-f96c80ea-0316-4fbf-b5eb-7fc7ce342459.jpeg)

**Comment by edgararuiz** [comment]
Hi @longhua8800w , I'm not able to recreate. What version of R and `sparklyr` are you using? I can tell from the screenshot.

``` r
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(sparklyr))

sc <- spark_connect("local", version = "3.0.0")
tbl_mtcars <- copy_to(sc, mtcars)

tbl_mtcars %>% 
  group_by(am) %>% 
  summarise(n_distinct(cyl))
#> # Source: spark<?> [?? x 2]
#>      am `n_distinct(cyl)`
#>   <dbl>             <dbl>
#> 1     1                 3
#> 2     0                 3

spark_disconnect(sc)
```

<sup>Created on 2023-06-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
