### ISSUE TITLE
Spark 1.8.0 Slow

### ISSUE THREAD

**Issue by EvertonTLima** [sparklyr/sparklyr#3324]
# Reporting an Issue with sparklyr

> devtools::session_info()
─ Session info ───────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  Portuguese_Brazil.utf8
 ctype    Portuguese_Brazil.utf8
 tz       America/Sao_Paulo
 date     2023-03-08
 rstudio  2022.12.0+353 Elsbeth Geranium (desktop)
 pandoc   2.19.2 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)

─ Packages ───────────────────────────────────────────────────
 package           * version    date (UTC) lib source
 abind               1.4-5      2016-07-21 [1] CRAN (R 4.2.0)
 abjutils          * 0.3.2      2022-02-01 [1] CRAN (R 4.2.0)
 agua              * 0.1.2      2023-02-23 [1] CRAN (R 4.2.2)
 alphavantager     * 0.1.2      2020-03-01 [1] CRAN (R 4.2.1)
 arrow             * 11.0.0.3   2023-03-08 [1] CRAN (R 4.2.2)
 askpass             1.1        2019-01-13 [1] CRAN (R 4.2.0)
 assertthat          0.2.1      2019-03-21 [1] CRAN (R 4.2.0)
 backports           1.4.1      2021-12-13 [1] CRAN (R 4.2.0)
 base64enc           0.1-3      2015-07-28 [1] CRAN (R 4.2.0)
 basedosdados      * 0.2.2      2023-03-07 [1] CRAN (R 4.2.2)
 bayestestR          0.13.0     2022-09-18 [1] CRAN (R 4.2.1)
 benchmarkme         1.0.8      2022-06-12 [1] CRAN (R 4.2.2)
 benchmarkmeData     1.0.4      2020-04-23 [1] CRAN (R 4.2.2)
 bigassertr          0.1.6      2023-01-10 [1] CRAN (R 4.2.2)
 bigreadr            0.2.5      2022-12-06 [1] CRAN (R 4.2.2)
 bigrquery           1.4.1      2022-10-27 [1] CRAN (R 4.2.1)
 bit                 4.0.5      2022-11-15 [1] CRAN (R 4.2.2)
 bit64               4.0.5      2020-08-30 [1] CRAN (R 4.2.0)
 bitops              1.0-7      2021-04-24 [1] CRAN (R 4.2.0)
 bizdays           * 1.0.13     2023-01-20 [1] CRAN (R 4.2.2)
 blob                1.2.3      2022-04-10 [1] CRAN (R 4.2.0)
 bonsai            * 0.2.1      2022-11-29 [1] CRAN (R 4.2.2)
 broom             * 1.0.3      2023-01-25 [1] CRAN (R 4.2.2)
 broom.mixed       * 0.2.9.4    2022-04-17 [1] CRAN (R 4.2.2)
 cachem              1.0.7      2023-02-24 [1] CRAN (R 4.2.2)
 callr               3.7.3      2022-11-02 [1] CRAN (R 4.2.2)
 car                 3.1-1      2022-10-19 [1] CRAN (R 4.2.1)
 carData             3.0-5      2022-01-06 [1] CRAN (R 4.2.1)
 caret             * 6.0-93     2022-08-09 [1] CRAN (R 4.2.1)
 cellranger          1.1.0      2016-07-27 [1] CRAN (R 4.2.0)
 checkmate           2.1.0      2022-04-21 [1] CRAN (R 4.2.0)
 class               7.3-20     2022-01-16 [2] CRAN (R 4.2.2)
 cli                 3.6.0      2023-01-09 [1] CRAN (R 4.2.2)
 cluster             2.1.4      2022-08-22 [2] CRAN (R 4.2.2)
 coda                0.19-4     2020-09-30 [1] CRAN (R 4.2.0)
 codetools           0.2-18     2020-11-04 [2] CRAN (R 4.2.2)
 colorspace          2.1-0      2023-01-23 [1] CRAN (R 4.2.2)
 config              0.3.1      2020-12-17 [1] CRAN (R 4.2.1)
 ConfusionTableR     1.0.4      2021-12-01 [1] CRAN (R 4.2.0)
 correlation       * 0.8.3      2022-10-09 [1] CRAN (R 4.2.1)
 corrplot            0.92       2021-11-18 [1] CRAN (R 4.2.1)
 crayon              1.5.2      2022-09-29 [1] CRAN (R 4.2.1)
 crul                1.3        2022-09-03 [1] CRAN (R 4.2.1)
 curl                5.0.0      2023-01-12 [1] CRAN (R 4.2.2)
 data.table          1.14.8     2023-02-17 [1] CRAN (R 4.2.2)
 datawizard          0.6.5      2022-12-14 [1] CRAN (R 4.2.2)
 DBI                 1.1.3      2022-06-18 [1] CRAN (R 4.2.0)
 dbplyr              2.3.1      2023-02-24 [1] CRAN (R 4.2.2)
 deldir              1.0-6      2021-10-23 [1] CRAN (R 4.2.0)
 devtools          * 2.4.5      2022-10-11 [1] CRAN (R 4.2.1)
 dials             * 1.1.0      2022-11-04 [1] CRAN (R 4.2.2)
 DiceDesign          1.9        2021-02-13 [1] CRAN (R 4.2.0)
 digest              0.6.31     2022-12-11 [1] CRAN (R 4.2.2)
 disk.frame        * 0.8.0      2023-02-05 [1] CRAN (R 4.2.2)
 dlookr            * 0.6.1      2022-11-08 [1] CRAN (R 4.2.2)
 doParallel          1.0.17     2022-02-07 [1] CRAN (R 4.2.0)
 dotenv              1.0.3      2021-04-22 [1] CRAN (R 4.2.0)
 dotwhisker        * 0.7.4      2021-09-02 [1] CRAN (R 4.2.2)
 dplyr             * 1.1.0      2023-01-29 [1] CRAN (R 4.2.2)
 easyalluvial      * 0.3.1      2022-07-05 [1] CRAN (R 4.2.2)
 ecoseries         * 0.1.5      2022-04-26 [1] Github (fernote7/ecoseries@7b20ec6)
 ellipsis            0.3.2      2021-04-29 [1] CRAN (R 4.2.0)
 embed             * 1.0.0      2022-07-02 [1] CRAN (R 4.2.2)
 emmeans             1.8.4-1    2023-01-17 [1] CRAN (R 4.2.2)
 entropy             1.3.1      2021-10-02 [1] CRAN (R 4.2.0)
 estimability        1.4.1      2022-08-05 [1] CRAN (R 4.2.1)
 evaluate            0.20       2023-01-17 [1] CRAN (R 4.2.2)
 extrafont           0.19       2023-01-18 [1] CRAN (R 4.2.2)
 extrafontdb         1.0        2012-06-11 [1] CRAN (R 4.2.0)
 fansi               1.0.4      2023-01-22 [1] CRAN (R 4.2.2)
 fastmap             1.1.1      2023-02-24 [1] CRAN (R 4.2.2)
 finetune          * 1.0.1      2022-10-12 [1] CRAN (R 4.2.2)
 fontBitstreamVera   0.1.1      2017-02-01 [1] CRAN (R 4.2.0)
 fontLiberation      0.1.0      2016-10-15 [1] CRAN (R 4.2.0)
 fontquiver          0.2.1      2017-02-01 [1] CRAN (R 4.2.2)
 forcats           * 1.0.0      2023-01-29 [1] CRAN (R 4.2.2)
 foreach             1.5.2      2022-02-02 [1] CRAN (R 4.2.0)
 foreign             0.8-83     2022-09-28 [2] CRAN (R 4.2.2)
 forge               0.2.0      2019-02-26 [1] CRAN (R 4.2.2)
 Formula           * 1.2-5      2023-02-24 [1] CRAN (R 4.2.2)
 fs                  1.6.1      2023-02-06 [1] CRAN (R 4.2.2)
 fst               * 0.9.8      2022-02-08 [1] CRAN (R 4.2.1)
 fstcore             0.9.14     2023-01-12 [1] CRAN (R 4.2.2)
 funModeling       * 1.9.4      2020-06-15 [1] CRAN (R 4.2.2)
 furrr               0.3.1      2022-08-15 [1] CRAN (R 4.2.1)
 future              1.32.0     2023-03-07 [1] CRAN (R 4.2.2)
 future.apply        1.10.0     2022-11-05 [1] CRAN (R 4.2.2)
 gargle              1.3.0      2023-01-30 [1] CRAN (R 4.2.2)
 gdata             * 2.18.0.1   2022-05-10 [1] CRAN (R 4.2.0)
 gdtools             0.3.1      2023-02-17 [1] CRAN (R 4.2.2)
 generics            0.1.3      2022-07-05 [1] CRAN (R 4.2.0)
 geoarrow          * 0.0.0.9000 2023-03-01 [1] Github (paleolimbot/geoarrow@feebf96)
 GetBCBData          0.7.0      2022-06-07 [1] CRAN (R 4.2.0)
 gfonts              0.2.0      2023-01-08 [1] CRAN (R 4.2.2)
 ggalluvial        * 0.12.5     2023-02-22 [1] CRAN (R 4.2.2)
 ggplot2           * 3.4.1      2023-02-10 [1] CRAN (R 4.2.2)
 ggpmisc           * 0.5.2      2022-12-17 [1] CRAN (R 4.2.2)
 ggpp              * 0.5.1      2023-02-03 [1] CRAN (R 4.2.2)
 ggpubr            * 0.6.0      2023-02-10 [1] CRAN (R 4.2.2)
 ggQC              * 0.0.31     2018-12-01 [1] CRAN (R 4.2.2)
 ggridges            0.5.4      2022-09-26 [1] CRAN (R 4.2.1)
 ggsignif            0.6.4      2022-10-13 [1] CRAN (R 4.2.1)
 ggstance            0.3.6      2022-11-16 [1] CRAN (R 4.2.2)
 glmnet            * 4.1-6      2022-11-27 [1] CRAN (R 4.2.2)
 globals             0.16.2     2022-11-21 [1] CRAN (R 4.2.2)
 glue                1.6.2      2022-02-24 [1] CRAN (R 4.2.0)
 gower               1.0.1      2022-12-22 [1] CRAN (R 4.2.2)
 GPfit               1.0-8      2019-02-08 [1] CRAN (R 4.2.0)
 gridExtra           2.3        2017-09-09 [1] CRAN (R 4.2.0)
 gtable              0.3.1      2022-09-01 [1] CRAN (R 4.2.1)
 gtools              3.9.4      2022-11-27 [1] CRAN (R 4.2.2)
 hardhat             1.2.0      2022-06-30 [1] CRAN (R 4.2.0)
 here                1.0.1      2020-12-13 [1] CRAN (R 4.2.1)
 highcharter       * 0.9.4      2022-01-03 [1] CRAN (R 4.2.1)
 Hmisc             * 5.0-0      2023-03-06 [1] CRAN (R 4.2.2)
 hms                 1.1.2      2022-08-19 [1] CRAN (R 4.2.1)
 hrbrthemes          0.8.0      2020-03-06 [1] CRAN (R 4.2.2)
 htmlTable           2.4.1      2022-07-07 [1] CRAN (R 4.2.1)
 htmltools           0.5.4      2022-12-07 [1] CRAN (R 4.2.2)
 htmlwidgets         1.6.1      2023-01-07 [1] CRAN (R 4.2.2)
 httpcode            0.3.0      2020-04-10 [1] CRAN (R 4.2.1)
 httpuv              1.6.9      2023-02-14 [1] CRAN (R 4.2.2)
 httr                1.4.5      2023-02-24 [1] CRAN (R 4.2.2)
 igraph              1.4.1      2023-02-24 [1] CRAN (R 4.2.2)
 infer             * 1.0.4      2022-12-02 [1] CRAN (R 4.2.2)
 insight             0.19.0     2023-01-30 [1] CRAN (R 4.2.2)
 interp              1.1-3      2022-07-13 [1] CRAN (R 4.2.1)
 inum                1.0-4      2021-04-12 [1] CRAN (R 4.2.2)
 ipred               0.9-13     2022-06-02 [1] CRAN (R 4.2.0)
 iterators           1.0.14     2022-02-05 [1] CRAN (R 4.2.0)
 janeaustenr         1.0.0      2022-08-26 [1] CRAN (R 4.2.1)
 janitor           * 2.2.0      2023-02-02 [1] CRAN (R 4.2.2)
 jpeg                0.1-10     2022-11-29 [1] CRAN (R 4.2.2)
 jsonlite            1.8.4      2022-12-06 [1] CRAN (R 4.2.2)
 kableExtra          1.3.4      2021-02-20 [1] CRAN (R 4.2.0)
 keras               2.11.0     2022-12-20 [1] CRAN (R 4.2.2)
 kernlab           * 0.9-32     2023-01-31 [1] CRAN (R 4.2.2)
 knitr               1.42       2023-01-25 [1] CRAN (R 4.2.2)
 later               1.3.0      2021-08-18 [1] CRAN (R 4.2.0)
 lattice           * 0.20-45    2021-09-22 [2] CRAN (R 4.2.2)
 latticeExtra        0.6-30     2022-07-04 [1] CRAN (R 4.2.1)
 lava                1.7.2.1    2023-02-27 [1] CRAN (R 4.2.2)
 lazyeval            0.2.2      2019-03-15 [1] CRAN (R 4.2.0)
 lhs                 1.1.6      2022-12-17 [1] CRAN (R 4.2.2)
 libcoin             1.0-9      2021-09-27 [1] CRAN (R 4.2.2)
 lifecycle           1.0.3      2022-10-07 [1] CRAN (R 4.2.1)
 listenv             0.9.0      2022-12-16 [1] CRAN (R 4.2.2)
 lubridate         * 1.9.2      2023-02-10 [1] CRAN (R 4.2.2)
 magrittr            2.0.3      2022-03-30 [1] CRAN (R 4.2.1)
 MASS                7.3-58.1   2022-08-03 [2] CRAN (R 4.2.2)
 Matrix            * 1.5-3      2022-11-11 [1] CRAN (R 4.2.2)
 MatrixModels        0.5-1      2022-09-11 [1] CRAN (R 4.2.1)
 memoise             2.0.1      2021-11-26 [1] CRAN (R 4.2.0)
 mime                0.12       2021-09-28 [1] CRAN (R 4.2.0)
 miniUI              0.1.1.1    2018-05-18 [1] CRAN (R 4.2.0)
 mnormt              2.1.1      2022-09-26 [1] CRAN (R 4.2.1)
 modeldata         * 1.1.0      2023-01-25 [1] CRAN (R 4.2.2)
 ModelMetrics        1.2.2.2    2020-03-17 [1] CRAN (R 4.2.0)
 moments             0.14.1     2022-05-02 [1] CRAN (R 4.2.0)
 multidplyr        * 0.1.2      2022-09-26 [1] CRAN (R 4.2.1)
 munsell             0.5.0      2018-06-12 [1] CRAN (R 4.2.0)
 mvtnorm             1.1-3      2021-10-08 [1] CRAN (R 4.2.0)
 naniar            * 1.0.0      2023-02-02 [1] CRAN (R 4.2.2)
 narrow              0.0.0.9000 2023-03-01 [1] Github (paleolimbot/narrow@3572fb5)
 nlme                3.1-160    2022-10-10 [2] CRAN (R 4.2.2)
 nnet                7.3-18     2022-09-28 [2] CRAN (R 4.2.2)
 openssl             2.0.5      2022-12-06 [1] CRAN (R 4.2.2)
 openxlsx          * 4.2.5.2    2023-02-06 [1] CRAN (R 4.2.2)
 pagedown            0.20       2022-12-13 [1] CRAN (R 4.2.2)
 pander              0.6.5      2022-03-18 [1] CRAN (R 4.2.2)
 parallelly          1.34.0     2023-01-13 [1] CRAN (R 4.2.2)
 parameters          0.20.2     2023-01-27 [1] CRAN (R 4.2.2)
 parsnip           * 1.0.4      2023-02-22 [1] CRAN (R 4.2.2)
 partykit            1.2-17     2023-02-28 [1] CRAN (R 4.2.2)
 patchwork         * 1.1.2      2022-08-19 [1] CRAN (R 4.2.1)
 pillar              1.8.1      2022-08-19 [1] CRAN (R 4.2.1)
 pkgbuild            1.4.0      2022-11-27 [1] CRAN (R 4.2.2)
 pkgconfig           2.0.3      2019-09-22 [1] CRAN (R 4.2.0)
 pkgload             1.3.2      2022-11-16 [1] CRAN (R 4.2.2)
 plyr                1.8.8      2022-11-11 [1] CRAN (R 4.2.2)
 png                 0.1-8      2022-11-29 [1] CRAN (R 4.2.2)
 prettyunits         1.1.1      2020-01-24 [1] CRAN (R 4.2.0)
 pROC                1.18.0     2021-09-03 [1] CRAN (R 4.2.0)
 processx            3.8.0      2022-10-26 [1] CRAN (R 4.2.1)
 prodlim             2019.11.13 2019-11-17 [1] CRAN (R 4.2.0)
 profvis             0.3.7      2020-11-02 [1] CRAN (R 4.2.1)
 progressr           0.13.0     2023-01-10 [1] CRAN (R 4.2.2)
 promises            1.2.0.1    2021-02-11 [1] CRAN (R 4.2.0)
 pryr                0.1.6      2023-01-17 [1] CRAN (R 4.2.2)
 ps                  1.7.2      2022-10-26 [1] CRAN (R 4.2.1)
 psych             * 2.2.9      2022-09-29 [1] CRAN (R 4.2.1)
 purrr             * 1.0.1      2023-01-10 [1] CRAN (R 4.2.2)
 qcc               * 2.7        2017-07-11 [1] CRAN (R 4.2.2)
 Quandl            * 2.11.0     2021-08-11 [1] CRAN (R 4.2.0)
 quantmod          * 0.4.20     2022-04-29 [1] CRAN (R 4.2.0)
 quantreg            5.94       2022-07-20 [1] CRAN (R 4.2.1)
 r2d3                0.2.6      2022-02-28 [1] CRAN (R 4.2.2)
 R6                  2.5.1      2021-08-19 [1] CRAN (R 4.2.0)
 ranger            * 0.14.1     2022-06-18 [1] CRAN (R 4.2.2)
 rappdirs            0.3.3      2021-01-31 [1] CRAN (R 4.2.1)
 raster              3.6-20     2023-03-06 [1] CRAN (R 4.2.2)
 rbcb              * 0.1.10     2022-03-30 [1] CRAN (R 4.2.0)
 RColorBrewer        1.1-3      2022-04-03 [1] CRAN (R 4.2.0)
 Rcpp                1.0.10     2023-01-22 [1] CRAN (R 4.2.2)
 RCurl               1.98-1.10  2023-01-27 [1] CRAN (R 4.2.2)
 reactable         * 0.4.3      2023-01-07 [1] CRAN (R 4.2.2)
 readr             * 2.1.4      2023-02-10 [1] CRAN (R 4.2.2)
 readxl            * 1.4.2      2023-02-09 [1] CRAN (R 4.2.2)
 recipes           * 1.0.5      2023-02-20 [1] CRAN (R 4.2.2)
 remotes             2.4.2      2021-11-30 [1] CRAN (R 4.2.0)
 repr                1.1.6      2023-01-26 [1] CRAN (R 4.2.2)
 reshape2            1.4.4      2020-04-09 [1] CRAN (R 4.2.0)
 reticulate        * 1.28       2023-01-27 [1] CRAN (R 4.2.2)
 rjson               0.2.21     2022-01-09 [1] CRAN (R 4.2.0)
 rlang             * 1.0.6      2022-09-24 [1] CRAN (R 4.2.1)
 rlist               0.4.6.2    2021-09-03 [1] CRAN (R 4.2.1)
 rmarkdown           2.20       2023-01-19 [1] CRAN (R 4.2.2)
 robotstxt         * 0.7.13     2020-09-03 [1] CRAN (R 4.2.2)
 ROCR                1.0-11     2020-05-02 [1] CRAN (R 4.2.2)
 ROSE                0.0-4      2021-06-14 [1] CRAN (R 4.2.2)
 rpart             * 4.1.19     2022-10-21 [2] CRAN (R 4.2.2)
 rpart.plot        * 3.1.1      2022-05-21 [1] CRAN (R 4.2.2)
 rprojroot           2.0.3      2022-04-02 [1] CRAN (R 4.2.0)
 rsample           * 1.1.1      2022-12-07 [1] CRAN (R 4.2.2)
 RSQLite             2.3.0      2023-02-17 [1] CRAN (R 4.2.2)
 rstatix             0.7.2      2023-02-01 [1] CRAN (R 4.2.2)
 rstudioapi          0.14       2022-08-22 [1] CRAN (R 4.2.1)
 Rttf2pt1            1.3.12     2023-01-22 [1] CRAN (R 4.2.2)
 rvest               1.0.3      2022-08-19 [1] CRAN (R 4.2.1)
 scales            * 1.2.1      2022-08-20 [1] CRAN (R 4.2.1)
 sessioninfo         1.2.2      2021-12-06 [1] CRAN (R 4.2.0)
 shape               1.4.6      2021-05-19 [1] CRAN (R 4.2.0)
 shiny               1.7.4      2022-12-15 [1] CRAN (R 4.2.2)
 showtext            0.9-5      2022-02-09 [1] CRAN (R 4.2.2)
 showtextdb          3.0        2020-06-04 [1] CRAN (R 4.2.2)
 sidrar            * 0.2.9      2022-07-12 [1] CRAN (R 4.2.1)
 skimr             * 2.1.5      2022-12-23 [1] CRAN (R 4.2.2)
 snakecase           0.11.0     2019-05-25 [1] CRAN (R 4.2.0)
 SnowballC           0.7.0      2020-04-01 [1] CRAN (R 4.2.0)
 sp                  1.6-0      2023-01-19 [1] CRAN (R 4.2.2)
 sparkline         * 2.0        2016-11-12 [1] CRAN (R 4.2.2)
 sparklyr          * 1.8.0      2023-03-07 [1] CRAN (R 4.2.2)
 SparseM             1.81       2021-02-18 [1] CRAN (R 4.2.0)
 stringi           * 1.7.12     2023-01-11 [1] CRAN (R 4.2.2)
 stringr           * 1.5.0      2022-12-02 [1] CRAN (R 4.2.2)
 survival          * 3.4-0      2022-08-09 [2] CRAN (R 4.2.2)
 svglite             2.1.1      2023-01-10 [1] CRAN (R 4.2.2)
 sysfonts            0.8.8      2022-03-13 [1] CRAN (R 4.2.2)
 systemfonts         1.0.4      2022-02-11 [1] CRAN (R 4.2.0)
 tensorflow          2.11.0     2022-12-19 [1] CRAN (R 4.2.2)
 terra               1.7-18     2023-03-06 [1] CRAN (R 4.2.2)
 tfruns              1.5.1      2022-09-05 [1] CRAN (R 4.2.1)
 themis            * 1.0.0      2022-07-02 [1] CRAN (R 4.2.2)
 tibble            * 3.1.8      2022-07-22 [1] CRAN (R 4.2.1)
 tidyAML           * 0.0.1      2023-02-16 [1] CRAN (R 4.2.2)
 tidymodels        * 1.0.0      2022-07-13 [1] CRAN (R 4.2.1)
 tidyr             * 1.3.0      2023-01-24 [1] CRAN (R 4.2.2)
 tidyselect          1.2.0      2022-10-10 [1] CRAN (R 4.2.1)
 tidytext          * 0.4.1      2023-01-07 [1] CRAN (R 4.2.2)
 tidyverse         * 2.0.0      2023-02-22 [1] CRAN (R 4.2.2)
 timechange          0.2.0      2023-01-11 [1] CRAN (R 4.2.2)
 timeDate            4022.108   2023-01-07 [1] CRAN (R 4.2.2)
 tokenizers          0.3.0      2022-12-22 [1] CRAN (R 4.2.2)
 TTR               * 0.24.3     2021-12-12 [1] CRAN (R 4.2.0)
 tune              * 1.0.1      2022-10-09 [1] CRAN (R 4.2.1)
 typed               0.0.1      2021-03-19 [1] CRAN (R 4.2.1)
 tzdb                0.3.0      2022-03-28 [1] CRAN (R 4.2.0)
 urlchecker          1.0.1      2021-11-30 [1] CRAN (R 4.2.1)
 usemodels         * 0.2.0      2022-02-18 [1] CRAN (R 4.2.2)
 usethis           * 2.1.6      2022-05-25 [1] CRAN (R 4.2.0)
 utf8                1.2.3      2023-01-31 [1] CRAN (R 4.2.2)
 uuid                1.1-0      2022-04-19 [1] CRAN (R 4.2.0)
 uwot                0.1.14     2022-08-22 [1] CRAN (R 4.2.2)
 vctrs               0.5.2      2023-01-23 [1] CRAN (R 4.2.2)
 vip               * 0.3.2      2020-12-17 [1] CRAN (R 4.2.2)
 viridisLite         0.4.1      2022-08-22 [1] CRAN (R 4.2.1)
 visdat              0.6.0      2023-02-02 [1] CRAN (R 4.2.2)
 webshot             0.5.4      2022-09-26 [1] CRAN (R 4.2.1)
 whisker             0.4.1      2022-12-05 [1] CRAN (R 4.2.2)
 withr               2.5.0      2022-03-03 [1] CRAN (R 4.2.0)
 wk                  0.7.1      2022-12-09 [1] CRAN (R 4.2.2)
 workflows         * 1.1.3      2023-02-22 [1] CRAN (R 4.2.2)
 workflowsets      * 1.0.0      2022-07-12 [1] CRAN (R 4.2.1)
 writexl             1.4.2      2023-01-06 [1] CRAN (R 4.2.2)
 xfun                0.37       2023-01-31 [1] CRAN (R 4.2.2)
 xml2                1.3.3      2021-11-30 [1] CRAN (R 4.2.0)
 xtable              1.8-4      2019-04-21 [1] CRAN (R 4.2.0)
 xts               * 0.13.0     2023-02-20 [1] CRAN (R 4.2.2)
 yaml                2.3.7      2023-01-23 [1] CRAN (R 4.2.2)
 yardstick         * 1.1.0      2022-09-07 [1] CRAN (R 4.2.1)
 yfR               * 1.1.0      2023-02-16 [1] CRAN (R 4.2.2)
 zeallot             0.1.0      2018-01-28 [1] CRAN (R 4.2.0)
 zip                 2.2.2      2022-10-26 [1] CRAN (R 4.2.2)
 zoo               * 1.8-11     2022-09-17 [1] CRAN (R 4.2.1)

 [1] C:/Users/Evert/AppData/Local/R/win-library/4.2
 [2] C:/Program Files/R/R-4.2.2/library

> packageVersion("sparklyr")
[1] ‘1.8.0’

sc <- spark_connect(master = "local", version = "3.3.2")

> Brasil.NDVI |> 
+   sdf_dim()
[1] 31300823       12

Brasil.NDVI |> sdf_describe() 

Very Slow !!!!

Running time of more than 3 hours

**Comment by oaoutpost0** [comment]
Hello,

I'm not familiar with the dataset you are using, but the "local" master only uses 1 CPU core. For 31 million records, 3 hours isn't unreasonable at all. Remember: Spark is designed to be scalable, not fast, per se (meaning that if you can do it on one core, Spark will be slower than native processes).

Try your code with `master = "local[*]` and see what the performance is.

**Comment by edgararuiz** [comment]
Were you having this issue on an older version of `sparklyr`?
