### ISSUE TITLE
Cannot install spark 3.2.3

### ISSUE THREAD

**Issue by mhamilton723** [sparklyr/sparklyr#3331]
`spark_install(version = "3.2.3", hadoop_version = "3.2")` 

fails on sparklyr 1.8.1 with the following error

```Error in download.file(...) : 
  cannot open URL 'https://dlcdn.apache.org/spark/spark-3.2.3/spark-3.2.3-bin-hadoop3.2.tgz'
```

To fix this sparklyr needs to pull from this URL instead

`https://archive.apache.org/dist/spark/spark-3.2.3/spark-3.2.3-bin-hadoop3.2.tgz`

**Comment by edgararuiz** [comment]
Fixed c32284916e8f36600ed2f70c4569a523163e91d1
