### ISSUE TITLE
Error validversion

### ISSUE THREAD

**Issue by rizal-mujahiddan69** [sparklyr/sparklyr#3348]
<img width="517" alt="image" src="https://github.com/sparklyr/sparklyr/assets/86094348/2e66ca2f-7433-4b7a-bfe8-b726153def00">

Why error in install spark, im in version sparklyr 1.8.1

**Comment by jtitusj** [comment]
+1 on this. getting the same error

**Comment by edgararuiz** [comment]
Hi, yes, that's fixed in the dev version. So it'll be fixed in the next CRAN version.

If you'd like to try it now, feel free to install `sparklyr` from Github:

```r
devtools::install_github("sparklyr/sparklyr")
```
