### ISSUE TITLE
Warnings with binary files

### ISSUE THREAD

**Issue by gregleleu** [sparklyr/sparklyr#3357]
Doing any manipulation with binary files produces warnings

```r
spark_version <- "3.4.0"
sc <- spark_connect(master = "local", version = spark_version)

# your reproducible example here
binary_sdf <- spark_read_binary(sc, 
  recursive_file_lookup = TRUE, 
  dir = "./tests/testthat/data/test_spark_read_binary_recursive_file_lookup", 
  name = "test")
binary_sdf %>% select(content)

# # Source: spark<?> [?? x 1]
#   content  
#   <list>   
# 1 <raw [4]>
# 2 <raw [4]>
# 3 <raw [4]>
# 4 <raw [4]>
# Warning message:
# In FUN(X[[i]], ...) : out-of-range values treated as 0 in coercion to raw
```

**Comment by edgararuiz** [comment]
Thanks @gregleleu ! I'm seeing the same in 3.4, and 3.0, but in my laptop. I don't see that in the CI test on the GitHub actions. Is where you testing a Mac?

**Comment by gregleleu** [comment]
I'm on a mac yes, but it also shows up in the Sedona CI: https://github.com/apache/sedona/actions/runs/5603748794/jobs/10250817504 (section "run tests").
I don't get an error either when I run the sparklyr tests, they don't call select.

**Comment by gregleleu** [comment]
We are now getting this issue even on mutates and other verbs in the Sedona tests.
dbGetQuery doesn't generate this, so I'm pretty sure the warning comes from some operation dplyr is running.

**Comment by gregleleu** [comment]
Some more research:
It seems to come from the now "by" in dplyr. The warning gets generated by a call to this function in tidyselect `tidyselect_data_proxy`

dbplyr has a `tidyselect_data_proxy.tbl_lazy` version that does not produce an issue, but I guess the tidyselect version is the one that gets called

**Comment by gregleleu** [comment]
Found it! 
It's the call to tidyselect_data_proxy.tbl_spark and subsequent call to simulate_vars_spark
it's here: https://github.com/sparklyr/sparklyr/blob/22aa571c1cb2820b916fff9e0860647c2ea024f5/R/utils.R#L475
