### ISSUE TITLE
Sparklyr is incompatible with Spark3.5 due to a refactor of RowEncoder

### ISSUE THREAD

**Issue by qianlanchen-db** [sparklyr/sparklyr#3362]
In Spark 3.5, API `RowEncoder` is refactored to `ExpressionEncoder`. Please see:  https://github.com/apache/spark/commit/071feabbd4325504332679dfa620bc5ee4359370. Sparklyr is incompatible with Spark 3.5 due to this change. `RowEncoder` is used in `workerhelper.scala`, and this is expected to be changed to `ExpressionEncoder`
https://github.com/sparklyr/sparklyr/blob/4d49e40c8cefd394358f64261fceeaeaef13f8cc/java/spark-2.0.0/workerhelper.scala#L100

Can this be fixed and published to CRAN?

**Comment by edgararuiz** [comment]
Hi, will this change be backwards compatible with Spark 3.4 and under?

**Comment by qianlanchen-db** [comment]
@edgararuiz this change will only be in Spark 3.5. For Spark 3.4 and older, the method is still `RowEncoder`. Will need to use different method for different spark version.

**Comment by edgararuiz** [comment]
Fixed in cdb20f94a26fbfc032ce1d3add0ae340c2367279
