### ISSUE TITLE
"Error in if: argument is of length zero" shows when creating a new connection in workbench with Spark 3.5, 3.4.1 and 3.3.3

### ISSUE THREAD

**Issue by astayleraz** [sparklyr/sparklyr#3386]
**Description:**
I see that when I install spark 3.5, 3.4.1 or 3.3.3 and then try and add a new connection from the connections pane, I see these warnings and error in the console, and in the spark version drop down it does not show those versions Im trying. In the console, I can create the connection with sc <- spark_connect(master = "local")

![Screenshot 2023-10-12 at 2 38 42 PM](https://github.com/sparklyr/sparklyr/assets/1482677/e4796fae-a15b-4e3d-8ef2-793fa3904789)

Test steps:

1. Open an RStudio session in workbench and load the sparklyr. `library(sparklyr)`
2. In the workbench terminal download spark 3.5.0 (happens with 3.4.1 and 3.3.3 as well) `wget -O spark-3.5.0-bin-hadoop3.tgz https://rstudio-workbench-qa.s3.us-west-2.amazonaws.com/spark-3.5.0-bin-hadoop3.tgz`
4. In the console, install that. `spark_install_tar("spark-3.5.0-bin-hadoop3.tgz")`
5. From the connections pane, click New Connection and select Spark.

Expected:
I would not expect any errors, and I would expect that version of spark to show as an option in the dropdown.

Actual:
I see the following warnings and error. This is from when I was testing 3.3.3.

```
Listening on http://127.0.0.1:4819
Warning in sprintf(versions$pattern, version$spark, version$hadoop) :
  2 arguments not used by format 'spark-3.3.3-bin-hadoop3'
Warning in sprintf(versions$pattern, version$spark, version$hadoop) :
  2 arguments not used by format 'spark-3.3.3-bin-hadoop3'
Warning in sprintf(versions$pattern, version$spark, version$hadoop) :
  2 arguments not used by format 'spark-3.3.3-bin-hadoop3'
Warning in sprintf(versions$pattern, version$spark, version$hadoop) :
  2 arguments not used by format 'spark-3.3.3-bin-hadoop3'
Warning in sprintf(versions$pattern, version$spark, version$hadoop) :
  2 arguments not used by format 'spark-3.3.3-bin-hadoop3'
Warning in sprintf(versions$pattern, version$spark, version$hadoop) :
  2 arguments not used by format 'spark-3.3.3-bin-hadoop3'
Warning in sprintf(versions$pattern, version$spark, version$hadoop) :
  2 arguments not used by format 'spark-3.3.3-bin-hadoop3'
Warning: Error in if: argument is of length zero
  68: paste
  67: generateCode [/opt/R/4.2.2/lib/R/library/sparklyr/rstudio/shinycon/app.R#270]
  66: <reactive:codeReactive> [/opt/R/4.2.2/lib/R/library/sparklyr/rstudio/shinycon/app.R#320]
  50: codeReactive
  46: observe [/opt/R/4.2.2/lib/R/library/sparklyr/rstudio/shinycon/app.R#342]
  45: <observer>
   2: shiny::runApp
   1: shiny::runGadget
Warning in sprintf(versions$pattern, version$spark, version$hadoop) :
  2 arguments not used by format 'spark-3.3.3-bin-hadoop3'
```

Note: Jonathan mentioned the error coming from here https://github.com/sparklyr/sparklyr/blob/0a3d847789ce218129bbbea710f7762cb7e97948/R/install_spark_versions.R#L206

**Comment by edgararuiz** [comment]
Hi @astayleraz , thank you I'll mark this one as a bug to work on
