### ISSUE TITLE
Is there a way to read partitioned Parquet datasets into a local Spark cluster using `sparklyr`?

### ISSUE THREAD

**Issue by JavOrraca** [sparklyr/sparklyr#3404]
I am working with NYC Taxi ride data in a partitioned Parquet dataset (by Year and Month) and struggling to read the data set directly into a local Spark cluster. I don't think this is possible but I also tried copying the Arrow binding (multi-file dataset) to Spark.

The code below is not a reprex but summarizes my intent:

```r
sc <- sparklyr::spark_connect(master = "local")

# Read 120 individual Parquet files via arrow::open_dataset()
nyc_taxi_tibble <- arrow::open_dataset(here::here("data/nyc-taxi"))

# Method 1 that fails:
nyc_taxi_spark_1 <- sparklyr::spark_read_parquet(sc, path = here::here("data/nyc-taxi"), name = "nyc_taxi_tibble_1")

# Method 2 that fails:
nyc_taxi_spark_2 <- dplyr::copy_to(sc, nyc_taxi_tibble, "nyc_taxi_tibble_2")
```

Any input would be appreciated! It'd be great if {sparklyr} had the capability to run `spark_read_dataset()` or `spark_open_dataset()` to copy a partitioned Parquet dataset into a local Spark cluster. Thanks again for this great package that I've been using a lot more frequently (locally and with Databricks)!

**Comment by edgararuiz** [comment]
Hi @JavOrraca , can you share the error you're getting? 

Also, `sparklyr` uses `arrow` if it has been previously loaded into your session. So, please try using:

```r
library(sparklyr)
library(arrow) 

sc <- sparklyr::spark_connect(master = "local")
nyc_taxi_spark_1 <- sparklyr::spark_read_parquet(sc, path = here::here("data/nyc-taxi"), name = "nyc_taxi_tibble_1")

```
