### ISSUE TITLE
Workbench IDE Connections Pane not reflecting changes when installing Sparklyr

### ISSUE THREAD

**Issue by Cecilsingh** [sparklyr/sparklyr#3406]
Hi Team,
 
Running into an issue here that appears to be a bug. I've tried this on the 2023.09 release of Workbench + 2023.05 release of the Pro Drivers, as well as the 2023.12 release of Workbench + 2023.12 release of Pro Drivers with the same results. Currently, there is no way to remove the Spark button from the connections tab. Whether the sparklyr package is installed or not, the Spark connection button shows up:
<img width="918" alt="IDE_Spark_Livy" src="https://github.com/sparklyr/sparklyr/assets/54638818/8f491baa-7dca-4934-ab00-a7ac81ef9dd7">
 
Installing the sparklyr package brings up the Livy connection button:
<img width="831" alt="IDE_Spark_Livy_sparklyr" src="https://github.com/sparklyr/sparklyr/assets/54638818/5d8520d3-a20e-4c39-83b3-b6e1bff957c5">

In addition, the docs referred to in the screenshot (https://support.posit.co/hc/en-us/articles/115010915687) under the Using RStudio Connections button states:
 
> The list of connection types in this dialog is drawn from a variety of sources. For instance, if you have the [sparklyr](http://spark.rstudio.com/) package installed, you’ll see the Spark type in the list.
 
How would we remove both the Livy and Spark connections from the connections pane?

Appreciate your help here team!

**Comment by edgararuiz** [comment]
I just realized that in fact, RStudio does have a reference to Spark. It will need to be removed from the IDE before removing it from `sparklyr`

https://github.com/rstudio/rstudio/blob/79f40d52f86dc1d0124240ff068e230cb7500079/src/cpp/session/modules/SessionConnections.R#L509-L512

**Comment by Cecilsingh** [comment]
Thank you, Edgar! I appreciate your help here. 

I'll close this off for now. Thank you for your input, it's very helpful!
