### ISSUE TITLE
AWS Glue metadata catalog of iceberg tables. Local spark master.

### ISSUE THREAD

**Issue by ssefick** [sparklyr/sparklyr#3422]
Hello, I am unable to leave a reprex because I have been unable to get this to work.

I can connect to local master, to iceberg/glue on the iceberg AWS integrations, but  'SHOW DATABASES' only shows default, and tables are not queryable.

Any help would be appreciated.

**Comment by edgararuiz** [comment]
Hi @ssefick , do you need to refer to a specific table inside Iceberg? If so, you can force it by using `in_catalog()`, for example: `my_tbl <- tbl(sc, in_catalog("my_catalog", "my_schema", "my_table"))`
