### ISSUE TITLE
Shiny app for connection frequently returns error

### ISSUE THREAD

**Issue by blairj09** [sparklyr/sparklyr#3438]
Using the latest dev version of `sparklyr` (`1.8.6`) I freqently see the following when trying to connect to Databricks via the packaged Shiny app:
```
Loading required package: shiny

Listening on http://127.0.0.1:7376
Error in regmatches(x, m)[[1]] : subscript out of bounds
```

When this happens, the App stays live, but sometimes clicking "Ok" in the connection dialogue doesn't result in a connection (the example below does successfully connect after the error).

https://github.com/sparklyr/sparklyr/assets/10444878/376c6906-259d-4b04-982e-f8cbf6bb5506

**Comment by edgararuiz** [comment]
Transferred to https://github.com/mlverse/pysparklyr/issues/114
