### ISSUE TITLE
  Failed while connecting to sparklyr to port (8880) for sessionid (8540): Gateway in port (8880) did not respond.

### ISSUE THREAD

**Issue by raghav20** [sparklyr/sparklyr#394]
Sparklyr package -0.5

 Parameters: --class, sparklyr.Backend, --packages, 'ai.h2o:sparkling-water-core_2.11:1.6.7','ai.h2o:sparkling-water-ml_2.11:1.6.7','ai.h2o:sparkling-water-repl_2.11:1.6.7', '/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.3/sparklyr/java/sparklyr-2.0-2.11.jar', 8880, 8540

--- Output Log ----

	  file:/home/ubuntu/.m2/repository/ai/h2o/sparkling-water-repl_2.11/1.6.7/sparkling-water-repl_2.11-1.6.7.jar

	==== local-ivy-cache: tried

	  /home/ubuntu/.ivy2/local/ai.h2o/sparkling-water-repl_2.11/1.6.7/ivys/ivy.xml

	  -- artifact ai.h2o#sparkling-water-repl_2.11;1.6.7!sparkling-water-repl_2.11.jar:

	  /home/ubuntu/.ivy2/local/ai.h2o/sparkling-water-repl_2.11/1.6.7/jars/sparkling-water-repl_2.11.jar

	==== central: tried

	  https://repo1.maven.org/maven2/ai/h2o/sparkling-water-repl_2.11/1.6.7/sparkling-water-repl_2.11-1.6.7.pom

	  -- artifact ai.h2o#sparkling-water-repl_2.11;1.6.7!sparkling-water-repl_2.11.jar:

	  https://repo1.maven.org/maven2/ai/h2o/sparkling-water-repl_2.11/1.6.7/sparkling-water-repl_2.11-1.6.7.jar

	==== spark-packages: tried

	  http://dl.bintray.com/spark-packages/maven/ai/h2o/sparkling-water-repl_2.11/1.6.7/sparkling-water-repl_2.11-1.6.7.pom

	  -- artifact ai.h2o#sparkling-water-repl_2.11;1.6.7!sparkling-water-repl_2.11.jar:

	  http://dl.bintray.com/spark-packages/maven/ai/h2o/sparkling-water-repl_2.11/1.6.7/sparkling-water-repl_2.11-1.6.7.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: ai.h2o#sparkling-water-core_2.11;1.6.7: not found

		:: ai.h2o#sparkling-water-ml_2.11;1.6.7: not found

		:: ai.h2o#sparkling-water-repl_2.11;1.6.7: not found

		::::::::::::::::::::::::::::::::::::::::::::::

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: ai.h2o#sparkling-water-core_2.11;1.6.7: not found, unresolved dependency: ai.h2o#sparkling-water-ml_2.11;1.6.7: not found, unresolved dependency: ai.h2o#sparkling-water-repl_2.11;1.6.7: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1076)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:294)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:158)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

---- Error Log ----
Calls: spark_connect ... tryCatchOne -> <Anonymous> -> abort_shell -> <Anonymous> -> force
Execution halted

**Comment by edgararuiz** [comment]
Hi @raghav20, are you trying to use sparkling water? and if so, can you confirm that it and H2O are  installed?  There process would have been something like this: http://spark.rstudio.com/h2o.html

**Comment by gbortz27** [comment]
I am getting a very similar thing on windows , see my 2 posts above showing my errors and messages in connction with ports being available. Not using H20 , just trying to run the same instructions as per tutorial on sparkly R R studio site. Get error on the sc command. I have a java home environmental variable and initiated the "Sys.getenv('JAVA_HOME')" and get the response "[1] "C:\\Program Files\\Java\\jdk1.8.0_112"

Is this correct ? ie the Java version etc and that I am running JDK andnot JRE?

Thanks
Graham

**Comment by raghav20** [comment]
Yes I have both Installed @edgararuiz

**Comment by raghav20** [comment]
I am running it this way  ./spark-1.6.2-bin-hadoop2.6/bin/spark-submit --packages ai.h2o:sparkling-water-core_2.11:2.0.0,ai.h2o:sparkling-water-examples_2.11:2.0.0 --num-executors 5  --master spark://ip-X.Y.Z.U.us-west-2.compute.internal:7077 --driver-memory 25g --executor-memory 20g ./spark-1.6.2-bin-hadoop2.6/examples/src/main/r/others.R 

@edgararuiz Please let me know.

**Comment by edgararuiz** [comment]
Hi @raghav20 , are you running this inside RStudio, an R shell or a Spark shell?

**Comment by raghav20** [comment]
Spark-submit

**Comment by javierluraschi** [comment]
This would be a feature request, currently we don't support running applicaitons in `spark-submit` the way python would, as in `spark-submit <params> --py-files python-file.py`, it would certainly open interesting batch scenarios, worth considering.

**Comment by raghav20** [comment]
When Can I hope for it to get resolved ?

**Comment by yitao-li** [comment]
Moving this to https://github.com/sparklyr/sparklyr/issues/3006
