### ISSUE TITLE
can't "copy_to" large datasets

### ISSUE THREAD

**Issue by PecoE** [sparklyr/sparklyr#487]
I try to copy somewhat large (~800MB) datasets into a Spark-Dataframe for benchmarking purposes. The data consists of one column with random numbers. Everything works well with smaller datasets, but at a specific point I just get the progressbar in the commandline, which goes up to 100% and then nothing happens anymore. I am working on a server with 100+ GB Memory, and 16 cores. I even tried to specify the executor and driver memory by hand, but nothing works.

The config looks like this:
```
spark_connect(master="yarn-client",
   config = list(
     default = list(
       spark.submit.deployMode= "client",
       spark.executor.instances= 20, 
       spark.executor.memory= "2G",
       spark.executor.cores= 4,
       spark.driver.memory= "4G")))
```
If I then stop the script, I get the following warning:
```

Warning message:
In spark_web.spark_shell_connection(sc) :
  Spark UI URL not found in logs, attempting to guess.
```

I don't know with which information I should provide you, since there is no error message.

**Comment by javierluraschi** [comment]
@PecoE a new fix improves `copy_to` speed specifically in `yarn_client`. Could you try with the latest version of `sparklyr`? To install the latest development version you can run:

```
devtools::install_github("rstudio/sparklyr")
```

**Comment by PecoE** [comment]
@javierluraschi Thanks for the reply. I am already working with sparklyr V0.5.1. I tried to do the command with gradually growing datasets, and at about 40MB, it stops working and at that point, it gives me an error. Unfortunatly, I can't reproduce the error right now. If I come across it again, I will paste it here if you want. But basically it says, that the memory alocated is to low, and that I have to change the settings for "frame.size". It says, I that I can allocate ~130MB but I am trying to allocate ~200MB (Which sounds a bit too much considering my 40MB set). 

All in all, I am not so satisfied with the benchmarking. The time-consumption for processing the data seems to rise exponentially on Spark and is rising much faster than the computation with standard R-functions. My hope is that I can see a significant improvement in performance on really large datasets. 
By the way: I am alternatively getting the data via a Hive-Connection, and there I can load larger Datasets (16GB+) and it looks like that on some functions, Spark is performing better.
Is there an approximation on the size of data, that is neccessary for spark to perform better than local computation?

**Comment by eijoac** [comment]
Not sure it will help, but I also had a `copy_to()` problem with a small dataset (babynames ~40M) in Spark standalone cluster. I solved it by configuring `sparklyr.shell.driver-memory` and `sparklyr.shell.executor-memory` parameters (someone recommended this to me,  https://github.com/rstudio/sparklyr/issues/379). I don't know why it worked. It seems that `copy_to()` is somehow related to spark shell (need to check its source code).

Regarding loading data, I tested a csv dataset about 31G. With 3nodes x 12core per nodes, I loaded it in 354s (`spark_read_csv()` with 36 partitions). Once I saved it in Parquet format on a regular file system (`spark_write_parquet()` with default setting), it took 138s to load. However, when I used `copy_to()` for the babynames dataset (about 40M), it took 132s to load (36 partitions). It seems that loading dataset into the memory and partitioning it has quite some overhead cost, or certain parameters need to be tuned for datasets of different size, or something is wrong with `copy_to()`.

**Comment by javierluraschi** [comment]
`copy_to` wasn't designed to copy large data sets, but it's expected to do this and is something that we will have to address eventually.

**Comment by ignacio82** [comment]
Is there any update about this? Is there any way to copy a large table from R to spark?

**Comment by lucasmation** [comment]
updates?

**Comment by renanxcortes** [comment]
Any updates on this issue, @javierluraschi ? I'm kinda stumbling in the same issue using a Livy connection in a remote cluster.

**Comment by yitao-li** [comment]
@renanxcortes Which version of `sparklyr` are you running? There is some serialization-related improvements in sparklyr 1.5 which might help.

Also, have you tried enabling `arrow` and see if that can help?

**Comment by renanxcortes** [comment]
Hi @yitao-li, I'm currently using `1.4.0`, is there any improvement in the later versions?

Also, what do you mean by enabling "arrow"? How could enable it in the `copy_to` function?

**Comment by renanxcortes** [comment]
Also, I'd like to put here the full log of the error:

```
Error in livy_validate_http_response("Failed to invoke livy statement",  :
  Failed to invoke livy statement (Server error: (500) Internal Server Error): "java.util.concurrent.ExecutionException: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Message (95146674 bytes) exceeds maximum allowed size (52428800 bytes)."
```

**Comment by yitao-li** [comment]
@renanxcortes Enabling `arrow` as in try to run `install.packages("arrow")` followed by `library(arrow)` before running the large `copy_to()` workload to Livy -- `sparklyr` will use Arrow serialization if the `arrow` package is attached, and this will help in 2 ways:
- Arrow serialization is faster, so that copying large dataset (hopefully) won't be prohibitively slow
- Arrow splits the serialized data into smaller batches (which can be configured with `spark.sql.execution.arrow.maxRecordsPerBatch`). The error message you saw previously essentially says the data copy request `sparklyr` sent to Livy was too large. I think this can be avoided if `sparklyr` uses Arrow serialization with a reasonable `spark.sql.execution.arrow.maxRecordsPerBatch` configured.

**Comment by renanxcortes** [comment]
> @renanxcortes Enabling `arrow` as in try to run `install.packages("arrow")` followed by `library(arrow)` before running the large `copy_to()` workload to Livy -- `sparklyr` will use Arrow serialization if the `arrow` package is attached, and this will help in 2 ways:
> 
> * Arrow serialization is faster, so that copying large dataset (hopefully) won't be prohibitively slow
> * Arrow splits the serialized data into smaller batches (which can be configured with `spark.sql.execution.arrow.maxRecordsPerBatch`). The error message you saw previously essentially says the data copy request `sparklyr` sent to Livy was too large. I think this can be avoided if `sparklyr` uses Arrow serialization with a reasonable `spark.sql.execution.arrow.maxRecordsPerBatch` configured.

Awesome, thanks for the detailed reply! I'll try this workaround in the upcoming days and post here how it went.

**Comment by renanxcortes** [comment]
Hey @yitao-li how could I specify the `spark.sql.execution.arrow.maxRecordsPerBatch` parameter in the livy connections? Here's what I tried (this is exactly what I'm currently using and it is working except for this new argument):

```
config <- livy_config(username = 'my_user_name',
                      password = 'my_password',
                      spark.sql.execution.arrow.maxRecordsPerBatch = "50000")

sc <- spark_connect(master = "my_internal_host_name_and_port",
                    method = "livy",
                    config = config
                    version = "2.4.5")
```

But I'm hitting a:

```
Error in livy_config(username = "renan.cortes", password = "vincentAGI123!!!!",  : 
  spark.sql.execution.arrow.maxRecordsPerBatch,  are not valid session parameters. Valid parameters are: proxy_user, jars, py_files, files, driver_memory, driver_cores, executor_memory, executor_cores, num_executors, archives, queue, name, heartbeat_timeout, conf, 
```

In addition, I tried the specification present in https://github.com/sparklyr/sparklyr/issues/2243#issuecomment-590431598, but also unsuccessfully :(

**Comment by renanxcortes** [comment]
Hey @yitao-li  Unfortunately, I'm still hitting the same issue. Here's what I tried (this is exactly what I'm currently using and it is working except for this new argument):

```
library(arrow)
config <- livy_config(username = 'my_username',
                      password = 'my_password') %>% 
  append(.,list("spark.sql.execution.arrow.maxRecordsPerBatch"="100000"))

sc <- spark_connect(master = "my_internal_host_name_and_port",
                    method = "livy",
                    config = config
                    version = "2.4.5")

sdf <- copy_to(sc, dataframe_with_332886_rows_and_15_columns)
```

I'm hitting a:

```
Error in livy_validate_http_response("Failed to invoke livy statement",  : 
  Failed to invoke livy statement (Server error: (500) Internal Server Error): "java.util.concurrent.ExecutionException: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Message (94370280 bytes) exceeds maximum allowed size (52428800 bytes)."
```

Here's my `sessionInfo()`:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252    LC_MONETARY=Portuguese_Brazil.1252
[4] LC_NUMERIC=C                       LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] arrow_2.0.0       aws.s3_0.3.21     tidyr_1.1.0       magrittr_1.5      lubridate_1.7.9   stringr_1.4.0     plotly_4.9.2.1   
 [8] bizdays_1.0.6     highcharter_0.8.2 ggplot2_3.3.2     purrr_0.3.4       dplyr_1.0.0       agibankR_2.1      sparklyr_1.4.0   

loaded via a namespace (and not attached):
 [1] tinytex_0.24          zoo_1.8-8             tidyselect_1.1.0      xfun_0.15             forge_0.2.0           lattice_0.20-41      
 [7] colorspace_1.4-1      vctrs_0.3.1           generics_0.0.2        viridisLite_0.3.0     htmltools_0.5.0       yaml_2.2.1           
[13] base64enc_0.1-3       blob_1.2.1            rlang_0.4.8           pillar_1.4.4          glue_1.4.1            withr_2.2.0          
[19] DBI_1.1.0             bit64_0.9-7           dbplyr_1.4.4          aws.ec2metadata_0.2.0 TTR_0.23-6            lifecycle_0.2.0      
[25] quantmod_0.4.17       munsell_0.5.0         gtable_0.3.0          htmlwidgets_1.5.1     parallel_4.0.2        curl_4.3             
[31] broom_0.5.6           r2d3_0.2.3            xts_0.12-0            Rcpp_1.0.4.6          scales_1.1.1          backports_1.1.7      
[37] jsonlite_1.7.0        config_0.3            bit_1.1-15.2          digest_0.6.25         stringi_1.4.6         rlist_0.4.6.1        
[43] grid_4.0.2            rprojroot_1.3-2       tools_4.0.2           lazyeval_0.2.2        tibble_3.0.1          aws.signature_0.6.0  
[49] crayon_1.3.4          pkgconfig_2.0.3       ellipsis_0.3.1        xml2_1.3.2            woeBinning_0.1.6      data.table_1.12.8    
[55] assertthat_0.2.1      httr_1.4.1            rstudioapi_0.11       R6_2.4.1              igraph_1.2.5          nlme_3.1-148         
[61] compiler_4.0.2       
```

Thank you so much for your help!

**Comment by yitao-li** [comment]
@renanxcortes Based on what I understood from Livy documentation I think another possible solution is to configure `livy.rsc.rpc.max.size` to be greater than 52428800 bytes in your `livy.conf` file (e.g., put `livy.rsc.rpc.max.size = 104857600`). This is a server-side configuration so restarting Livy server is required. I don't know whether this is something individual Livy clients can override (most likely not).
