### ISSUE TITLE
Add residuals() method for ml_model objects

### ISSUE THREAD

**Issue by richierocks** [sparklyr/sparklyr#557]
At the moment, it's slightly tricky to get the residuals from a model.

The basic idea is this:

```r
residuals.ml_model <- function(x, ...) {
  sdf_register(x$data) %>% 
    select_(actual = x$response) %>% 
    transmute(
      residual = predict(x) - actual
    )
}
```

This doesn't work for me without `collect()`ing the data, and for some models you need to think about weights, but the basic idea is right.

**Comment by kevinushey** [comment]
We do in fact have a `residuals.ml_model()` method already; it's defined like so:

```
#' @export
residuals.ml_model <- function(object, ...) {
  object$.model %>%
    invoke("summary") %>%
    invoke("residuals") %>%
    sdf_read_column("residuals")
}
```

This may perhaps only be valid for e.g. Spark linear regression models, though. Can you elaborate on what kind of model you're trying to get residuals from?

**Comment by richierocks** [comment]
@kevinushey Oh, so you do. I tried `residuals()` on a random forest model, and got this error.

```
 Error: java.lang.IllegalArgumentException: invalid method summary for object 750
```

A method for gradient boosted trees would also be really useful.

**Comment by kevinushey** [comment]
Gotcha, that makes sense. I agree it would be worth adding a more general `residuals()` implementation here.
