### ISSUE TITLE
I can't find the equivelant of rowSums for spark dataframes

### ISSUE THREAD

**Issue by oghanmi** [sparklyr/sparklyr#573]
Hi everyone,

I am trying to create a new column that is the sum of different columns. This is possible using dplyr on an T data frame using rowSums(tbl[,n1:n2]).

When I tried it on a spark data frame, i got this error : 

**error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "c('tbl_spark', 'tbl_sql', 'tbl_lazy', 'tbl')"**

thank you so much for your help

**Comment by javierluraschi** [comment]
@oghanmi Right, `rowSums` is currently not supported in `sparkylr`. Can you use `mutate` instead?

```
sc <- spark_connect(master = "local")
iris_tbl <- copy_to(sc, iris)
iris_tbl %>% mutate(y = Petal_Length + Petal_Width)
```

**Comment by oghanmi** [comment]
@javierluraschi Thank you for your answer. Actually we can sum differnt columns by indicating their names, i.e :iris_tbl %>% mutate(y = Petal_Length + Petal_Width)
It's only problematic when you have lots of columns  from n1 to n2 to sum.

Hope it will be available in the next release

**Comment by conangal** [comment]
Hi @javierluraschi. Thanks for all your work on sparklyr. 
Are there any new plans on this feature request? It would be a great help to be able to aggregate by row. I guess the challenge is that it would need to use a native Spark function rather than Spark-SQL?

**Comment by yitao-li** [comment]
It will be supported in the upcoming release of `sparklyr` 1.5.0.
