### ISSUE TITLE
Is there a sparklyr function to save one csv file.

### ISSUE THREAD

**Issue by statkclee** [sparklyr/sparklyr#585]
I am looking for a way to save one csv file on S3 bucket.

It seems to me that `repartion(xxx, 1)` function from sparkr works.

With spark_write_csv() function, I can have only splitted csv files.

Thanks.

**Comment by javierluraschi** [comment]
```
ml_classification_eval(predicted_tbl, label, predicted_lbl, metric = "accuracy")
```

**Comment by javierluraschi** [comment]
Took a quick look but seems like you would have to use `invoke`, marking this as a feature request to provide this functionality.

**Comment by gbisschoff** [comment]
Has this feature been incorporated yet? Is there a workaround in the meantime?

**Comment by Jiang-Li** [comment]
Is anyone can give me an example of how to export the single csv file? Thanks.

**Comment by javierluraschi** [comment]
Reopening to consider feature request. Notice that in general, while dealing with big data, writing a single CSV file is not feasible due to the nature of the distributed problem; However, at times, I would agree its easier/feasible to export this to single file.

**Comment by joscani** [comment]
Hi javier. 
At this moment I need to write a spark dataframe in a single csv on amazon s3 to Viz purpose. How can I use invoke inside sparklyr to do that? Thanks in advance

**Comment by kevinykuo** [comment]
Have y'all tried calling `sdf_coalesce()` before exporting to csv?

**Comment by iamkbpark** [comment]
@kevinykuo  `sdf_coalesce()` solved the problem for me.

**Comment by GraemeTorrance** [comment]
@kevinykuo and @iamkbpark how did you use `sdf_coalesce()` in this instance? Within Azure Databricks I have tried;

`sdf <- sdf_coalesce(sdf, 1)`
`spark_write_csv(sdf, 'BLOB_path')`

But when I look in the blob the file remains partioned
