### ISSUE TITLE
Implement broom functions

### ISSUE THREAD

**Issue by kevinykuo** [sparklyr/sparklyr#670]
Working on this. Will start with GLM type models. Blocked by https://github.com/rstudio/sparklyr/issues/557 but the GLM case is easy to resolve so I'll submit a fix for that soon.

TODO
- [x] Implement `residuals()` for GLM type models
- [x] Implement method to get training data from model https://github.com/rstudio/sparklyr/issues/555
- [x] Implement `tidy`, `augment`, and `glance`
- [x] Informative error messages for models not yet supported
- [x] Tests
- [x] Support logistic regression and rest of supervised learning models
- [x] Support unsupervised learning models

**Comment by kevinykuo** [comment]
Regarding column names in `broom` output -- should we follow the naming convention with dots, e.g. `std.error` and `.resid`, or come up with our own scheme since we've sort of gone down the path of sanitizing column names?

@kevinushey

**Comment by kevinushey** [comment]
That's a good question... from the README at https://github.com/tidyverse/broom, it sounds like the convention is to use `.`-separated names, so we should likely want to use that here. However, given that some versions of Spark don't handle `.`s in names all that well, we should provide a mechanism for users to generate names using camelCase as well.

What's your opinion here?

**Comment by kevinushey** [comment]
Maybe we want something like `tidy(data, style = "dotcase")` vs. `tidy(data, style = "camelcase")`?

**Comment by kevinykuo** [comment]
I'm actually leaning towards `dot.case` for broom consistency and `snake_case`, because tidyverse. Will continue this discussion in a PR.

**Comment by yitao-li** [comment]
Looks like this work is actually complete by now. We can close this issue.
