### ISSUE TITLE
Unable to connect using Windows

### ISSUE THREAD

**Issue by igornoberto** [sparklyr/sparklyr#694]
I'm runing with
R 3.4 with Rstudio 1.0.143
Sparklyr 0.5.4
Spark 2.0.2
Windows Server 2012 build 9200

`sc <- spark_connect(master = "spark://##.#.#.###:7077")`

error:

> ChangeFileModeByMask error (5): Access is denied.
> 
> Error in file(con, "r") : cannot open the connection
> In addition: Warning messages:
> 1: running command '"d:\spark\tmp\hadoop\bin\winutils.exe" chmod 777 "d:\spark\tmp\hive"' had status 1 
> 2: In file(con, "r") :
>   cannot open file 'C:\Users\User\AppData\Local\Temp\15\RtmpyUapBt\file22543ffb280_spark.log': Permission denied

**Comment by javierluraschi** [comment]
@igornoberto could you rerun as:

```
sc <- spark_connect(master = "spark://##.#.#.###:7077", config = list(sparklyr.log.console = TRUE))
```

?

**Comment by Haskman** [comment]
@javierluraschi I ran into the same problem and tried your solution. No dice

**Comment by javierluraschi** [comment]
@igornoberto @Haskman my suggestion would not resolve the issue but should show more logging information to help troublehsoot, could you rerun as follows and share the output?

```
sc <- spark_connect(master = "spark://##.#.#.###:7077", config = list(sparklyr.log.console = TRUE))
```

Feel free to also find me in gitter to chat about urgent connectivity issue, happy to help as time permits.
