### ISSUE TITLE
Issues with sdf_copy_to fail

### ISSUE THREAD

**Issue by PozzOver13** [sparklyr/sparklyr#713]
I'm getting this error when trying to copy a dataframe to Spark and don't know how to fix it.
```
|================================================================================| 100%  352 MB
Error in invoke_method.spark_shell_connection(sc, TRUE, class, method,  : 
  No status is returned. Spark R backend might have failed.
```
It happens when trying to copy a dataframe (neraly 360 MB) to Spark, while I have no problem with smaller dataframes (around 15 MB). 

`tmp_big_Spark <- sdf_copy_to(sc, tmp_big, "tmp_big", repartition = 0, memory = F, overwrite = T)`

I've also tried to set "repartition = 3" but no results.
The dataframe is not big for hadoop standard so maybe it depends on the configuration. 
These are the configuration settings:

```
# Configure cluster
config <- spark_config()
config$spark.yarn.keytab <- "path_to_keytab/mykeytab.keytab"
config$spark.yarn.principal <- "myYarnPrincipal"
config$sparklyr.gateway.start.timeout <- 10
config$spark.executor.instances <- 2
config$spark.executor.cores <- 4
config$spark.executor.memory <- "8G"
config$spark.driver.memory <- "4G"

config$spark.kryoserializer.buffer.max  <- "1G"

Sys.setenv(SPARK_HOME = "/opt/cloudera/parcels/CDH/lib/spark")
Sys.setenv(HADOOP_CONF_DIR = '/etc/hadoop/conf.cloudera.hdfs')
Sys.setenv(YARN_CONF_DIR = '/etc/hadoop/conf.cloudera.yarn')
#Sys.setenv(HIVE_CONF_DIR = '/etc/hive/conf.cloudera.hive')

# Connect to spark
sc <- spark_connect(master = "yarn-client", config = config, version = '1.6.0')
```

**Comment by javierluraschi** [comment]
Currently, there is an open feature request to support large uploads/downloads into Spark, we will try to get this implemented soon.

**Comment by learndm** [comment]
Hi Javier,

are you planning to work on that ?

Thanks

**Comment by dkincaid** [comment]
Just ran into this myself today. What size is a "large" upload? What is the biggest upload we should be able to do?

**Comment by samuelmacedo83** [comment]
I would load the files using `spark_read_csv()`, for example.  It is considerable faster than upload the object using `sdf_copy_to()`. 
Regarding the maximun file's size, I don't know precisely, but sparklyr improved since this question and now it is possible to upload 360mb using `sdf_copy_to()`.

Thank you for your feedback and feel free to reopen this issue if you have another question.
