### ISSUE TITLE
unable to resolve 's3.amazonaws.com'

### ISSUE THREAD

**Issue by tarunparmar** [sparklyr/sparklyr#732]
I was able to connect to Spark until yesterday, seems my company IT policy changed that may be blocking package access to internet (not sure, just my guess). 

Does the package access internet in anyway when it's called ?

This is what I am running...

```r
# sparklyr_0.5.5
# spark_version <- "2.0.0"
library(dplyr)
library(sparklyr)
sc <- spark_connect(master = "spark://fc8rstuds02:7077")
```

Output
```
#unable to resolve 's3.amazonaws.com'
#Error in file(file, "rt") : cannot open the connection
```

**Comment by samuelmacedo83** [comment]
Hi @tarunparmar , sorry for not answer you before. I hope you have resolved this problem.
I'll close this issue, but feel free to reopen if the problem persists.
