### ISSUE TITLE
Newlines are properly serialized / deserialized

### ISSUE THREAD

**Issue by javierluraschi** [sparklyr/sparklyr#776]
Removing `NYI` test. Looks like we need to use `wholefile` from Spark 2.2, see https://github.com/databricks/spark-csv/issues/425.

```
test_that("newlines are properly serialized / deserialized", {
  skip("NYI")

  df <- data.frame(
    x = 1:3,
    y = c("a\nb", "b", "c"),
    stringsAsFactors = FALSE
  )

  ensure_round_trip(sc, df)

})
```

**Comment by yitao-li** [comment]
This is no longer an issue with the revised R-to-Spark serialization routines.
