### ISSUE TITLE
Is it possible to connect sparklyr to mongodb?

### ISSUE THREAD

**Issue by jconesam** [sparklyr/sparklyr#811]
I know how [to connect sparkR to mongodb](https://docs.mongodb.com/spark-connector/master/r-api/):

But I do not know how to combine that code with sparklyr to get data from mongo. I have tried this code, but it does not work:

`
Sys.setenv(SPARK_HOME=spark_home)

config <- sparklyr::spark_config()
config$sparklyr.defaultPackages <- c("org.mongodb.spark:mongo-spark-connector_2.10:1.1.0")
config$spark.mongodb.input.uri <- "mongodb://localhost:27017/nasa.eva"
config$spark.mongodb.output.uri <- "mongodb://localhost:27017/nasa.eva"
  
Spark.connection <<- sparklyr::spark_connect(master = "local", version = "2.0.1", config = config)

Spark.session <<-
  sparklyr::invoke_static(Spark.connection, "org.apache.spark.sql.SparkSession", "builder") %>%
  sparklyr::invoke("getOrCreate")

uri <- "mongodb://localhost/nasa.eva"

load <- invoke(Spark.session, "read") %>%
  invoke("format", "com.mongodb.spark.sql.DefaultSource") %>%
  invoke("option", "spark.mongodb.input.uri", uri) %>%
  invoke("option", "keyspace", "nasa") %>%
  invoke("option", "table", "eva") %>%
  invoke("load")
`

nasa and eva are my mongodatabase and mongo collection. The last load statement gets stuck and does not retrieve anything. There is a similar question in stackoverflow but no one answers me. May anyone give me some clue to sort it out?

**Comment by javierluraschi** [comment]
Yes, it should be possible.

BTW. There is an easier way we are adding for the development version of `sparklyr` (although, does the same under the covers), you can install with `devtools::install_github("rstudio/sparklyr")` followed by:

```r
spark_read_source(
  sc,
  "table-name",
  "com.mongodb.spark.sql.DefaultSource",
  list(
    spark.mongodb.input.uri = uri,
    keyspace = "nasa",
    table = "eva"),
  memory = FALSE)
```

That said, it will probably also hang since it's a wrapper for logic similar to the one you provide.

If this is a restricted resource, you might need to specify `user` and `password` under the options.

That said, what would really help would be to get a few screenshots of the Spark task that are running when this hangs, it's possible that this is working as expected but is taking too long.

Another suggestion is to specify the schema yourself to avoid having Spark infer it which usually takes a performance hit, something like this should work from `sparklyr`:

```r
spark_read_source(
  sc,
  "table-name",
  "com.mongodb.spark.sql.DefaultSource",
  list(
    spark.mongodb.input.uri = uri,
    keyspace = "nasa",
    table = "eva"),
  memory = FALSE,
  columns = list(colum1 = "character", column2 = "integer")
```

**Comment by gosselinmarcantoine** [comment]
@javierluraschi,

What argument is "com.mongodb.spark.sql.DefaultSource"? I tried to use the code you provided but consistently get back the error at the bottom. The two likely sources of errors I can see, either the sc argument which I have set as `sc = spark_connect(master = "local")` or it is the "com.mongodb.spark.sql.DefaultSource" argument (which I guess is the source). 

my code:
`devtools::install_github("rstudio/sparklyr")`
`sparkR.session()`
`spark_install()`
`sc = spark_connect(master = "local")`
`spark_read_source(
  sc,
  "table_name",
  "com.mongodb.spark.sql.DefaultSource",
  list(
    spark.mongodb.input.uri = my_uri,
    keyspace = "collection_name",
    table = "dataframe_name"),
  memory = FALSE)`



The error: 
`Error: java.lang.Exception: No matched method found for class org.apache.spark.sql.DataFrameReader.format
	at sparklyr.Invoke.invoke(invoke.scala:136)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by gosselinmarcantoine** [comment]
> @javierluraschi,
> 
> What argument is "com.mongodb.spark.sql.DefaultSource"? I tried to use the code you provided but consistently get back the error at the bottom. The two likely sources of errors I can see, either the sc argument which I have set as `sc = spark_connect(master = "local")` or it is the "com.mongodb.spark.sql.DefaultSource" argument (which I guess is the source).
> 
> my code:
> `devtools::install_github("rstudio/sparklyr")`
> `sparkR.session()`
> `spark_install()`
> `sc = spark_connect(master = "local")`
> `spark_read_source( sc, "table_name", "com.mongodb.spark.sql.DefaultSource", list( spark.mongodb.input.uri = my_uri, keyspace = "collection_name", table = "dataframe_name"), memory = FALSE)`
> 
> The error:
> `Error: java.lang.Exception: No matched method found for class org.apache.spark.sql.DataFrameReader.format at sparklyr.Invoke.invoke(invoke.scala:136) at sparklyr.StreamHandler.handleMethodCall(stream.scala:123) at sparklyr.StreamHandler.read(stream.scala:66) at sparklyr.BackendHandler.channelRead0(handler.scala:51) at sparklyr.BackendHandler.channelRead0(handler.scala:4) at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) at java.lang.Thread.run(Thread.java:748)`

I was able to solve the problem, it was a problem stemming from authentication rights not being added to the uri.

**Comment by Satishjis256** [comment]
@gosselinmarcantoine : Even I am getting same issue when trying to connect mongodb with sparklyr , could you  provide resolution , what actually you have done

**Comment by Satishjis256** [comment]
@gosselinmarcantoine : I am trying to connect from local mongodb , is there also any authentication right is required to add in uri.

**Comment by vhrtan** [comment]
I received the same error while using the old version of defaultPackage. The new one worked fine.

```
conf <- spark_config()
conf$sparklyr.defaultPackages <- c("org.mongodb.spark:mongo-spark-connector_2.12:3.0.1")
conf$spark.mongodb.input.uri="mongodb://user:pwd@host:port/db.collection?authSource=space"

sc <- spark_connect(master = "local", config = conf)

data <- spark_read_source(
  sc,
  "data",
  source = "com.mongodb.spark.sql.DefaultSource",
  memory = FALSE
)
```
