### ISSUE TITLE
Issues with NA _character_ and count(x)?

### ISSUE THREAD

**Issue by 3zhang** [sparklyr/sparklyr#835]
First issue is that `NA _character_ ` seems to be converted to "NA" in `copy_to`:
```
test=data.frame(a=c(c(1:9),NA),b=c(letters[1:9],NA))
test1=copy_to(sc,test,'test',overwrite=T)
```
```
> collect(test1)$b
 [1] "a"  "b"  "c"  "d"  "e"  "f"  "g"  "h"  "i"  "NA"
```

Second issue is that whether we can have a `count(x)` function like SQL? In SQL, `count(x)` means to count the number of rows which are not null in column x. 
```
> test1 %>% summarise(count())
# Source:   lazy query [?? x 1]
# Database: spark_connection
  `count()`
      <dbl>
1        10
```
```
> test1 %>% summarise(count(a))
Error in count(b) : unused argument (a)
```
I can only achieve this by:
```
> test1 %>% summarise(count=sum(ifelse(is.na(a),0,1)))
# Source:   lazy query [?? x 1]
# Database: spark_connection
  count
  <dbl>
1     9
```

**Comment by 3zhang** [comment]
@javierluraschi 
I modified the count variant in sql_translate_env.spark_connection. Can I make a pull request?

**Comment by yitao-li** [comment]
The `NA_character_` issue has brennan fixed after CSV-based serialization routines are replaced with ones based on RDS.

**Comment by yitao-li** [comment]
Thanks for the feedback.

Re: `NA` -> `"NA"` -- yes that was a serialization bug and was addressed in recent version of `sparklyr`.

Re: `count()` -- current behavior on Spark dataframes seems consistent with what `dplyr` does for R dataframes. Essentially, you do need `cnt = sum(ifelse(...))` for counting only non-NA values. See https://stackoverflow.com/questions/44290704/count-non-na-values-by-group
