### ISSUE TITLE
how to setup spark_home into spark_lyr

### ISSUE THREAD

**Issue by sebastien1981** [sparklyr/sparklyr#839]
# Reporting an Issue with sparklyr

I am trying to connect to a cluster via spark_lyr. How can I connect it? Which files do I need to modify?

![image](https://user-images.githubusercontent.com/13273914/28155227-0affd18e-67ae-11e7-89f4-ef3f76f6a547.png)

**Comment by javierluraschi** [comment]
@sebastien1981 you need to set the right `Sys.setenv(SPARK_HOME = "<path-to-clusters-spark-home>")`. This is something that your cluster admin would know, it is assumed that the machine you are using is already inside the cluster for this to function properly. Most users install RStudio Server in a cluster machine and RStudio from that URL.

**Comment by sebastien1981** [comment]
Thanks you. Can you tell me on which file I need to set it up? I am trying to set it up into rocker/rstudio.

**Comment by renjithmadhavan** [comment]
> @javierluraschi
> Thanks you. Can you tell me on which file I need to set it up? I am trying to set it up into rocker/rstudio.
> Can I define it directly into the R-shell? or in one of those files : rserver.conf rsession.conf
> I am trying to set it up on a docker on rocker/rstudio

Did this ever work. I was trying to do the same.
