### ISSUE TITLE
how to create a hive table from a sparkdataframe

### ISSUE THREAD

**Issue by joscani** [sparklyr/sparklyr#854]
I would like to write a hive table (to allow other users read the table)  from a sparkdataframe using sparklyr
I'm using an Amazon EMR in a project and I found that sparklyr works fine but I need write my result in hive table. I can write in s3 and after create a hive query to create as external table but it would be great to create hive table in only one step. 

Thanks

**Comment by kevinykuo** [comment]
@joscani could you look at `?spark_write_table` and see if it works for your use case?
