### ISSUE TITLE
Spark Connect on local throws error

### ISSUE THREAD

**Issue by dguleria** [sparklyr/sparklyr#864]
# Reporting an Issue with sparklyr

@kevinykuo @javierluraschi - I am getting below error when I try to connect spark in my R studio version 0.99. I copied required winutils file in the bin folder and ran command below.

DO I NEED TO INSTALL LATEST R STUDIO 1.0.153 to connect ?
command - > sc <- spark_connect(master = "local", spark_home=spark_home_dir(version = "1.6.2"))

Error in force(code) :
Failed while connecting to sparklyr to port (8880) for sessionid (4261): Gateway in port (8880) did not respond.
Path: C:\Users\dguleria\AppData\Local\rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\bin\spark-submit2.cmd
Parameters: --class, sparklyr.Backend, --jars, "C:\Users\dguleria\Documents\R\win-library\3.4\sparklyr\java\spark-csv_2.11-1.3.0.jar","C:\Users\dguleria\Documents\R\win-library\3.4\sparklyr\java\commons-csv-1.1.jar","C:\Users\dguleria\Documents\R\win-library\3.4\sparklyr\java\univocity-parsers-1.5.1.jar", "C:\Users\dguleria\Documents\R\win-library\3.4\sparklyr\java\sparklyr-1.6-2.10.jar", 8880, 4261

---- Output Log ----
'"java"' is not recognized as an internal or external command,
operable program or batch file.

---- Error Log ----
In addition: Warning message:
running command '"C:\Users\dguleria\AppData\Local\rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\tmp\hadoop\bin\winutils.exe" chmod 777 "C:\Users\dguleria\AppData\Local\rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\tmp\hive"' had status 127

**Comment by asishbalakrishnan** [comment]
Can you please check if Java is installed and is added to the Path variable.

**Comment by kevinykuo** [comment]
@dguleria like @asishbalakrishnan suggested please confirm Java is installed – you should be able to issue `java -version` in the command prompt and get a result.
