### ISSUE TITLE
Consider streamlining versions tested in run-tests

### ISSUE THREAD

**Issue by kevinykuo** [sparklyr/sparklyr#898]
Right now we've got: 2.1.0 2.0.2 2.0.1 2.0.0 1.6.2 1.6.1

Instead of running tests for every maintenance release we could do the latest from each `major.feature` release: 2.2.0, 2.1.1, 2.0.2, 1.6.3

Thoughts?

@javierluraschi @kevinushey

**Comment by kevinushey** [comment]
I think there are occasionally bugs between minor releases that we'd only catch if we test explicitly on that version of Spark.

How much flexibility do users in enterprise environments have when it comes to updating Spark? Are most users typically able to at least stick with the newest minor release, or is it possible that some users will be locked in on e.g. Spark 1.6.2 and not Spark 1.6.3?

(really, we should see if we can get some kind of continuous integration system set up that can test each version of Spark in parallel, but that's a longer project -- I just added `run-tests` as a local smoke-test for myself to run e.g. before a CRAN release)
