### ISSUE TITLE
support for data types (especially dates) in spark_read_parquet 

### ISSUE THREAD

**Issue by slopp** [sparklyr/sparklyr#90]
Posting on behalf of DTCC, please follow up with any questions in the associated email thread.

a.  df1 <- spark_read_parquet(sc,"sd_cnd_frq_inter","/user/sd_cnd_frq_inter")

> head(df1)

Source:   query [?? x 45]

Database: spark connection master=spark://…:7077 app=sparklyr local=FALSE

```
id           pr_date  pr_price bndate prv_bndate dp_interval prv_dp_price price_chg_pct  pr_vol prv_dp_vol vol_chg_pct sum_dp_val prv_sum_dp_val

   <chr>   <chr>     <dbl>  <chr>      <chr>       <int>        <dbl>         <dbl>   <dbl>      <dbl>       <dbl>      <dbl>          <dbl>
```

1  007C6      16889    8.7000  16889      16888           1       8.3500      4.191617  735304     656673    11.97415   15606.15       38176.32

b.    Vs. if I use SparkR, it preserves the variable types – including the date

> library(SparkR)
> sc <- sparkR.init(sparkHome = "/opt/spark")
> sqlContext <- sparkRSQL.init(sc)
> bdf1 <- read.df(sqlContext, "/user/sd_cnd_frq_inter","parquet")
> head(bdf1)
> id    pr_date  pr_price     bndate prv_bndate dp_interval prv_dp_price price_chg_pct  pr_vol prv_dp_vol vol_chg_pct sum_dp_val prv_sum_dp_val
> 1 007C6       2016-03-29    8.7000 2016-03-29 2016-03-28    1     8.3500      4.191617  735304     656673    11.97415   15606.15       38176.32

**Comment by yitao-li** [comment]
Not entirely sure why user ran into this type of problem, but what I have observed so far is parquet file written by `sparklyr` containing date columns can be read back from disk to a Spark dataframe with the exact same values, see below:

```
library(sparklyr)
sc <- spark_connect(master = "local")

tbl <- copy_to(sc, tibble::tibble(x = as.POSIXct(c(0, 100000000), origin = "1970-01-01")))

tmp_path <- "/tmp/tbl"
spark_write_parquet(tbl, path = tmp_path)

tbl2 <- spark_read_parquet(sc, path = tmp_path)

print(tbl2)
```

```
tbl2 <- spark_read_parquet(sc, path = tmp_path)
print(tbl2)
```

`spark_read_parquet()` and `spark_write_parquet()` calls standard parquet read/write routines shipped with whichever version of Spark that `sparklyr` is connected to. Is it possible that there is some backward compatibility issue across different versions of Spark or some non-compatibility between parquet file written by other processes and Spark? Suggestions are welcome.

**Comment by benmwhite** [comment]
@yitao-li It looks like [this was an active Spark 1.x issue at the time](https://issues.apache.org/jira/browse/SPARK-8824), but it was resolved after this post. Anecdotally I've had no issues with parquet column types in Spark 2.3 and above.
