### ISSUE TITLE
Mutate not working but transmute working

### ISSUE THREAD

**Issue by MJFND** [sparklyr/sparklyr#970]
I am using Sparklyr, and using transmute everything works fine, but mutate does not work,

`data_temp %>% transmute(FName = as.character(FName))`
`data_temp %>% mutate(FName = as.character(FName))`

Mutate gives me the error "object FName not found", due to this issue I could not solve several things, I have seen people using this and they are not having problem. I wonder whats going on.

**Comment by javierluraschi** [comment]
@MJFND Have you tried restarting your `rsession` and clearing your environment? If that doesn't help, do you have the latest CRAN versions for `sparklyr`? If all fails, please paste here the full output of the failure and the results of running `sessionInfo()` to help out.

**Comment by MJFND** [comment]
I have done all the stuff, also removed and installed the Sparklyr again... Here is the error:
`> data_temp %>% mutate(FName = as.character(FName))
Error in eval(cols[[col]], .data, parent.frame()) : 
  object 'FName' not found`

While using transmute it works fine...

**Comment by hlendway** [comment]
I had an issue with a column name called id and found it worked when I referenced it as `id`. Kind of hacky but worth a shot.

**Comment by MJFND** [comment]
I have tried with all the columns, it is not even working in any... wonder how it worked on my first day of sparklyr but then it stops working.

**Comment by jfarland** [comment]
Have you tried being explicit about the potential namespace conflicts? Try specifically using mutate from sparklyr versus dplyr. Something like:  `data_temp %>% sparklyr::mutate(FName = as.character(FName))` .

**Comment by MJFND** [comment]
interesting, I will try.. Thanks

**Comment by kevinykuo** [comment]
@MJFND @hlendway if you're able to provide reproducible examples we'll be able to take a better look.

**Comment by milton9901** [comment]
Running into similar problem, however just "plain" dplyr (e.g. not sparklyr) and putting dplyr:: in front of mutate seems to be working.  Odd because as with other posts transmute works.  And again mystifying because this issue seemed to pop up out of now where.

**Comment by yl790** [comment]
@milton9901 Sounds like this could be some other package also exporting `mutate` that would mask `dplyr::mutate`.

I think you can even try launch an interactive R prompt, attach all packages you work with (e.g., `library(sparklyr)`, `library(dplyr)` etc) and then enter `?mutate` to search for `mutate` in namespaces. If there are multiple ones, you'll see a prompt similar to the one below (here I'm using `?filter` as an example):

```
> ?filter
Help on topic ‘filter’ was found in the following packages:

  Package               Library
  dplyr                 /mnt/sda7/lib/R/library
  stats                 /mnt/sda7/lib/R/library

Choose one 

1: Return rows with matching conditions {dplyr}
2: Linear Filtering on a Time Series {stats}

```

**Comment by milton9901** [comment]
@yl790, good to know.  For some reason this problem seemed to kick in after installing the nomclust package.

**Comment by yl790** [comment]
So by taking a quick look at NAMESPACE files from `nomclust` and `plyr`, looks like it's because of https://github.com/cran/nomclust/blob/master/NAMESPACE#L22 and https://github.com/hadley/plyr/blob/master/NAMESPACE#L79 , and the latter clashes with `dplyr::mutate`

It's generally considered a good practice to replace `mutate` with `dplyr::mutate` for namespace disambiguation reasons (e.g., we do this everywhere in `sparklyr` source code).
