### ISSUE TITLE
Type of NA ignored in dplyr::mutate()

### ISSUE THREAD

**Issue by JohnMount** [sparklyr/sparklyr#985]
Notice the column `z` has type `chr`, not the expected `numeric`.

I have also filed related [`dbplyr` issue](https://github.com/tidyverse/dplyr/issues/3081): but I don't know how many data sources have this issue (or if it is similar mechanisms in all cases).

``` r
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("sparklyr"))
packageVersion("dplyr")
#> [1] '0.7.2.9000'
packageVersion("dbplyr")
#> [1] '1.1.0.9000'
packageVersion("sparklyr")
#> [1] '0.6.2'

sc <- spark_connect(master= 'local')
#> * Using Spark: 2.1.0

dRemote <- dplyr::copy_to(sc, 
                          data.frame(x = 1:2), 
                          'dRemote')

dRemote <- dRemote %>%
  mutate(z = NA_real_)
print(dRemote)
#> # Source:   lazy query [?? x 2]
#> # Database: spark_connection
#>       x     z
#>   <int> <chr>
#> 1     1  <NA>
#> 2     2  <NA>
# notice z column type is wrong, adding as.numeric() does fix it

spark_disconnect(sc)
```

**Comment by yitao-li** [comment]
IMHO because `sparklyr` uses `dbplyr` for R-to-Spark-SQL translations, the correct place to fix such problem should be in `dbplyr`.
PR coming soon.

**Comment by yitao-li** [comment]
Proposed fix: https://github.com/tidyverse/dbplyr/pull/541 (it fixes the problem that was reported for `sparklyr`, so, I shall boldly assume it's the right fix :slightly_smiling_face:  )

**Comment by yitao-li** [comment]
I'm hoping the long-term fix for this in https://github.com/tidyverse/dbplyr/pull/541 will be included in some future version of `dbplyr`.

Meanwhile there is also https://github.com/sparklyr/sparklyr/pull/2808 which is a slightly hacky workaround that can be included in the next version of `sparklyr`. It doesn't cover all cases where `NA_real_` could arise though. All it does is forcing any `NA_real_` literal to be translated to `"CAST(NULL AS DOUBLE)"` in SQL within the context of `dplyr::mutate()` and `dplyr::transmute()`.
